Repository geosolutions-it/MapStore2, pull requests merged in 2018-12, with the labels that each got.

#3369 #3287 Timeline zoom to current time
  web/client/components/time/InlineDateTimeSelector.jsx
  web/client/plugins/Timeline.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Timeline, geonode_integration, pending review, review

#3384 #3348 resetting timeline/playback/dimension state when switching to a new map
  web/client/reducers/__tests__/dimension-test.js
  web/client/reducers/__tests__/playback-test.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/dimension.js
  web/client/reducers/playback.js
  web/client/reducers/timeline.js
Labels: Timeline, geonode_integration, pending review, review

#3392 fix #3391 update backgrounds for standard template and i18n doc
  docs/developer-guide/internationalization.md
  project/standard/templates/new.json
Labels: Priority: Medium, enhancement, pending review, review

#3399 Fix #3396 Minor fixes to Timeline UI
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3401 Fix #3395. Follow cursor on click/forward/backward. Increased unit tests
  web/client/components/playback/__tests__/PlaybackSettings-test.jsx
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
Labels: pending review, review

#3403 Fix range operator "><" for ogcDateField
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: pending review, review

#3402 Fix #3397 Improve timeline's buttons
  web/client/components/playback/PlaybackSettings.jsx
  web/client/components/time/InlineDateTimeSelector.jsx
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/themes/default/less/timeline.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3408 Fix #3397 Improve timeline's buttons (Failing test)
  web/client/components/playback/PlaybackSettings.jsx
Labels: pending review, review

#3394 Writing epics dev guide
  docs/developer-guide/dev-how-to.md
  docs/developer-guide/writing-epics.md
Labels: pending review, review

#3424 Fix #3420 Timeline playback range is not visible, Fix #3421 Layer doesn't update on timeline list, Fix #3422 Steps forward/backward don't update when select a new layer in Timeline
  web/client/epics/__tests__/playback-test.js
  web/client/epics/playback.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/timeline/Timeline.jsx
Labels: pending review, review

#3426 Fix #3417. Use correct click event object.
  web/client/components/time/enhancers/__tests__/clickHandlers-test.js
  web/client/components/time/enhancers/clickHandlers.js
  web/client/plugins/timeline/Timeline.jsx
Labels: pending review, review

#3434 Fix #3429. Fixed css for IE11 partial calc support
  web/client/plugins/Timeline.jsx
  web/client/themes/default/less/timeline.less
Labels: pending review, review

#3430 Fix #3418 made month date input read only
  web/client/components/time/InlineDateTimeSelector.jsx
  web/client/components/time/__tests__/InlineDateTimeSelector-test.jsx
  web/client/plugins/Timeline.jsx
Labels: pending review, review
