Repository geosolutions-it/MapStore2, pull requests merged in 2018-07, with the labels that each got.

#3047 Fixes #3046: thematic wms layers through SLDservice, initial support
  docma-config.json
  package.json
  web/client/actions/__tests__/thematic-test.js
  web/client/actions/thematic.js
  web/client/api/SLDService.js
  web/client/api/__tests__/SLDService-test.js
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThematicLayer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/misc/toolbar/ToolbarButton.jsx
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/style/ColorRangeSelector.jsx
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/config.json
  web/client/containers/Embedded.jsx
  web/client/containers/MapViewer.jsx
  web/client/epics/__tests__/thematic-test.js
  web/client/epics/thematic.js
  web/client/libs/ajax.js
  web/client/localConfig.json
  web/client/plugins/TOCItemsSettings.jsx
  web/client/plugins/ThematicLayer.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/product/plugins.js
  web/client/reducers/__tests__/thematic-test.js
  web/client/reducers/thematic.js
  web/client/test-resources/thematic/classification.json
  web/client/test-resources/thematic/fields.json
  web/client/themes/default/less/colorrangeselector.less
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/LayersUtils.js
  web/client/utils/LocaleUtils.js
  web/client/utils/PluginsUtils.js
  web/client/utils/SecurityUtils.js
  web/client/utils/URLUtils.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/URLUtils-test.js
Labels: pending review, review

#3048 Fixes #3046: do not change chosen field on saved thematic
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
Labels: pending review, review

#3050 Fixes #3046: improvements for thematic layers
  web/client/actions/__tests__/thematic-test.js
  web/client/actions/thematic.js
  web/client/api/SLDService.js
  web/client/api/__tests__/SLDService-test.js
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThematicLayer-test.jsx
  web/client/components/map/openlayers/plugins/GoogleLayer.js
  web/client/components/style/ColorPicker.jsx
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/plugins/ThematicLayer.jsx
  web/client/reducers/__tests__/thematic-test.js
  web/client/reducers/thematic.js
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3049 Added parameters to enable printing end to load version in MapStore2 api
  web/client/jsapi/MapStore2.js
Labels: pending review, review

#3055 Fix #3045 parsing of provider for tileProvider (#3054)
  web/client/components/map/openlayers/plugins/TileProviderLayer.js
  web/client/utils/ConfigProvider.js
  web/client/utils/TileProviderUtils.js
  web/client/utils/__tests__/TileProviderUtils-test.js
Labels: pending review, review

#3053 Fixes #3046: security token is not applied correctly to SLD params
  web/client/api/SLDService.js
  web/client/api/__tests__/SLDService-test.js
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThematicLayer-test.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/epics/__tests__/thematic-test.js
  web/client/epics/thematic.js
  web/client/plugins/ThematicLayer.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/PluginsUtils.js
  web/client/utils/SecurityUtils.js
  web/client/utils/leaflet/WMSUtils.js
  web/client/utils/mapinfo/wms.js
Labels: pending review, review

#3056 Fixes #3046: fixed translation for classification errors
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
Labels: pending review, review

#3060 Fix #3059. Remove auth params from param object
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
Labels: pending review, review

#3061 Fixes #3057: TOCItemsSettings original settings handling, Fixes #3058: leaflet WMS layers visibility on login / logout
  web/client/components/TOC/enhancers/__tests__/tocitemssettings-test.js
  web/client/components/TOC/enhancers/tocItemsSettings.js
  web/client/components/map/leaflet/plugins/WMSLayer.js
Labels: pending review, review

#3065 Update default print style
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Project: C125, bug, pending review, review

#3069 Fixes #3068: correct monitoring of plugins state to limit re-renderings
  web/client/components/plugins/PluginsContainer.jsx
Labels: pending review, review

#3067 Fix #3066. Replaced LRU cache with a IE11 compliant lib
  package.json
  web/client/utils/ElevationUtils.js
  web/client/utils/__tests__/ElevationUtils-test.js
Labels: pending review, review

#3072 Fixes #3070: thematic style removed on opacity change, fixes #3071: validation of thematic classes ranges
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThematicLayer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/epics/__tests__/thematic-test.js
  web/client/epics/thematic.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Project: C040, pending review, review

#3074 Fix #3073 date picker fixes
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.jsx
  web/client/themes/default/less/react-data-grid.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Project: C040, pending review, review

#3076 Fix #3075 legend missing message
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/legend/__tests__/Legend-test.jsx
  web/client/test-resources/img/geoserver-GetLegendGraphic.image
Labels: Project: C040, pending review, review

#3079 #3078 Feature info settings are always saved
  web/client/components/TOC/enhancers/__tests__/tocitemssettings-test.js
  web/client/components/TOC/enhancers/tocItemsSettings.js
Labels: pending review, review

#3081 Small improvements here and there, mostly missing defaults useful for…
  web/client/components/app/StandardAppComponent.jsx
  web/client/components/app/__tests__/StandardAppComponent-test.jsx
  web/client/components/app/__tests__/StandardRouter-test.jsx
  web/client/components/map/leaflet/Layer.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/plugins/PluginsContainer.jsx
  web/client/examples/plugins/plugins.js
  web/client/product/main.jsx
  web/client/stores/StandardStore.js
  web/client/themes/default/less/mouse-position.less
  web/client/utils/PluginsUtils.js
Labels: pending review, review

#3082 Add 4 decimals, text annotations and print style
  project/custom/templates/.gitignore
  project/standard/templates/.gitignore
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/CoordinateEntry.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/CoordinatesRow.jsx
  web/client/components/mapcontrols/annotations/GeometryEditor.jsx
  web/client/components/mapcontrols/annotations/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/mapcontrols/annotations/enhancers/__tests__/decimalToAeronautical-test.js
  web/client/components/mapcontrols/annotations/enhancers/decimalToAeronautical.js
  web/client/components/style/TextStyler.jsx
  web/client/epics/annotations.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/annotations.js
  web/client/selectors/__tests__/annotations-test.js
  web/client/selectors/annotations.js
  web/client/test-resources/Annotation.json
  web/client/utils/AnnotationsUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Project: C125, pending review, review

#3080 Fix #3066. Replaced LRU cache with a IE11 compliant lib (Porting)
  package.json
  web/client/utils/ElevationUtils.js
  web/client/utils/__tests__/ElevationUtils-test.js
Labels: pending review, review

#3085 Port minor fixes to 2018.02.00
  web/client/plugins/Annotations.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/HelpLink.jsx
  web/client/plugins/Save.jsx
  web/client/plugins/SaveAs.jsx
  web/client/plugins/Tutorial.jsx
  web/client/product/plugins/About.jsx
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3091 Fix #3087 support viewparams in featuregrid
  web/client/actions/__tests__/wfsquery-test.js
  web/client/actions/wfsquery.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
  web/client/observables/wfs.js
  web/client/plugins/widgetbuilder/enhancers/connection/viewportBuilderConnect.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/ogc/WFS/RequestBuilder.js
Labels: pending review, review

#3094 Fix #3088 viewparams support for widgets
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/CounterWizard.jsx
  web/client/components/widgets/enhancers/__tests__/dependenciesToOptions-test.jsx
  web/client/components/widgets/enhancers/dependenciesToOptions.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/triggerFetch-test.js
  web/client/components/widgets/enhancers/wfsTable/noPaginationFetch.js
  web/client/components/widgets/enhancers/wfsTable/triggerFetch.js
  web/client/components/widgets/enhancers/wfsTable/virtualScrollFetch.js
  web/client/components/widgets/enhancers/wpsChart.js
  web/client/components/widgets/enhancers/wpsCounter.js
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/epics/widgets.js
  web/client/observables/wfs.js
  web/client/observables/wps/aggregate.js
  web/client/selectors/widgets.js
  web/client/utils/ogc/WFS/RequestBuilder.js
Labels: pending review, review

#3097 Fix #3095 fix a bug related to dashboard catalog with wms
  web/client/components/catalog/CompactCatalog.jsx
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: pending review, review

#3064 Fix #3062 update default print style for polygons
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: pending review, review

#3099 Port minor fixes to 2018.02.00 dashboard related
  docs/developer-guide/developing.md
  project/custom/templates/.gitignore
  project/custom/templates/build.sh
  project/standard/templates/.gitignore
  project/standard/templates/build.sh
  project/standard/templates/web/pom.xml
  web/client/components/catalog/CompactCatalog.jsx
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Dashboard, pending review, review

#3103 Geonode integration fixes
  web/client/jsapi/MapStore2.js
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: pending review, review

#3100 Fix #3090 cql filter support for charts
  web/client/components/widgets/enhancers/__tests__/dependenciesToFilter-test.jsx
  web/client/components/widgets/enhancers/dependenciesToFilter.js
  web/client/components/widgets/enhancers/dependenciesToOptions.js
  web/client/components/widgets/enhancers/utils.js
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
  web/client/utils/ogc/Filter/fromObject.js
Labels: pending review, review

#3086 Fix #2686: Loading custom search services in embedded
  web/client/product/embedded.jsx
Labels: pending review, review

#3108 Update documentation for development
  docs/developer-guide/developing.md
Labels: pending review, review

#3107 Fix #3089. Support for CQL_FILTER in feature grid
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/VendorParamsUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/mapinfo/wms.js
  web/client/utils/mapinfo/wmts.js
Labels: pending review, review

#3111 Add possibility to extend and reconfigure pluginsConfigs
  web/client/containers/MapViewer.jsx
  web/client/product/components/viewer/MapViewerCmp.jsx
Labels: pending review, review

#3115 Fix #3112. Removed old configuration from localConfig
  web/client/localConfig.json
Labels: pending review, review

#3116 Fix #3112. Removed old configuration from localConfig (Porting 2018.02.00)
  web/client/localConfig.json
Labels: pending review, review

#3118 Fix #3113 featuregrid synch popover updates its position accordingly
  web/client/components/data/featuregrid/enhancers/withPopover.js
  web/client/components/data/featuregrid/toolbars/toolbar.css
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
Labels: pending review, review

#3120 Fix #3113 featuregrid synch popover (Porting 2018.02.00)
  web/client/components/data/featuregrid/enhancers/withPopover.js
  web/client/components/data/featuregrid/toolbars/toolbar.css
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
Labels: pending review, review

#3130 Improvements on French language file
  web/client/translations/data.fr-FR
Labels: backlog, review

#3126 Replacing Value with Use
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review
