Repository geosolutions-it/MapStore2, pull requests merged in 2018-10, with the labels that each got.

#3210 Closes #3209
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/plugins/TOCItemsSettings.jsx
Labels: pending review, review

#3207 Removes console logs from browser from karma testing output
  testConfig.js
Labels: pending review, review

#3213 Revert "hiding the wrapped div" (porting)
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/components/misc/quillmodules/ResizeModule.js
  web/client/components/resources/modals/DetailSheet.jsx
Labels: pending review, review

#3212 Revert "hiding div to allow playing/showing the video"
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/components/misc/quillmodules/ResizeModule.js
  web/client/components/resources/modals/DetailSheet.jsx
Labels: pending review, review

#3216 Fix #3214 download outputFormat issue for porting of PR (#3215)for 2018.02.xx
  web/client/epics/__tests__/wfsdownload-test.js
  web/client/epics/wfsdownload.js
  web/client/utils/ConfigUtils.js
  web/client/utils/__tests__/ConfigUtils-test.js
Labels: pending review, review

#3215 Fix #3214. Remove duplicated ? from request in download
  web/client/epics/__tests__/wfsdownload-test.js
  web/client/epics/wfsdownload.js
  web/client/utils/ConfigUtils.js
  web/client/utils/__tests__/ConfigUtils-test.js
Labels: pending review, review

#3219 updating joyride dependency
  package.json
Labels: Priority: Medium, Project: C126, bug, pending review, review

#3221 Porting of the fix for #3156 on 2018.02.xx
  package.json
Labels: Priority: Medium, Project: C126, bug, pending review, review

#3222 Updated Croatian translation (#3218) - backport to 2018.02.xx
  web/client/translations/data.hr-HR
Labels: enhancement

#3223 adding map.mapID as a selector
  web/client/selectors/map.js
Labels: Priority: High, bug, pending review, review

#3234 Porting of the fix for #3197 on 2018.02.xx #3223
  web/client/selectors/map.js
Labels: Priority: High, bug, pending review, review

#3239 Fix #3235 CQL_FILTER is removed correctly when sync tool is de-selected
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
Labels: OL3, Priority: High, Project: C028, bug, pending review, review

#3240 #3237 Removes the use of StandardRouter from MapStore 2 jsapi
  web/client/components/app/StandardContainer.jsx
  web/client/components/app/__tests__/StandardContainer-test.jsx
  web/client/jsapi/MapStore2.js
Labels: pending review, review

#3247 Baloola timeline
  web/client/components/playback/Playback.jsx
  web/client/epics/playback.js
  web/client/plugins/Playback.jsx
  web/client/selectors/playback.js
  web/client/themes/default/less/timeline.less
Labels: pending review, review

#3246 Fix #3243 circle radius problem for openlayers
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: OL3, Priority: High, Project: C028, bug, pending review, review

#3254 Fix #3121 searchText in catalog is reset after adding a new catalog service
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/components/catalog/Catalog.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
Labels: Priority: High, bug, pending review, review

#3260 Fix #3174 delete annotations from GFI panel
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/epics/maplayout.js
  web/client/plugins/Annotations.jsx
  web/client/selectors/annotations.js
Labels: Priority: High, bug, pending review, review

#3263 Porting of the fix for #3121 on 2018.02.xx
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/components/catalog/Catalog.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
Labels: Priority: High, bug, pending review, review

#3261 Porting of fix for #3243 on 2018.02.xx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: OL3, Priority: High, Project: C028, pending review, review

#3265 porting of fix #3174 (PR #3260) on 2018.02.xx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/epics/maplayout.js
  web/client/plugins/Annotations.jsx
  web/client/selectors/annotations.js
Labels: Priority: High, bug, pending review, review

#3268 Baloola timeline
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/timeline/Timeline.jsx
  web/client/selectors/timeline.js
Labels: Timeline, geonode_integration, pending review, review

#3270 Timeline functionalities
  package.json
  web/client/actions/__tests__/dimension-test.js
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/dimension.js
  web/client/actions/playback.js
  web/client/actions/timeline.js
  web/client/api/MultiDim.js
  web/client/api/__tests__/MultiDim-test.js
  web/client/components/playback/Playback.jsx
  web/client/epics/dimension.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/localConfig.json
  web/client/observables/ogcDimension.js
  web/client/observables/pausable.js
  web/client/plugins/Playback.jsx
  web/client/plugins/Timeline.jsx
  web/client/plugins/timeline/InlineDateTimeSelector.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/dimension-test.js
  web/client/reducers/dimension.js
  web/client/reducers/playback.js
  web/client/reducers/timeline.js
  web/client/selectors/dimension.js
  web/client/selectors/playback.js
  web/client/selectors/timeline.js
  web/client/selectors/widgets.js
  web/client/stores/StandardStore.js
  web/client/test-resources/wmts/DescribeDomains.xml
  web/client/test-resources/wmts/DomainValues.xml
  web/client/test-resources/wmts/Histogram1.xml
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/less/timeline.less
  web/client/themes/default/ms2-theme.less
  web/client/utils/ObservableUtils.js
  web/client/utils/ReselectUtils.js
  web/client/utils/TimeUtils.js
  web/client/utils/__tests__/TimeUtils-test.js
Labels: pending review, review

#3256 Fixes #3155 and Fixes #3266 and loads fontAwesome when the application starts
  package.json
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/notifications/NotificationContainer.jsx
  web/client/components/notifications/__tests__/NotificationContainer-test.jsx
  web/client/plugins/Map.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: OL3, Priority: Medium, bug, pending review, review

#3295 porting of fix #3155 (PR #3256) on 2018.02.xx
  package.json
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/notifications/NotificationContainer.jsx
  web/client/components/notifications/__tests__/NotificationContainer-test.jsx
  web/client/plugins/Map.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: OL3, Priority: Medium, bug, pending review, review

#3299 Fix #3298 Update travis.yml in order to match stable branch name 2018.02.xx
  .travis.yml
Labels: Environment, Priority: High, pending review, review

#3293 Update ConfigProvider.js with LINZ WMTS provider
  web/client/utils/ConfigProvider.js
Labels: review

#3297 fix qa build
  web/client/utils/LocaleUtils.js
Labels: pending review, review

#3291 TimeLine animation range
  web/client/api/MultiDim.js
  web/client/epics/playback.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/selectors/playback.js
Labels: Timeline, geonode_integration, pending review, review

#3301 TimeLine initial setup
  web/client/epics/timeline.js
  web/client/plugins/Timeline.jsx
Labels: Timeline, geonode_integration, pending review, review

#3269 Introduce withRef connect option in plugins connected components
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/plugins/__tests__/PluginsContainer-test.jsx
  web/client/utils/PluginsUtils.js
Labels: pending review, review
