Repository geosolutions-it/MapStore2, pull requests merged in 2018-05, with the labels that each got.

#2848 Add support for epics in c039 branch
  web/client/utils/DebugUtils.js
  web/client/utils/PluginsUtils.js
Labels: pending review, review

#2841 Fixes #2824: enable elevation layer only for cesium or when mouseposition is enabled
  web/client/plugins/Map.jsx
Labels: pending review, review

#2847 fix #2803 synch popover defaults
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
Labels: pending review, review

#2846 fix #2825 interactions between featuregrid anche chart wizard
  web/client/components/data/featuregrid/enhancers/withHint.js
  web/client/components/data/featuregrid/enhancers/withPopover.js
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/plugins/widgetbuilder/enhancers/withMapExitButton.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2839 Fixes #2838 Remove github link from navbar in homepage
  web/client/product/assets/img/GitHub-Mark-32px.png
  web/client/product/plugins/Fork.jsx
Labels: pending review, review

#2853 fix #2852 dev build fails
  web/client/components/dashboard/modals/fragments/DetailsRow.jsx
Labels: pending review, review

#2855 Fix #2825. Fixed error message for layers with no attributes
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2849 Fix #2563: Fixed unnecessary details request on Map open
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
  web/client/test-resources/geostore/resources/resource/2/attributes
Labels: pending review, review

#2850 Fixes #2700 Toolbar icon for 3D map
  web/client/components/buttons/GlobeViewSwitcherButton.jsx
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
Labels: pending review, review

#2869 Minor fixes to localized strings
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2871 Fix #2870 Compact new map/dashboard buttons
  web/client/plugins/CreateNewMap.jsx
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
Labels: pending review, review

#2868 Fix #2843 and Fix #2659. Fixed resize issues on dashboard and map widgets
  web/client/components/dashboard/Dashboard.jsx
  web/client/components/layout/enhancers/__tests__/gridLayout-test.js
  web/client/components/layout/enhancers/gridLayout.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/plugins/Widgets.jsx
Labels: pending review, review

#2873 Fix #2872 GeoFence Admin Rule Icon
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
Labels: pending review, review

#2857 Fix #2856 Legend action plugin
  docma-config.json
  web/client/actions/__tests__/floatinglegend-test.js
  web/client/actions/floatinglegend.js
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/FloatingLegend.jsx
  web/client/components/TOC/__tests__/DefaultLayer-test.jsx
  web/client/components/TOC/__tests__/FloatingLegend-test.jsx
  web/client/components/misc/Slider.jsx
  web/client/components/misc/cardgrids/SideGrid.jsx
  web/client/epics/identify.js
  web/client/localConfig.json
  web/client/plugins/DrawerMenu.jsx
  web/client/plugins/FloatingLegend.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/floatinglegend.js
  web/client/reducers/floatinglegend.js
  web/client/selectors/__tests__/floatinglegend-test.js
  web/client/selectors/floatinglegend.js
  web/client/selectors/map.js
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: pending review, review

#2877 Fix #2876 Cross layer filter doesn't work if layer has localized title
  web/client/components/misc/enhancers/localizeStringMap.js
  web/client/plugins/FloatingLegend.jsx
  web/client/selectors/queryform.js
  web/client/utils/LocaleUtils.js
  web/client/utils/__tests__/LocaleUtils-test.js
Labels: pending review, review

#2886 Temporary disabled video from detail sheet
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/components/resources/modals/DetailSheet.jsx
Labels: pending review, review

#2884 Fix #2842. Add legend widget
  web/client/actions/widgets.js
  web/client/components/TOC/FloatingLegend.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/misc/cardgrids/SideGrid.jsx
  web/client/components/misc/cardgrids/__tests__/SideGrid-test.jsx
  web/client/components/widgets/builder/WidgetTypeSelector.jsx
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/builder/wizard/__tests__/LegendWizard-test.jsx
  web/client/components/widgets/builder/wizard/legend/Toolbar.jsx
  web/client/components/widgets/enhancers/emptyLegendState.js
  web/client/components/widgets/enhancers/legendWidget.js
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/components/widgets/widget/LegendWidget.jsx
  web/client/components/widgets/widget/__tests__/LegendView-test.jsx
  web/client/components/widgets/widget/__tests__/LegendWidget-test.jsx
  web/client/epics/widgets.js
  web/client/plugins/Dashboard.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/plugins/widgetbuilder/LegendBuilder.jsx
  web/client/plugins/widgetbuilder/WidgetTypeBuilder.jsx
  web/client/plugins/widgetbuilder/enhancers/connection/legendBuilderConnect.js
  web/client/themes/default/less/toc.less
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/WidgetsUtils.js
Labels: pending review, review

#2895 Fixed home button position
  web/client/localConfig.json
Labels: pending review, review

#2899 Fix #2862. Add geofence icon to the manager menu
  web/client/plugins/manager/ManagerMenu.jsx
Labels: pending review, review

#2904 Fix #2903. Add support to hide spatial and cross layer filter
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/__tests__/QueryBuilder-test.jsx
  web/client/localConfig.json
  web/client/plugins/QueryPanel.jsx
Labels: pending review, review

#2905 fix #2696 map rotation disables correctly
  web/client/plugins/Map.jsx
Labels: Project: C040, pending review, review

#2863 fix #2861 layer metadata layout
  web/client/themes/default/less/modal.less
Labels: Project: C125, pending review, review

#2865 fix #2864 properties row viewer
  web/client/components/data/identify/viewers/row/PropertiesViewer.jsx
  web/client/components/data/identify/viewers/row/__tests__/PropertiesViewer-test.jsx
  web/client/utils/StringUtils.js
  web/client/utils/__tests__/StringUtils-test.js
Labels: Project: C125, pending review, review

#2900 Fix #2898 TOC moves down if Measure tool and print are opened
  web/client/plugins/FloatingLegend.jsx
Labels: pending review, review

#2902 fix #2711 remove arc layer when toggling length measure tool (leaflet)
  web/client/components/map/leaflet/MeasurementSupport.jsx
Labels: LeafLetJS, Project: C125, pending review, review

#2907 RuleEditor Layers filter always enabled
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/LayersFilter.jsx
Labels: pending review, review

#2897 fix #2709 annotations editor layout
  web/client/themes/default/less/annotations.less
Labels: Project: C125, pending review, review

#2875 49 great circle annotations
  web/client/components/map/leaflet/MeasurementSupport.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Project: C125, pending review, review

#2880 fix #2879 add highlight for text annotations
  web/client/components/map/openlayers/VectorStyle.js
Labels: Project: C125, pending review, review

#2906 Showing spatial filter selection area when FeatureGrid is open
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/Map.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/highlight-test.js
  web/client/selectors/highlight.js
Labels: pending review, review

#2919 Include printing fixes from master and fix the color of line vector when printing
  package.json
  web/client/utils/ColorUtils.js
  web/client/utils/PrintUtils.js
Labels: pending review, review

#2917 Modify SaveLayer in order to take the custom origin of a wms layer
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: backlog, review

#2896 Fix #2893 Improve CSW management of OGC:WMS reference and bounding box, Fix #2883 Red screen error on catalog
  web/client/api/CSW.js
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/epics/wfsquery.js
  web/client/plugins/CreateNewMap.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: pending review, review

#2921 Enhancement #2603: details on map cards can be enabled/disabled from localConfig
  web/client/actions/__tests__/maps-test.js
  web/client/actions/maps.js
  web/client/components/maps/MapCard.jsx
  web/client/components/maps/MapGrid.jsx
  web/client/plugins/Maps.jsx
  web/client/plugins/maps/MapsGrid.jsx
  web/client/plugins/maps/MetadataModal.jsx
  web/client/reducers/__tests__/maps-test.js
  web/client/reducers/maps.js
  web/client/selectors/__tests__/maps-test.js
  web/client/selectors/maps.js
Labels: pending review, review

#2909 Update Chinese i18n (zh-ZH)
  web/client/translations/data.zh-ZH
Labels: pending review, review

#2924 Improved dashboard viewmode style
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/themes/default/less/widget.less
Labels: pending review, review

#2925 Fixes #2441: introduces scale parameter for WMS GetLegendGraphic in print
  buildConfig.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: pending review, review

#2915 Fix #2914 Mismatch between DrawSupport radius length and distance length of Measure Plugin (openlayers)
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/data/query/SpatialFilter.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/plugins/QueryPanel.jsx
Labels: pending review, review

#2920 Fixes #2918: quick fix to printing styles of vector
  web/client/utils/PrintUtils.js
Labels: pending review, review

#2929 Configurable "New dashboard" button visibility
  docma-config.json
  web/client/plugins/CreateNewMap.jsx
Labels: pending review, review

#2930 Fixed tooltips for charts and widgets
  web/client/components/widgets/builder/wizard/chart/Toolbar.jsx
  web/client/components/widgets/builder/wizard/counter/Toolbar.jsx
  web/client/components/widgets/builder/wizard/legend/Toolbar.jsx
  web/client/components/widgets/builder/wizard/map/Toolbar.jsx
  web/client/components/widgets/builder/wizard/table/Toolbar.jsx
  web/client/components/widgets/builder/wizard/text/Toolbar.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review

#2913 RuleEditor - minor fixes
  web/client/components/manager/rulesmanager/ruleseditor/EditMain.jsx
  web/client/components/manager/rulesmanager/ruleseditor/Header.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/EditMain-test.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/Header-test.jsx
  web/client/components/manager/rulesmanager/ruleseditor/attributeselectors/Layer.jsx
  web/client/plugins/manager/EditorEnhancer.js
  web/client/plugins/manager/RulesEditor.jsx
  web/client/themes/default/less/rulesmanager.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/RulesEditor.js
Labels: pending review, review

#2933 fix #2861 extra scrollbar when dragging down layer metadata modal
  web/client/localConfig.json
  web/client/themes/default/less/modal.less
Labels: Priority: High, Project: C125, bug, pending review, review

#2935 fix 2934 removed singlePage option, change default value virtualScroll
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
Labels: pending review, review

#2940 Fix #2939 Wrong geometry update and center of geodesic circle in query panel
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/SpatialFilter.jsx
  web/client/components/data/query/__tests__/GeometryDetails-test.jsx
  web/client/components/map/leaflet/DrawSupport.jsx
  web/client/components/map/leaflet/__tests__/DrawSupport-test.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/plugins/QueryPanel.jsx
Labels: pending review, review

#2938 Fix #2306: preserving changes on map after login
  web/client/epics/__tests__/login-test.js
  web/client/epics/login.js
  web/client/selectors/__tests__/mapInitialConfig-test.js
  web/client/selectors/mapInitialConfig.js
Labels: pending review, review

#2952 Fix #2951 circle draw and styles annotations
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/style/CircleStyler.jsx
  web/client/components/style/PolygonStyler.jsx
  web/client/components/style/PolylineStyler.jsx
  web/client/components/style/TextStyler.jsx
Labels: Project: C125, pending review, review

#2944 Fixed #2943 use https for nominatim URL
  web/client/api/Nominatim.js
  web/client/localConfig.json
Labels: pending review, review
