Repository geosolutions-it/MapStore2, pull requests merged in 2018-04, with the labels that each got.

#2791 Multiple map connection support
  web/client/actions/__tests__/widgets-test.js
  web/client/actions/widgets.js
  web/client/components/dashboard/Dashboard.jsx
  web/client/components/misc/enhancers/__tests__/withMask-test.jsx
  web/client/components/misc/enhancers/withMask.js
  web/client/components/misc/enhancers/withPropsStream.js
  web/client/components/widgets/enhancers/dependenciesToWidget.js
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/view/enhancers/__tests__/withSelection-test.jsx
  web/client/components/widgets/view/enhancers/withSelection.js
  web/client/epics/__tests__/widgets-test.js
  web/client/epics/widgets.js
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/plugins/widgetbuilder/ChartBuilder.jsx
  web/client/plugins/widgetbuilder/CounterBuilder.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/plugins/widgetbuilder/enhancers/connection/mapBuilderConnect.js
  web/client/plugins/widgetbuilder/enhancers/connection/mapBuilderConnectMask.jsx
  web/client/plugins/widgetbuilder/enhancers/connection/mapPositionConnect.js
  web/client/plugins/widgetbuilder/enhancers/connection/viewportBuilderConnect.js
  web/client/plugins/widgetbuilder/enhancers/connection/viewportBuilderConnectMask.jsx
  web/client/plugins/widgetbuilder/enhancers/connection/viewportConnect.js
  web/client/plugins/widgetbuilder/enhancers/connection/withConnectButton.js
  web/client/plugins/widgetbuilder/enhancers/connection/withMapConnect.js
  web/client/plugins/widgetbuilder/enhancers/connection/withViewportConnectButtons.js
  web/client/plugins/widgetbuilder/enhancers/mapToolbar.js
  web/client/selectors/widgets.js
  web/client/themes/default/less/common.less
  web/client/themes/default/less/widget.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: In Test, pending review, review

#2771 Fixes #1506 OpenLayers and Leaflet vector different default styles
  package.json
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/leaflet/__tests__/Feature-test.jsx
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
  web/client/utils/ColorUtils.js
  web/client/utils/__tests__/ColorUtils-test.js
Labels: In Test, review

#2793 Fix #2662. Add widget connections and colors
  web/client/actions/dashboard.js
  web/client/components/dashboard/Dashboard.jsx
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/enhancers/withGroupColor.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/TextWidget.jsx
  web/client/components/widgets/widget/WidgetContainer.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/plugins/widgetbuilder/enhancers/connection/withConnectButton.js
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/dashboard.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/widgets.js
  web/client/test-resources/widgets/complex_graph.json
  web/client/test-resources/widgets/widgets1.json
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/GraphUtils.js
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: In Test, review

#2795 Improved suggestion when the user can not create a widget
  web/client/components/misc/Overlay.jsx
  web/client/components/widgets/widget/InfoPopover.jsx
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: In Test, review

#2796 Charts builder improvements
  web/client/components/charts/Pie.jsx
  web/client/components/charts/SimpleChart.jsx
  web/client/components/widgets/builder/wizard/chart/ChartType.jsx
Labels: In Test, pending review, review

#2792 Fixed color style in pdf print
  package.json
  web/client/utils/ColorUtils.js
  web/client/utils/PrintUtils.js
Labels: In Test, review

#2800 Fix #2798 search clickable
  docma-config.json
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/examples/3dviewer/containers/Viewer.jsx
  web/client/plugins/MapSearch.jsx
  web/client/themes/default/less/map-search-bar.less
Labels: pending review, review

#2802 Add empty state to featuregrid widget
  TableWidget.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
Labels: pending review, review

#2788 Fix #2787 Panels hide the feature info marker
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/identify.js
  web/client/epics/maplayout.js
  web/client/plugins/Identify.jsx
  web/client/product/embedded.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/__tests__/maplayout-test.js
  web/client/reducers/mapInfo.js
  web/client/reducers/maplayout.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/__tests__/maplayout-test.js
  web/client/selectors/layers.js
  web/client/selectors/maplayout.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: In Test, review

#2805 Merge pull request #1 from geosolutions-it/master
  web/client/translations/data.zh-ZH
Labels: backlog, review

#2810 Fixed #2809. Moved utility function in the proper place
  package.json
  web/client/components/app/StandardApp.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/observables/wfs.js
  web/client/product/pages/Dashboard.jsx
  web/client/test-resources/localConfig.json
  web/client/utils/FilterUtils.jsx
Labels: pending review, review

#2804 Fixed layout of counter widget
  web/client/components/layout/BorderLayout.jsx
  web/client/components/widgets/builder/wizard/CounterWizard.jsx
  web/client/components/widgets/widget/CounterView.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/WidgetContainer.jsx
  web/client/components/widgets/widget/__tests__/CounterView-test.jsx
  web/client/themes/default/less/widget.less
Labels: pending review, review

#2813 Add empty map to map selector
  web/client/components/maps/MapCatalog.jsx
  web/client/components/maps/__tests__/MapCatalog-test.jsx
  web/client/components/maps/enhancers/enhancers.js
  web/client/components/maps/enhancers/mapCatalog.js
  web/client/components/maps/enhancers/mapCatalogWithEmptyMap.js
  web/client/components/misc/enhancers/infiniteScroll/withScrollSpy.js
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/builder/wizard/map/MapSelector.jsx
  web/client/components/widgets/builder/wizard/map/__tests__/MapOptions-test.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2814 Fix #2794 Force update of map widget position on save
  web/client/components/widgets/builder/wizard/map/PreviewMap.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/previewMap-test.js
  web/client/components/widgets/builder/wizard/map/enhancers/previewMap.js
Labels: pending review, review

#2808 Fix #2807 and add a tool to create chart from feature grid
  web/client/actions/__tests__/widgets-test.js
  web/client/actions/widgets.js
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/widgetsbuilder.js
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/selectors/featuregrid.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2817 Exclude google background #2786 from widgets
  web/client/components/widgets/builder/wizard/map/MapSelector.jsx
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: pending review, review

#2818 Fix #2812 parseInitialState function
  web/client/components/app/StandardApp.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/utils/FeatureGridUtils.js
Labels: pending review, review

#2819 Fix #2790 improved wizard messages
  web/client/components/catalog/CatalogForm.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/misc/enhancers/localizeStringMap.js
  web/client/components/misc/enhancers/localizedProps.js
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/builder/wizard/map/MapSelector.jsx
  web/client/plugins/widgetbuilder/Catalog.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2816 Fixes #2815: elevation support in MousePosition, through elevation layers
  docs/developer-guide/maps-configuration.md
  package.json
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/Layer.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/mapcontrols/mouseposition/MousePosition.jsx
  web/client/components/mapcontrols/mouseposition/__tests__/MousePosition-test.js
  web/client/plugins/Map.jsx
  web/client/plugins/MousePosition.jsx
  web/client/plugins/TOC.jsx
  web/client/test-resources/elevation.bin
  web/client/themes/default/less/mouse-position.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
  web/client/utils/ElevationUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/ElevationUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/cesium/BILTerrainProvider.js
  web/client/utils/cesium/ClickUtils.js
Labels: MEV, Project: C040, pending review, review

#2821 fix #2807 back interaction from widget to feature grid
  web/client/epics/widgetsbuilder.js
  web/client/plugins/widgetbuilder/enhancers/withMapExitButton.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
Labels: MEV, Project: C040, pending review, review

#2829 Fix #2803 add popover overlay to the sync tool in feature grid
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/components/data/featuregrid/enhancers/withHint.js
  web/client/components/data/featuregrid/enhancers/withPopover.js
  web/client/components/data/featuregrid/enhancers/withTooltip.js
  web/client/components/data/featuregrid/toolbars/TButton.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/components/widgets/widget/InfoPopover.jsx
  web/client/epics/maplayout.js
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/themes/default/less/common.less
  web/client/themes/default/variables.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: MEV, Project: C040, pending review, review

#2820 Fix #2696 map rotation style for openlayers
  web/client/localConfig.json
  web/client/themes/default/less/ol.less
Labels: MEV, OL3, Project: C040, pending review, review

#2834 fix #2835 Build of mapstore
  web/client/plugins/featuregrid/panels/index.jsx
Labels: pending review, review

#2831 Fix #2798 change configuration and make search icon clickable and configurable
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/localConfig.json
  web/client/plugins/MapSearch.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/manager/GroupManager.jsx
  web/client/plugins/manager/UserManager.jsx
  web/client/themes/default/less/map-search-bar.less
Labels: MEV, Project: C040, pending review, review

#2833 Fix #2825. Improved messages in case of no attributes layer
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/CounterWizard.jsx
  web/client/components/widgets/builder/wizard/__tests__/CounterWizard-test.jsx
  web/client/components/widgets/builder/wizard/common/noAttributesEmptyView.js
  web/client/components/widgets/builder/wizard/counter/Toolbar.jsx
  web/client/components/widgets/builder/wizard/counter/__tests__/Toolbar-test.jsx
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/builder/wizard/table/Toolbar.jsx
  web/client/components/widgets/builder/wizard/table/__tests__/TableOptions-test.jsx
  web/client/localConfig.json
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#2836 #2827 Minor fixes
  web/client/actions/maps.js
  web/client/components/maps/MapCard.jsx
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/Maps.jsx
  web/client/reducers/__tests__/featuredmaps-test.js
  web/client/reducers/featuredmaps.js
  web/client/selectors/featuredmaps.js
  web/client/themes/default/less/maps-properties.less
  web/client/themes/default/less/square-button.less
Labels: pending review, review

#2832 Fix #2660 implemented first version of save functionalities for dashboard
  web/client/actions/__tests__/dashboard-test.js
  web/client/actions/dashboard.js
  web/client/api/GeoStoreDAO.js
  web/client/components/dashboard/forms/Metadata.jsx
  web/client/components/dashboard/forms/Thumbnail.jsx
  web/client/components/dashboard/forms/__tests__/Metadata-test.jsx
  web/client/components/dashboard/forms/__tests__/Thumbnail-test.jsx
  web/client/components/dashboard/modals/Confirm.jsx
  web/client/components/dashboard/modals/DetailSheet.jsx
  web/client/components/dashboard/modals/Save.jsx
  web/client/components/dashboard/modals/__tests__/Confirm-test.jsx
  web/client/components/dashboard/modals/__tests__/Save-test.jsx
  web/client/components/dashboard/modals/enhancers/__tests__/handlePermission-test.jsx
  web/client/components/dashboard/modals/enhancers/__tests__/handleResourceData-test.jsx
  web/client/components/dashboard/modals/enhancers/handlePermission.jsx
  web/client/components/dashboard/modals/enhancers/handleResourceData.jsx
  web/client/components/dashboard/modals/enhancers/ruleEditor.js
  web/client/components/dashboard/modals/fragments/DetailsRow.jsx
  web/client/components/dashboard/modals/fragments/ErrorBox.jsx
  web/client/components/dashboard/modals/fragments/MainForm.jsx
  web/client/components/dashboard/modals/fragments/PermissionEditor.jsx
  web/client/epics/dashboard.js
  web/client/epics/widgets.js
  web/client/localConfig.json
  web/client/observables/epics.js
  web/client/observables/geostore.js
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/dashboard/SaveDialog.jsx
  web/client/product/appConfig.js
  web/client/product/pages/Dashboard.jsx
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/dashboard.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/security.js
  web/client/selectors/widgets.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review
