Repository geosolutions-it/MapStore2, pull requests merged in 2018-11, with the labels that each got.

#3305 Fix #3304 update default backgrounds
  web/client/new.json
  web/client/plugins/BackgroundSelector.jsx
  web/client/plugins/background/assets/img/s2cloudless.jpg
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
Labels: Priority: High, bug, pending review, review

#3308 porting of fix #3298 for travis build (PR #3299) on 2018.02.xx
  .travis.yml
Labels: Environment, Priority: High, pending review, review

#3307 porting of fix #3304 (PR #3305) on 2018.02.xx
  web/client/new.json
  web/client/plugins/BackgroundSelector.jsx
  web/client/plugins/background/assets/img/s2cloudless.jpg
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
Labels: Priority: High, bug, pending review, review

#3294 #3236 Added maptypeselector to Print plugin connect function
  web/client/plugins/Print.jsx
Labels: geonode_integration, pending review, review

#3310 Fix #3309 Hints doesn't show up in style editor
  web/client/components/styleeditor/Editor.jsx
  web/client/themes/default/less/style-editor.less
Labels: pending review, review

#3314 Fix #3313 Style Editor doesn't work after building the application
  web/client/plugins/StyleEditor.jsx
Labels: pending review, review

#3318 Fix #3316 Style editor role management, Fix #3317 TOCItemSettings doesn't save from alert modal
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/enhancers/__tests__/tocitemssettings-test.js
  web/client/components/TOC/enhancers/tocItemsSettings.js
  web/client/epics/styleeditor.js
  web/client/plugins/StyleEditor.jsx
  web/client/plugins/styleeditor/index.js
Labels: pending review, review

#3320 Fix #3319. Fixed Nav menu and add some documentation
  web/client/product/plugins/NavMenu.jsx
Labels: pending review, review

#3321 Fix #3319. Fixed issue and add some documentation (Back port 2018.02.xx)
  web/client/product/plugins/NavMenu.jsx
Labels: pending review, review

#3296 Adding arcgis layer from geonode csw catalog
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: pending review, review

#3322 Fix #3155 font loading errors
  package.json
  web/client/plugins/Map.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
  web/client/utils/AgentUtils.js
Labels: OL3, Priority: Medium, bug, pending review, review

#3328 Fix #3279. Added settings form for timeline
  web/client/actions/playback.js
  web/client/components/misc/switch/SwitchButton.jsx
  web/client/components/playback/Playback.jsx
  web/client/components/playback/PlaybackSettings.jsx
  web/client/components/playback/__tests__/PlaybackSettings-test.jsx
  web/client/components/time/InlineDateTimeSelector.jsx
  web/client/plugins/Playback.jsx
  web/client/plugins/Timeline.jsx
  web/client/reducers/playback.js
  web/client/selectors/playback.js
  web/client/themes/default/less/switch.less
  web/client/themes/default/less/timeline.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3327 Widget Builder and Catalog are not contained in Map Viewer of API
  web/client/components/misc/panels/DockPanel.jsx
  web/client/components/misc/panels/__tests__/DockPanel-test.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/WidgetsBuilder.jsx
Labels: pending review, review

#3325 Timline_range_interaction
  package.json
  web/client/actions/dimension.js
  web/client/actions/playback.js
  web/client/actions/timeline.js
  web/client/components/playback/PlaybackSettings.jsx
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/Playback.jsx
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/plugins/timeline/TimelineComponent.jsx
  web/client/reducers/dimension.js
  web/client/reducers/timeline.js
  web/client/selectors/dimension.js
  web/client/selectors/playback.js
  web/client/selectors/timeline.js
  web/client/themes/default/less/timeline.less
Labels: Timeline, geonode_integration, pending review, review

#3331 Fix #3282. Implemented range animation
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/dimension.js
  web/client/actions/timeline.js
  web/client/epics/dimension.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/reducers/dimension.js
  web/client/reducers/timeline.js
  web/client/selectors/dimension.js
  web/client/selectors/timeline.js
Labels: pending review, review

#3333 Fix #3285 Timeline scroll
  web/client/epics/timeline.js
  web/client/plugins/timeline/Timeline.jsx
  web/client/themes/default/less/timeline.less
Labels: pending review, review

#3339 Support for local values in animation
  web/client/epics/playback.js
  web/client/observables/epics.js
  web/client/selectors/timeline.js
Labels: pending review, review

#3340 fixing the elevation altering bug and rang/playback conflict
  web/client/epics/dimension.js
  web/client/epics/timeline.js
Labels: bug, pending review, review

#3342 Fix #3264. localization for timeline and some fixes
  web/client/epics/dimension.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Timeline, geonode_integration, pending review, review

#3343 Fix #3341 Implemented playback range, forward/backward
  web/client/actions/playback.js
  web/client/components/playback/PlaybackSettings.jsx
  web/client/components/playback/__tests__/PlaybackSettings-test.jsx
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/playback/Playback.jsx
  web/client/selectors/dimension.js
  web/client/selectors/playback.js
  web/client/selectors/timeline.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Timeline, pending review, review

#3346 Fix #3251 add autoSelect option to force guide layer selection
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/reducers/timeline.js
  web/client/selectors/timeline.js
Labels: pending review, review

#3349 fix #3345 adding a check for timeline data before expanding the component
  web/client/plugins/Timeline.jsx
  web/client/selectors/timeline.js
Labels: Timeline, geonode_integration, pending review, review

#3347 Fix #3344 queryable layers not filtered anymore by clicked point layer
  web/client/components/data/identify/Identify.jsx
  web/client/components/data/identify/__tests__/Identify-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
Labels: Priority: High, Project: C125, bug, pending review, review

#3351 Fix #3267. Sync with map layout. other minor fixes
  web/client/epics/playback.js
  web/client/plugins/Timeline.jsx
Labels: pending review, review

#3358 Initial setup and catalog support
  web/client/api/MultiDim.js
  web/client/epics/dimension.js
  web/client/epics/timeline.js
  web/client/selectors/timeline.js
Labels: pending review, review

#3354 fix #3278 Disable tools during animation
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/themes/default/less/timeline.less
Labels: Timeline, geonode_integration, pending review, review

#3362 Fix #3361. Autohide timeline when space is not enough
  web/client/plugins/Timeline.jsx
Labels: pending review, review

#3364 Fixed play button visibility
  web/client/plugins/Timeline.jsx
Labels: pending review, review

#3312 Fix #3311 fix mouse positions roundings
  web/client/components/I18N/Number.jsx
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDM.jsx
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMSNW.jsx
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: LeafLetJS, OL3, Priority: Medium, Project: C125, bug, pending review, review, user feedback

#3365 Fix #3286. Error notification and other minor fixes
  web/client/components/playback/PlaybackSettings.jsx
  web/client/epics/dimension.js
  web/client/epics/timeline.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3356 Fixes #3355: relative public path in webpack config
  package.json
  prod-webpack.config.js
  webpack.config.js
Labels: pending review, review

#3363 #3359 Timeline delete
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/reducers/__tests__/dimension-test.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/dimension.js
  web/client/reducers/timeline.js
Labels: Timeline, geonode_integration, pending review, review

#3378 Added missing croatian translations & fix typos
  web/client/translations/data.hr-HR
Labels: backlog, review

#3376 #3345 fixing the initial component re-rendering
  web/client/components/time/TimelineComponent.jsx
  web/client/components/time/__tests__/TimelineComponent-test.jsx
  web/client/plugins/Timeline.jsx
  web/client/plugins/timeline/InlineDateTimeSelector.jsx
  web/client/plugins/timeline/Timeline.jsx
Labels: Timeline, geonode_integration, pending review, review

#3377 Fix #3373. Support for disable playback buttons
  web/client/actions/playback.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/playback/Playback.jsx
  web/client/plugins/playback/Settings.jsx
  web/client/reducers/__tests__/playback-test.js
  web/client/reducers/playback.js
  web/client/selectors/playback.js
Labels: pending review, review

#3381 Use Alpine in the Dockerfile
  Dockerfile
Labels: pending review, review
