Repository geosolutions-it/MapStore2, pull requests merged in 2018-09, with the labels that each got.

#3167 check if the title is string
  web/client/components/TOC/FloatingLegend.jsx
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/__tests__/FloatingLegend-test.jsx
  web/client/components/TOC/__tests__/TOCItemsSettings-test.jsx
Labels: pending review, review

#3171 Fix #2965 Authentication Popup
  docma-config.json
  web/client/actions/__tests__/dashboard-test.js
  web/client/actions/__tests__/feedbackMask-test.js
  web/client/actions/dashboard.js
  web/client/actions/feedbackMask.js
  web/client/components/misc/enhancers/__tests__/withMask-test.jsx
  web/client/components/misc/enhancers/withMask.js
  web/client/containers/Embedded.jsx
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/dashboard.js
  web/client/epics/feedbackMask.js
  web/client/epics/login.js
  web/client/localConfig.json
  web/client/plugins/FeedbackMask.jsx
  web/client/product/apiPlugins.js
  web/client/product/plugins.js
  web/client/reducers/__tests__/feedbackMask-test.js
  web/client/reducers/feedbackMask.js
  web/client/themes/default/less/loading-mask.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3176 Fix #3153 Embedded doesn't work on ie11
  buildConfig.js
  package.json
  web/client/components/app/StandardApp.jsx
  web/client/components/app/appPolyfill.js
Labels: pending review, review

#3180 Fix #3153 Embedded doesn't work on ie11 2018.02.00
  buildConfig.js
  package.json
  web/client/components/app/StandardApp.jsx
  web/client/components/app/appPolyfill.js
Labels: pending review, review

#3187 Closes #3186
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
Labels: pending review, review

#3189 Fix #3186. Fix Firefox 62/Chrome 69 flat function conflicts (Porting)
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
Labels: pending review, review

#3184 Closes #3183 Save and SaveAs plugins - Persistence Api
  web/client/actions/__tests__/maps-test.js
  web/client/actions/maps.js
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
  web/client/plugins/Save.jsx
  web/client/plugins/SaveAs.jsx
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: pending review, review

#3181 Fixes #3104: issues with printing
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: pending review, review

#3190 Fix #2965 Authentication Popup
  docma-config.json
  web/client/actions/__tests__/dashboard-test.js
  web/client/actions/__tests__/feedbackMask-test.js
  web/client/actions/dashboard.js
  web/client/actions/feedbackMask.js
  web/client/components/errors/ResourceUnavailable.jsx
  web/client/components/errors/__tests__/ResourceUnavailable-test.jsx
  web/client/components/misc/enhancers/__tests__/withMask-test.jsx
  web/client/components/misc/enhancers/withMask.js
  web/client/containers/Embedded.jsx
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/__tests__/login-test.js
  web/client/epics/dashboard.js
  web/client/epics/feedbackMask.js
  web/client/epics/login.js
  web/client/localConfig.json
  web/client/plugins/FeedbackMask.jsx
  web/client/product/apiPlugins.js
  web/client/product/plugins.js
  web/client/reducers/__tests__/feedbackMask-test.js
  web/client/reducers/feedbackMask.js
  web/client/selectors/__tests__/feedbackmask-test.js
  web/client/selectors/feedbackmask.js
  web/client/themes/default/less/loading-mask.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3185 adding some translations
  web/client/components/data/query/ComboField.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Priority: Medium, bug, pending review, review

#3203 Porting of fix for 3051 on 2018.02.xx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TocUtils-test.js
Labels: Priority: High, bug, pending review, review

#3141 Fix #3051 toc group/layers problems
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Priority: High, bug, pending review, review

#3188 hiding div to allow playing/showing the video
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/components/misc/quillmodules/ResizeModule.js
  web/client/components/resources/modals/DetailSheet.jsx
Labels: Priority: High, bug, pending review, review

#3201 hiding the wrapped div
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/components/misc/quillmodules/ResizeModule.js
  web/client/components/resources/modals/DetailSheet.jsx
Labels: pending review, review

#3205 fixing some translations
  web/client/translations/data.de-DE
Labels: Priority: Medium, bug, pending review, review

#3204 adding missing translations (Backport 2018.02.xx)
  web/client/components/data/query/ComboField.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.zh-ZH
Labels: Priority: Medium, bug

#3206 Porting of the fix for #3192 on 2018.02.xx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/automapupdate-test.js
Labels: Priority: Blocker, bug, pending review, review

#3199 setting the default layer as object
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/automapupdate-test.js
Labels: Priority: Blocker, bug, review

#3133 Automatic definition of proj codes from configuration in OpenLayers maps
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/utils/openlayers/projUtils.js
Labels: Priority: High, enhancement, pending review, review

#3182 Fixes #2669: use https version of geosolutions maven repo
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
  web/pom.xml
Labels: Priority: High, pending review, review, task
