Repository geosolutions-it/MapStore2, pull requests merged in 2019-06, with the labels that each got.

#3830 Fix Geostore update resource and other fixes for components and utils
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
  web/client/api/persistence/index.js
  web/client/components/data/query/DateField.jsx
  web/client/components/layout/BorderLayout.jsx
  web/client/components/misc/enhancers/infiniteScroll/withScrollSpy.js
  web/client/components/security/PermissionEditor.jsx
  web/client/observables/geostore.js
  web/client/plugins/import/StyleDialog.jsx
  web/client/utils/FileUtils.js
  web/client/utils/openlayers/Icons.js
  web/client/utils/openlayers/__tests__/Icons-test.js
Labels: enhancement

#3828 Disable CSS for StyleEditor
  web/client/localConfig.json
Labels: Priority: High

#3831 Improved ui catalog and added customizable metadata template
  package-lock.json
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordGrid.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/img/default.jpg
  web/client/components/misc/cardgrids/SideCard.jsx
  web/client/components/misc/cardgrids/__tests__/SideCard-test.jsx
  web/client/components/misc/switch/SwitchPanel.jsx
  web/client/components/misc/switch/SwitchToolbar.jsx
  web/client/components/misc/switch/__tests__/SwitchPanel-test.jsx
  web/client/components/misc/switch/__tests__/SwitchToolbar-test.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/metadataexplorer/css/style.css
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/themes/default/less/annotations.less
  web/client/themes/default/less/catalog.less
  web/client/themes/default/less/sidegrid.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/TemplateUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
  web/client/utils/__tests__/TemplateUtils-test.js
Labels: enhancement

#3846 Fixed draw of the marker
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/LegacyVectorStyle.js
  web/client/reducers/mapimport.js
Labels: bug

#3848 Fix 3824 catalog issues in Firefox and template example
  web/client/components/catalog/Catalog.jsx
  web/client/themes/default/less/catalog.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: bug

#3872 Fix 3867 added dct:temporal metadata to the list available for creating the template
  web/client/plugins/MetadataExplorer.jsx
  web/client/selectors/__tests__/locale-test.js
  web/client/selectors/locale.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement

#3873 porting for fix 3867 dct:temporal metadata (2019.01.xx)
  web/client/plugins/MetadataExplorer.jsx
  web/client/selectors/__tests__/locale-test.js
  web/client/selectors/locale.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Project: C027

#3876 fix formatting of temporal metadata
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Project: C027

#3877 porting of temporal metadata formatting (2019.01.xx)
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Project: C027

#3879 add support for oblique labels for line and bar chart in widgets
  web/client/components/charts/Bar.jsx
  web/client/components/charts/Line.jsx
  web/client/components/charts/ObliqueLabel.jsx
  web/client/components/charts/SimpleChart.jsx
  web/client/components/charts/__tests__/SimpleChart-test.jsx
  web/client/components/charts/cartesian.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/WPSWidgetOptions-test.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: Project: C040, enhancement

#3880 Plugins are now sorted alphabetically for readability reasons
  web/client/product/apiPlugins.js
  web/client/product/plugins.js
Labels: enhancement

#3881 Fix 3398 Added label shortening on y axis for bar and line charts
  web/client/components/charts/Bar.jsx
  web/client/components/charts/Line.jsx
  web/client/components/charts/ObliqueLabel.jsx
  web/client/components/charts/YAxisLabel.jsx
  web/client/components/charts/__tests__/YAxisLabel-test.js
  web/client/components/charts/cartesian.jsx
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: Project: C040, enhancement
