Repository geosolutions-it/MapStore2, pull requests merged in 2019-12, with the labels that each got.

#4580 #4550 Application Context - Parametric viewers - Viewer
  web/client/actions/config.js
  web/client/actions/contextcreator.js
  web/client/actions/map.js
  web/client/api/GeoStoreDAO.js
  web/client/api/persistence/index.js
  web/client/components/contextcreator/ConfigureMapStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/contextcreator/__tests__/ContextCreator-test.jsx
  web/client/components/misc/Stepper.jsx
  web/client/containers/MapViewer.jsx
  web/client/epics/config.js
  web/client/epics/context.js
  web/client/epics/contextcreator.js
  web/client/epics/contextmanager.js
  web/client/epics/feedbackMask.js
  web/client/observables/geostore.js
  web/client/plugins/BackToPage.jsx
  web/client/plugins/ContextCreator.jsx
  web/client/plugins/__tests__/ContextCreator-test.jsx
  web/client/plugins/contextmanager/ContextManager.jsx
  web/client/plugins/maps/MapSave.jsx
  web/client/product/appConfig.js
  web/client/product/assets/css/viewer.css
  web/client/product/pages/ContextCreator.jsx
  web/client/reducers/contextcreator.js
  web/client/selectors/contextcreator.js
  web/client/selectors/searchconfig.js
  web/client/themes/default/less/context-creator.less
  web/client/themes/default/less/stepper.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Priority: High, geOrchestra

#4585 #4570 no story reload on language change
  web/client/epics/feedbackMask.js
  web/client/product/pages/Dashboard.jsx
  web/client/product/pages/GeoStory.jsx
Labels: geOrchestra

#4575 #4566 Fix issues with application path
  web/client/components/resources/enhancers/__tests__/withShareTool-test.js
  web/client/components/resources/enhancers/withShareTool.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/contextmanager/ContextGrid.jsx
  web/client/plugins/dashboard/DashboardsGrid.jsx
  web/client/plugins/geostories/GeostoriesGrid.jsx
Labels: geOrchestra

#4583 4450 ScaleBox plugin added in devguide
  docs/developer-guide/maps-configuration.md
Labels: Dev Guide, Documentation

#4588 Edit properties allows to save contexts with spaces in title
  web/client/components/resources/ResourceGrid.jsx
  web/client/components/resources/forms/Metadata.jsx
  web/client/components/resources/forms/__tests__/Metadata-test.jsx
  web/client/components/resources/modals/Save.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/plugins/contextmanager/ContextManager.jsx
Labels: geOrchestra

#4594 Application Context fix
  web/client/epics/config.js
  web/client/plugins/contextmanager/ContextManager.jsx
Labels: geOrchestra

#4542 4367 blocking access to new map or dashboard for anonymous users
  web/client/actions/__tests__/security-test.js
  web/client/actions/security.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/context-test.js
  web/client/epics/__tests__/dashboard-test.js
  web/client/epics/__tests__/login-test.js
  web/client/epics/config.js
  web/client/epics/dashboard.js
  web/client/epics/login.js
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
  web/client/product/main.jsx
  web/client/product/pages/Dashboard.jsx
  web/client/product/pages/Maps.jsx
  web/client/test-resources/testConfig.broken.json.txt
  web/client/test-resources/testConfigEPSG31468.json.txt
  web/client/utils/ConfigUtils.js
  web/client/utils/__tests__/ConfigUtils-test.js
Labels: Priority: Medium, enhancement

#4574 Advanced Editor from Inline Editor
  web/client/components/TOC/Toolbar.jsx
  web/client/components/geostory/common/MapEditor.jsx
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: GeoStory

#4599 Fixes for 4501 zoom control alignment in geostory
  web/client/themes/default/less/geostory.less
  web/client/translations/data.it-IT
Labels: GeoStory

#4586 #4577 Circle radius uom corrections
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/GeometryEditor.jsx
  web/client/components/mapcontrols/annotations/MeasureEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/MeasureEditor-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/mouseposition/MousePosition.jsx
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/selectors/annotations.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: annotations, bug

#4604 add ordered and unordered list
  web/client/components/geostory/contents/enhancers/editableText.jsx
Labels: GeoStory, enhancement

#4607 #4602 fix the editor error in geostory
  build/buildConfig.js
  web/client/components/geostory/contents/enhancers/editableText.jsx
Labels: GeoStory, bug

#4600 Builder - Content Editor - Web page (C039 - #32)
  docma-template/less/bootstrap/variables.less
  docma-template/less/bs-variables.less
  web/client/actions/geostory.js
  web/client/components/geostory/builder/SectionsPreview.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/Content.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/geostory/contents/Contents.jsx
  web/client/components/geostory/contents/SectionContents.jsx
  web/client/components/geostory/contents/WebPage.jsx
  web/client/components/geostory/contents/WebPageWrapper.jsx
  web/client/components/geostory/contents/__tests__/WebPage-test.jsx
  web/client/components/geostory/contents/__tests__/WebPageWrapper-test.jsx
  web/client/components/geostory/contents/enhancers/editURL.js
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/sections/Paragraph.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/GeoStory.jsx
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/geostory.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/GeoStoryUtils.js
  web/client/utils/URLUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
  web/client/utils/__tests__/URLUtils-test.js
Labels: GeoStory, Priority: High, Project: C039

#4633 #4593 Disabled permission only with owner attribute
  web/client/actions/__tests__/maps-test.js
  web/client/actions/maps.js
  web/client/components/resources/modals/Save.jsx
  web/client/components/resources/modals/__tests__/Save-test.jsx
  web/client/reducers/__tests__/maps-test.js
  web/client/reducers/maps.js
Labels: Priority: High

#4625 Fix 4392 Hide timestamp on new resource save
  web/client/components/resources/forms/Metadata.jsx
  web/client/components/resources/forms/__tests__/Metadata-test.jsx
Labels: Priority: High, bug, geOrchestra

#4632 Fix Map preview for widget
  web/client/components/mediaEditor/map/MapList.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
Labels: Dashboard, bug

#4631 4382 gfi mobile coord editor
  package.json
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/themes/default/less/get-feature.less
Labels: Mobile, Priority: Medium, bug

#4646 4643 userguide updating to 03.00 first step
  docs/user-guide/home-page.md
  docs/user-guide/img/button/acc-manager.jpg
  docs/user-guide/img/button/featured.jpg
  docs/user-guide/img/button/login-b.jpg
  docs/user-guide/img/button/remove-edit.jpg
  docs/user-guide/img/button/share.jpg
  docs/user-guide/img/button/unfeatured.jpg
  docs/user-guide/img/home-page/config.jpg
  docs/user-guide/img/home-page/connections.jpg
  docs/user-guide/img/home-page/contents.jpg
  docs/user-guide/img/home-page/feat-cont.jpg
  docs/user-guide/img/home-page/featured.jpg
  docs/user-guide/img/home-page/home-page.jpg
  docs/user-guide/img/home-page/homepage-admin.jpg
  docs/user-guide/img/home-page/homepage-anonym.jpg
  docs/user-guide/img/home-page/homepage-user.jpg
  docs/user-guide/img/home-page/language-switcher.jpg
  docs/user-guide/img/home-page/login.jpg
  docs/user-guide/img/home-page/manage-accounts.jpg
  docs/user-guide/img/home-page/map-dash.jpg
  docs/user-guide/img/home-page/new-res.jpg
  docs/user-guide/img/home-page/own-account.jpg
  docs/user-guide/img/home-page/search-bar.jpg
  docs/user-guide/resources-properties.md
  docs/user-guide/text-editor-details.md
Labels: Documentation, User Guide

#4652 #3533 Add Zoom to Layer Dashboard map widget (Backport #4595) for 2019.03.xx
  web/client/plugins/widgetbuilder/enhancers/__tests__/handleMapZoomLayer-test.js
  web/client/plugins/widgetbuilder/enhancers/handleMapZoomLayer.js
  web/client/plugins/widgetbuilder/enhancers/mapToolbar.js
Labels: Backport

#4637 Fix 4636 Story Model - Continuous Scroll - Lazy loading
  web/client/components/geostory/common/VisibilityContainer.jsx
  web/client/components/geostory/common/__tests__/VisibilityContainer-test.jsx
  web/client/components/geostory/contents/WebPageWrapper.jsx
  web/client/components/geostory/contents/__tests__/Content-test.jsx
  web/client/components/geostory/contents/__tests__/SectionContent-test.jsx
  web/client/components/geostory/layouts/sections/Background.jsx
  web/client/components/geostory/layouts/sections/__tests__/Background-test.jsx
  web/client/components/geostory/layouts/sections/__tests__/Immersive-test.jsx
  web/client/components/geostory/layouts/sections/__tests__/Title-test.jsx
  web/client/components/geostory/media/Image.jsx
  web/client/components/geostory/media/__tests__/index-test.js
  web/client/components/geostory/media/index.js
  web/client/test-resources/geostory/sampleStory_1.json
  web/client/themes/default/less/geostory.less
Labels: GeoStory, Project: C039

#4656 4643 exploring maps and menu bar
  docs/user-guide/exploring-maps.md
  docs/user-guide/home-page.md
  docs/user-guide/img/button/change-search-tool.jpg
  docs/user-guide/img/button/logged.jpg
  docs/user-guide/img/button/next-txt.jpg
  docs/user-guide/img/exploring-maps/map-viewer.jpg
  docs/user-guide/img/managing-users-and-groups/acc-info.jpg
  docs/user-guide/img/managing-users-and-groups/change-psw.jpg
  docs/user-guide/img/managing-users-and-groups/login-win.jpg
  docs/user-guide/img/managing-users-and-groups/login.jpg
  docs/user-guide/img/menu-bar/about.jpg
  docs/user-guide/img/menu-bar/aboutold.jpg
  docs/user-guide/img/menu-bar/aeronautical.jpg
  docs/user-guide/img/menu-bar/burger-menu.jpg
  docs/user-guide/img/menu-bar/create-edit-service-panel.jpg
  docs/user-guide/img/menu-bar/custom-search-results-click-records.jpg
  docs/user-guide/img/menu-bar/custom-search-results.jpg
  docs/user-guide/img/menu-bar/decimal.jpg
  docs/user-guide/img/menu-bar/decimal_coordinates_editor.jpg
  docs/user-guide/img/menu-bar/default-osm-search.jpg
  docs/user-guide/img/menu-bar/menu-bar.jpg
  docs/user-guide/img/menu-bar/menu-options.jpg
  docs/user-guide/img/menu-bar/override-default-service-results.jpg
  docs/user-guide/img/menu-bar/override-default-service.jpg
  docs/user-guide/img/menu-bar/override-no.jpg
  docs/user-guide/img/menu-bar/override-yes.jpg
  docs/user-guide/img/menu-bar/performed-search.jpg
  docs/user-guide/img/menu-bar/search-types.jpg
  docs/user-guide/img/menu-bar/search_by_aeronautical_coordinates.gif
  docs/user-guide/img/menu-bar/search_by_coordinates_option.jpg
  docs/user-guide/img/menu-bar/search_by_decimal_coordinates.gif
  docs/user-guide/img/menu-bar/search_tool.jpg
  docs/user-guide/img/menu-bar/settings.jpg
  docs/user-guide/managing-users-and-groups.md
  docs/user-guide/menu-bar.md
  mkdocs.yml
Labels: Documentation, User Guide

#4648 Fix 4623 WMS GetCapabilities and DescribeLayer do not support custom query parameters (2019.03.xx)
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/epics/styleeditor.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Backport

#4598 #4569 updating mapstore package.json
  build/buildConfig.js
  build/testConfig.js
  docs/developer-guide/custom-dependencies.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/mapstore-migration-guide.md
  package.json
Labels: Environment

#4641 Fix 4640 Add icons for add geostory, edit map, preview and webpage section
  web/client/components/geostory/builder/Builder.jsx
  web/client/components/geostory/builder/SectionsPreview.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/geostory/layouts/sections/Paragraph.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/components/geostory/layouts/sections/__tests__/Immersive-test.jsx
  web/client/components/geostory/layouts/sections/__tests__/Title-test.jsx
  web/client/plugins/CreateNewMap.jsx
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/add-geostory.svg
  web/client/themes/default/svg/map-edit.svg
  web/client/themes/default/svg/map-marker.svg
  web/client/themes/default/svg/preview.svg
  web/client/themes/default/svg/story-webpage-section.svg
  web/client/themes/default/svg/webpage.svg
Labels: GeoStory, Project: C039

#4444 Proposal: new template for Issues and Pull Requests
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/new_feature.md
  .github/ISSUE_TEMPLATE/other.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
  .github/PULL_REQUEST_TEMPLATE/other.md
Labels: enhancement

#4657 Fix 4514: Builder - Content Editor - Web page
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory, Project: C039

#4620 #4619 Story - Share - Tool
  package.json
  web/client/actions/geostory.js
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/components/home/Home.jsx
  web/client/components/resources/enhancers/withShareTool.jsx
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/localConfig.json
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/GeoStoryNavigation.jsx
  web/client/plugins/OmniBar.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/plugins/contextmanager/ContextGrid.jsx
  web/client/plugins/geostories/GeostoriesGrid.jsx
  web/client/product/appConfig.js
  web/client/product/pages/GeoStory.jsx
  web/client/selectors/__tests__/router-test.js
  web/client/selectors/router.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ShareUtils.js
  web/client/utils/URLUtils.js
  web/client/utils/__tests__/ShareUtils-test.js
  web/client/utils/__tests__/URLUtils-test.js
Labels: GeoStory, Project: C039

#4581 #4034 Confirmation dialog in map on user logout
  docs/developer-guide/local-config.md
  web/client/actions/map.js
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/home/Home.jsx
  web/client/components/security/UserMenu.jsx
  web/client/epics/__tests__/login-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/login.js
  web/client/epics/map.js
  web/client/plugins/Home.jsx
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/searchconfig-test.js
  web/client/reducers/config.js
  web/client/reducers/map.js
  web/client/reducers/searchconfig.js
  web/client/selectors/controls.js
  web/client/stores/StandardStore.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement

#4676 4643 toc and import
  docs/user-guide/img/button/export.jpg
  docs/user-guide/img/button/group-close.jpg
  docs/user-guide/img/button/group-open.jpg
  docs/user-guide/img/button/import.jpg
  docs/user-guide/img/button/select-files.jpg
  docs/user-guide/img/import/add-vector.jpg
  docs/user-guide/img/import/export-import.gif
  docs/user-guide/img/import/import-screen.jpg
  docs/user-guide/img/import/local-files-added.jpg
  docs/user-guide/img/local-files/add-files.jpg
  docs/user-guide/img/local-files/local-files.jpg
  docs/user-guide/img/local-files/map-localfile.jpg
  docs/user-guide/img/local-files/style-shapefile.jpg
  docs/user-guide/img/toc/add-layer-to-group.jpg
  docs/user-guide/img/toc/add-sub-group.jpg
  docs/user-guide/img/toc/catalog.jpg
  docs/user-guide/img/toc/ded-groups.gif
  docs/user-guide/img/toc/ded-layers.gif
  docs/user-guide/img/toc/group-added.jpg
  docs/user-guide/img/toc/group-imagery-1.jpg
  docs/user-guide/img/toc/group-settings.jpg
  docs/user-guide/img/toc/group-toolbar.jpg
  docs/user-guide/img/toc/group.jpg
  docs/user-guide/img/toc/imagery.jpg
  docs/user-guide/img/toc/layer-in-group.jpg
  docs/user-guide/img/toc/layer-moved.jpg
  docs/user-guide/img/toc/layer-settings.jpg
  docs/user-guide/img/toc/layer-to-subgroup.jpg
  docs/user-guide/img/toc/layer-toolbar.jpg
  docs/user-guide/img/toc/layer-tools.jpg
  docs/user-guide/img/toc/layer-usa.jpg
  docs/user-guide/img/toc/layer_group.jpg
  docs/user-guide/img/toc/new-subgroup.jpg
  docs/user-guide/img/toc/new_group.jpg
  docs/user-guide/img/toc/north_america_subgroup.jpg
  docs/user-guide/img/toc/order-layers.jpg
  docs/user-guide/img/toc/search.jpg
  docs/user-guide/img/toc/second-layer.jpg
  docs/user-guide/img/toc/settings-group.jpg
  docs/user-guide/img/toc/subgroup-in-group.jpg
  docs/user-guide/img/toc/toc.jpg
  docs/user-guide/img/toc/transparency-bar.jpg
  docs/user-guide/img/toc/usa_group.jpg
  docs/user-guide/import.md
  docs/user-guide/local-files.md
  docs/user-guide/menu-bar.md
  docs/user-guide/toc.md
  mkdocs.yml
Labels: Documentation, User Guide

#4672 #4569 updating mapstore package.json (Backport 2020.01.xx of #4598)
  build/buildConfig.js
  build/testConfig.js
  docs/developer-guide/custom-dependencies.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/mapstore-migration-guide.md
  package.json
Labels: Backport

#4685 4643 save and background
  docs/user-guide/background.md
  docs/user-guide/basemap.md
  docs/user-guide/exploring-maps.md
  docs/user-guide/img/background/add-new-bck.jpg
  docs/user-guide/img/background/add-ocean.jpg
  docs/user-guide/img/background/back-selector.jpg
  docs/user-guide/img/background/background.jpg
  docs/user-guide/img/background/bck-available.jpg
  docs/user-guide/img/background/bck-catalog.jpg
  docs/user-guide/img/background/bck-delete.jpg
  docs/user-guide/img/background/bck-unselectable.jpg
  docs/user-guide/img/background/edit-back-window.jpg
  docs/user-guide/img/basemap/add-back.jpg
  docs/user-guide/img/basemap/add-bck-ocean.jpg
  docs/user-guide/img/basemap/back-selector.jpg
  docs/user-guide/img/basemap/background.jpg
  docs/user-guide/img/basemap/bck-delete.jpg
  docs/user-guide/img/basemap/bck-setted.jpg
  docs/user-guide/img/basemap/bck-settings.jpg
  docs/user-guide/img/basemap/edit-back-window.jpg
  docs/user-guide/img/basemap/search-ocean.jpg
  docs/user-guide/img/save/my-map.jpg
  docs/user-guide/img/save/save-as-1.jpg
  docs/user-guide/img/save/save-as.jpg
  docs/user-guide/img/save/save.jpg
  docs/user-guide/menu-bar.md
  docs/user-guide/save.md
  mkdocs.yml
Labels: Documentation, User Guide
