Repository geosolutions-it/MapStore2, pull requests merged in 2019-04, with the labels that each got.

#3661 Fix #3660 Zoom to Extent on visible area
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/epics/__tests__/map-test.js
  web/client/epics/map.js
  web/client/plugins/Map.jsx
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/maplayout-test.js
  web/client/selectors/maplayout.js
  web/client/utils/MapUtils.js
Labels: pending review, review

#3662 Fix #3617 minor bug fixes and improvements
  docma-config.json
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/identify/navigationButtons.js
  web/client/plugins/identify/toolButtons.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
  web/client/translations/data.de-DE
Labels: pending review, review

#3648 Replace InchCI badge with ReadTheDocs badge
  README.md
Labels: pending review, review

#3649 Connected to #2971. Use mock lib to speed up wfstable test
  web/client/components/widgets/enhancers/wfsTable/__tests__/wfsTable-test.js
Labels: pending review, review

#3665 Fix #3664 DockPanel do not render content when closed
  web/client/components/TOC/__tests__/TOCItemsSettings-test.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/components/misc/panels/__tests__/DockPanel-test.jsx
Labels: pending review, review

#3667 3548 fix ui drag menu for coordinate editor (c125_annotations)
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/plugins/identify/IdentifyEditor.jsx
Labels: pending review, review

#3669 Align master
  .gitignore
  README.md
  web/client/components/TOC/__tests__/TOCItemsSettings-test.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/components/misc/panels/__tests__/DockPanel-test.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/wfsChartOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/wfsTable-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/__tests__/playback-test.js
  web/client/epics/map.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/localConfig.json
  web/client/plugins/Map.jsx
  web/client/plugins/playback/Playback.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/product/components/viewer/MapViewerCmp.jsx
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/maplayout-test.js
  web/client/selectors/maplayout.js
  web/client/utils/MapUtils.js
  web/client/utils/ReselectUtils.js
  web/client/utils/__tests__/ReselectUtils-test.js
Labels: pending review, review

#3663 Fix #3608 Toc tooltips options saved in map configuration
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Priority: High, Project: C125

#3670 Search tool changes to format menu , search icon always visible (c125_annotations)
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/themes/default/less/map-search-bar.less
Labels: Project: C125, pending review, review

#3672 Fixed default lon to east in aeronautical format
  web/client/components/misc/coordinateeditors/enhancers/__tests__/decimalToAeronautical-test.js
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
Labels: pending review, review

#3673 Align OL measure number format of tooltip to measure panel's one
  web/client/components/I18N/enhancers/__tests__/addI18NProps-test.js
  web/client/components/I18N/enhancers/addI18NProps.js
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/plugins/map/openlayers/index.js
Labels: pending review, review

#3674 C125 align with master branch
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: pending review, review

#3676 FeatureInfo coordinates in aeronautical format
  web/client/components/I18N/Number.jsx
  web/client/components/data/identify/GeocodeViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/GeocodeViewer-test.jsx
  web/client/components/data/identify/coordinates/Coordinate.jsx
  web/client/components/data/identify/coordinates/Editor.jsx
  web/client/components/data/identify/coordinates/Viewer.jsx
  web/client/components/data/identify/coordinates/__tests__/Coordinate-test.jsx
  web/client/components/data/identify/coordinates/__tests__/Editor-test.jsx
  web/client/components/data/identify/coordinates/__tests__/Viewer-test.jsx
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDM.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
  web/client/themes/default/less/get-feature.less
Labels: pending review, review

#3675 autoDetectCORS option for proxy config
  package.json
  web/client/libs/__tests__/ajax-test.js
  web/client/libs/ajax.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/utils/SecurityUtils.js
Labels: pending review, review

#3678 Revert "autoDetectCORS option for proxy config"
  package.json
  web/client/libs/__tests__/ajax-test.js
  web/client/libs/ajax.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/utils/SecurityUtils.js
Labels: pending review, review

#3677 Backports for timeline
  web/client/epics/__tests__/playback-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/playback/Playback.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/product/components/viewer/MapViewerCmp.jsx
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
  web/client/utils/ReselectUtils.js
  web/client/utils/__tests__/ReselectUtils-test.js
Labels: pending review, review

#3686 Fix #3685 print support for dashed stroke
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: annotations, bug, pending review, review

#3689 Fix #3685 update dashStrokestyle property
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: Project: C125, annotations, bug, pending review, review

#3687 Update localConfig.json
  web/client/localConfig.json
Labels: pending review, review

#3680 Fixes #3441: root dir cleanup
  build/buildConfig.js
  build/docma-config.json
  build/examples-webpack.config.js
  build/examples.js
  build/karma.conf.continuous-test.js
  build/karma.conf.single-run.js
  build/prod-webpack.config.js
  build/testConfig.js
  build/tests-travis.webpack.js
  build/tests.webpack.js
  build/themes.js
  build/webpack.config.js
  createProject.js
  docs/developer-guide/mapstore-migration-guide.md
  examples.js
  package.json
  project/custom/templates/prod-webpack.config.js
  project/custom/templates/webpack.config.js
  project/standard/static/karma.conf.continuous-test.js
  project/standard/static/karma.conf.single-run.js
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
  tests-travis.webpack.js
  tests.webpack.js
  utility/build/checkCesium.js
  utility/projects/projectLib.js
  utility/projects/projectScripts.json
  web/client/.babelrc
  webpack.config.js
Labels: pending review, review

#3681 autoDetectCORS option for proxy config
  package.json
  web/client/libs/__tests__/ajax-test.js
  web/client/libs/ajax.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/utils/SecurityUtils.js
Labels: pending review, review

#3692 Delete old files in MapStore2 root
  .doclets.yml
  .github_changelog_generator
  docs/developer-guide/release.md
  inch.json
Labels: pending review, review

#3700 Documented Widgets collapse/pin tool
  docs/user-guide/img/widgets-tray.jpg
  docs/user-guide/widgets.md
Labels: pending review, review

#3690 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pending review, review

#3698 Fix #3642 Switch between widgets and timeline
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/widgetsTray-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/epics/widgetsTray.js
  web/client/localConfig.json
  web/client/plugins/Timeline.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/WidgetsTray.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/plugins/timeline/TimelineToggle.jsx
  web/client/plugins/widgets/WidgetsBar.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
  web/client/plugins/widgets/widgetsPermission.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
  web/client/selectors/__tests__/timeline-test.js
  web/client/selectors/timeline.js
  web/client/selectors/widgetsTray.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3697 Fix #3696 Various fixes, utils and drawSupport
  web/client/actions/notifications.js
  web/client/api/persistence/index.js
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/misc/enhancers/loadingState.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/components/misc/toolbar/DropdownToolbarOptions.jsx
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/openlayers/Icons.js
Labels: Project: C098, pending review, review
