Repository geosolutions-it/MapStore2, pull requests merged in 2019-03, with the labels that each got.

#3594 Fix #3545 BBOX query param
  web/client/components/misc/Dialog.jsx
  web/client/components/misc/style/dialog.css
  web/client/components/share/ShareApi.jsx
  web/client/components/share/ShareCopyToClipboard.jsx
  web/client/components/share/ShareEmbed.jsx
  web/client/components/share/ShareLink.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/ShareQRCode.jsx
  web/client/components/share/ShareSocials.jsx
  web/client/components/share/__tests__/ShareApi-test.jsx
  web/client/components/share/__tests__/ShareCopyToClipboard-test.jsx
  web/client/components/share/__tests__/ShareEmbed-test.jsx
  web/client/components/share/__tests__/ShareLink-test.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/components/share/__tests__/ShareQRCode-test.jsx
  web/client/components/share/__tests__/ShareSocials-test.jsx
  web/client/components/share/share.css
  web/client/epics/__tests__/share-test.js
  web/client/epics/share.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/product/embedded.jsx
  web/client/product/main.jsx
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/share.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: pending review, review

#3597 Renaming MapStore2 to MapStore in user and dev guides
  docs/developer-guide/API-usage.md
  docs/developer-guide/application-tutorial.md
  docs/developer-guide/building-and-deploying.md
  docs/developer-guide/code-conventions.md
  docs/developer-guide/configuration-files.md
  docs/developer-guide/contributing-guidelines.md
  docs/developer-guide/custom-search-service.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/developing.md
  docs/developer-guide/how-to-use-a-cdn.md
  docs/developer-guide/index.md
  docs/developer-guide/infrastructure-and-general-architecture.md
  docs/developer-guide/internationalization.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/plugins-architecture.md
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/project-structure.md
  docs/developer-guide/reactjs-and-redux-introduction.md
  docs/developer-guide/release.md
  docs/index.md
  docs/quick-start.md
  docs/theme/partials/footer.html
  docs/user-guide/attributes-table.md
  docs/user-guide/catalog.md
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/exploring-maps.md
  docs/user-guide/home-page.md
  docs/user-guide/layer-settings.md
  docs/user-guide/local-files.md
  docs/user-guide/measure.md
  docs/user-guide/menu-bar.md
  docs/user-guide/side-bar.md
  docs/user-guide/widgets.md
  mkdocs.yml
Labels: pending review, review

#3595 Fix #2996. Support for RESTful WMTS with Multiple URLs
  docs/developer-guide/maps-configuration.md
  web/client/api/WMTS.js
  web/client/api/__tests__/WMTS-test.js
  web/client/components/catalog/RecordItem.jsx
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMTSLayer.js
  web/client/components/map/leaflet/plugins/WMTSLayer.js
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/selectors/map.js
  web/client/test-resources/wmts/GetCapabilities-rest.xml
  web/client/utils/CatalogUtils.js
  web/client/utils/ConfigUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
  web/client/utils/__tests__/ConfigUtils-test.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/WMTSUtils-test.js
  web/client/utils/leaflet/WMTS.js
Labels: pending review, review

#3596 Fix #3387. Allow catalog names with dots
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
Labels: pending review, review

#3590 Fixes #3589: problems of the standard template project build
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/web/pom.xml
Labels: pending review, review

#3592 Fixes #3591: implements automatic compression of deployed HTML, JS and CSS files
  project/custom/templates/web/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  web/pom.xml
  web/src/main/webapp/WEB-INF/web.xml
Labels: pending review, review

#3555 Fixes #3554: external init of StandardApp
  docma-config.json
  web/client/components/app/StandardApp.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
Labels: pending review, review

#3512 Fixes #3454 plugins developers documentation - round 2
  docs/developer-guide/plugins-howto.md
Labels: pending review, review

#3599 Fixes #3598: legends size in printing layouts
  resources/geoserver/print/config.yaml
Labels: pending review, review

#3600 Fix #2996 - OpenLayers WMTS refactor
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
Labels: pending review, review

#3603 Fix #2996 . Support for RESTful WMTS
  CHANGELOG.md
  docma-config.json
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/release.md
  project/custom/templates/web/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  resources/geoserver/print/config.yaml
  web/client/api/WMTS.js
  web/client/api/__tests__/WMTS-test.js
  web/client/components/app/StandardApp.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMTSLayer.js
  web/client/components/map/leaflet/plugins/WMTSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/epics/mapexport.js
  web/client/libs/__tests__/ajax-test.js
  web/client/plugins/Save.jsx
  web/client/plugins/SaveAs.jsx
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/__tests__/query-test.js
  web/client/selectors/catalog.js
  web/client/selectors/featuregrid.js
  web/client/selectors/map.js
  web/client/selectors/mapsave.js
  web/client/selectors/query.js
  web/client/test-resources/wmts/GetCapabilities-rest.xml
  web/client/utils/CatalogUtils.js
  web/client/utils/ConfigUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
  web/client/utils/__tests__/ConfigUtils-test.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
  web/client/utils/__tests__/SecurityUtils-test.js
  web/client/utils/__tests__/WMTSUtils-test.js
  web/client/utils/leaflet/Vector.js
  web/client/utils/leaflet/WMTS.js
  web/pom.xml
  web/src/main/webapp/WEB-INF/web.xml
Labels: Project: C125, pending review, review

#3604 Fix #3531 collapsible hidden widgets
  docma-config.json
  web/client/components/app/StandardApp.jsx
  web/client/components/misc/enhancers/security/accessRuleParser.jsx
  web/client/components/widgets/enhancers/tools/__tests__/collapsibleWidget-test.js
  web/client/components/widgets/enhancers/tools/collapsibleWidget.js
  web/client/plugins/Widgets.jsx
  web/client/plugins/WidgetsTray.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
Labels: pending review, review

#3609 Fix #3608 add TOC tooltip customization
  web/client/components/TOC/DefaultGroup.jsx
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/components/TOC/fragments/__tests__/GroupTitle-test.jsx
  web/client/components/TOC/fragments/__tests__/Title-test.jsx
  web/client/plugins/TOC.jsx
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: pending review, review

#3606 Fix #3523 Fix #3548 Fix problems with coordinate editor for the search and GFI tools
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/openlayers/Feature.jsx
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
  web/client/components/misc/coordinateeditors/enhancers/tempAeronauticalValue.js
  web/client/components/style/vector/Manager.jsx
  web/client/components/style/vector/Stroke.jsx
  web/client/utils/leaflet/Vector.js
Labels: Project: C125, pending review, review

#3610 Fix #3601 measure updates
  web/client/actions/__tests__/measurement-test.js
  web/client/actions/measurement.js
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/leaflet/MeasurementSupport.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/MeasureDialog.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureDialog-test.jsx
  web/client/components/mapcontrols/measure/measure.css
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/epics/annotations.js
  web/client/epics/featuregrid.js
  web/client/epics/maplayout.js
  web/client/epics/measurement.js
  web/client/plugins/Annotations.jsx
  web/client/plugins/Measure.jsx
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/annotations.js
  web/client/reducers/config.js
  web/client/reducers/mapInfo.js
  web/client/reducers/measurement.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/__tests__/measurement-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  web/client/selectors/measurement.js
  web/client/themes/default/less/annotations.less
  web/client/themes/default/less/get-feature.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/AnnotationsUtils.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/MeasureUtils.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/MeasureUtils-test.js
  web/client/utils/__tests__/VectorStyleUtils-test.js
Labels: pending review, review

#3612 Align master over c125_annotations
  web/client/components/TOC/DefaultGroup.jsx
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/components/TOC/fragments/__tests__/GroupTitle-test.jsx
  web/client/components/TOC/fragments/__tests__/Title-test.jsx
  web/client/plugins/TOC.jsx
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Project: C125, pending review, review

#3616 Externalized in epic getFeatureInfo retrieval logic
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/Identify.jsx
  web/client/components/data/identify/__tests__/Identify-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/selectors/mapinfo.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/mapinfo/vector.js
  web/client/utils/mapinfo/wms.js
Labels: Project: C125, pending review, review

#3619 Fix #3387. Allow catalog names with dots (2019.01.xx)
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
Labels: pending review, review

#3618 Fix #3608 improved tooltip customization in TOC
  docma-config.json
  web/client/components/TOC/DefaultGroup.jsx
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/components/TOC/fragments/__tests__/GroupTitle-test.jsx
  web/client/components/TOC/fragments/__tests__/Title-test.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
  web/client/themes/default/less/dropdown-menu.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Project: C125, pending review, review

#3613 Fix #3601 bugs on Print for distance measure
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: Project: C125, pending review, review

#3623 Align master on c125_annotations 14 03 2019
  docma-config.json
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/TOC/DefaultGroup.jsx
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/GroupTitle.jsx
  web/client/components/TOC/fragments/Title.jsx
  web/client/components/TOC/fragments/__tests__/GroupTitle-test.jsx
  web/client/components/TOC/fragments/__tests__/Title-test.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/components/data/identify/Identify.jsx
  web/client/components/data/identify/__tests__/Identify-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
  web/client/selectors/mapInfo.js
  web/client/themes/default/less/dropdown-menu.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/LayersUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/TOCUtils-test.js
  web/client/utils/mapinfo/vector.js
  web/client/utils/mapinfo/wms.js
Labels: Project: C125, pending review, review

#3621 Fix #3496 Add attribution support for WMS layers
  docs/developer-guide/maps-configuration.md
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/examples/rasterstyler/assets/css/viewer.css
  web/client/examples/styler/assets/css/viewer.css
  web/client/plugins/MetadataExplorer.jsx
  web/client/product/assets/css/viewer.css
  web/client/test-resources/wms/attribution.xml
  web/client/themes/default/less/cesium.less
  web/client/themes/default/less/leaflet.less
  web/client/themes/default/less/map-footer.less
  web/client/themes/default/ms2-theme.less
  web/client/utils/CatalogUtils.js
  web/client/utils/ConfigProvider.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: pending review, review

#3632 Fix #3593 Adjusted catalog position when modals are opened (2019.01.xx)
  web/client/components/mapcontrols/measure/MeasureDialog.jsx
  web/client/components/share/SharePanel.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/Settings.jsx
  web/client/plugins/metadataexplorer/css/style.css
  web/client/plugins/shapefile/ShapeFile.jsx
  web/client/product/assets/css/viewer.css
  web/client/product/components/viewer/about/About.jsx
  web/client/themes/default/less/panels.less
Labels: Priority: High, annotations, pending review, review

#3631 fix #3608 IE11 combobox problem
  web/client/themes/default/less/dropdown-menu.less
Labels: Priority: High, Project: C125, bug, pending review, review

#3634 Porting fix for Catalog and modals #3593 (master)
  web/client/components/mapcontrols/measure/MeasureDialog.jsx
  web/client/components/share/SharePanel.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/Settings.jsx
  web/client/plugins/metadataexplorer/css/style.css
  web/client/plugins/shapefile/ShapeFile.jsx
  web/client/product/assets/css/viewer.css
  web/client/product/components/viewer/about/About.jsx
  web/client/themes/default/less/panels.less
Labels: pending review, review

#3628 Adding tests for increasing coverage on c125_annotations branch and other fixes
  web/client/actions/__tests__/measurement-test.js
  web/client/actions/measurement.js
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/Feature.jsx
  web/client/components/map/openlayers/LegacyVectorStyle.js
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/Overview.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/components/map/openlayers/__tests__/LegacyVectorStyle-test.js
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
  web/client/components/map/openlayers/__tests__/Overview-test.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/DropdownFeatureType.jsx
  web/client/components/mapcontrols/annotations/__tests__/Annotations-test.js
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/DropdownFeatureType-test.js
  web/client/components/mapcontrols/annotations/__tests__/MeasureEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/SelectAnnotationsFile-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/mapcontrols/measure/measure.css
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/enhancers/draggableContainer.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/epics/measurement.js
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/annotations.js
  web/client/reducers/measurement.js
  web/client/selectors/__tests__/measurement-test.js
  web/client/selectors/measurement.js
  web/client/test-resources/drawsupport/features.js
  web/client/themes/default/less/annotations.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/AnnotationsUtils.js
  web/client/utils/DrawSupportUtils.jsx
  web/client/utils/MeasureUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/MeasureUtils-test.js
  web/client/utils/openlayers/DrawUtils.js
  web/client/utils/openlayers/__tests__/DrawUtils-test.js
Labels: Project: C125, pending review, review

#3635 Fix #3617. Add feature zoomTo and highlight to Identify
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/enhancers/__tests__/defaultViewer-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/__tests__/zoomToFeatureHandler-test.js
  web/client/components/data/identify/enhancers/defaultViewer.js
  web/client/components/data/identify/enhancers/identify.js
  web/client/components/data/identify/enhancers/zoomToFeatureHandler.js
  web/client/components/map/openlayers/Feature.jsx
  web/client/components/map/openlayers/VectorStyle.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/plugins/identify/defaultIdentifyButtons.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/draw.js
  web/client/selectors/featuregrid.js
  web/client/selectors/layers.js
  web/client/selectors/mapInfo.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapInfoUtils.js
Labels: Project: C125, pending review, review

#3637 Align master 21 03 19 on c125_annotations branch
  docs/developer-guide/maps-configuration.md
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/share/SharePanel.jsx
  web/client/examples/rasterstyler/assets/css/viewer.css
  web/client/examples/styler/assets/css/viewer.css
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/Settings.jsx
  web/client/plugins/import/StyleDialog.jsx
  web/client/plugins/metadataexplorer/css/style.css
  web/client/product/assets/css/viewer.css
  web/client/product/components/viewer/about/About.jsx
  web/client/test-resources/wms/attribution.xml
  web/client/themes/default/less/cesium.less
  web/client/themes/default/less/dropdown-menu.less
  web/client/themes/default/less/leaflet.less
  web/client/themes/default/less/map-footer.less
  web/client/themes/default/less/panels.less
  web/client/themes/default/ms2-theme.less
  web/client/utils/CatalogUtils.js
  web/client/utils/ConfigProvider.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: pending review, review

#3636 Fix circular dependencies on c125_annotations branch
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/identify/viewers/TemplateViewer.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/utils/AnnotationsUtils.js
  web/client/utils/DrawSupportUtils.jsx
  web/client/utils/FeatureGridEditorUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/TemplateUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/DrawSupportUtils-test.js
  web/client/utils/__tests__/FeatureGridEditorUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/__tests__/TemplateUtils-test.js
  web/client/utils/featuregrid/EditorRegistry.jsx
  web/client/utils/featuregrid/__tests__/EditorRegistry-test.js
Labels: Project: C125, pending review, review

#3626 Fix #3625. Support numeric aggregation for integer data type
  web/client/components/widgets/builder/wizard/common/__tests__/wfsChartOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
Labels: pending review, review

#3639 Remove Floating Legend
  web/client/localConfig.json
Labels: pending review, review

#3638 Update gitignore
  .gitignore
Labels: pending review, review

#3641 Fix #3625. Support numeric aggregation for integer data type (2019.01.xx)
  web/client/components/widgets/builder/wizard/common/__tests__/wfsChartOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
Labels: pending review, review

#3646 Fix #3367 removing layers from timeline during animation
  web/client/plugins/timeline/Timeline.jsx
  web/client/utils/ReselectUtils.js
  web/client/utils/__tests__/ReselectUtils-test.js
Labels: pending review, review

#3645 Fix #3640 Start animation from the current time
  web/client/epics/__tests__/playback-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/plugins/playback/Playback.jsx
Labels: pending review, review

#3647 Fix #2590. Reload map on URL change
  web/client/product/components/viewer/MapViewerCmp.jsx
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
Labels: pending review, review
