Repository geosolutions-it/MapStore2, pull requests merged in 2019-02, with the labels that each got.

#3505 Fixes to align WMS gridsets
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
Labels: pending review, review

#3493 Style Editor user guide section
  docs/user-guide/admin.md
  docs/user-guide/attributes-table.md
  docs/user-guide/home-page.md
  docs/user-guide/img/add-rule-icon.jpg
  docs/user-guide/img/create-edit-service-panel.jpg
  docs/user-guide/img/custom-search-results.jpg
  docs/user-guide/img/default-osm-search.jpg
  docs/user-guide/img/delete-service-icon.jpg
  docs/user-guide/img/edit-map-properties-icon.jpg
  docs/user-guide/img/edit-map-properties-map.jpg
  docs/user-guide/img/edit-map-properties-panel.jpg
  docs/user-guide/img/edit-service-icon.jpg
  docs/user-guide/img/optional-props-form.jpg
  docs/user-guide/img/override-default-service-results.jpg
  docs/user-guide/img/override-default-service.jpg
  docs/user-guide/img/permission-rule-added.jpg
  docs/user-guide/img/remove-rule-icon.jpg
  docs/user-guide/img/result-display-properties-form.jpg
  docs/user-guide/img/save-update-button.jpg
  docs/user-guide/img/select-rule-for-groups.jpg
  docs/user-guide/img/settings-icon.jpg
  docs/user-guide/img/settings-panel.jpg
  docs/user-guide/img/style_editor.jpg
  docs/user-guide/img/style_editor_add_style_button.jpg
  docs/user-guide/img/style_editor_add_style_template.jpg
  docs/user-guide/img/style_editor_autocomplete.jpg
  docs/user-guide/img/style_editor_back_button.jpg
  docs/user-guide/img/style_editor_color_picker.jpg
  docs/user-guide/img/style_editor_color_picker_icon.jpg
  docs/user-guide/img/style_editor_edit_button.jpg
  docs/user-guide/img/style_editor_edit_new_style.gif
  docs/user-guide/img/style_editor_edit_style.gif
  docs/user-guide/img/style_editor_error_icon.jpg
  docs/user-guide/img/style_editor_new_style_button.jpg
  docs/user-guide/img/style_editor_new_style_in_list.jpg
  docs/user-guide/img/style_editor_new_style_name.jpg
  docs/user-guide/img/style_editor_save_current_style.jpg
  docs/user-guide/img/style_editor_syntax_error.jpg
  docs/user-guide/img/wfs-service-props-form.jpg
  docs/user-guide/img/wfs-services-list.jpg
  docs/user-guide/index.md
  docs/user-guide/layer-settings.md
  docs/user-guide/managing-groups.md
  docs/user-guide/managing-user-rights.md
  docs/user-guide/managing-users-and-groups.md
  docs/user-guide/managing-users.md
  docs/user-guide/menu-bar.md
  mkdocs.yml
Labels: pending review, review

#3511 User-guide docs Editing section
  docs/user-guide/attributes-table.md
  docs/user-guide/home-page.md
  docs/user-guide/img/add-new-feature-attributes.jpg
  docs/user-guide/img/add-new-feature-icon.jpg
  docs/user-guide/img/add-shape-icon.jpg
  docs/user-guide/img/attribute-table-editing-layer.jpg
  docs/user-guide/img/cancel-changes.jpg
  docs/user-guide/img/delete-features-button.jpg
  docs/user-guide/img/delete-geometry-button.jpg
  docs/user-guide/img/delete-line-shape.gif
  docs/user-guide/img/drawing-line-shape.gif
  docs/user-guide/img/drawing-point-shape.gif
  docs/user-guide/img/drawing-polygon-shape.gif
  docs/user-guide/img/edit-mode.jpg
  docs/user-guide/img/editing-button.jpg
  docs/user-guide/img/marker.jpg
  docs/user-guide/img/missing-geometry-exclamation-point.jpg
  docs/user-guide/img/missing-geometry.jpg
  docs/user-guide/img/quit-edit-mode-button.jpg
  docs/user-guide/img/save-changes.jpg
  docs/user-guide/img/update-polygon-shape.gif
  docs/user-guide/index.md
  docs/user-guide/layer-settings.md
Labels: pending review, review

#3510 Fix #3483 Confirmation dialog (when you cancel changes in feature grid) has some visualization problems
  web/client/components/data/featuregrid/dialog/ConfirmClear.jsx
  web/client/components/data/featuregrid/dialog/ConfirmDelete.jsx
  web/client/components/data/featuregrid/dialog/ConfirmFeatureClose.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmClear-test.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmDelete-test.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmFeatureClose-test.jsx
Labels: pending review, review

#3506 Fix #3370 Add more templates in Style Editor
  web/client/components/misc/cardgrids/SquareCard.jsx
  web/client/components/styleeditor/SVGPreview.jsx
  web/client/components/styleeditor/StyleList.jsx
  web/client/components/styleeditor/StyleTemplates.jsx
  web/client/components/styleeditor/mode/geocss.js
  web/client/plugins/styleeditor/index.js
  web/client/themes/default/less/sidegrid.less
  web/client/themes/default/less/style-editor.less
  web/client/utils/styleeditor/img/randomdots.png
  web/client/utils/styleeditor/stylesTemplates.js
Labels: pending review, review

#3513 Fix #3498. Set configurable minZoom and Extent for mutliple projections
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/mapcontrols/scale/ScaleBox.jsx
  web/client/components/mapcontrols/scale/__tests__/ScaleBox-test.jsx
  web/client/epics/__tests__/map-test.js
  web/client/epics/map.js
  web/client/plugins/Map.jsx
  web/client/plugins/ScaleBox.jsx
  web/client/plugins/ZoomOut.jsx
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/map.js
Labels: pending review, review

#3514 Fix warnings and set states for resize observable and deprecations
  web/client/components/misc/enhancers/withResizeSpy.js
  web/client/components/widgets/view/WidgetsView.jsx
Labels: pending review, review

#3518 User docs
  docs/theme/partials/footer.html
  docs/user-guide/attributes-table.md
  docs/user-guide/css/extra.css
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/exploring-maps.md
  docs/user-guide/home-page.md
  docs/user-guide/img/geosolutions-brand.png
  docs/user-guide/index.md
  docs/user-guide/layer-settings.md
  docs/user-guide/managing-groups.md
  docs/user-guide/managing-users-and-groups.md
  docs/user-guide/managing-users.md
  docs/user-guide/measure.md
  docs/user-guide/menu-bar.md
  docs/user-guide/quick-start.md
  docs/user-guide/share.md
  docs/user-guide/toc.md
  docs/user-guide/widgets.md
  mkdocs.yml
Labels: pending review, review

#3520 User guide and developer guide integration
  docs/developer-guide/configuration-files.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/index.md
  docs/developer-guide/infrastructure-and-general-architecture.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/plugins-documentation.md
  docs/index.md
  docs/quick-start.md
  docs/theme/css/extra.css
  docs/theme/img/geosolutions-brand.png
  docs/theme/img/mapstore2-logo.png
  docs/theme/partials/footer.html
  docs/theme/partials/tabs.html
  docs/user-guide/index.md
  mkdocs.yml
Labels: pending review, review

#3519 Fix grid set misalignment in some crs
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
Labels: pending review, review

#3521 Fixes wrong links
  README.md
  docma-config.json
  docs/index.md
  docs/theme/css/extra.css
  docs/theme/partials/footer.html
  docs/theme/partials/tabs.html
  mkdocs.yml
  web/client/jsapi/MapStore2.js
  web/client/plugins/HelpLink.jsx
  web/client/plugins/index.jsdoc
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3517 Fixes #3516: more override functionalities for plugins
  web/client/components/plugins/PluginsContainer.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/Map-test.jsx
  web/client/plugins/__tests__/ZoomIn-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginUtils-test.js
Labels: pending review, review

#3526 Update README.md
  README.md
Labels: pending review, review

#3529 Renaming MapStore2 to MapStore in user and dev guides
  docs/developer-guide/API-usage.md
  docs/developer-guide/application-tutorial.md
  docs/developer-guide/building-and-deploying.md
  docs/developer-guide/code-conventions.md
  docs/developer-guide/configuration-files.md
  docs/developer-guide/contributing-guidelines.md
  docs/developer-guide/custom-search-service.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/developing.md
  docs/developer-guide/how-to-use-a-cdn.md
  docs/developer-guide/index.md
  docs/developer-guide/infrastructure-and-general-architecture.md
  docs/developer-guide/internationalization.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/plugins-architecture.md
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/project-structure.md
  docs/developer-guide/reactjs-and-redux-introduction.md
  docs/developer-guide/release.md
  docs/index.md
  docs/quick-start.md
  docs/theme/partials/footer.html
  docs/user-guide/attributes-table.md
  docs/user-guide/catalog.md
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/exploring-maps.md
  docs/user-guide/home-page.md
  docs/user-guide/layer-settings.md
  docs/user-guide/local-files.md
  docs/user-guide/measure.md
  docs/user-guide/menu-bar.md
  docs/user-guide/side-bar.md
  docs/user-guide/widgets.md
  mkdocs.yml
Labels: pending review, review

#3524 Fix #3523 add coordinated editor in search bar
  web/client/actions/__tests__/additionallayers-test.js
  web/client/actions/__tests__/map-test.js
  web/client/actions/__tests__/search-test.js
  web/client/actions/additionallayers.js
  web/client/actions/map.js
  web/client/actions/search.js
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/misc/coordinateeditors/CoordinateEntry.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/DecimalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
  web/client/components/misc/coordinateeditors/enhancers/__tests__/decimalToAeronautical-test.js
  web/client/components/misc/coordinateeditors/enhancers/__tests__/no90Lat-test.js
  web/client/components/misc/coordinateeditors/enhancers/coordinateTypePreset.js
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
  web/client/components/misc/coordinateeditors/enhancers/no90Lat.js
  web/client/components/misc/coordinateeditors/enhancers/tempAeronauticalValue.js
  web/client/components/misc/toolbar/DropdownToolbarOptions.jsx
  web/client/components/misc/toolbar/Toolbar.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/map.js
  web/client/epics/search.js
  web/client/localConfig.json
  web/client/plugins/MapSearch.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/manager/GroupManager.jsx
  web/client/plugins/manager/UserManager.jsx
  web/client/reducers/__tests__/additionallayers-test.js
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/additionallayers.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
  web/client/themes/default/less/map-search-bar.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: Project: C125, enhancement, pending review, review

#3527 Config provider pdok
  docs/developer-guide/maps-configuration.md
  web/client/utils/ConfigProvider.js
Labels: review

#3536 Fix #3525 add possibility to save and load mapInfo configuration
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/share/ShareEmbed.jsx
  web/client/epics/mapexport.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Save.jsx
  web/client/plugins/SaveAs.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapinfo-test.js
  web/client/selectors/mapinfo.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Project: C125, pending review, review

#3539 Fix #3530. Fixed layer properties in dashboard
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/nodeEditor-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/nodeEditor.js
Labels: pending review, review

#3541 Fixing image in user guide home page
  docs/quick-start.md
  docs/user-guide/img/home-page.jpg
Labels: pending review, review

#3540 Update CONTRIBUTING.md
  CONTRIBUTING.md
  docs/developer-guide/developing-with-mapstore-2-intro.md
Labels: Documentation, pending review, review

#3543 Fixing wrong links in dev doc
  docs/developer-guide/developing-with-mapstore-2-intro.md
Labels: pending review, review

#3538 Fix #3537 Zoom to layer does not work
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
Labels: pending review, review

#3544 Fix #3523 improved search tool
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/details/DetailsPanel.jsx
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
  web/client/components/misc/coordinateeditors/CoordinateEntry.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/DecimalCoordinateEditor.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
  web/client/plugins/SearchServicesConfig.jsx
  web/client/product/assets/img/marker-icon-red.png
  web/client/product/assets/img/marker-shadow.png
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/less/map-search-bar.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/SearchUtils.js
  web/client/utils/__tests__/SearchUtils-test.js
Labels: Project: C125, pending review, review

#3546 Fix #3545 BBOX query param
  web/client/components/misc/Dialog.jsx
  web/client/components/misc/style/dialog.css
  web/client/components/share/ShareApi.jsx
  web/client/components/share/ShareCopyToClipboard.jsx
  web/client/components/share/ShareEmbed.jsx
  web/client/components/share/ShareLink.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/ShareQRCode.jsx
  web/client/components/share/ShareSocials.jsx
  web/client/components/share/__tests__/ShareApi-test.jsx
  web/client/components/share/__tests__/ShareCopyToClipboard-test.jsx
  web/client/components/share/__tests__/ShareEmbed-test.jsx
  web/client/components/share/__tests__/ShareLink-test.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/components/share/__tests__/ShareQRCode-test.jsx
  web/client/components/share/__tests__/ShareSocials-test.jsx
  web/client/components/share/share.css
  web/client/epics/__tests__/share-test.js
  web/client/epics/share.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/product/embedded.jsx
  web/client/product/main.jsx
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/share.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: pending review, review

#3551 fix default style for coordinate editor
  web/client/plugins/Search.jsx
Labels: bug

#3553 Fix require mapInfo selector for c125_annotations branch
  docma-config.json
  web/client/epics/identify.js
  web/client/epics/maplayout.js
  web/client/plugins/Save.jsx
  web/client/plugins/TOC.jsx
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/annotations.js
  web/client/selectors/mapInfo.js
Labels: Project: C125, pending review, review

#3558 Fix #3138. Avoid purgeMapInfoResults to refresh layout
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/annotations.js
  web/client/epics/featuregrid.js
  web/client/epics/maplayout.js
Labels: pending review, review

#3560 Add configuration to Footer plugin
  web/client/product/plugins/Footer.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: enhancement, pending review, review

#3556 Fix #3138. Avoid purgeMapInfoResults to refresh layout (2019.01.xx)
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/annotations.js
  web/client/epics/featuregrid.js
  web/client/epics/maplayout.js
Labels: Blocked, bug, pending review, review

#3559 Some improvements for #3523 address and coordinate search
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/localConfig.json
Labels: Project: C125

#3563 Updated style of active toggled buttons
  web/client/components/buttons/FullScreenButton.jsx
  web/client/components/buttons/GlobeViewSwitcherButton.jsx
  web/client/components/mapcontrols/locate/LocateBtn.jsx
  web/client/plugins/playback/Playback.jsx
Labels: enhancement, pending review, review

#3565 Updated style of active toggled buttons
  web/client/components/buttons/FullScreenButton.jsx
  web/client/components/buttons/GlobeViewSwitcherButton.jsx
  web/client/components/mapcontrols/locate/LocateBtn.jsx
  web/client/plugins/playback/Playback.jsx
Labels: pending review, review

#3566 Fix #3562. Fixed API map load action sequence
  web/client/components/development/Debug.jsx
  web/client/containers/Embedded.jsx
  web/client/jsapi/MapStore2.js
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/test-resources/geostore/data/1
  web/client/test-resources/version.txt
  web/client/utils/DebugUtils.js
Labels: pending review, review

#3567 Fix #3564. Annotation panel closes when annotation layer removed
  web/client/selectors/__tests__/annotations-test.js
  web/client/selectors/annotations.js
Labels: pending review, review

#3569 Fix #3564. Annotation panel closes when annotation layer removed (2019.01.00)
  web/client/selectors/__tests__/annotations-test.js
  web/client/selectors/annotations.js
Labels: pending review, review

#3568 Fix #3562. Fixed API map load action sequence (2019.01.00)
  web/client/components/development/Debug.jsx
  web/client/containers/Embedded.jsx
  web/client/jsapi/MapStore2.js
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/test-resources/geostore/data/1
  web/client/test-resources/version.txt
  web/client/utils/DebugUtils.js
Labels: pending review, review

#3557 Fix #3548 add coordinate editor for GFI panel
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/GeocodeViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/GeocodeViewer-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/enhancers/draggableComponent.jsx
  web/client/components/misc/enhancers/draggableContainer.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/identify/CoordinatesEditor.jsx
  web/client/plugins/identify/defaultIdentifyButtons.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: Project: C125, pending review, review

#3570 Fixed doc version and URLs
  .github/config.yml
  README.md
  docma-config.json
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/frontend-building-tools-and-configuration.md
  docs/theme/css/extra.css
  mkdocs.yml
  web/client/jsapi/MapStore2.js
  web/client/plugins/HelpLink.jsx
  web/client/plugins/index.jsdoc
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3572 Fixed doc(porting of #3570)(2019.01.xx)
  .github/config.yml
  README.md
  docma-config.json
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/frontend-building-tools-and-configuration.md
  docs/theme/css/extra.css
  mkdocs.yml
  web/client/jsapi/MapStore2.js
  web/client/plugins/HelpLink.jsx
  web/client/plugins/index.jsdoc
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
Labels: pending review, review

#3571 Fix update symbol style in annotation styler panel
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/Feature.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/components/style/StyleCanvas.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/utils/VectorStyleUtils.js
Labels: Project: C125, annotations, bug, pending review, review

#3575 Fix #3574 Remove Google plus link in Share panel
  web/client/components/share/ShareSocials.jsx
Labels: Priority: Blocker, pending review, review

#3576 CHANGELOG 2019.01.00 release
  CHANGELOG.md
Labels: pending review, review

#3577 Remove FloatingLegend for the release
  web/client/localConfig.json
Labels: Task, pending review, review

#3573 Merge master 25 02 2019 on c125_annotations
  .github/config.yml
  README.md
  docma-config.json
  docs/developer-guide/developing-with-mapstore-2-intro.md
  docs/developer-guide/frontend-building-tools-and-configuration.md
  docs/theme/css/extra.css
  mkdocs.yml
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/buttons/FullScreenButton.jsx
  web/client/components/buttons/GlobeViewSwitcherButton.jsx
  web/client/components/data/identify/GeocodeViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/GeocodeViewer-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/components/development/Debug.jsx
  web/client/components/mapcontrols/locate/LocateBtn.jsx
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/enhancers/draggableComponent.jsx
  web/client/containers/Embedded.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/annotations.js
  web/client/epics/featuregrid.js
  web/client/epics/maplayout.js
  web/client/jsapi/MapStore2.js
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/localConfig.json
  web/client/plugins/HelpLink.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/identify/CoordinatesEditor.jsx
  web/client/plugins/identify/defaultIdentifyButtons.js
  web/client/plugins/index.jsdoc
  web/client/plugins/playback/Playback.jsx
  web/client/product/plugins/Footer.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/annotations-test.js
  web/client/selectors/annotations.js
  web/client/test-resources/geostore/data/1
  web/client/test-resources/version.txt
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/DebugUtils.js
Labels: Project: C125, annotations, pending review, review

#3579 Fix #3578. Fix issues with layernames containing points
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/__tests__/query-test.js
  web/client/selectors/featuregrid.js
  web/client/selectors/query.js
Labels: pending review, review

#3580 Release 2019.01.00 - porting changelog and docs changes to master
  CHANGELOG.md
  docs/developer-guide/release.md
Labels: pending review, review

#3583 Fixed formatting of project creation guide
  docs/developer-guide/project-creation-script.md
Labels: pending review, review

#3587 exclude spring dependencies from print plugin
  project/standard/templates/web/pom.xml
  web/pom.xml
Labels: pending review, review

#3582 Fix #3578. Fix issues with layernames containing points (2019.01.xx)
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/__tests__/query-test.js
  web/client/selectors/featuregrid.js
  web/client/selectors/query.js
Labels: pending review, review

#3588 Fixes #3584: security token added to printed wms layers and legends
  web/client/libs/__tests__/ajax-test.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
  web/client/utils/__tests__/SecurityUtils-test.js
Labels: pending review, review
