Repository geosolutions-it/MapStore2, pull requests merged in 2019-08, with the labels that each got.

#4070 Add documentation for timesync and notes
  docs/user-guide/img/timeline-sync-button.jpg
  docs/user-guide/img/timeline-sync-example.jpg
  docs/user-guide/timeline.md
Labels: Documentation

#4017 Fix 4009 add_layers from catalog
  docs/developer-guide/map-query-parameters.md
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/epics/queryparams.js
  web/client/test-resources/csw/getRecordsResponse-gs-us_states.xml
Labels: Project: C040, enhancement

#4096 Fix issue 78 Load story configuration (C039_geostory)
  package-lock.json
  web/client/actions/__tests__/geostory-test.js
  web/client/actions/geostory.js
  web/client/components/home/Home.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/GeoStory.jsx
  web/client/product/appConfig.js
  web/client/product/pages/GeoStory.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
  web/client/sampleStory.json
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.vi-VN
  web/client/translations/data.zh-ZH
Labels: Task

#4102 Geostory - Normal editor - Title (C039_geostory)
  web/client/components/geostory/builder/SectionsPreview.jsx
  web/client/components/geostory/common/AddBar.jsx
  web/client/components/geostory/common/ToolbarDropdownButton.jsx
  web/client/components/geostory/common/__tests__/ToolbarDropdownButton-test.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/geostory/contents/ContentWrapper.jsx
  web/client/components/geostory/contents/Contents.jsx
  web/client/components/geostory/contents/__tests__/ContentToolbar-test.jsx
  web/client/components/geostory/contents/__tests__/ContentWrapper-test.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Paragraph.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/sampleStory.json
  web/client/themes/default/less/geostory.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.vi-VN
  web/client/translations/data.zh-ZH
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: Task

#4109 Fix #4009 wms records and improved error handling
  docs/developer-guide/map-query-parameters.md
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.vi-VN
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Project: C040

#4111 Porting on (2019.02.xx) of fix for #4009 wms records and improved error handling
  docs/developer-guide/map-query-parameters.md
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.vi-VN
  web/client/translations/data.zh-ZH
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Project: C040

#4112 Fix 3814 single_layer option for launchInfoPanel and highlight features
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/identify.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
  web/client/test-resources/featureInfo-response.json
Labels: enhancement
