Repository geosolutions-it/MapStore2, pull requests merged in 2019-05, with the labels that each got.

#3651 Fix #3585 date-time and time support
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/BaseDateTimeFilter-test.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/DateTimeFilter-test.jsx
  web/client/components/data/query/DateField.jsx
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/DateField-test.jsx
  web/client/components/misc/enhancers/__tests__/utcDateWrapper-test.jsx
  web/client/components/misc/enhancers/utcDateWrapper.js
  web/client/utils/FeatureTypeUtils.js
  web/client/utils/LocaleUtils.js
  web/client/utils/TimeUtils.js
  web/client/utils/__tests__/LocaleUtils-test.js
  web/client/utils/__tests__/TimeUtils-test.js
Labels: Priority: High, bug, pending review, review

#3710 Fix #3585 date-time and time support (2019.01.xx)
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/BaseDateTimeFilter-test.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/DateTimeFilter-test.jsx
  web/client/components/data/query/DateField.jsx
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/DateField-test.jsx
  web/client/components/misc/enhancers/__tests__/utcDateWrapper-test.jsx
  web/client/components/misc/enhancers/utcDateWrapper.js
  web/client/utils/FeatureTypeUtils.js
  web/client/utils/LocaleUtils.js
  web/client/utils/TimeUtils.js
  web/client/utils/__tests__/LocaleUtils-test.js
  web/client/utils/__tests__/TimeUtils-test.js
Labels: pending review, review

#3705 Fix #3456 action and reducer dev guide
  build/docma-config.json
  docs/developer-guide/application-modes.md
  docs/developer-guide/application-pages.md
  docs/developer-guide/dev-how-to.md
  docs/developer-guide/plugins-howto.md
  docs/developer-guide/project-structure.md
  docs/developer-guide/writing-actions-reducers.md
  mkdocs.yml
  web/client/utils/ImmutableUtils.js
Labels: Dev Guide, pending review, review

#3707 Fix #3706 Add support for simple GeoJSON to shapefile
  web/client/components/shapefile/ShapefileUploadAndStyle.jsx
  web/client/components/shapefile/__tests__/ShapefileUploadAndStyle-test.jsx
  web/client/test-resources/LineGeoJSON.zip
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Project: C098, enhancement, pending review, review

#3711 Fixed issue with usergroup name
  web/client/components/manager/users/UserCard.jsx
  web/client/components/manager/users/__tests__/UserCard-test.jsx
Labels: pending review, review

#3701 Some improvements to projects ecosystem: aliases, proxy configuration interactive createProject script
  build/buildConfig.js
  build/testConfig.js
  createProject.js
  docs/developer-guide/project-creation-script.md
  package.json
  project/custom/static/jsconfig.json
  project/custom/static/karma.conf.continuous-test.js
  project/custom/static/karma.conf.single-run.js
  project/custom/templates/prod-webpack.config.js
  project/custom/templates/webpack.config.js
  project/standard/static/jsconfig.json
  project/standard/static/karma.conf.continuous-test.js
  project/standard/static/karma.conf.single-run.js
  project/standard/templates/js/app.jsx
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
  utility/projects/projectScripts.json
  web/client/selectors/highlight.js
Labels: pending review, review

#3709 Fix #3708 The "Create new style" popup does not appear in Safari
  web/client/components/styleeditor/StyleTemplates.jsx
  web/client/components/styleeditor/StyleToolbar.jsx
  web/client/components/styleeditor/__tests__/StyleTemplates-test.jsx
  web/client/components/styleeditor/__tests__/StyleToolbar-test.jsx
  web/client/plugins/styleeditor/index.js
Labels: pending review, review

#3714 Fix #3642 Switch between widgets and timeline (2019.01.xx)
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/widgetsTray-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/epics/widgetsTray.js
  web/client/localConfig.json
  web/client/plugins/Timeline.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/WidgetsTray.jsx
  web/client/plugins/timeline/Timeline.jsx
  web/client/plugins/timeline/TimelineToggle.jsx
  web/client/plugins/widgets/WidgetsBar.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
  web/client/plugins/widgets/widgetsPermission.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
  web/client/selectors/__tests__/timeline-test.js
  web/client/selectors/timeline.js
  web/client/selectors/widgetsTray.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3717 Fix #3713 Pop up Validation error doesn't show up for SLD
  web/client/reducers/__tests__/styleeditor-test.js
  web/client/reducers/styleeditor.js
Labels: pending review, review

#3718 Fix #3712 SLD styles version 1.1.0 are not saved correctly from Style Editor
  web/client/actions/__tests__/styleeditor-test.js
  web/client/actions/styleeditor.js
  web/client/api/geoserver/Styles.js
  web/client/api/geoserver/__tests__/Styles-test.js
  web/client/components/styleeditor/StyleList.jsx
  web/client/components/styleeditor/StyleToolbar.jsx
  web/client/epics/__tests__/styleeditor-test.js
  web/client/epics/styleeditor.js
  web/client/plugins/styleeditor/index.js
  web/client/reducers/__tests__/styleeditor-test.js
  web/client/reducers/styleeditor.js
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
Labels: pending review, review

#3719 Fix #3415 Layer properties are not accessible if its style is invalid
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
Labels: pending review, review

#3722 Fix #3708 The "Create new style" popup does not appear in Safari (2019.01.xx)
  web/client/components/styleeditor/StyleTemplates.jsx
  web/client/components/styleeditor/StyleToolbar.jsx
  web/client/components/styleeditor/__tests__/StyleTemplates-test.jsx
  web/client/components/styleeditor/__tests__/StyleToolbar-test.jsx
  web/client/plugins/styleeditor/index.js
Labels: pending review, review

#3723 Fix #3713 Pop up Validation error doesn't show up for SLD (2019.01.xx)
  web/client/reducers/__tests__/styleeditor-test.js
  web/client/reducers/styleeditor.js
Labels: pending review, review

#3724 Fix #3712 SLD styles version 1.1.0 are not saved correctly from Style Editor (2019.01.xx)
  web/client/actions/__tests__/styleeditor-test.js
  web/client/actions/styleeditor.js
  web/client/api/geoserver/Styles.js
  web/client/api/geoserver/__tests__/Styles-test.js
  web/client/components/styleeditor/StyleList.jsx
  web/client/components/styleeditor/StyleToolbar.jsx
  web/client/epics/__tests__/styleeditor-test.js
  web/client/epics/styleeditor.js
  web/client/plugins/styleeditor/index.js
  web/client/reducers/__tests__/styleeditor-test.js
  web/client/reducers/styleeditor.js
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
Labels: pending review, review

#3725 Fix #3415 Layer properties are not accessible if its style is invalid (2019.01.xx)
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
Labels: pending review, review

#3730 Closes #3385 After login on public map you can not save
  web/client/epics/__tests__/map-test.js
  web/client/epics/map.js
  web/client/plugins/SaveAs.jsx
Labels: Priority: High

#3733 Closes #3534 No result on one content tab cause switch to the other tab (maps/dashboards)
  web/client/actions/__tests__/contenttabs-test.js
  web/client/actions/contenttabs.js
  web/client/epics/__tests__/contenttabs-test.js
  web/client/epics/contenttabs.js
  web/client/plugins/ContentTabs.jsx
  web/client/plugins/Dashboards.jsx
  web/client/plugins/Maps.jsx
  web/client/reducers/__tests__/contenttabs-test.js
  web/client/reducers/contenttabs.js
Labels: Priority: High, pending review, review

#3735 Closes #3393 Featured maps are not updated on user log(in/out)
  web/client/plugins/FeaturedMaps.jsx
Labels: pending review, review

#3736 Closes #3671 Fixed translations in advanced filter
  web/client/components/data/query/CrossLayerFilter.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: pending review, review

#3737 Closes #2349 Improve search plugin error message
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Priority: High, pending review, review

#3728 Closes #3695 Wrong west coordinates in mouse position
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx
  web/client/components/mapcontrols/mouseposition/__tests__/MousePositionLabelDMS-test.js
Labels: Priority: High, pending review, review

#3739 Fix #3738 Add the possibility to customize default regex for GeoServer
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: pending review, review

#3743 Fix #3738 Add the possibility to customize default regex for GeoServer (2019.01.xx)
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: pending review, review

#3742 Close #3695 Wrong west south coordinates
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx
  web/client/components/mapcontrols/mouseposition/__tests__/MousePositionLabelDMS-test.js
Labels: Priority: High, pending review, review

#3745 Fix #3671 add missing i18n for advanced filter (#3736)
  web/client/components/data/query/CrossLayerFilter.jsx
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Priority: High, pending review, review

#3744 Fix #3393 Featured maps update on user login/logout (#3735)
  web/client/plugins/FeaturedMaps.jsx
Labels: Priority: High

#3746 Closes #3534 switch content tab when 0 results (maps/dashboards) (#3733)
  web/client/actions/__tests__/contenttabs-test.js
  web/client/actions/contenttabs.js
  web/client/epics/__tests__/contenttabs-test.js
  web/client/epics/contenttabs.js
  web/client/plugins/ContentTabs.jsx
  web/client/plugins/Dashboards.jsx
  web/client/plugins/Maps.jsx
  web/client/reducers/__tests__/contenttabs-test.js
  web/client/reducers/contenttabs.js
Labels: Priority: High, pending review, review

#3747 Backport Fix #3385 fix missing save button after login to 2019.xx
  web/client/epics/__tests__/map-test.js
  web/client/epics/map.js
  web/client/plugins/SaveAs.jsx
Labels: Priority: High

#3748 Port Fix #2349 Improve search plugin error message (#3737) to 2019.xx
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Priority: High, pending review, review

#3749 Port of #3695 Wrong west south coordinates (#3742)
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx
  web/client/components/mapcontrols/mouseposition/__tests__/MousePositionLabelDMS-test.js
Labels: Priority: High, pending review, review

#3751 Fix #3624. Add documentation to solve strict CITE compliance
  docs/user-guide/attributes-table.md
Labels: pending review, review

#3757 Close #3385 Close missing save button after login
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: pending review, review

#3755 Fix #3754 Add default configuration for testing in Style Editor
  web/client/localConfig.json
Labels: pending review, review

#3760 Fix #3754 Add default configuration for testing in Style Editor (2019.01.xx)
  web/client/localConfig.json
Labels: pending review, review

#3761 Close #3385 Close missing save button after login
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: pending review, review

#3741 Fix #3456 action and reducers doc updated
  docs/developer-guide/writing-actions-reducers.md
  web/client/actions/map.js
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Dev Guide, pending review, review

#3702 Some improvements to plugins and projects documentation
  docs/developer-guide/mapstore-projects.md
  docs/developer-guide/plugins-howto.md
  mkdocs.yml
Labels: pending review, review

#3759 Close 3758 add git tracking of package-lock.json file (#3758)
  package-lock.json
Labels: pending review, review

#3752 Fix #3083 - When adding a new group/user is not clear which section is opened
  web/client/components/manager/users/GroupDialog.jsx
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/manager/users/__tests__/GroupDialog-test.jsx
  web/client/components/manager/users/__tests__/UserDialog-test.jsx
Labels: Priority: Medium, enhancement, pending review, review

#3766 Fix #2231 - Readability of username in manager
  docs/developer-guide/writing-actions-reducers.md
  web/client/components/manager/users/UserCard.jsx
  web/client/components/manager/users/__tests__/UserCard-test.jsx
Labels: pending review, review

#3780 Fix #3450 Added docker files to standard proj
  createProject.js
Labels: Environment, enhancement

#3734 Fixes #3732: createPlugin helper function
  web/client/plugins/BurgerMenu.jsx
  web/client/plugins/ShapeFile.jsx
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginUtils-test.js
Labels: pending review, review

#3799 Merge master over c125_annotations branch
  web/client/components/data/query/CrossLayerFilter.jsx
  web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx
  web/client/components/mapcontrols/mouseposition/__tests__/MousePositionLabelDMS-test.js
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/style/thumbGeoms/__tests__/MultiGeomThumb-test.js
  web/client/components/style/thumbGeoms/__tests__/PolygonThumb-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Project: C125, annotations

#3797 #2215: add group in TOC toolbar
  web/client/actions/__tests__/controls-test.js
  web/client/actions/__tests__/layers-test.js
  web/client/actions/controls.js
  web/client/actions/layers.js
  web/client/components/TOC/DefaultGroup.jsx
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordGrid.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/maplayout.js
  web/client/localConfig.json
  web/client/plugins/AddGroup.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/__tests__/AddGroup-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/product/plugins.js
  web/client/reducers/__tests__/controls-test.js
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/controls.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
  web/client/utils/CatalogUtils.js
Labels: Priority: High, enhancement

#3798 CRS Selector Merge
  docs/developer-guide/release.md
  package.json
  web/client/actions/__tests__/crsselector-test.js
  web/client/actions/__tests__/map-test.js
  web/client/actions/crsselector.js
  web/client/actions/map.js
  web/client/components/background/BackgroundSelector.jsx
  web/client/components/background/PreviewIcon.jsx
  web/client/components/background/__tests__/PreviewIcon-test.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Feature.jsx
  web/client/components/map/openlayers/Layer.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/mapcontrols/crsselectormenu/CrsSelectorMenu.jsx
  web/client/components/mapcontrols/crsselectormenu/__tests__/crsSelectormenu-test.js
  web/client/components/mapcontrols/scale/ScaleBox.jsx
  web/client/components/mapcontrols/scale/__tests__/ScaleBox-test.jsx
  web/client/epics/__tests__/map-test.js
  web/client/epics/identify.js
  web/client/epics/map.js
  web/client/epics/maplayout.js
  web/client/localConfig.json
  web/client/plugins/BackgroundSelector.jsx
  web/client/plugins/CRSSelector.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/ScaleBox.jsx
  web/client/plugins/ZoomOut.jsx
  web/client/plugins/map/index.js
  web/client/product/plugins.js
  web/client/reducers/__tests__/crsselector-test.js
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/crsselector.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/crsselector-test.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/crsselector.js
  web/client/selectors/map.js
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/less/dropdown-menu.less
  web/client/themes/default/less/map-footer.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.hr-HR
  web/client/translations/data.it-IT
  web/client/translations/data.nl-NL
  web/client/translations/data.pt-PT
  web/client/translations/data.zh-ZH
  web/client/utils/CoordinatesUtils.js
  web/client/utils/openlayers/Layers.js
Labels: Priority: High, enhancement

#3764 Fix #3763. Fixed cql filter for date filter operator between (><)
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: pending review, review
