Repository geosolutions-it/MapStore2, pull requests merged in 2020-03, with the labels that each got.

#4951 #4950: fixes upload request content-type and reloading of extensionsjson after a plugin upload
  package.json
  project/custom/static/js/app.jsx
  web/client/actions/__tests__/contextcreator-test.js
  web/client/actions/__tests__/theme-test.js
  web/client/actions/contextcreator.js
  web/client/actions/theme.js
  web/client/api/__tests__/plugins-test.js
  web/client/api/plugins.js
  web/client/components/app/StandardApp.jsx
  web/client/components/app/StandardRouter.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/components/app/__tests__/StandardRouter-test.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmClear-test.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmDelete-test.jsx
  web/client/components/data/featuregrid/dialog/__tests__/ConfirmFeatureClose-test.jsx
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/examples/plugins/store.js
  web/client/plugins/ThemeSwitcher.jsx
  web/client/product/main.jsx
  web/client/reducers/__tests__/theme-test.js
  web/client/reducers/theme.js
  web/client/stores/StandardStore.js
  web/client/stores/__tests__/StandardStore-test.js
  web/client/test-resources/plugin.zip
Labels: geOrchestra

#4949 4944 Impossible to remove all plugins from the right list of wizard s…
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
Labels: geOrchestra

#4958 4946 filtering layers
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/button/advanced-search.jpg
  docs/user-guide/img/button/cond_group.JPG
  docs/user-guide/img/button/search.jpg
  docs/user-guide/img/filtering-layers/applied_filter.jpg
  docs/user-guide/img/filtering-layers/ar_sync.gif
  docs/user-guide/img/filtering-layers/att_filter.gif
  docs/user-guide/img/filtering-layers/attribute-table-quick-filter-1.jpg
  docs/user-guide/img/filtering-layers/attribute-table-quick-filter-3.jpg
  docs/user-guide/img/filtering-layers/edit_geom.jpg
  docs/user-guide/img/filtering-layers/enable_layer_filter.gif
  docs/user-guide/img/filtering-layers/filter_layer_button.jpg
  docs/user-guide/img/filtering-layers/filter_set_up.jpg
  docs/user-guide/img/filtering-layers/geom_filter.gif
  docs/user-guide/img/filtering-layers/layer-filter-1.jpg
  docs/user-guide/img/filtering-layers/layer_filter.gif
  docs/user-guide/img/filtering-layers/modify_layer_filter.gif
  docs/user-guide/img/filtering-layers/query-panel.jpg
  docs/user-guide/img/filtering-layers/query_builder.jpg
  docs/user-guide/img/filtering-layers/rectangle_filter.jpg
  docs/user-guide/img/filtering-layers/remove_layer_filter.gif
  docs/user-guide/img/filtering-layers/toogle-layer.jpg
Labels: Documentation, User Guide

#4953 4938 invert context wizard steps
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/contextcreator/__tests__/ContextCreator-test.jsx
  web/client/plugins/__tests__/ContextCreator-test.jsx
Labels: Priority: High, geOrchestra

#4961 4946 attribute table
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/attribute-filter-1.jpg
  docs/user-guide/img/attributes-table/attribute-filter-2.jpg
  docs/user-guide/img/attributes-table/attribute-filter-3.jpg
  docs/user-guide/img/attributes-table/attribute-filter-4.jpg
  docs/user-guide/img/attributes-table/attribute-filter-5.jpg
  docs/user-guide/img/attributes-table/attribute-filter-6.jpg
  docs/user-guide/img/attributes-table/attribute-filter-7.jpg
  docs/user-guide/img/attributes-table/attribute-filter-8.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-1.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-2.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-3.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-4.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter.jpg
  docs/user-guide/img/attributes-table/download_grid.jpg
  docs/user-guide/img/attributes-table/filter-types.jpg
  docs/user-guide/img/attributes-table/geometry-filter-1.jpg
  docs/user-guide/img/attributes-table/geometry-filter-2.jpg
  docs/user-guide/img/attributes-table/geometry-filter.jpg
  docs/user-guide/img/attributes-table/hide-show-1.jpg
  docs/user-guide/img/attributes-table/layer-filter-1.jpg
  docs/user-guide/img/attributes-table/layer-filter-2.jpg
  docs/user-guide/img/attributes-table/layer-filter-3.jpg
  docs/user-guide/img/attributes-table/marker.jpg
  docs/user-guide/img/attributes-table/ordering_records.gif
  docs/user-guide/img/attributes-table/show_hide_columns.gif
  docs/user-guide/img/button/down_grid_data.jpg
  docs/user-guide/img/button/export_at.jpg
  docs/user-guide/img/button/hide_show_col.jpg
  docs/user-guide/img/button/sync.jpg
  docs/user-guide/img/button/sync_en.jpg
  docs/user-guide/img/button/zoom-feature.jpg
  docs/user-guide/menu-bar.md
  docs/user-guide/widgets.md
Labels: Documentation, User Guide

#4939 #4922: fixed ol WMTS layer extent usage, to skip only the invalid ones
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
Labels: enhancement, geOrchestra

#4965 4946 review settings, filter and att table
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/layer-settings/panel_sections.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/resources-properties.md
  docs/user-guide/widgets.md
Labels: Documentation, User Guide

#4960 Speed up OpenLayers map loading (#4750)
  web/client/components/map/openlayers/Map.jsx
Labels: OpenLayers, enhancement

#4976 4967 Modify the "follow user" functionality.
  web/client/components/mapcontrols/locate/LocateBtn.jsx
  web/client/components/mapcontrols/locate/__tests__/LocateBtn-test.jsx
  web/client/plugins/Locate.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: geOrchestra

#4982 4946 catalog
  docs/user-guide/catalog.md
  docs/user-guide/img/button/cancel_service.jpg
  docs/user-guide/img/button/delete_service.jpg
  docs/user-guide/img/button/save_service.jpg
  docs/user-guide/img/catalog/add-service.jpg
  docs/user-guide/img/catalog/add_edit_services.jpg
  docs/user-guide/img/catalog/advanced_settings.jpg
  docs/user-guide/img/catalog/cat-adv-settings.jpg
  docs/user-guide/img/catalog/catalog-option.jpg
  docs/user-guide/img/catalog/catalog_firenze.jpg
  docs/user-guide/img/catalog/general_settings.jpg
  docs/user-guide/img/catalog/new_service.jpg
  mkdocs.yml
Labels: Documentation, User Guide

#4985 4946 measure
  docs/user-guide/img/button/measure-area-green.jpg
  docs/user-guide/img/button/measure-bearing-green.jpg
  docs/user-guide/img/button/measure-distance-green.jpg
  docs/user-guide/img/button/measure-icon.jpg
  docs/user-guide/img/measure/add-as-annotation-ex.jpg
  docs/user-guide/img/measure/annotation-prefill.jpg
  docs/user-guide/img/measure/area-uom.jpg
  docs/user-guide/img/measure/distance-uom.jpg
  docs/user-guide/img/measure/measure-area-1.jpg
  docs/user-guide/img/measure/measure-area-ex.gif
  docs/user-guide/img/measure/measure-bearing-1.jpg
  docs/user-guide/img/measure/measure-bearing-ex.gif
  docs/user-guide/img/measure/measure-distance-1.jpg
  docs/user-guide/img/measure/measure-distance-ex.gif
  docs/user-guide/img/measure/measure.jpg
  docs/user-guide/measure.md
Labels: Documentation, User Guide

#4987 4946 share
  docs/user-guide/img/button/sharebm.jpg
  docs/user-guide/img/share/embed.jpg
  docs/user-guide/img/share/share-1.jpg
  docs/user-guide/img/share/share-2.jpg
  docs/user-guide/img/share/share-3.jpg
  docs/user-guide/img/share/share-bbox.jpg
  docs/user-guide/img/share/share_cards.jpg
  docs/user-guide/img/share/share_window.jpg
  docs/user-guide/img/share/social.jpg
  docs/user-guide/share.md
  mkdocs.yml
Labels: Documentation, User Guide

#4966 4962 Allow the user to visualize the layer legend corresponding t…
  web/client/components/TOC/fragments/WMSLegend.jsx
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/legend/__tests__/Legend-test.jsx
  web/client/localConfig.json
  web/client/plugins/TOC.jsx
Labels: geOrchestra

#4969 Fix 4968 Navbar does not work on GeoStory mobile
  web/client/components/geostory/layouts/sections/Section.jsx
Labels: GeoStory, Mobile, bug

#4964 Fix 4963 GeoStory on Mobile
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/__tests__/Cascade-test.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/components/geostory/layouts/sections/__tests__/Immersive-test.jsx
  web/client/components/geostory/layouts/sections/__tests__/Title-test.jsx
  web/client/components/geostory/media/Map.jsx
  web/client/components/geostory/media/__tests__/Map-test.jsx
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/epics/geostory.js
  web/client/localConfig.json
  web/client/plugins/GeoStoryEditor.jsx
  web/client/plugins/GeoStoryNavigation.jsx
  web/client/plugins/__tests__/Map-test.jsx
  web/client/themes/default/less/geostory.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory, Mobile, enhancement

#4995 fix 4993 thumbnail catalog is being removed
  .eslintrc
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/Catalog-test.jsx
  web/client/components/data/identify/coordinates/Editor.jsx
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/components/manager/users/CloseConfirmButton.jsx
  web/client/components/manager/users/GroupDialog.jsx
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/map/BaseMap.jsx
  web/client/components/map/openlayers/__tests__/Feature-test.jsx
  web/client/components/mapcontrols/Snapshot/__tests__/SnapshotPanel-test.jsx
  web/client/components/misc/FocusMask.jsx
  web/client/components/security/UserMenu.jsx
  web/client/plugins/GridContainer.jsx
  web/client/test-resources/wmc/config.json
  web/client/utils/styleeditor/stylesTemplates.js
Labels: Backport Needed, Priority: High

#4996 Backport 2020.01.xx - 4993 thumbnail catalog is being removed (#4995)
  .eslintrc
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/Catalog-test.jsx
  web/client/components/data/identify/coordinates/Editor.jsx
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/components/manager/users/CloseConfirmButton.jsx
  web/client/components/manager/users/GroupDialog.jsx
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/map/BaseMap.jsx
  web/client/components/map/openlayers/__tests__/Feature-test.jsx
  web/client/components/mapcontrols/Snapshot/__tests__/SnapshotPanel-test.jsx
  web/client/components/misc/FocusMask.jsx
  web/client/components/security/UserMenu.jsx
  web/client/plugins/GridContainer.jsx
  web/client/plugins/Map.jsx
  web/client/test-resources/wmc/config.json
  web/client/utils/styleeditor/stylesTemplates.js
Labels: Backport

#4989 4977 Documentation extension. Add the logic to get configured url ins…
  build/docma-config.json
  web/client/plugins/HelpLink.jsx
  web/client/plugins/__tests__/HelpLink-test.jsx
  web/client/product/plugins.js
Labels: geOrchestra

#4956 Backport 2020.01.xx - #4827: Merging dashboard guide in master (#4901)
  docs/user-guide/connecting-widgets.md
  docs/user-guide/img/button/connections.jpg
  docs/user-guide/img/connecting-widgets/available_connections.jpg
  docs/user-guide/img/connecting-widgets/changes.gif
  docs/user-guide/img/connecting-widgets/connections-showed.jpg
  docs/user-guide/img/connecting-widgets/connections_widgets.gif
  docs/user-guide/img/connecting-widgets/filter_on_table.gif
  docs/user-guide/img/connecting-widgets/interaction_a.gif
  docs/user-guide/img/connecting-widgets/interaction_ab.gif
  docs/user-guide/img/connecting-widgets/table_filter.jpg
  docs/user-guide/img/connecting-widgets/widgets_interaction.gif
Labels: Backport

#5000 #4999 Fix relative path link in context-manager link
  web/client/epics/__tests__/contextmanager-test.js
  web/client/epics/contextmanager.js
Labels: Priority: Blocker, bug

#5005 MapCatalog plugin icon
  web/client/plugins/MapCatalog.jsx
  web/client/pluginsConfig.json
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/maps-catalog.svg
Labels: geOrchestra

#5001 #4990 background selector edit buttons
  web/client/plugins/BackgroundSelector.jsx
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/map.js
Labels: bug, geOrchestra

#4997 #4968 Navbar does not work on GeoStory mobile
  package.json
  web/client/components/geostory/navigation/MenuItems.jsx
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/components/geostory/navigation/__tests__/ScrollMenu-test.jsx
  web/client/themes/default/less/geostory-navigation.less
  web/client/themes/default/less/navigation.less
  web/client/themes/default/ms2-theme.less
Labels: GeoStory, Mobile, bug

#4973 Fix 4910 Contents - Map - Popups
  web/client/actions/__tests__/mapPopups-test.js
  web/client/actions/mapPopups.js
  web/client/components/data/identify/PopupViewer.jsx
  web/client/components/data/identify/SwipeHeader.jsx
  web/client/components/data/identify/__tests__/SwipeHeader-test.jsx
  web/client/components/geostory/common/MapInfoViewer.jsx
  web/client/components/geostory/common/MapView.jsx
  web/client/components/geostory/common/enhancers/withIdentifyPopup.jsx
  web/client/components/geostory/common/map/Controls.jsx
  web/client/components/geostory/common/map/__tests__/Controls-test.jsx
  web/client/components/geostory/media/Map.jsx
  web/client/components/geostory/media/__tests__/Map-test.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/PopupSupport.jsx
  web/client/components/map/leaflet/__tests__/PopupSupport-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/PopupSupport.jsx
  web/client/components/map/openlayers/__tests__/PopupSupport-test.jsx
  web/client/components/map/plugins/leaflet.js
  web/client/components/map/plugins/openlayers.js
  web/client/components/map/popups/index.js
  web/client/components/misc/FeatureInfoFormatSelector.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/map/index.js
  web/client/plugins/map/leaflet/index.js
  web/client/plugins/map/openlayers/index.js
  web/client/product/main.jsx
  web/client/reducers/__tests__/mapPopups-test.js
  web/client/reducers/mapPopups.js
  web/client/selectors/mapInfo.js
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/geostory.less
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/less/map-popup.less
  web/client/themes/default/ms2-theme.less
  web/client/themes/default/svg/back.svg
  web/client/themes/default/svg/next.svg
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/PopupUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory

#4986 #4984: improved usage of datadir to externalize stuff, in particular …
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/main/java/it/geosolutions/mapstore/utils/ResourceUtils.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/bundle.js
  docs/developer-guide/externalized-configuration.md
  docs/developer-guide/local-config.md
  mkdocs.yml
  web/client/components/app/StandardApp.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/utils/ConfigUtils.js
Labels: geOrchestra

#5024 Added some docs about config.json and fixed a typo in localConfig docs
  docs/developer-guide/local-config.md
  docs/developer-guide/maps-configuration.md
Labels: Priority: Medium, geOrchestra

#4955 #4954: basic support for user session persistence
  docs/developer-guide/user-sessions.md
  mkdocs.yml
  web/client/actions/__tests__/usersession-test.js
  web/client/actions/usersession.js
  web/client/epics/__tests__/epicTestUtils.js
  web/client/epics/__tests__/usersession-test.js
  web/client/epics/usersession.js
  web/client/reducers/__tests__/usersession-test.js
  web/client/reducers/usersession.js
  web/client/selectors/__tests__/usersession-test.js
  web/client/selectors/usersession.js
Labels: geOrchestra

#5004 MapCatalog and MapTemplates plugins doc
  build/docma-config.json
  web/client/plugins/MapCatalog.jsx
  web/client/plugins/MapTemplates.jsx
Labels: geOrchestra

#5010 Fix 5009 Update routing workflow of geostories between shared page and default page
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/GeoStoryEditor.jsx
  web/client/product/pages/GeoStory.jsx
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
Labels: GeoStory, enhancement

#5012 Error while saving context's map
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: Priority: High, geOrchestra

#5027 #5026: extensions uninstall UI and backend service
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/extensionsWithPlugin.json
  backend/src/test/resources/pluginsConfigWithPlugin.json
  web/client/actions/__tests__/contextcreator-test.js
  web/client/actions/contextcreator.js
  web/client/api/__tests__/plugins-test.js
  web/client/api/plugins.js
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/contextcreator/__tests__/ConfigurePluginsStep-test.jsx
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/plugins/ContextCreator.jsx
  web/client/plugins/TOC.jsx
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: geOrchestra

#5029 MS Landing Page Advanced Search Filter
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
  web/client/themes/default/less/createnewmap.less
Labels: geOrchestra

#5019 5018 When the follow mode and the user position are deactivated, the …
  web/client/components/mapcontrols/locate/LocateBtn.jsx
  web/client/components/mapcontrols/locate/__tests__/LocateBtn-test.jsx
  web/client/utils/openlayers/OlLocate.js
Labels: bug, geOrchestra

#5016 #5002 Small style problems in MS panels.
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/epics/maplayout.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/UserExtensions.js
Labels: geOrchestra

#5032 #4954: added machinery for user session loading
  web/client/actions/__tests__/config-test.js
  web/client/actions/__tests__/usersession-test.js
  web/client/actions/config.js
  web/client/actions/usersession.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/usersession-test.js
  web/client/epics/config.js
  web/client/epics/usersession.js
  web/client/reducers/__tests__/usersession-test.js
  web/client/reducers/usersession.js
Labels: geOrchestra

#5025 Backport in 2020.01.xx - Fix 4940 CRS Selector and allowed Roles (#4941)
  web/client/plugins/CRSSelector.jsx
  web/client/plugins/__tests__/CRSSelector-test.jsx
Labels: Backport

#5038 Improved epic error handling
  web/client/utils/EpicsUtils.js
Labels: Priority: Low, enhancement

#5042 Some fixes and updates to the DOC index page
  docs/index.md
Labels: Documentation, Priority: High

#5053 #5049 solve issues with failing tests
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/components/misc/combobox/PagedComboboxWithFeatures.jsx
  web/client/examples/print/components/PrintPreview.jsx
Labels: Priority: Blocker, bug

#5048 #4739: Fix - Changing language the Tutorial doesn't work anymore
  web/client/components/tutorial/Tutorial.jsx
Labels: Priority: Medium, bug

#5041 Improve Plugin configuration in Application Contexts
  web/client/epics/contextcreator.js
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
Labels: Priority: High, geOrchestra

#5011 WMC Developer Guide
  docs/developer-guide/local-config.md
Labels: geOrchestra

#5057 Fix WMC doc
  build/docma-config.json
  docs/developer-guide/local-config.md
  docs/developer-guide/maps-configuration.md
  web/client/plugins/MapExport.jsx
  web/client/plugins/MapImport.jsx
Labels: Documentation, geOrchestra

#5046 #5017 The advanced options for the Share tool must be availables by de…
  web/client/components/share/SharePanel.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
Labels: Priority: High, geOrchestra

#5076 #4739: Fix - Changing language the Tutorial doesn't work anymore
  web/client/components/tutorial/Tutorial.jsx
Labels: Backport, Priority: Medium, bug

#5056 5054 Feature Attribute Form - Identify tool.
  web/client/epics/identify.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/layers.js
Labels: Priority: High, geOrchestra

#5085 #4954: missing translations messages for user sessions management
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: geOrchestra

#5087 #4954: added explicit actions for user session saving handling (start…
  web/client/actions/__tests__/usersession-test.js
  web/client/actions/usersession.js
Labels: geOrchestra

#5044 Fix 5043 GeoStory custom themes
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThematicLayer-test.jsx
  web/client/components/geostory/builder/Settings.jsx
  web/client/components/geostory/common/CustomThemePicker.jsx
  web/client/components/geostory/common/ToolbarDropdownButton.jsx
  web/client/components/geostory/common/__tests__/CustomThemePicker-test.jsx
  web/client/components/geostory/contents/ContentWrapper.jsx
  web/client/components/geostory/contents/Contents.jsx
  web/client/components/geostory/contents/Text.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/contents/__tests__/Content-test.jsx
  web/client/components/geostory/contents/__tests__/ContentToolbar-test.jsx
  web/client/components/geostory/contents/__tests__/ContentWrapper-test.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/__tests__/Cascade-test.jsx
  web/client/components/geostory/layouts/sections/Background.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/components/geostory/layouts/sections/__tests__/Background-test.jsx
  web/client/components/geostory/layouts/sections/patterns/world.svg
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/components/geostory/navigation/__tests__/ScrollMenu-test.jsx
  web/client/components/style/CircleStyler.jsx
  web/client/components/style/ColorPicker.jsx
  web/client/components/style/ColorSelector.jsx
  web/client/components/style/PolygonStyler.jsx
  web/client/components/style/PolylineStyler.jsx
  web/client/components/style/StylePoint.jsx
  web/client/components/style/StylePolygon.jsx
  web/client/components/style/StylePolyline.jsx
  web/client/components/style/TextStyler.jsx
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ColorPiker-test.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/style/colorpicker.css
  web/client/components/style/vector/Fill.jsx
  web/client/components/style/vector/Stroke.jsx
  web/client/configs/newgeostory.json
  web/client/plugins/GeoStory.jsx
  web/client/themes/default/less/annotations.less
  web/client/themes/default/less/geostory-navigation.less
  web/client/themes/default/less/geostory.less
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory, Priority: High, enhancement

#5058 #4882: Fix - Unsaved modal appearing for saved changes
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: Backport Needed, Priority: High, bug

#5086 #5075: Fix - Layer properties for other groups in map widget
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/withSelectedNode-test.js
  web/client/components/widgets/builder/wizard/map/enhancers/nodeEditor.js
  web/client/components/widgets/builder/wizard/map/enhancers/withSelectedNode.js
Labels: Backport Needed, Priority: High, bug

#5078 4946 sidebar review
  docs/user-guide/img/button/setting_button.jpg
  docs/user-guide/img/side-bar/3D-mode.jpg
  docs/user-guide/img/side-bar/areonautical-ex.gif
  docs/user-guide/img/side-bar/coordinate.jpg
  docs/user-guide/img/side-bar/decimal-ex.gif
  docs/user-guide/img/side-bar/format-options.jpg
  docs/user-guide/img/side-bar/format_example.jpg
  docs/user-guide/img/side-bar/hightlight-point1.gif
  docs/user-guide/img/side-bar/identify-tool.jpg
  docs/user-guide/img/side-bar/more-info.jpg
  docs/user-guide/img/side-bar/sidebar.jpg
  docs/user-guide/side-bar.md
Labels: Documentation, User Guide

#5080 5059 review
  docs/user-guide/img/button/mapstore_format_button.jpg
  docs/user-guide/img/button/wmc_format_button.jpg
  docs/user-guide/img/import/import-screen.jpg
  docs/user-guide/img/import/wmc_import.gif
  docs/user-guide/import.md
Labels: Documentation, User Guide

#5069 #4773: Fix - Map widget presents an issue during creation
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleMapSelect-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
Labels: Backport Needed, Priority: High, bug

#5093 5075: Fix - Layer properties- Backport
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/withSelectedNode-test.js
  web/client/components/widgets/builder/wizard/map/enhancers/nodeEditor.js
  web/client/components/widgets/builder/wizard/map/enhancers/withSelectedNode.js
Labels: Backport, Priority: High, bug

#5091 #5084: Fix - Layer group naming issue in dashboard
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleMapSelect-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
Labels: Backport Needed, Priority: High, bug

#5097 Backport - #4773 - Fix - Map widget presents an issue during creation
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleMapSelect-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
  web/client/libs/bindings/rxjsRecompose.js
Labels: Backport

#5094 #4712: Fix -Share tool button missing in the Options menu
  web/client/localConfig.json
  web/client/selectors/__tests__/localConfig-test.js
Labels: Backport Needed, Priority: Low, bug

#5098 5084- Backport
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleMapSelect-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
Labels: Backport

#5051 fix 4491 error page
  web/client/components/app/ErrorFallBackComp.jsx
  web/client/components/app/StandardApp.jsx
  web/client/components/app/StandardRouter.jsx
  web/client/localConfig.json
  web/client/themes/default/less/common.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport Needed, Priority: High, enhancement

#5102 #4712: Fix -Share tool button missing in the Options menu
  web/client/localConfig.json
  web/client/selectors/__tests__/localConfig-test.js
Labels: Priority: Low, bug

#5100 Fix #5062 Small issue while saving a context
  web/client/components/buttons/CloseButton.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/misc/Stepper.jsx
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/plugins/__tests__/ContextCreator-test.jsx
Labels: Priority: Medium, geOrchestra

#5082 Fix 5021 Improve popup layout for get feature info (Identify)
  web/client/components/TOC/fragments/settings/WMSStyle.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/identify/viewers/TemplateViewer.jsx
  web/client/components/data/identify/viewers/ViewerPage.jsx
  web/client/components/data/identify/viewers/row/PropertiesViewer.jsx
  web/client/components/data/identify/viewers/row/__tests__/PropertiesViewer-test.jsx
  web/client/components/geostory/common/enhancers/withIdentifyPopup.jsx
  web/client/components/geostory/common/map/Controls.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Paragraph.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/components/geostory/layouts/sections/__tests__/Immersive-test.jsx
  web/client/components/geostory/layouts/sections/__tests__/Title-test.jsx
  web/client/components/geostory/media/Map.jsx
  web/client/components/manager/importer/Workspace.jsx
  web/client/components/manager/users/UserGroups.jsx
  web/client/components/map/leaflet/PopupSupport.jsx
  web/client/components/map/openlayers/PopupSupport.jsx
  web/client/components/misc/FeatureInfoFormatSelector.jsx
  web/client/components/misc/__tests__/FeatureInfoFormatSelector-test.jsx
  web/client/components/resources/modals/fragments/PermissionEditor.jsx
  web/client/components/security/PermissionEditor.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/Settings.jsx
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/geostory.less
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/less/map-popup.less
  web/client/themes/default/less/media-editor.less
  web/client/themes/default/less/react-select.less
  web/client/themes/default/less/select.less
  web/client/themes/default/ms2-theme.less
Labels: GeoStory, Priority: High, enhancement
