Repository geosolutions-it/MapStore2, pull requests merged in 2020-06, with the labels that each got.

#5376 [Backport 2020.02.xx] Improved the extension sample (#5300)
  build/extensions/app.jsx
  build/extensions/bundle/index.json
  build/extensions/components/Extension.jsx
  build/extensions/extensions.js
  build/extensions/plugins/SampleExtension.jsx
  docs/developer-guide/extensions.md
  docs/user-guide/application-context.md
Labels: Backport

#5317 Search Service - show GFI
  web/client/actions/search.js
  web/client/components/mapcontrols/search/SearchResult.jsx
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResult-test.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
  web/client/components/mapcontrols/searchservicesconfig/ResultsProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/__tests__/ResultsProps-test.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/examples/3dviewer/containers/Viewer.jsx
  web/client/plugins/Search.jsx
  web/client/themes/default/less/searchbar.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/SearchUtils.js
  web/client/utils/__tests__/SearchUtils-test.js
Labels: Project: C125

#5374 Backport 2020.02.xx - #4809: supported browsers pre-check (#5337)
  build/prod-webpack.config.js
  project/standard/templates/embeddedTemplate.html
  project/standard/templates/indexTemplate.html
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/unsupportedBrowser.html
  web/client/embeddedTemplate.html
  web/client/indexTemplate.html
  web/client/product/assets/img/main-desktop-browser-logos.jpg
  web/client/unsupportedBrowser.html
Labels: Backport, Priority: High, enhancement

#5297 remove cleanResource from saveDashboard
  web/client/epics/__tests__/dashboard-test.js
  web/client/epics/dashboard.js
  web/client/utils/DashboardUtils.js
  web/client/utils/__tests__/DashboardUtils-test.js
Labels: Backport Needed, Dashboard, Priority: High, bug

#5385 issue 5226 - improve geostory tutorial
  web/client/components/geostory/builder/Builder.jsx
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
  web/client/localConfig.json
  web/client/plugins/tutorial/preset.js
  web/client/plugins/tutorial/preset/geostory_edit_tutorial.js
  web/client/plugins/tutorial/preset/geostory_tutorial.js
  web/client/plugins/tutorial/preset/geostory_view_tutorial.js
  web/client/reducers/geostory.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport Needed, New Feature

#5394 Fix 5365 GeoStory Nav Bar should disappear if empty
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/themes/default/less/geostory-navigation.less
Labels: Backport Needed, GeoStory, enhancement

#5395 #5363: Video thumbnail refresh
  web/client/components/maps/forms/__tests__/Thumbnail-test.jsx
  web/client/components/mediaEditor/video/VideoForm.jsx
  web/client/components/mediaEditor/video/__tests__/VideoForm-test.jsx
  web/client/components/misc/Thumbnail.jsx
  web/client/components/misc/__tests__/Thumbnail-test.jsx
  web/client/components/resources/forms/Thumbnail.jsx
  web/client/components/resources/forms/__tests__/Thumbnail-test.jsx
  web/client/themes/default/less/dropzone.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport Needed, GeoStory, enhancement

#5392 5384. add new categories
  docs/developer-guide/mapstore-migration-guide.md
  project/custom/templates/web/src/main/resources/sample_categories.xml
  project/standard/templates/web/src/main/resources/sample_categories.xml
  web/src/main/resources/sample_categories.xml
Labels: Backport Needed, bug

#5402 5401. fix rectangular roundvalue and step
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/data/query/__tests__/GeometryDetails-test.jsx
Labels: Backport Needed, Priority: Blocker, Project: C028

#5412 Backport for the #5401. fix rectangular roundvalue and step.
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/data/query/__tests__/GeometryDetails-test.jsx
Labels: Project: C028

#5404 Identify will not be disabled when advanced editor is closed with OK
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport Needed, GeoStory, Priority: Blocker, bug

#5415 [Backport 2020.02.xx] #5363: Video thumbnail refresh (#5395)
  web/client/components/maps/forms/__tests__/Thumbnail-test.jsx
  web/client/components/mediaEditor/video/VideoForm.jsx
  web/client/components/mediaEditor/video/__tests__/VideoForm-test.jsx
  web/client/components/misc/Thumbnail.jsx
  web/client/components/misc/__tests__/Thumbnail-test.jsx
  web/client/components/resources/forms/Thumbnail.jsx
  web/client/components/resources/forms/__tests__/Thumbnail-test.jsx
  web/client/themes/default/less/dropzone.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, GeoStory, enhancement

#5405 Fix empty list for image
  web/client/components/mediaEditor/image/ImageList.jsx
  web/client/components/mediaEditor/image/__tests__/ImageList-test.jsx
  web/client/components/mediaEditor/map/MapList.jsx
  web/client/components/mediaEditor/video/VideoList.jsx
  web/client/configs/newgeostory.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport Needed, GeoStory, Priority: High, enhancement

#5416 Backport 2020.02.xx - #5310: Fix empty list for image (#5405)
  web/client/components/mediaEditor/image/ImageList.jsx
  web/client/components/mediaEditor/image/__tests__/ImageList-test.jsx
  web/client/components/mediaEditor/map/MapList.jsx
  web/client/components/mediaEditor/video/VideoList.jsx
  web/client/configs/newgeostory.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, GeoStory, Priority: High, enhancement

#5417 Backport 2020.02.xx - #5364: Identify will not be disabled when advanced editor is closed with OK (#5404)
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport, GeoStory, Priority: Blocker, bug

#5418 #5074 add documentation for layer groups
  docs/developer-guide/maps-configuration.md
Labels: Backport Needed, Documentation, Priority: High

#5421 #5290: Improved custom editors documentation.
  build/docma-config.json
  docma-template/js/app.js
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/components/data/featuregrid/editors/AttributeEditor.jsx
  web/client/components/data/featuregrid/editors/AutocompleteEditor.jsx
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/featuregrid/editors/FormatEditor.jsx
  web/client/components/data/featuregrid/editors/NumberEditor.jsx
  web/client/components/data/featuregrid/editors/customEditors.jsx
  web/client/components/data/featuregrid/editors/index.jsdoc
  web/client/plugins/FeatureEditor.jsx
Labels: Backport Needed, Documentation, Priority: High

#5423 #5325: add WPS process references in the user guide
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/widgets.md
Labels: Backport Needed, Documentation, Priority: High

#5299 Set active tab of layer settings
  web/client/components/TOC/enhancers/__tests__/tocitemssettings-test.js
  web/client/components/TOC/enhancers/tocItemsSettings.js
  web/client/plugins/TOCItemsSettings.jsx
Labels: Priority: Medium, Project: C125

#5428 #5325: add WPS process references in the user guide (#5423)
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/widgets.md
Labels: Backport, Documentation

#5429 #5290: Improved custom editors documentation. (#5421)
  build/docma-config.json
  docma-template/js/app.js
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/components/data/featuregrid/editors/AttributeEditor.jsx
  web/client/components/data/featuregrid/editors/AutocompleteEditor.jsx
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/featuregrid/editors/FormatEditor.jsx
  web/client/components/data/featuregrid/editors/NumberEditor.jsx
  web/client/components/data/featuregrid/editors/customEditors.jsx
  web/client/components/data/featuregrid/editors/index.jsdoc
  web/client/plugins/FeatureEditor.jsx
Labels: Backport, Documentation

#5411 add font size to geostory editor
  web/client/components/geostory/contents/enhancers/editableText.jsx
  web/client/themes/default/less/geostory.less
Labels: Backport Needed, GeoStory, Priority: High, enhancement

#5260 C125-151: Share map by coordinate
  docs/user-guide/img/share/embed.jpg
  docs/user-guide/img/share/share_window.jpg
  docs/user-guide/img/share/share_window_center_zoom.jpg
  docs/user-guide/img/share/social.jpg
  docs/user-guide/share.md
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/localConfig.json
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/less/share.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Medium, Project: C125

#5431 Backport 2020.02.xx - add font size to geostory editor (#5411)
  web/client/components/geostory/contents/enhancers/editableText.jsx
  web/client/themes/default/less/geostory.less
Labels: Backport, GeoStory, Priority: High, enhancement

#5426 fix legend widget object title
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/components/widgets/widget/__tests__/LegendView-test.jsx
  web/client/plugins/widgetbuilder/LegendBuilder.jsx
Labels: Backport Needed, Priority: Blocker, Project: C028, bug

#5433 #5432: Remove schemaLocation from Query
  web/client/components/widgets/enhancers/dependenciesToExtent.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: Backport Needed, Priority: Medium, Project: C028, bug

#5434 Backport 2020.01.xx for #5425: Fix legend widget object title (#5426)
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/components/widgets/widget/__tests__/LegendView-test.jsx
  web/client/plugins/widgetbuilder/LegendBuilder.jsx
Labels: Backport, Priority: High, Project: C028, bug

#5313 Add annotation style documentation
  docs/developer-guide/img/vector-style-annotations.jpg
  docs/developer-guide/maps-configuration.md
Labels: Documentation, Priority: Medium

#5435 Backport 2020.02.xx - #5425: Fix legend widget object title (#5426)
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/components/widgets/widget/__tests__/LegendView-test.jsx
  web/client/plugins/widgetbuilder/LegendBuilder.jsx
Labels: Backport, Priority: High, Project: C028, bug

#5393 4686. add message on error dashboard editor
  web/client/components/catalog/CompactCatalog.jsx
Labels: Backport Needed, Priority: Medium, enhancement

#5424 Fix problem with info_format defined at layer level in Geostory
  web/client/components/geostory/common/enhancers/withIdentifyPopup.jsx
Labels: Backport Needed, New Feature, Priority: High

#5437 #5432: Remove schemaLocation from Query (#5433)
  web/client/components/widgets/enhancers/dependenciesToExtent.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: Backport, bug

#5438 #5432: Remove schemaLocation from Query (#5433)
  web/client/components/widgets/enhancers/dependenciesToExtent.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: Backport, Project: C028, bug

#5443 Backport 2020.02.xx - #5280: Fix problem with info_format defined at layer level in Geostory (#5424)
  web/client/components/geostory/common/enhancers/withIdentifyPopup.jsx
Labels: Backport, New Feature, Priority: High

#5442 #5312: [Backport] Support for WMTS with not sorted matrix sets (#5328)
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/WMTSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/WMTSUtils-test.js
Labels: Backport

#5456 #5346: include security reducer in JS API
  web/client/jsapi/MapStore2.js
Labels: Backport Needed, enhancement

#5457 [2020.02.xx] #5346: include security reducer in JS API (#5456)
  web/client/jsapi/MapStore2.js
Labels: Backport

#5458 [2020.02.xx] Fix #5448 Edit map configuration problem with change size button (#5450)
  web/client/components/geostory/common/ToolbarDropdownButton.jsx
  web/client/components/geostory/common/__tests__/ToolbarDropdownButton-test.jsx
Labels: Backport

#5460 [2020.02.xx] Fix 5439 Mobile - Interactivity of background maps problem (#5454)
  web/client/themes/default/less/geostory.less
Labels: Backport

#5459 [2020.02.xx] Fix #5447 Disable Use description as caption when the Map Configuration is open (#5451)
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/geostory/contents/__tests__/ContentToolbar-test.jsx
Labels: Backport

#5420 fix changeGroupPropery on expanded
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleNodePropertyChanges-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleNodePropertyChanges.js
Labels: Backport Needed, Dashboard, Priority: Low, bug

#5464 Backport for 4709
  web/client/components/widgets/builder/wizard/map/enhancers/__tests__/handleNodePropertyChanges-test.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleNodePropertyChanges.js
Labels: Backport, Dashboard, Priority: Low, bug

#5463 5462. add env to baseMap. add layer styles override from localconfig
  web/client/components/map/BaseMap.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/plugins/widgetbuilder/enhancers/manageLayers.js
  web/client/selectors/__tests__/localizedLayerStyles-test.js
  web/client/selectors/localizedLayerStyles.js
Labels: Backport Needed, Priority: High, Project: C028, bug

#5468 Backport for #5462
  web/client/components/map/BaseMap.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/plugins/widgetbuilder/enhancers/manageLayers.js
  web/client/selectors/__tests__/localizedLayerStyles-test.js
  web/client/selectors/localizedLayerStyles.js
Labels: Backport, Priority: High, Project: C028, bug

#5469 Backport for 5462
  web/client/components/map/BaseMap.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/components/widgets/builder/wizard/map/MapOptions.jsx
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/plugins/widgetbuilder/enhancers/manageLayers.js
  web/client/selectors/__tests__/localizedLayerStyles-test.js
  web/client/selectors/localizedLayerStyles.js
Labels: Backport, Priority: High, Project: C028, bug

#5372 Store the currently selected datetime for the timeslider inside the map configuration
  docs/developer-guide/maps-configuration.md
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/dimension.js
  web/client/epics/timeline.js
  web/client/selectors/mapsave.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport Needed, Priority: High

#5476 Backport 2020.02.xx - #5226 geostory tutorial
  web/client/components/geostory/builder/Builder.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/tutorial/Tutorial.jsx
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
  web/client/localConfig.json
  web/client/plugins/tutorial/preset.js
  web/client/plugins/tutorial/preset/geostory_edit_tutorial.js
  web/client/plugins/tutorial/preset/geostory_tutorial.js
  web/client/plugins/tutorial/preset/geostory_view_tutorial.js
  web/client/reducers/geostory.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#5477 issue #5475 - add language prop to LegendPreview
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
Labels: BackportNeeded, Priority: Blocker, Project: C028, bug

#5473 #5280 - fix tooltip for identify in geostory maps
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, GeoStory, enhancement

#5483 Backport for #5475
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
Labels: Backport, Project: C028, bug

#5481 Backport for 5475
  web/client/components/widgets/builder/wizard/LegendWizard.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/commons.js
Labels: Backport, Project: C028, bug

#5472 #5471: Display default legend values
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
Labels: BackportNeeded, Priority: Blocker, bug

#5484 #5471: Backport for display default legend values
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
Labels: Backport, Priority: Blocker, bug

#5478 Add DXF format support from server
  web/client/epics/wfsdownload.js
Labels: BackportNeeded, enhancement

#5486 Store the currently selected datetime for the timeslider inside the map configuration backport on 2020.02.xx
  docs/developer-guide/maps-configuration.md
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/dimension.js
  web/client/epics/timeline.js
  web/client/selectors/mapsave.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport

#5487 #5479: [Backport] Add DXF format support from server (#5478)
  web/client/epics/wfsdownload.js
Labels: Backport

#5488 Backport for 2020.02.xx #5280 - fix tooltip for identify in geostory maps (#5473)
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#5489 #5074: [Backport ] add documentation for layer groups (#5418)
  docs/developer-guide/maps-configuration.md
Labels: Backport

#5375 Printing engine not included by default in the build (new profiles fo…
  docs/developer-guide/building-and-deploying.md
  pom.xml
  printing/assembly/mapstore-printing.xml
  printing/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/resources/applicationContext.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/web/src/printing/applicationContext-print.xml
  web/client/localConfig.json
  web/client/plugins/Print.jsx
  web/pom.xml
  web/src/main/resources/applicationContext.xml
  web/src/main/webapp/WEB-INF/web.xml
  web/src/printing/applicationContext-print.xml
Labels: BackportNeeded, Blocked

#5493 [2020.02.xx] Printing engine not included by default in the build (new profiles for maven) (#5375)
  docs/developer-guide/building-and-deploying.md
  pom.xml
  printing/assembly/mapstore-printing.xml
  printing/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/resources/applicationContext.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/web/src/printing/applicationContext-print.xml
  web/client/localConfig.json
  web/client/plugins/Print.jsx
  web/pom.xml
  web/src/main/resources/applicationContext.xml
  web/src/main/webapp/WEB-INF/web.xml
  web/src/printing/applicationContext-print.xml
Labels: Priority: Blocker

#5492 Fix 5491 - Geostory fails when advanced editor is opened and config is missing
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
  web/client/reducers/tutorial.js
Labels: BackportNeeded, GeoStory, bug

#5494 Backport 2020.02.xx - #5491 Geostory fails when advanced editor is opened and config is missing #5492
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
  web/client/reducers/tutorial.js
Labels: Backport

#5496 5495 link
  mkdocs.yml
Labels: BackportNeeded, Dev Guide, Documentation

#5497 Backport 2020.02.xx - #5495 Application tutorial link
  mkdocs.yml
Labels: Backport

#5500 #5309: Confirmation dialog for GeoStory pending changes
  web/client/actions/geostory.js
  web/client/actions/map.js
  web/client/actions/pendingChanges.js
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/__tests__/pendingChanges-test.js
  web/client/epics/contextcreator.js
  web/client/epics/geostory.js
  web/client/epics/map.js
  web/client/epics/pendingChanges.js
  web/client/plugins/Home.jsx
  web/client/plugins/Login.jsx
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
  web/client/selectors/geostory.js
  web/client/selectors/mapsave.js
Labels: BackportNeeded, enhancement

#5509 issue #5501 - Fix problem with virtual scroll in FeatureGrid
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: BackportNeeded, Project: C039, bug

#5513 Backport 2020.02.xx - issue #5501 - Fix problem with virtual scroll in FeatureGrid (#5509)
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: Backport, Project: C039, bug

#5507 #5309: [Backport] Confirmation dialog for GeoStory pending changes (#5500)
  web/client/actions/geostory.js
  web/client/actions/map.js
  web/client/actions/pendingChanges.js
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/__tests__/pendingChanges-test.js
  web/client/epics/contextcreator.js
  web/client/epics/geostory.js
  web/client/epics/map.js
  web/client/epics/pendingChanges.js
  web/client/plugins/Home.jsx
  web/client/plugins/Login.jsx
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
  web/client/selectors/geostory.js
  web/client/selectors/mapsave.js
Labels: Backport

#5330 C125-164: Import annotation layer via Map menu
  web/client/components/import/dragZone/enhancers/__tests__/processFiles-test.jsx
  web/client/components/import/dragZone/enhancers/__tests__/testData.js
  web/client/components/import/dragZone/enhancers/__tests__/useFiles-test.js
  web/client/components/import/dragZone/enhancers/processFiles.jsx
  web/client/components/import/dragZone/enhancers/useFiles.js
  web/client/components/import/style/StylePanel.jsx
  web/client/components/import/style/__tests__/StylePanel-test.jsx
  web/client/components/mapcontrols/annotations/SelectAnnotationsFile.jsx
  web/client/epics/annotations.js
  web/client/plugins/MapImport.jsx
  web/client/test-resources/caput-mundi/caput-mundi.config
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/AnnotationsUtils.js
  web/client/utils/StyleUtils.js
Labels: Priority: High, Project: C125

#5520 #5518 Add missing user to provide group list in map templates
  web/client/components/contextcreator/ConfigureMapTemplates.jsx
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/plugins/ContextCreator.jsx
  web/client/plugins/__tests__/ContextCreator-test.jsx
Labels: BackportNeeded

#5521 #5518 [Backport] Add missing user to provide group list in map templates (#5520)
  web/client/components/contextcreator/ConfigureMapTemplates.jsx
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/plugins/ContextCreator.jsx
  web/client/plugins/__tests__/ContextCreator-test.jsx
Labels: Backport

#5389 C125:152 - Drop Down for different map views
  docs/user-guide/img/button/get_bbox.jpg
  docs/user-guide/img/menu-bar/add-bookmark.jpg
  docs/user-guide/img/menu-bar/aeronautical.jpg
  docs/user-guide/img/menu-bar/decimal.jpg
  docs/user-guide/img/menu-bar/menu-bar.jpg
  docs/user-guide/img/menu-bar/search-bookmark.jpg
  docs/user-guide/img/menu-bar/search-types.jpg
  docs/user-guide/img/menu-bar/view-bookmark.jpg
  docs/user-guide/menu-bar.md
  web/client/actions/__tests__/searchbookmarkconfig-test.js
  web/client/actions/searchbookmarkconfig.js
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/mapcontrols/searchbookmarkconfig/AddNewBookmark.jsx
  web/client/components/mapcontrols/searchbookmarkconfig/BookmarkList.js
  web/client/components/mapcontrols/searchbookmarkconfig/BookmarkSelect.jsx
  web/client/components/mapcontrols/searchbookmarkconfig/__tests__/AddNewBookmark-test.jsx
  web/client/components/mapcontrols/searchbookmarkconfig/__tests__/BookmarkList-test.jsx
  web/client/components/mapcontrols/searchbookmarkconfig/__tests__/BookmarkSelect-test.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/epics/contextcreator.js
  web/client/epics/mapexport.js
  web/client/epics/maptemplates.js
  web/client/localConfig.json
  web/client/plugins/MapSearch.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/SearchByBookmark.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/mapEditor/enhancers/editor.js
  web/client/plugins/maps/MapSave.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/searchbookmarkconfig-test.js
  web/client/reducers/searchbookmarkconfig.js
  web/client/selectors/mapsave.js
  web/client/selectors/searchconfig.js
  web/client/themes/default/less/map-search-bar.less
  web/client/themes/default/less/panels.less
  web/client/themes/default/less/search-bookmark-config.less
  web/client/themes/default/less/searchbar.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Priority: High, Project: C125

#5524 #5514 Allow using a popup window as map container
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
Labels: New Feature, Project: C039

#5525 #5516: moved UserSession doc to the dedicated plugin
  build/docma-config.json
  docs/developer-guide/user-sessions.md
  mkdocs.yml
  web/client/plugins/UserSession.jsx
Labels: BackportNeeded, Documentation

#5523 #5517 new story login prompt on logout.
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/feedbackMask.js
Labels: BackportNeeded

#5527 #5517 [Backport] new story login prompt on logout. (#5523)
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/feedbackMask.js
Labels: Backport

#5526 #5516: [Backport] moved UserSession doc to the dedicated plugin (#5525)
  build/docma-config.json
  docs/developer-guide/user-sessions.md
  mkdocs.yml
  web/client/plugins/UserSession.jsx
Labels: Backport, Documentation

#5508 Fix missing version and correct url in homepage for maps
  web/client/components/resources/enhancers/__tests__/withShareTool-test.js
  web/client/components/resources/enhancers/withShareTool.jsx
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/Maps.jsx
Labels: BackportNeeded, bug

#5529 issue #5228 - Fix custom theme usage
  web/client/components/app/StandardRouter.jsx
  web/client/components/app/__tests__/StandardRouter-test.jsx
Labels: BackportNeeded, bug

#5536 Backport 2020.02.xx - #5528 - Fix custom theme usage (#5529)
  web/client/components/app/StandardRouter.jsx
  web/client/components/app/__tests__/StandardRouter-test.jsx
Labels: Backport

#5537 Backport 2020.02xx - #5502: Fix missing version and correct url in homepage for maps (#5508)
  web/client/components/resources/enhancers/__tests__/withShareTool-test.js
  web/client/components/resources/enhancers/withShareTool.jsx
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/Maps.jsx
Labels: Backport

#5542 issue #5535 - Fix embedded problems
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: BackportNeeded

#5543 Fix #5531 Measure tool has a bug when switching type of measure
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
Labels: Priority: High, bug

#5331 Simplyfing Annotation creation and editing (TEXT ROTATION)
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/components/mapcontrols/annotations/Annotations.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/style/vector/Manager.jsx
  web/client/components/style/vector/Text.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/VectorStyleUtils.js
Labels: Priority: High, Project: C125

#5545 Backport 2020.02.xx - #5535: Fix embedded problems (#5542)
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: Backport

#5398 Fix 5397 Map info data wrongly requested for static map configurations
  web/client/config.json
  web/client/epics/__tests__/config-test.js
  web/client/epics/config.js
Labels: bug

#5546 Fix #5512. add object handler extractTileMatrixFromSources
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: AppContext, Priority: High, bug

#5544 #5533 fix crash on new context due to wrong tutorial setup
  web/client/actions/contextcreator.js
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
Labels: AppContext, BackportNeeded, bug

#5548 Backport 2020.02.xx - #5533 fix crash on new context due to wrong tutorial setup (#5544)
  web/client/actions/contextcreator.js
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
Labels: AppContext, Backport, bug

#5554 #5553 - fix crash for print plugin used in contexts
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: BackportNeeded, bug

#5552 #5549: Fixed infinite loop in re-open feature grid system
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: BackportNeeded, bug

#5558 Backport 2020.02.xx - #5553 fix crash for print plugin used in contexts (#5554)
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport, Project: C040, bug

#5559 #5549: Fixed infinite loop in re-open feature grid system (#5552)
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Backport
