Repository geosolutions-it/MapStore2, pull requests merged in 2020-10, with the labels that each got.

#5943 Update configuration-files.md
  docs/developer-guide/configuration-files.md
Labels: BackportNeeded, Dev Guide, Documentation

#5953 Print support for WMTS/TMS/tileprovider
  web/client/api/catalog/TMS_1_0_0.js
  web/client/test-resources/layers/tileprovider.js
  web/client/test-resources/layers/tms/index.js
  web/client/test-resources/layers/tms/poi.js
  web/client/test-resources/layers/wmts/KVP1.js
  web/client/test-resources/layers/wmts/REST1.js
  web/client/test-resources/layers/wmts/index.js
  web/client/utils/ConfigProvider.js
  web/client/utils/PrintUtils.js
  web/client/utils/TMSUtils.js
  web/client/utils/TileProviderUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: New Feature, Project: C125, geOrchestra

#5924 #5812: GFI swipe fix on mobile view
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/__tests__/DefaultViewer-test.jsx
  web/client/components/data/identify/viewers/HTMLViewer.jsx
  web/client/components/data/identify/viewers/ViewerPage.jsx
  web/client/plugins/Identify.jsx
  web/client/themes/default/less/get-feature.less
Labels: Project: C125, bug

#5958 [Backport 2020.02.xx] Update configuration-files.md (#5943)
  docs/developer-guide/configuration-files.md
Labels: Backport, Documentation

#5959 [Backport 2020.02.xx] #5292: Print support for WMTS/TMS/tileprovider (#5953)
  web/client/api/catalog/TMS_1_0_0.js
  web/client/test-resources/layers/tileprovider.js
  web/client/test-resources/layers/tms/index.js
  web/client/test-resources/layers/tms/poi.js
  web/client/test-resources/layers/wmts/KVP1.js
  web/client/test-resources/layers/wmts/REST1.js
  web/client/test-resources/layers/wmts/index.js
  web/client/utils/ConfigProvider.js
  web/client/utils/PrintUtils.js
  web/client/utils/TMSUtils.js
  web/client/utils/TileProviderUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Backport, geOrchestra

#5963 ContextCreator save fix
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
Labels: bug

#5966 #5960: Localized form control for bookmark config
  web/client/components/mapcontrols/searchbookmarkconfig/AddNewBookmark.jsx
Labels: Priority: High, Project: C125, enhancement

#5970 #5944: fixed issue on upload backend
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
Labels: bug

#5955 SpyGlassSupport for Openlayers(#5899)
  web/client/components/map/openlayers/swipe/SpyGlassSupport.jsx
  web/client/plugins/Swipe.jsx
  web/client/plugins/__tests__/Swipe-test.jsx
Labels: Priority: High

#5971 Search Service - show GFI
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
Labels: Priority: Blocker, Project: C125, bug

#5962 GeoStory editor enhancement
  web/client/components/geostory/contents/enhancers/__tests__/editableText-test.jsx
  web/client/components/geostory/contents/enhancers/editableText.jsx
  web/client/utils/EditorUtils.js
Labels: Priority: Blocker, Project: C125

#5972 #5292: Fixed opacity issues in printing
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: BackportNeeded, Project: C125, bug, geOrchestra

#5964 Update to GeoStore 1.6-SNAPSHOT
  web/pom.xml
Labels: dependencies

#5919 #5882: Highlight icon anchor position fix for symbol
  web/client/utils/openlayers/Icons.js
  web/client/utils/openlayers/__tests__/Icons-test.js
Labels: Priority: Blocker, Project: C125, bug

#5974 [Backport 2020.02.xx] #5292: Fixed opacity issues in printing (#5972)
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Backport, Project: C125, bug, geOrchestra

#5940 #5607 Fix checkout to current branch of submodule
  createProject.js
  docs/developer-guide/project-creation-script.md
  package.json
  utility/projects/projectLib.js
Labels: BackportNeeded

#5968 ContextCreator save fix (backport on 2020.02.xx)
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
Labels: Backport, bug

#5969 #5898: Swipe Tool Configuration / Switcher
  web/client/actions/__tests__/swipe-test.js
  web/client/actions/swipe.js
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
  web/client/components/TOC/swipe/SwipeButton.jsx
  web/client/components/TOC/swipe/__tests__/SwipeButton-test.jsx
  web/client/components/map/openlayers/swipe/EffectSupport.jsx
  web/client/components/map/openlayers/swipe/SliderSwipeSupport.jsx
  web/client/components/map/openlayers/swipe/SpyGlassSupport.jsx
  web/client/components/misc/ResizableModal.jsx
  web/client/epics/swipe.js
  web/client/plugins/Swipe.jsx
  web/client/plugins/SwipeSettings.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/__tests__/Swipe-test.jsx
  web/client/plugins/__tests__/SwipeSettings-test.jsx
  web/client/reducers/__tests__/swipe-test.js
  web/client/reducers/swipe.js
  web/client/selectors/__tests__/swipe-test.js
  web/client/selectors/swipe.js
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/square-button.less
  web/client/themes/default/less/swipe.less
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Medium

#5973 Uniformation of Edit Properties and detail card
  web/client/components/resources/ResourceGrid.jsx
  web/client/components/resources/enhancers/resourceGrid.js
  web/client/components/resources/modals/enhancers/__tests__/handleDetailsDownload-test.jsx
  web/client/components/resources/modals/enhancers/handleDetailsDownload.js
  web/client/components/resources/modals/fragments/Details.jsx
  web/client/components/resources/modals/fragments/__tests__/Details-test.jsx
  web/client/components/resources/modals/fragments/editors/QuillEditor.jsx
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
Labels: Project: C125, enhancement

#5982 Fix Swipe/spyglass tool issue with layer group(#5980)
  web/client/epics/__tests__/swipe-test.js
  web/client/epics/swipe.js
Labels: Priority: High, Project: C190, bug

#5979 Improve styling of MapSwipe bar(#5957)
  web/client/components/map/openlayers/swipe/SliderSwipeSupport.jsx
  web/client/themes/default/less/swipe.less
Labels: Priority: High, Project: C190, enhancement

#5949 Fix icon and screenshot on UserGuide
  docs/user-guide/img/application-context/upload_plugin1.jpg
  docs/user-guide/img/application-context/upload_plugin2.jpg
  docs/user-guide/img/button/web-page-button.JPG
  docs/user-guide/img/button/web_page_button.jpg
  docs/user-guide/paragraph-section.md
Labels: BackportNeeded, Documentation, User Guide

#5942 Measurement edit and store via annotation
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/__tests__/measurement-test.js
  web/client/actions/annotations.js
  web/client/actions/measurement.js
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
  web/client/components/mapcontrols/annotations/Annotations.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/__tests__/measurement-test.jsx
  web/client/epics/annotations.js
  web/client/epics/measurement.js
  web/client/localConfig.json
  web/client/plugins/Annotations.jsx
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/annotations.js
  web/client/reducers/mapInfo.js
  web/client/reducers/measurement.js
  web/client/selectors/annotations.js
  web/client/selectors/measurement.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/annotations.less
  web/client/themes/default/svg/1-measure-bearing.svg
  web/client/themes/default/svg/1-measure-length.svg
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
Labels: Priority: Blocker, Project: C125

#5956 #5539 Update Layer Title and Description
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/LayerNameEditField.jsx
  web/client/components/TOC/fragments/settings/__tests__/LayerNameEditField-test.jsx
  web/client/epics/__tests__/layerinfo-test.js
  web/client/epics/__tests__/layers-test.js
  web/client/epics/layerinfo.js
  web/client/epics/layers.js
  web/client/plugins/TOC.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/plugins/__tests__/Save-test.jsx
  web/client/plugins/__tests__/SaveAs-test.jsx
  web/client/plugins/__tests__/TOC-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/reducers/layers.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Blocker, Project: C125

#5993 #5986:Removed owner saving, not needed anymore
  web/client/plugins/maps/MapSave.jsx
Labels: Internal, Priority: High, bug

#5989 #5985 - Geometry highlight on annotation
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/plugins/Annotations.jsx
Labels: Priority: High, Project: C125

#6004 #5996: Fix glitch in toc toolbar
  web/client/components/TOC/Toolbar.jsx
Labels: Priority: High, Project: C190, bug

#6011 fix missing .default for reducers requires
  web/client/plugins/CRSSelector.jsx
  web/client/plugins/ContentTabs.jsx
  web/client/plugins/Cookie.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/Login.jsx
  web/client/plugins/Measure.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/stores/StandardStore.js
Labels: QF

#6003 Advanced settings problem for WMS and CSW services #5932
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
Labels: BackportNeeded, Internal, Priority: High

#5997 [Backport 2020.02.xx] #5948: Fix icon on Paragraph section (#5949)
  docs/user-guide/img/application-context/upload_plugin1.jpg
  docs/user-guide/img/application-context/upload_plugin2.jpg
  docs/user-guide/img/button/web-page-button.JPG
  docs/user-guide/img/button/web_page_button.jpg
  docs/user-guide/paragraph-section.md
Labels: Backport

#6023 Fix #5783 Request to sldservice are failing (gs-stable)
  web/client/localConfig.json
Labels: Priority: High, StyleEditor, bug

#6020 #5136: Fix issue in TMS printing
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Project: C125, bug

#6027 [Backport 2020.02.xx] #5136: Fix issue in TMS printing (#6020)
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Backport, Project: C125, bug

#5988 #5987: Fix swipe bar misalignment when resizing browser window
  web/client/components/map/openlayers/swipe/SliderSwipeSupport.jsx
Labels: Priority: High, Project: C190, bug

#6030 Backport 2020.02.xx - #5607: Fix checkout to current branch of submodule (#5940)
  createProject.js
  docs/developer-guide/project-creation-script.md
  package.json
  utility/projects/projectLib.js
Labels: Backport, bug

#5921 #5920: App Infrastucture Review
  build/docma-config.json
  docs/developer-guide/mapstore-migration-guide.md
  project/custom/static/js/app.jsx
  web/client/components/app/StandardApp.jsx
  web/client/components/app/StandardAppComponent.jsx
  web/client/components/app/__tests__/StandardApp-test.jsx
  web/client/components/app/__tests__/withExtensions-test.jsx
  web/client/components/app/main.jsx
  web/client/components/app/withExtensions.js
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/plugins/__tests__/PluginsContainer-test.jsx
  web/client/containers/Embedded.jsx
  web/client/containers/HolyGrail.jsx
  web/client/containers/MapViewer.jsx
  web/client/containers/Page.jsx
  web/client/examples/featuregrid/pages/MapViewer.jsx
  web/client/examples/featuregrid/stores/store.js
  web/client/jsapi/MapStore2.js
  web/client/product/__tests__/main-test.jsx
  web/client/product/app.jsx
  web/client/product/embedded.jsx
  web/client/product/main.jsx
  web/client/stores/StandardStore.js
  web/client/stores/__tests__/StandardStore-test.js
  web/client/stores/defaultOptions.js
  web/client/themes/default/less/react-select.less
Labels: Project: C117, QF, enhancement

#6032 #5607 fix problem when creating a new project
  utility/projects/projectLib.js
Labels: BackportNeeded, bug

#5978 #5976: Add media editor settings configurations to localConfig for GeoStory plugin
  web/client/actions/__tests__/geostory-test.js
  web/client/actions/geostory.js
  web/client/actions/mediaEditor.js
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/GeoStory.jsx
  web/client/plugins/__tests__/GeoStory-test.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/__tests__/mediaEditor-test.js
  web/client/reducers/geostory.js
  web/client/reducers/mediaEditor.js
  web/client/selectors/geostory.js
Labels: GeoStory, Priority: High, Project: C183, enhancement

#6034 Backport 2020.02.xx - #5607: fix problem when creating a new project (#6032)
  utility/projects/projectLib.js
Labels: Backport, bug

#6033 Fix #6031 Feature grid doesn't open anymore
  web/client/plugins/FeatureEditor.jsx
Labels: Internal, Priority: Blocker, bug

#5999 This modification ables MapStore2 to handle correctly customization o…
  web/client/utils/mapinfo/vector.js
Labels: BackportNeeded, Priority: High, Project: C169, geOrchestra

#5906 Settings and Paragraph sections
  docs/user-guide/img/button/change_size2.jpg
  docs/user-guide/img/button/color-picker.jpg
  docs/user-guide/img/paragraph-section/add-paragraph.jpg
  docs/user-guide/img/paragraph-section/image-map.jpg
  docs/user-guide/img/paragraph-section/map-content.jpg
  docs/user-guide/img/paragraph-section/map-web.jpg
  docs/user-guide/img/paragraph-section/map-web5.jpg
  docs/user-guide/img/paragraph-section/p-add-content.jpg
  docs/user-guide/img/paragraph-section/p-text-content.jpg
  docs/user-guide/img/paragraph-section/parag-section.jpg
  docs/user-guide/img/paragraph-section/paragraph-section.jpg
  docs/user-guide/img/paragraph-section/paragraphe-size.jpg
  docs/user-guide/img/paragraph-section/text-image.jpg
  docs/user-guide/img/paragraph-section/text_content.jpg
  docs/user-guide/img/paragraph-section/web-content.jpg
  docs/user-guide/img/story-setting/font_family.gif
  docs/user-guide/img/story-setting/links.gif
  docs/user-guide/img/story-setting/story-setting-1.jpg
  docs/user-guide/img/story-setting/story-settings-2.jpg
  docs/user-guide/img/story-setting/story_header.jpg
  docs/user-guide/paragraph-section.md
  docs/user-guide/story-setting.md
Labels: Documentation, GeoStory, Project: C039, User Guide

#6039 Update story-setting.md
  docs/user-guide/story-setting.md
Labels: Documentation, User Guide

#6037 Search bar returns always a maximun of 15 results even with custom services #5929
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/search/SearchBarUtils.js
Labels: BackportNeeded, Priority: High, bug, investigation

#6042 Porting 5929
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/search/SearchBarUtils.js
Labels: Backport, Priority: High, bug, investigation

#6038 Fix #6025 Error page selecting "Display Legend" adding chart widget
  web/client/components/widgets/enhancers/__tests__/wpsChart-test.js
  web/client/components/widgets/enhancers/errorChartState.js
  web/client/components/widgets/enhancers/wpsChart.js
  web/client/test-resources/widgetbuilder/aggregate2
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Dashboard, Internal, Priority: Blocker, bug

#6028 #6024: Retain geometry on deselect
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
  web/client/epics/annotations.js
  web/client/plugins/Annotations.jsx
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
Labels: Priority: Blocker, Project: C125, bug

#6046 #6043: Fix annotation modal overlap in Geostory
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/style-editor.less
Labels: Priority: High, bug

#6045 Error in GFI for (imported) vector layer #5961
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/mapinfo/vector.js
Labels: BackportNeeded, Priority: Blocker, bug

#6049 [Backport 2020.02.xx] #5961: Fix icon on Paragraph section (#6045)
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/mapinfo/vector.js
Labels: Backport, Priority: High, bug

#6056 Marker property modal hidden in geostory
  web/client/themes/default/less/annotations.less
Labels: Priority: Blocker, Project: C125

#6018 #6002: Fix wrong alignement on buttons in story nav bar
  web/client/themes/default/less/geostory-navigation.less
Labels: GeoStory, Priority: Blocker, bug

#6010 #6001: Fix home button link issue in Story share
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory, Internal, Priority: Blocker, bug

#6060 #6057: Allow OSM background selection for custom CRS
  web/client/components/background/PreviewIcon.jsx
  web/client/components/background/__tests__/PreviewIcon-test.jsx
Labels: Project: C008

#6058 Timeline showing but WMTS layer with time dimension are not supported #5786
  web/client/epics/dimension.js
Labels: BackportNeeded, Priority: High, bug

#6065 [Backport 2020.02.xx] #5786: Fix Timeline showing when adding WMTS layer (#6058)
  web/client/epics/dimension.js
Labels: Backport, Priority: High, bug

#6067 #6064: forces encoding of MVC responses to UTF-8 in ConfigController
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
Labels: BackportNeeded

#6054 Fix #6051 Search bar on homepage does not work
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/search/SearchBarUtils.js
  web/client/components/search/__tests__/SearchBarUtils-test.js
Labels: BackportNeeded, Priority: Blocker, bug

#5984 #5778: Fix1-GeoStory Contents - Rich Text - Interactions
  web/client/components/geostory/contents/enhancers/__tests__/editableText-test.jsx
  web/client/components/geostory/contents/enhancers/editableText.jsx
  web/client/components/geostory/contents/texteditor/CustomEditorLink.jsx
Labels: GeoStory, Internal, Priority: High, Task, bug

#6050 Fix #6025 Error page selecting "Display Legend" adding chart widget(Backport 2020.02.xx)
  web/client/components/widgets/enhancers/__tests__/wpsChart-test.js
  web/client/components/widgets/enhancers/errorChartState.js
  web/client/components/widgets/enhancers/wpsChart.js
  web/client/test-resources/widgetbuilder/aggregate2
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, Priority: Blocker

#5855 #5530 - Redirected to the homepage after logout of the dashboard and story
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/feedbackMask.js
  web/client/epics/map.js
Labels: BackportNeeded, Dashboard, GeoStory, Priority: Blocker, bug

#6069 Backport 2020.02.xx: #6002 Fix wrong alignment on buttons in story nav bar
  web/client/themes/default/less/geostory-navigation.less
Labels: Backport

#6068 Backport 2020.02.xx: #6001 Fix home button link issue in Story share
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: Backport

#6070 #5530 - Redirected to the homepage after logout of the dashboard and story(Backport on 2020.02.xx)
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/feedbackMask.js
  web/client/epics/map.js
Labels: Backport, Priority: Blocker

#6071 Fix #6051 Search bar on homepage does not work(Backport on 2020.02.xx)
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/search/SearchBarUtils.js
  web/client/components/search/__tests__/SearchBarUtils-test.js
Labels: Backport, Priority: Blocker

#5995 #5994: Missing default center and zoom props in ol maps
  web/client/components/map/openlayers/Map.jsx
Labels: Priority: High, Project: C117, QF, enhancement

#5990 #5952: set mapstore-backend and print-lib to use a tagged version, added machinery to deploy mapstore-backend to maven with mvn deploy
  backend/pom.xml
  pom.xml
  project/custom/templates/backend/pom.xml
  project/custom/templates/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/backend/pom.xml
  project/standard/templates/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
  web/pom.xml
Labels: BackportNeeded, Priority: Blocker, dependencies

#6047 Fix #5873 Deactivation of feature filter inside the feature grid doesn't work if the advanced filter panel is opened
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Internal, Priority: Blocker, bug

#6083 Fix #5873 Deactivation of feature filter inside the feature grid doesn't work if the advanced filter panel is opened(Backport on 2020.02.xx)
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Backport, Priority: Blocker

#6082 [Backport for 2020.02.xx]: #6064: forces encoding of MVC responses to UTF-8 in ConfigController (#6067)
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
Labels: Backport, Priority: High, bug, geOrchestra

#6066 Identify maxItems cfg option removed #4238
  web/client/epics/__tests__/identify-test.js
  web/client/selectors/mapInfo.js
Labels: Priority: Medium, user feedback

#6073 Placeholder for new souce catalog in URL field #5933
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
Labels: BackportNeeded, Priority: Low, enhancement

#6088 [Backport 2020.02.xx] ##5933: Fix Add Placeholders for source catalog in URL field(#6073)
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
Labels: Backport, Priority: Low, enhancement

#6090 #6089: Template update fix
  web/client/components/data/template/jsx/Template.jsx
  web/client/components/data/template/jsx/__tests__/Template-test.jsx
Labels: Project: C008, bug

#6087 update react-draft-wysiwyg to 1.14.8
  package.json
Labels: BackportNeeded, Priority: High, Project: C039, bug

#6100 [Backport 2020.02.xx] #4238: Fix Maxcfg option removed(#6066)
  web/client/epics/__tests__/identify-test.js
  web/client/selectors/mapInfo.js
Labels: Backport, Priority: Medium, user feedback

#6098 Improve augment store to avoid to update the state twice
  web/client/utils/StateUtils.js
  web/client/utils/__tests__/StateUtils-test.js
Labels: QF, enhancement

#6110 #6026: Ensure layer registration is imported before map loading
  web/client/plugins/map/index.js
Labels: Priority: High, bug

#6109 #6063: use the new geostore parameter to limit the result of "all use…
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
Labels: Project: C039, bug

#6118 #6026: Fix map plugin failing test
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/Map-test.jsx
Labels: QF, bug

#6062 Fix #5378 MapStore not respecting WMS protocol version!
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/utils/CatalogUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: bug

#6117 Fix #6093 Leaving an edited dashboard does not show any warning panel
  web/client/epics/pendingChanges.js
  web/client/plugins/Home.jsx
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/dashboard.js
  web/client/selectors/__tests__/dashboardsave-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/dashboardsave.js
Labels: Priority: Medium, bug

#6119 Introduce ordering on column for table widget #2691
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/widgets/enhancers/tableWidget.js
  web/client/components/widgets/enhancers/wfsTable/virtualScrollFetch.js
  web/client/components/widgets/widget/TableWidget.jsx
Labels: Priority: High, Project: C040, Widgets

#6106 #6076: Deactivate MapSync by default
  web/client/reducers/query.js
Labels: Priority: High, Project: C155, enhancement

#6097 #6075: Fix filter on map active by default
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Priority: High, Project: C155, enhancement

#6122 #6113 - Fix embedded and refactor function to check missing plugins
  project/custom/static/js/app.jsx
  project/standard/templates/js/app.jsx
  web/client/product/apiPlugins.js
  web/client/product/app.jsx
  web/client/product/embedded.jsx
  web/client/utils/DebugUtils.js
  web/client/utils/__tests__/DebugUtils-test.js
Labels: Priority: Blocker, bug
