Repository geosolutions-it/MapStore2, pull requests merged in 2020-04, with the labels that each got.

#5105 Backport 2020.01.xx - #4491 Improved error page (#5051)
  web/client/components/app/ErrorFallBackComp.jsx
  web/client/components/app/StandardApp.jsx
  web/client/components/app/StandardRouter.jsx
  web/client/localConfig.json
  web/client/themes/default/less/common.less
  web/client/translations/data.de-DE
  web/client/translations/data.en-US
  web/client/translations/data.es-ES
  web/client/translations/data.fr-FR
  web/client/translations/data.it-IT
Labels: Backport, Priority: High, enhancement

#5096 #3861: Fix - Disable editing of dashboard on mobile
  web/client/components/widgets/view/__tests__/WidgetsView-test.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardSave.jsx
  web/client/selectors/__tests__/localConfig-test.js
  web/client/selectors/dashboard.js
Labels: Backport Needed, Priority: Medium, bug

#5106 Backport 3861
  web/client/components/widgets/view/__tests__/WidgetsView-test.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardSave.jsx
  web/client/selectors/__tests__/localConfig-test.js
  web/client/selectors/dashboard.js
Labels: Backport, bug

#5116 #5115 Fix to version identification issue for timeline mapSync
  web/client/test-resources/wmts/DescribeDomains1.1.xml
  web/client/utils/TimeUtils.js
  web/client/utils/__tests__/TimeUtils-test.js
Labels: Priority: High, bug

#5117 Fix #5107 Map Template thumbnail is not displayed
  web/client/epics/__tests__/maptemplates-test.js
  web/client/epics/maptemplates.js
Labels: Priority: High, geOrchestra

#5114 Update release procedure
  docs/developer-guide/release.md
Labels: Documentation

#5112 Improved datadir documentation
  docs/developer-guide/externalized-configuration.md
Labels: Documentation

#5122 #5121: preventive client-side validation of uploaded extensions
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/test-resources/extensions/myplugin.zip
  web/client/test-resources/extensions/myplugin_no_index.zip
  web/client/test-resources/extensions/myplugin_no_js.zip
  web/client/test-resources/extensions/myplugin_no_plugin.zip
  web/client/test-resources/extensions/myplugin_too_many_bundles.zip
  web/client/test-resources/extensions/myplugin_wrong_json.zip
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ExtensionsUtils.js
  web/client/utils/__tests__/ExtensionsUtils-test.js
Labels: Priority: High, geOrchestra

#5125 Add console log for errors triggered by UI
  web/client/components/app/StandardRouter.jsx
Labels: Priority: Low, enhancement

#5104 Add catalog services to WMC import/export
  docs/developer-guide/maps-configuration.md
  web/client/epics/catalog.js
  web/client/test-resources/wmc/config.json
  web/client/test-resources/wmc/context.wmc
  web/client/test-resources/wmc/exported-context.wmc
  web/client/utils/ogc/WMC/index.js
  web/client/utils/ogc/__tests__/WMC-test.js
Labels: Priority: High, geOrchestra

#5123 Map templates handling enhancements
  web/client/actions/contextcreator.js
  web/client/components/contextcreator/ConfigureMapTemplates.jsx
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/maptemplates/MapTemplatesPanel.jsx
  web/client/components/misc/cardgrids/SideCard.jsx
  web/client/components/misc/cardgrids/__tests__/SideCard-test.jsx
  web/client/components/resources/modals/enhancers/handleResourceData.jsx
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/epics/maptemplates.js
  web/client/reducers/contextcreator.js
  web/client/themes/default/less/context-creator.less
  web/client/themes/default/less/maptemplates.less
  web/client/themes/default/less/sidegrid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FileFormatUtils.js
Labels: Priority: High, geOrchestra

#5092 Advanced measurement tool
  web/client/actions/__tests__/measurement-test.js
  web/client/actions/measurement.js
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/VectorStyle.js
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureDialog-test.jsx
  web/client/epics/measurement.js
  web/client/plugins/Measure.jsx
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/measurement.js
  web/client/themes/default/less/ol.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MeasurementUtils.js
Labels: Priority: High, geOrchestra

#5127 Closes #5126 Easing Ms2 migration in projects
  createProject.js
  docs/developer-guide/project-creation-script.md
  package.json
  project/custom/static/checkCesium.js
  project/custom/static/updateDevDependencies.js
  project/standard/static/checkCesium.js
  project/standard/static/updateDevDependencies.js
  utility/build/checkCesium.js
  utility/build/postInstall.js
  utility/projects/projectScripts.json
Labels: Priority: Medium

#5130 C125-143: Coordinate editing mode in GFI
  docs/user-guide/img/button/tick_button.jpg
  docs/user-guide/img/side-bar/aeronautical_coordinates_editor.gif
  docs/user-guide/img/side-bar/decimal_coordinates_editor.gif
  docs/user-guide/side-bar.md
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/coordinates/Coordinate.jsx
  web/client/components/data/identify/coordinates/Editor.jsx
  web/client/components/data/identify/coordinates/__tests__/Editor-test.jsx
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/DecimalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/DecimalCoordinateEditor-test.js
  web/client/plugins/Identify.jsx
  web/client/themes/default/less/get-feature.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: Project: C125

#5103 #5083 Columns/paragraph media (map and web-page) size height changes
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/contents/__tests__/ContentToolbar-test.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/themes/default/less/geostory.less
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: GeoStory, Priority: Medium, enhancement

#5152 5083 Change IT translation for Change Size button
  web/client/translations/data.it-IT.json
Labels: GeoStory, bug

#5153 Add support for disablePermission
  web/client/components/resources/modals/Save.jsx
  web/client/components/resources/modals/enhancers/__tests__/handlePermission-test.jsx
  web/client/components/resources/modals/enhancers/handlePermission.jsx
  web/client/plugins/Save.jsx
  web/client/plugins/SaveAs.jsx
  web/client/plugins/__tests__/Save-test.jsx
  web/client/plugins/__tests__/SaveAs-test.jsx
Labels: enhancement, geonode_integration

#5155 Small fix to autofit the window when permissions are disabled
  web/client/components/resources/modals/Save.jsx
Labels: enhancement

#5156 Fix issue with cfg of StyleEditor
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
Labels: Priority: High, geonode_integration

#5157 Layer Editing - Editing tool
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/filterRenderers/GeometryFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/index.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/epics/identify.js
  web/client/plugins/featuregrid/gridEvents.js
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/reducers/featuregrid.js
  web/client/selectors/query.js
  web/client/themes/default/less/featuregrid.less
  web/client/themes/default/ms2-theme.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FeatureGridUtils.js
  web/client/utils/FilterUtils.jsx
  web/client/utils/__tests__/FilterUtils-test.js
Labels: Priority: High, geOrchestra

#5162 #4712: Share button disable in new dashboard
  web/client/epics/__tests__/dashboard-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/dashboard.js
  web/client/plugins/CreateNewMap.jsx
  web/client/plugins/Share.jsx
Labels: Priority: Low, bug

#5161 #5160: Updated web/pom.xml with new osgeo mvn repo URL
  backend/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
  web/pom.xml
Labels: Environment, Priority: Blocker, bug

#5165 5159 getMap request env param added
  web/client/components/map/openlayers/Layer.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/localConfig.json
  web/client/plugins/Map.jsx
  web/client/selectors/__tests__/localizedLayerStyles-test.js
  web/client/selectors/localizedLayerStyles.js
Labels: Project: C028

#5081 5068 Feature Attribute Popup - Floating Identify tool.
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/PopupSupport.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/PopupSupport.jsx
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/epics/identify.js
  web/client/epics/maplayout.js
  web/client/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/plugins/MousePosition.jsx
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/mousePosition-test.js
  web/client/reducers/map.js
  web/client/reducers/mousePosition.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/localConfig.js
  web/client/selectors/map.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, geOrchestra

#5147 C125-146: Legend size
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/toc.md
  web/client/components/TOC/fragments/WMSLegend.jsx
  web/client/components/TOC/fragments/__tests__/WMSLegend-test.jsx
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/legend/__tests__/Legend-test.jsx
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/localConfig.json
  web/client/plugins/TOC.jsx
  web/client/plugins/__tests__/TOCItemsSettings-test.jsx
  web/client/themes/default/less/toc.less
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Project: C125

#5164 C125-147: Max zoom level for search service
  docs/user-guide/img/menu-bar/optional-props-form.jpg
  docs/user-guide/menu-bar.md
  web/client/components/mapcontrols/searchservicesconfig/WFSOptionalProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/__tests__/WFSOptionalProps-test.jsx
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Project: C125

#5142 C125-145: Display and renaming of Bearing
  web/client/components/map/leaflet/MeasurementSupport.jsx
  web/client/components/map/leaflet/__tests__/MeasurementSupport-test.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureDialog-test.jsx
  web/client/plugins/Measure.jsx
  web/client/selectors/measurement.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/MeasureUtils.js
  web/client/utils/__tests__/MeasureUtils-test.js
Labels: Project: C125

#5179 C125-149: GFI behaviour
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: Project: C125

#5171 5168 GetLegendGraphic request, legend localization added
  docs/developer-guide/local-config.md
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/WMSLegend.jsx
  web/client/components/TOC/fragments/__tests__/WMSLegend-test.jsx
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/TOC.jsx
  web/client/selectors/__tests__/locale-test.js
  web/client/selectors/locale.js
Labels: Project: C028

#5167 Identify tool - Edit mode
  web/client/actions/featuregrid.js
  web/client/actions/mapInfo.js
  web/client/actions/wfsquery.js
  web/client/components/data/featuregrid/filterRenderers/GeometryFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/GeometryFilter-test.jsx
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/featuregrid.js
  web/client/epics/identify.js
  web/client/epics/wfsquery.js
  web/client/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/identify/toolButtons.js
  web/client/reducers/mapInfo.js
  web/client/selectors/featuregrid.js
  web/client/selectors/mapInfo.js
  web/client/themes/default/less/featuregrid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/IdentifyUtils.js
Labels: Priority: High, geOrchestra

#5151 4946 identify and measurament tools
  docs/user-guide/img/button/json_export_button.jpg
  docs/user-guide/img/button/layers_button.jpg
  docs/user-guide/img/button/x_button.jpg
  docs/user-guide/img/measure/as_layer.jpg
  docs/user-guide/img/measure/measure-area-ex.gif
  docs/user-guide/img/measure/measure-bearing-ex.gif
  docs/user-guide/img/measure/measure-distance-ex.gif
  docs/user-guide/img/measure/measure.jpg
  docs/user-guide/img/side-bar/layer.gif
  docs/user-guide/img/side-bar/layers.jpg
  docs/user-guide/measure.md
  docs/user-guide/side-bar.md
  mkdocs.yml
Labels: Documentation, User Guide, geOrchestra

#5154 #5139 standard user session plugin
  build/docma-config.json
  docs/developer-guide/user-sessions.md
  utility/translations/findMissingTranslations.js
  web/client/actions/__tests__/usersession-test.js
  web/client/actions/usersession.js
  web/client/api/usersession/__tests__/browser-test.js
  web/client/api/usersession/__tests__/server-test.js
  web/client/api/usersession/__tests__/serverbackup-test.js
  web/client/api/usersession/browser.js
  web/client/api/usersession/index.js
  web/client/api/usersession/server.js
  web/client/api/usersession/serverbackup.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/context-test.js
  web/client/epics/__tests__/epicTestUtils.js
  web/client/epics/__tests__/usersession-test.js
  web/client/epics/config.js
  web/client/epics/context.js
  web/client/epics/usersession.js
  web/client/localConfig.json
  web/client/plugins/UserSession.jsx
  web/client/pluginsConfig.json
  web/client/product/plugins.js
  web/client/reducers/usersession.js
  web/client/selectors/__tests__/usersession-test.js
  web/client/selectors/mapInitialConfig.js
  web/client/selectors/usersession.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ConfigUtils.js
Labels: enhancement, geOrchestra

#5170 4946 footer and timeline
  docs/user-guide/footer.md
  docs/user-guide/img/footer/CRS_selector.gif
  docs/user-guide/img/footer/crs_selector.jpg
  docs/user-guide/img/footer/searchCRS.jpg
  docs/user-guide/img/footer/show_coordinates.jpg
  docs/user-guide/img/footer/show_coordinates1.jpg
  docs/user-guide/img/footer/show_scale.jpg
  docs/user-guide/img/footer/show_scale1.jpg
  docs/user-guide/img/timeline/animation-passage.jpg
  docs/user-guide/img/timeline/frame-duration.jpg
  docs/user-guide/img/timeline/timeline-animation-buttons.jpg
  docs/user-guide/img/timeline/timeline-animation-green-range.gif
  docs/user-guide/img/timeline/timeline-animation-range.gif
  docs/user-guide/img/timeline/timeline-animation-settings.jpg
  docs/user-guide/img/timeline/timeline-animation.gif
  docs/user-guide/img/timeline/timeline-base.jpg
  docs/user-guide/img/timeline/timeline-current-time-range.jpg
  docs/user-guide/img/timeline/timeline-current-time.jpg
  docs/user-guide/img/timeline/timeline-histogram.jpg
  docs/user-guide/img/timeline/timeline-sync-example.jpg
  docs/user-guide/timeline.md
Labels: Documentation, User Guide
