Repository geosolutions-it/MapStore2, pull requests merged in 2020-11, with the labels that each got.

#6130 Update data.nl-NL.json
  web/client/translations/data.nl-NL.json
Labels: Priority: Medium

#6123 New configuration property for Locate tool
  web/client/components/map/leaflet/Locate.jsx
  web/client/components/map/openlayers/Locate.jsx
  web/client/plugins/Locate.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/map/leaflet/index.js
  web/client/product/plugins.js
  web/client/utils/openlayers/OlLocate.js
Labels: Priority: High, Project: C155, enhancement

#6150 #6095 Enabled extensions by default
  web/client/components/app/withExtensions.js
Labels: bug

#6147 #6146 Plugin injection for TOC toolbar
  web/client/components/TOC/Toolbar.jsx
  web/client/plugins/Swipe.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/__tests__/TOC-test.jsx
  web/client/plugins/swipe/SwipeButton.jsx
  web/client/plugins/swipe/__tests__/SwipeButton-test.jsx
Labels: Priority: High

#5860 Eslint Update and Config Sharing
  .eslintignore
  .eslintrc
  CONTRIBUTING.md
  createProject.js
  docs/developer-guide/building-and-deploying.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/project-structure.md
  package.json
  utility/eslint/README.md
  utility/eslint/index.js
  utility/eslint/package.json
  web/client/components/buttons/CloseButton.jsx
  web/client/components/geostory/builder/Settings.jsx
  web/client/components/geostory/common/CustomThemePicker.jsx
  web/client/components/geostory/contents/texteditor/CustomEditorLink.jsx
  web/client/components/geostory/media/Map.jsx
  web/client/components/geostory/media/Video.jsx
  web/client/components/manager/users/CloseConfirmButton.jsx
  web/client/components/map/openlayers/swipe/SliderSwipeSupport.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mediaEditor/video/VideoForm.jsx
  web/client/components/misc/FeatureInfoFormatSelector.jsx
  web/client/components/styleeditor/Band.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/Popover.jsx
  web/client/components/styleeditor/RulesEditor.jsx
Labels: Priority: Medium, QF

#6129 #6126 - Annotations highlight and circle draw fix
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
Labels: Priority: High, Project: C125, annotations, bug

#6152 Fix #6151 Catalogue : Search by CSW : no preview
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Priority: High, geOrchestra

#6107 #6079: Enable multiple highlighting for OL/Leaflet DrawSupport tool
  web/client/components/map/leaflet/DrawSupport.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Priority: High, Project: C155, enhancement

#6158 Fix #6154 Buttons in Feature Info are not aligned anymore
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/maplayout.js
Labels: Priority: High, bug

#6155 #6076: Deactivate MapSync featuregrid close
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
Labels: Priority: High, Project: C155, enhancement

#6121 #6077: Multiple selection on Map
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Medium, Project: C155, enhancement

#6163 Plotly charts
  package.json
  web/client/components/charts/Bar.jsx
  web/client/components/charts/DataStreamChart.jsx
  web/client/components/charts/Gauge.jsx
  web/client/components/charts/Line.jsx
  web/client/components/charts/ObliqueLabel.jsx
  web/client/components/charts/Pie.jsx
  web/client/components/charts/SimpleChart.jsx
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/YAxisLabel.jsx
  web/client/components/charts/__tests__/DataStreamChart-test.jsx
  web/client/components/charts/__tests__/SimpleChart-test.js
  web/client/components/charts/__tests__/SimpleChart-test.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/YAxisLabel-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/components/charts/cartesian.jsx
  web/client/components/charts/polar.jsx
  web/client/components/widgets/builder/WidgetBuilder.jsx
  web/client/components/widgets/builder/__tests__/WidgetsBuilder-test.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/__tests__/ChartWizard-test.jsx
  web/client/components/widgets/builder/wizard/chart/ChartType.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ChartType-test.jsx
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/WPSWidgetOptions-test.jsx
  web/client/components/widgets/enhancers/__tests__/builderConfiguration-test.jsx
  web/client/components/widgets/enhancers/tools/__tests__/exportableWidget-test.js
  web/client/components/widgets/enhancers/tools/__tests__/withMenu-test.js
  web/client/components/widgets/enhancers/tools/exportableWidget.js
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/ChartView.jsx
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/components/widgets/widget/__tests__/ChartView-test.jsx
  web/client/components/widgets/widget/__tests__/ChartWidget-test.jsx
  web/client/components/widgets/widget/enhancedWidgets.js
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/plugins/widgetbuilder/ChartBuilder.jsx
  web/client/plugins/widgetbuilder/WidgetTypeBuilder.jsx
  web/client/product/plugins.js
Labels: Priority: Blocker, Project: C117, enhancement

#6165 use minimal bundle for the required functionalities
  package.json
  web/client/components/charts/PlotlyChart.jsx
  web/client/components/charts/WidgetChart.jsx
Labels: Priority: Blocker, Project: C117, bug

#6164 Ability to disable Identify for a layer #6101
  web/client/components/misc/panels/Accordion.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/MapInfoUtils-test.js
Labels: Priority: Medium, Project: C040, enhancement

#6145 #6078: Box Selection on Map
  web/client/actions/__tests__/box-test.js
  web/client/actions/box.js
  web/client/components/map/openlayers/BoxSelectionSupport.jsx
  web/client/components/map/openlayers/__tests__/BoxSelectionSupport-test.jsx
  web/client/components/map/plugins/openlayers.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/Map.jsx
  web/client/plugins/map/index.js
  web/client/plugins/map/openlayers/index.js
  web/client/reducers/__tests__/box-test.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/box.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/box-test.js
  web/client/selectors/box.js
Labels: Priority: Medium, Project: C155, enhancement

#6170 #6080: Save (one or multiple) edits in same context
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/plugins/FeatureEditor.jsx
  web/client/reducers/featuregrid.js
Labels: Priority: Medium, Project: C155, enhancement

#6171 #6081: Copy edits to multiple features
  web/client/components/data/featuregrid/enhancers/editor.js
Labels: Priority: Low, Project: C155, enhancement

#6105 #5977: Add the possibility to register a new service to media editor plugin
  web/client/actions/__tests__/mediaEditor-test.js
  web/client/actions/mediaEditor.js
  web/client/api/media/__tests__/geostore-test.js
  web/client/api/media/__tests__/geostory-test.js
  web/client/api/media/geostore.js
  web/client/api/media/geostory.js
  web/client/api/media/index.js
  web/client/components/geostory/common/enhancers/withMediaVisibilityContainer.jsx
  web/client/components/geostory/media/index.js
  web/client/components/mediaEditor/MediaEditor.jsx
  web/client/components/mediaEditor/MediaList.jsx
  web/client/components/mediaEditor/__tests__/MediaList-test.jsx
  web/client/components/mediaEditor/__tests__/MediaSelector-test.jsx
  web/client/components/mediaEditor/enhancers/__tests__/withSelectedMapReload-test.js
  web/client/components/mediaEditor/enhancers/withMapEditing.js
  web/client/components/mediaEditor/enhancers/withSelectedMapReload.js
  web/client/components/mediaEditor/image/ImageList.jsx
  web/client/components/mediaEditor/image/__tests__/ImageList-test.jsx
  web/client/components/mediaEditor/map/MapList.jsx
  web/client/components/mediaEditor/video/VideoList.jsx
  web/client/components/mediaEditor/video/__tests__/VideoList-test.jsx
  web/client/components/misc/enhancers/__tests__/withDebounceOnCallback-test.jsx
  web/client/components/misc/enhancers/infiniteScroll/withScrollSpy.js
  web/client/components/misc/enhancers/withDebounceOnCallback.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/__tests__/mediaEditor-test.js
  web/client/epics/geostory.js
  web/client/epics/mediaEditor.js
  web/client/plugins/GeoStory.jsx
  web/client/plugins/mediaEditor/MediaModal.jsx
  web/client/reducers/__tests__/mediaEditor-test.js
  web/client/reducers/geostory.js
  web/client/reducers/mediaEditor.js
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
  web/client/themes/default/less/geostory.less
  web/client/themes/default/less/media-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: GeoStory, Priority: High, Project: C183, enhancement

#6169 #6134: Add types and other options for X/Y Axis
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/misc/switch/SwitchButton.jsx
  web/client/components/misc/switch/__tests__/SwitchButton-test.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/CounterWizard.jsx
  web/client/components/widgets/builder/wizard/common/ChartAdvancedOptions.jsx
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/ChartAdvancedOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/WPSWidgetOptions-test.jsx
  web/client/themes/default/less/sliders.less
  web/client/themes/default/less/switch.less
  web/client/themes/default/less/widget.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Blocker, Project: C117

#6176 Ability to disable Identify for a layer #6101
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: Priority: Medium, Project: C040, enhancement

#6181 Additional SVG Annotation Symbols
  web/client/product/assets/symbols/arrow-east.svg
  web/client/product/assets/symbols/arrow-north-east.svg
  web/client/product/assets/symbols/arrow-north-west.svg
  web/client/product/assets/symbols/arrow-north.svg
  web/client/product/assets/symbols/arrow-south-east.svg
  web/client/product/assets/symbols/arrow-south-west.svg
  web/client/product/assets/symbols/arrow-south.svg
  web/client/product/assets/symbols/arrow-west.svg
  web/client/product/assets/symbols/circle.svg
  web/client/product/assets/symbols/diamond.svg
  web/client/product/assets/symbols/drawing-pin.svg
  web/client/product/assets/symbols/square.svg
  web/client/product/assets/symbols/star.svg
  web/client/product/assets/symbols/symbols.json
  web/client/product/assets/symbols/traffic-cone.svg
Labels: annotations

#6178 #6168: Filter feature selection in feature grid is disabled when advanced search is closed
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: Project: C155, bug

#6183 #6077: Multiple Selection/wmsSync bug fix
  web/client/actions/featuregrid.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: C155-IBF-2020-MeteoBlue, Priority: Medium, bug, enhancement

#6188 #5967 Add format an formulas to the PR
  package.json
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/misc/popover/DisposablePopover.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/common/ChartAdvancedOptions.jsx
  web/client/components/widgets/builder/wizard/common/FormulaInput.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/ChartAdvancedOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/FormulaInput-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ExpressionUtils.js
  web/client/utils/__tests__/ExpressionUtils-test.js
Labels: C117-UNESCO-2019-GEONODE, New Feature, Priority: High

#6194 #6184: Geometry modification problem on the feature grid
  web/client/epics/featuregrid.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
Labels: C155-IBF-2020-MeteoBlue, Priority: Blocker, bug

#6195 #6185: Attribute Table - Multiline editing Issue
  web/client/reducers/featuregrid.js
Labels: C155-IBF-2020-MeteoBlue, Priority: Blocker, bug

#6220 Featuregrid fixes
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/components/data/featuregrid/Footer.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/featuregrid.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: C155-IBF-2020-MeteoBlue, bug

#6223 #6149: fixed standard project broken by import/export migration
  project/standard/templates/js/app.jsx
Labels: bug

#6213 #6208 Problem creating Map Templates in application contexts
  web/client/components/contextcreator/ConfigureMapTemplates.jsx
  web/client/components/contextcreator/__tests__/ConfigureMapTemplates-test.jsx
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
Labels: C169-Rennes-Métropole-2019-GeOrchestra, Priority: High, bug

#6229 #6207: use ALT for box selection in spatial quick filter
  web/client/components/map/openlayers/BoxSelectionSupport.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C155-IBF-2020-MeteoBlue

#6227 #6224: fixed issues with advanced filter
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/utils/FilterUtils.js
Labels: C155-IBF-2020-MeteoBlue, bug

#6215 #6120: Text change to GeoStory
  docs/user-guide/exploring-stories.md
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, bug

#6233 #6186. Support for custom spatialFieldOperator in widgetFilter
  web/client/components/widgets/enhancers/__tests__/dependenciesToFilter-test.jsx
  web/client/components/widgets/enhancers/utils.js
  web/client/test-resources/widgets/dependenciesToFiltersData.js
Labels: C155-IBF-2020-MeteoBlue, Priority: Blocker

#6237 #6159: New Icon needed for disable identify
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/hide-marker.svg
Labels: Priority: Medium, enhancement

#6214 improve {de,}activatePlugin fr-FR translations
  web/client/translations/data.fr-FR.json
Labels: geOrchestra

#6236 #6235 fix map sync button popup position
  web/client/components/data/featuregrid/toolbars/TButton.jsx
Labels: Priority: High, bug

#6201 #6167 - Hide marker and popup on clear warning
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: bug

#6244 #6238: Review parsing of properties with 0 values in the Visual Style Editor
  web/client/components/styleeditor/config/property.js
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, bug

#6192 #6190: Cannot read property 'features' of undefined error with Identify
  web/client/components/data/identify/viewers/PropertiesViewer.js
Labels: bug

#6222 #6166: Display on load error for failed WFS requests
  web/client/components/map/openlayers/Layer.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WFSLayer.js
Labels: bug

#6225 #6103 Full screen widgets
  web/client/actions/__tests__/widgets-test.js
  web/client/actions/widgets.js
  web/client/components/dashboard/Dashboard.jsx
  web/client/components/dashboard/__tests__/Dashboard-test.jsx
  web/client/components/widgets/enhancers/tools/collapsibleWidget.js
  web/client/components/widgets/enhancers/tools/hidableWidget.js
  web/client/components/widgets/enhancers/tools/index.js
  web/client/components/widgets/enhancers/tools/maximizableWidget.js
  web/client/components/widgets/enhancers/tools/pinnableWidget.js
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/view/__tests__/WidgetsView-test.jsx
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/LegendWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/TextWidget.jsx
  web/client/components/widgets/widget/WidgetContainer.jsx
  web/client/plugins/Widgets.jsx
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C040-2020-COMUNE_GE-SUPPORT, Priority: Medium, enhancement

#6241 Update Layer Title and Description
  web/client/epics/__tests__/layerinfo-test.js
  web/client/epics/layerinfo.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug

#6246 Fix #5930 Details do not work in emedded mode
  web/client/actions/__tests__/details-test.js
  web/client/actions/__tests__/maps-test.js
  web/client/actions/details.js
  web/client/actions/maps.js
  web/client/epics/__tests__/details-test.js
  web/client/epics/__tests__/maps-test.js
  web/client/epics/details.js
  web/client/epics/maps.js
  web/client/localConfig.json
  web/client/plugins/Details.jsx
  web/client/plugins/Maps.jsx
  web/client/plugins/maps/MapsGrid.jsx
  web/client/product/apiPlugins.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/__tests__/maps-test.js
  web/client/reducers/config.js
  web/client/reducers/details.js
  web/client/reducers/maps.js
  web/client/selectors/details.js
Labels: C040-2020-COMUNE_GE-SUPPORT, Priority: High, bug

#6239 Responsive Design - Info Box
  web/client/plugins/Details.jsx
  web/client/themes/default/less/modal.less
  web/client/utils/EditorUtils.js
  web/client/utils/__tests__/EditorUtils-test.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug

#6216 #6179: MapSwipe shouldn't be deactivated when the layer is deactivated
  web/client/epics/__tests__/swipe-test.js
  web/client/epics/swipe.js
Labels: C190-OAW-2020-SUPPORT, Priority: High, enhancement

#6253 #6251: Fix default marker style
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug
