Repository geosolutions-it/MapStore2, pull requests merged in 2020-08, with the labels that each got.

#5731 Fix 5681 Add standard deviation method to classfication rule (static service configuration)
  web/client/plugins/StyleEditor.jsx
  web/client/plugins/__tests__/StyleEditor-test.jsx
Labels: Project: C183, StyleEditor, enhancement

#5723 Backport 2020.02.xx - #5574 Empty cover for stories - Navbar Fixes (#5718)
  web/client/components/geostory/builder/__tests__/Builder-test.jsx
  web/client/components/geostory/builder/__tests__/SectionsPreview-test.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/components/geostory/navigation/__tests__/ScrollMenu-test.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
  web/client/test-resources/geostory/sampleStory_1.json
Labels: Backport, GeoStory, Priority: Medium, enhancement

#5707 #5067. add color default color picker for geostory overlays
  web/client/components/geostory/builder/Settings.jsx
  web/client/components/geostory/common/CustomThemePicker.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/__tests__/Cascade-test.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/configs/newgeostory.json
  web/client/plugins/GeoStory.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: BackportNeeded, GeoStory, Priority: Medium, Project: C039, enhancement

#5722 Availability to define a filter for a layer
  web/client/components/contextcreator/ContextCreator.jsx
Labels: BackportNeeded, geOrchestra

#5413 Set symbols as default
  docs/developer-guide/local-config.md
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/mapcontrols/annotations/Annotations.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/DropdownFeatureType.jsx
  web/client/components/style/vector/Fill.jsx
  web/client/components/style/vector/Manager.jsx
  web/client/components/style/vector/Stroke.jsx
  web/client/components/style/vector/marker/SymbolLayout.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/plugins/Annotations.jsx
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/selectors/annotations.js
  web/client/utils/AnnotationsUtils.js
Labels: Priority: High, Project: C125

#5608 localized layer on user guide
  docs/user-guide/catalog.md
  docs/user-guide/layer-settings.md
Labels: BackportNeeded, Documentation, User Guide

#5740 Tooltip settings for groups cannot be stored (#4552)
  web/client/utils/LayersUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: BackportNeeded, Priority: High, Project: C125, user feedback

#5701 Identify Mode not persisted when map saved (#5566)
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/epics/__tests__/map-test.js
  web/client/epics/__tests__/mapInfo-test.js
  web/client/epics/mapInfo.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Map.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
Labels: BackportNeeded, Priority: High, enhancement

#5747 Backport 2020 02 xx - #4552: Persist tooltip settings for groups in TOC
  web/client/utils/LayersUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport

#5742 Fix #5467 MapTemplate Issue (Backport on 2020.02.xx)
  web/client/epics/maptemplates.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport

#5729 #5571. fix removing media content on restoration
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
Labels: BackportNeeded, GeoStory, Priority: Medium, enhancement

#5752 Backport 5566-backport-2020.02.xx - #5566: Identify Mode not persisted when map saved
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/__tests__/map-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
Labels: Backport

#5745 Backport 2020.02.xx - #5580 localized layer on user guide (#5608)
  docs/user-guide/catalog.md
  docs/user-guide/layer-settings.md
Labels: Backport

#5759 Backport 2020.02.xx - #5571 Restore an empty background for Story section (#5729)
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
Labels: Backport, GeoStory, Priority: Medium, enhancement

#5753 #5751 - Add postInstall script to the list used when creating a new project
  utility/projects/projectScripts.json
Labels: BackportNeeded, bug

#5743 Fix #5532 Group manager card has layout problem (Backport on 2020.02.xx)
  web/client/components/manager/users/GroupCard.jsx
  web/client/components/manager/users/UserCard.jsx
  web/client/components/manager/users/__tests__/GroupCard-test.jsx
  web/client/components/manager/users/__tests__/UserCard-test.jsx
  web/client/components/manager/users/style/usercard.css
  web/client/components/misc/GridCard.jsx
Labels: Backport

#5741 Availability to define a filter for a layer (Backport on 2020.02.xx)
  web/client/components/contextcreator/ContextCreator.jsx
Labels: Backport

#5760 Fix #4758 Ability to save resource with thumbnail not allowed
  web/client/components/resources/forms/Thumbnail.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
Labels: Priority: Medium, bug

#5738 Backport 2020.02.xx - #5067 Introduce a default color picker for all text content (#5707)
  web/client/components/geostory/builder/Settings.jsx
  web/client/components/geostory/common/CustomThemePicker.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/__tests__/Cascade-test.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/configs/newgeostory.json
  web/client/plugins/GeoStory.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: Backport, GeoStory, Priority: Medium, Project: C039, enhancement

#5764 Fix issue where setting hyperlinks introduces a space (#5726)
  package.json
Labels: GeoStory, Priority: High, Project: C039, bug

#5735 #5690 New Icon for Banner Section
  docma-template/less/bs-variables.less
  web/client/components/geostory/builder/SectionsPreview.jsx
  web/client/components/geostory/common/AddBar.jsx
  web/client/components/geostory/common/ToolbarPopover.jsx
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/sections/Banner.jsx
  web/client/components/geostory/layouts/sections/Immersive.jsx
  web/client/components/geostory/layouts/sections/Paragraph.jsx
  web/client/components/geostory/layouts/sections/Title.jsx
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/geostory.less
  web/client/themes/default/svg/story-banner-section.svg
Labels: BackportNeeded, Priority: High

#5761 Fix initially misaligned About modal(#5749)
  web/client/components/buttons/css/infoButton.css
Labels: BackportNeeded, Priority: Medium, bug

#5769 Backport 2020.02.xx: #5749 Fix initially misaligned About modal
  web/client/components/buttons/css/infoButton.css
Labels: Backport

#5232 C125-150: Central coordinate setting
  docs/developer-guide/local-config.md
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/plugins/Measure.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/Share.jsx
  web/client/selectors/__tests__/config-test.jsx
  web/client/selectors/annotations.js
  web/client/selectors/config.js
Labels: Priority: High, Project: C125

#5466 Order of Layer and select drop-down in GFI
  docs/user-guide/img/side-bar/areonautical-ex.gif
  docs/user-guide/img/side-bar/coordinate.jpg
  docs/user-guide/img/side-bar/decimal-ex.gif
  docs/user-guide/img/side-bar/edit_identify.gif
  docs/user-guide/img/side-bar/format_example.jpg
  docs/user-guide/img/side-bar/hightlight-point1.gif
  docs/user-guide/img/side-bar/identify-tool.jpg
  docs/user-guide/img/side-bar/layer.gif
  docs/user-guide/img/side-bar/layers.jpg
  docs/user-guide/img/side-bar/more-info.jpg
  docs/user-guide/side-bar.md
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/LayerSelector.jsx
  web/client/components/data/identify/PopupViewer.jsx
  web/client/components/data/identify/__tests__/DefaultViewer-test.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
  web/client/components/data/identify/__tests__/LayerSelector-test.jsx
  web/client/components/data/identify/coordinates/Coordinate.jsx
  web/client/components/data/identify/coordinates/__tests__/Coordinate-test.jsx
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/plugins/identify/featureButtons.js
  web/client/plugins/identify/navigationButtons.js
  web/client/plugins/identify/toolButtons.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/mapInfo.js
  web/client/themes/default/less/annotations.less
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/less/map-search-bar.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
Labels: Priority: High, Project: C125

#5565 #5511 - Misplaced layers in TOC while adding a Map Template
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: AppContext, BackportNeeded, Priority: High, bug

#5770 Fix #4758 Ability to save resource with thumbnail not allowed (Backport on 2020.02.xx)
  web/client/components/resources/forms/Thumbnail.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
Labels: Backport

#5763 Size of bullet points in stories (#5725)
  web/client/themes/default/less/geostory.less
Labels: GeoStory, Priority: High, Project: C039, bug

#5771 Save the templates list of map-templates plugin inside map-templates configuration (Backport on 2020.02.xx)
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/epics/contextcreator.js
  web/client/plugins/ContextCreator.jsx
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/selectors/contextcreator.js
  web/client/themes/default/less/modal.less
Labels: Backport, Priority: High, enhancement

#5756 Fix #5750 Map Catalog remains empty
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: Priority: High, bug

#5538 #5539 Update Layer Title and Description
  build/docma-config.json
  web/client/actions/__tests__/layerinfo-test.js
  web/client/actions/layerinfo.js
  web/client/api/WMTS.js
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
  web/client/components/layerinfo/LayerInfo.jsx
  web/client/components/layerinfo/__tests__/LayerInfo-test.jsx
  web/client/components/misc/ResizableModal.jsx
  web/client/components/misc/transfer/TransferColumnCardList.jsx
  web/client/epics/__tests__/layerinfo-test.js
  web/client/epics/layerinfo.js
  web/client/localConfig.json
  web/client/plugins/LayerInfo.jsx
  web/client/plugins/TOC.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/layerinfo-test.js
  web/client/reducers/layerinfo.js
  web/client/selectors/layerinfo.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/layerinfo.less
  web/client/themes/default/less/modal.less
  web/client/themes/default/ms2-theme.less
  web/client/themes/default/svg/layer-info.svg
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
Labels: Project: C125

#5774 Backport 2020.02.xx - #5511 Misplaced layers in TOC while adding a Map Template (#5565)
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: AppContext, Backport, Priority: High, bug

#5780 Fix #5750 Map Catalog remains empty (Backport on 2020.02.xx)
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: Backport

#5767 #5757. add new url pattern, key navigation
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/product/appConfig.js
  web/client/utils/GeoStoryUtils.js
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: BackportNeeded, GeoStory, Priority: High, Project: C039, bug

#5788 Backport 2020.02.xx - #5757 Story section URL problems (#5767)
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/product/appConfig.js
  web/client/utils/GeoStoryUtils.js
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: Backport, GeoStory, Priority: High, Project: C039

#5790 #5613 creating a new story now works on newly created project
  createProject.js
  project/custom/static/configs/newgeostory.json
  project/custom/static/js/__tests__/app-test.js
  project/standard/static/configs/newgeostory.json
  project/standard/templates/js/__tests__/app-test.js
  utility/build/checkCesium.js
  utility/build/postInstall.js
  utility/projects/projectScripts.json
Labels: BackportNeeded

#5794 Backport 2020.02.xx - #5613 creating a new story now works on newly created project (#5790)
  createProject.js
  project/custom/static/configs/newgeostory.json
  project/custom/static/js/__tests__/app-test.js
  project/standard/static/configs/newgeostory.json
  project/standard/templates/js/__tests__/app-test.js
  utility/build/checkCesium.js
  utility/build/postInstall.js
  utility/projects/projectScripts.json
Labels: Backport

#5680 Fix 5624 Sorting rules in visual style editor
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/PropertyField.jsx
  web/client/components/styleeditor/Rule.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/Rule-test.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/style-editor.less
  web/client/themes/default/svg/grab-handle.svg
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, Project: C183, StyleEditor, enhancement

#5648 Fix 5620 Save button not disabled on error in the visual editor
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/reducers/styleeditor.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: Priority: High, Project: C183, StyleEditor, bug

#5736 Unable to zoom on layer
  web/client/actions/catalog.js
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/epics/__tests__/catalog-test.js
  web/client/test-resources/csw/getRecordsResponseDC.xml
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Priority: High, geOrchestra

#5808 Fix test for IT browsers
  web/client/utils/__tests__/TOCUtils-test.js
Labels: BackportNeeded, bug

#5781 try to fix travis watch count exceed
  .travis.yml
Labels: BackportNeeded

#5802 Backport 2020.02.xx - #5703 Fix the print icon (#5705)
  docs/user-guide/img/button/print_button.jpg
  docs/user-guide/print.md
Labels: Backport
