Repository geosolutions-it/MapStore2, pull requests merged in 2020-12, with the labels that each got.

#6230 #6196: Cesium map on click error fix
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
Labels: bug

#6269 #6053: Improved error handling for extensions
  web/client/components/app/__tests__/withExtensions-test.jsx
  web/client/components/app/withExtensions.js
Labels: C169-Rennes-Métropole-2020-GeOrchestra2, Priority: High, bug

#6268 #6266: Allow override of default user locale via localConfig.json
  docs/developer-guide/internationalization.md
  web/client/components/app/StandardApp.jsx
  web/client/components/app/withExtensions.js
Labels: C117-UNESCO-2019-GEONODE, enhancement

#6259 #6256: ported align fix to details editor
  web/client/themes/default/less/details.less
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug

#6267 Restore initial position after feature info close
  web/client/epics/identify.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, user feedback

#6265 #6262: Modify true bearing label
  web/client/components/map/leaflet/__tests__/MeasurementSupport-test.jsx
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/epics/__tests__/measurement-test.jsx
  web/client/plugins/Measure.jsx
  web/client/utils/MeasureUtils.js
  web/client/utils/__tests__/MeasureUtils-test.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement

#6271 #6263: Enhance saving annotation and geometry
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/misc/ConfirmDialog.jsx
  web/client/themes/default/less/annotations.less
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement

#6252 #6250: Check if the LayerDownload plugin doc is up to date
  web/client/components/data/download/DownloadDialog.jsx
  web/client/plugins/LayerDownload.jsx
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Documentation, Priority: High

#6276 #6275: Hide layers with no identify content in GFI
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/LayerSelector.jsx
  web/client/components/data/identify/__tests__/LayerSelector-test.jsx
  web/client/components/geostory/common/enhancers/withIdentifyPopup.jsx
  web/client/reducers/mapInfo.js
  web/client/selectors/mapInfo.js
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement

#6270 #6254: The Embed mode is no longer present for the map in the Contents section
  web/client/plugins/maps/MapsGrid.jsx
Labels: Priority: High, bug

#6274 #6273: Enhancement to share tool
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/themes/default/less/panels.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ShareUtils.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement

#6283 #6281: Share plugin render fix
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug

#6279 feat: add helper to create polygon from radius and center
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: C039-2020-HALLIBURTON-SUPPORT

#6278 feat: Add possibility to hide details button in spatial filter
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/SpatialFilter.jsx
  web/client/utils/CoordinatesUtils.js
Labels: C039-2020-HALLIBURTON-SUPPORT

#6284 #6282: Annotation layer visibility sync
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
  web/client/utils/AnnotationsUtils.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, enhancement

#6286 #6255: Extra whitespace on details
  web/client/components/resources/modals/fragments/DetailsSheet.jsx
Labels: bug

#6285 #6231: Next button is disabled when editing some existing context
  web/client/components/contextcreator/ContextCreator.jsx
Labels: Priority: Medium, bug

#6292 #6287: Provide maxZoomLevel config property for Attribute Table zoom to feature
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/gridTools.jsx
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, enhancement

#6290 #6289: Shape file style fix for MultiPoint
  web/client/components/map/openlayers/LegacyVectorStyle.js
  web/client/components/map/openlayers/__tests__/LegacyVectorStyle-test.js
Labels: C039-2020-HALLIBURTON-Quickplates, bug

#6260 3916 cql exceed
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
Labels: C039-2020-HALLIBURTON-SUPPORT, bug

#6277 #6179: Deactivate swipe tool on location change
  web/client/epics/__tests__/swipe-test.js
  web/client/epics/swipe.js
Labels: C190-OAW-2020-SUPPORT, Priority: High, bug

#6299 #6296: Share tool not working in MS home
  web/client/components/share/SharePanel.jsx
Labels: Internal, Priority: High, bug

#6258 #6103: Full screen widgets on dashboards
  web/client/components/dashboard/Dashboard.jsx
  web/client/plugins/Dashboard.jsx
Labels: C040-2020-COMUNE_GE-SUPPORT, Priority: High, enhancement

#6243 #5883: Uniform geodesic property setting across plugins
  web/client/actions/annotations.js
  web/client/components/data/query/SpatialFilter.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/mapcontrols/annotations/Annotations.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/epics/annotations.js
Labels: Internal, Priority: Low, enhancement

#6301 #6300 fix layer info when layer name has changed
  web/client/epics/__tests__/layerinfo-test.js
  web/client/epics/layerinfo.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug

#6298 #6291: Small issue in measure panel while editing a measure annotation
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/measurement.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, enhancement

#6303 #6282: Annotation visibility sync fix
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/__tests__/measurement-test.js
  web/client/actions/annotations.js
  web/client/actions/measurement.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/__tests__/MeasureComponent-test.jsx
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/__tests__/measurement-test.jsx
  web/client/epics/annotations.js
  web/client/epics/measurement.js
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/measurement.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug, enhancement

#6232 #4150: Enable the Identify tool for Map widgets in dashboards
  web/client/components/common/MapInfoViewer.jsx
  web/client/components/common/enhancers/withIdentifyPopup.jsx
  web/client/components/geostory/common/MapView.jsx
  web/client/components/widgets/builder/wizard/map/Toolbar.jsx
  web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js
  web/client/components/widgets/widget/MapView.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/__tests__/MapWidget-test.jsx
  web/client/plugins/widgetbuilder/MapSelector.jsx
  web/client/plugins/widgetbuilder/commons.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C040-2020-COMUNE_GE-SUPPORT, Dashboard, Priority: Medium, enhancement

#6304 #6103: Full screen widgets
  web/client/components/dashboard/Dashboard.jsx
  web/client/themes/default/less/dashboard.less
Labels: BackportNeeded, C040-2020-COMUNE_GE-SUPPORT, Priority: High, bug

#6311 [Backport for 2021.01.xx]: #6103 Full screen widgets
  web/client/components/dashboard/Dashboard.jsx
  web/client/themes/default/less/dashboard.less
Labels: Backport, C040-2020-COMUNE_GE-SUPPORT, Priority: High, bug

#6249 #6197: Style list can not be loaded from this service
  web/client/epics/__tests__/styleeditor-test.js
  web/client/epics/styleeditor.js
Labels: BackportNeeded, bug

#6280 Webpack 5 - Module Federation for extension
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/extensionsWithPlugin.json
  backend/src/test/resources/index.js
  backend/src/test/resources/invalid.zip
  backend/src/test/resources/plugin.zip
  build/buildConfig.js
  build/createExtensionWebpackConfig.js
  build/extensions/app.jsx
  build/extensions/bundle/index.json
  build/extensions/bundle/translations/data.en-US.json
  build/extensions/bundle/translations/data.it-IT.json
  build/extensions/components/Extension.jsx
  build/extensions/extensions.js
  build/extensions/index.html
  build/extensions/plugins.js
  build/extensions/plugins/SampleExtension.jsx
  build/extensions/prod-webpack.config.js
  build/extensions/webpack.config.js
  build/moduleFederation.js
  build/prod-webpack.config.js
  build/testConfig.js
  build/webpack.config.js
  docs/developer-guide/application-tutorial.md
  docs/developer-guide/extensions.md
  docs/developer-guide/mapstore-migration-guide.md
  package.json
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
  utility/projects/projectScripts.json
  web/client/components/app/__tests__/withExtensions-test.jsx
  web/client/components/app/withExtensions.js
  web/client/components/contextcreator/__tests__/ConfigurePluginsStep-test.jsx
  web/client/components/import/dragZone/enhancers/__tests__/testData.js
  web/client/components/map/leaflet/overview.css
  web/client/test-resources/extension.zip
  web/client/test-resources/extensions/myextension.js
  web/client/test-resources/extensions/myplugin.zip
  web/client/test-resources/extensions/myplugin_no_plugin.zip
  web/client/test-resources/extensions/myplugin_too_many_bundles.zip
  web/client/test-resources/extensions/myplugin_wrong_json.zip
  web/client/test-resources/extensions/otherextension.js
  web/client/utils/ExtensionsUtils.js
  web/client/utils/MarkerUtils.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/ExtensionsUtils-test.js
  web/client/utils/__tests__/PluginsUtils-test.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: AppContext, BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker

#6317 #6308: attempt to solve memory issues
  build/buildConfig.js
  build/moduleFederation.js
  web/client/utils/MarkerUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/MarkerUtils-test.js
Labels: BackportNeeded, Priority: High

#6309 #6305: Map size doesn't fit the new widget size
  web/client/components/misc/enhancers/withResizeSpy.js
Labels: BackportNeeded, Dashboard, Internal, Priority: Blocker, bug

#6320 [Backport 2021.01.xx] #6308: WepPack 5 and module federation
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/extensionsWithPlugin.json
  backend/src/test/resources/index.js
  backend/src/test/resources/invalid.zip
  backend/src/test/resources/plugin.zip
  build/buildConfig.js
  build/createExtensionWebpackConfig.js
  build/extensions/app.jsx
  build/extensions/bundle/index.json
  build/extensions/bundle/translations/data.en-US.json
  build/extensions/bundle/translations/data.it-IT.json
  build/extensions/components/Extension.jsx
  build/extensions/extensions.js
  build/extensions/index.html
  build/extensions/plugins.js
  build/extensions/plugins/SampleExtension.jsx
  build/extensions/prod-webpack.config.js
  build/extensions/webpack.config.js
  build/moduleFederation.js
  build/prod-webpack.config.js
  build/testConfig.js
  build/webpack.config.js
  docs/developer-guide/application-tutorial.md
  docs/developer-guide/extensions.md
  docs/developer-guide/mapstore-migration-guide.md
  package.json
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
  utility/projects/projectScripts.json
  web/client/components/app/__tests__/withExtensions-test.jsx
  web/client/components/app/withExtensions.js
  web/client/components/contextcreator/__tests__/ConfigurePluginsStep-test.jsx
  web/client/components/import/dragZone/enhancers/__tests__/testData.js
  web/client/components/map/leaflet/overview.css
  web/client/test-resources/extension.zip
  web/client/test-resources/extensions/myextension.js
  web/client/test-resources/extensions/myplugin.zip
  web/client/test-resources/extensions/myplugin_no_plugin.zip
  web/client/test-resources/extensions/myplugin_too_many_bundles.zip
  web/client/test-resources/extensions/myplugin_wrong_json.zip
  web/client/test-resources/extensions/otherextension.js
  web/client/utils/ExtensionsUtils.js
  web/client/utils/MarkerUtils.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
  web/client/utils/__tests__/ExtensionsUtils-test.js
  web/client/utils/__tests__/MarkerUtils-test.js
  web/client/utils/__tests__/PluginsUtils-test.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: AppContext, Backport, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker

#6323 [Backport for 2021.01.xx]: #6305: Map size doesn't fit the new widget size
  web/client/components/misc/enhancers/withResizeSpy.js
Labels: Backport, Dashboard, Internal, Priority: Blocker, bug

#6319 #6318: Shape upload polygon fill opacity fix
  web/client/components/map/openlayers/LegacyVectorStyle.js
  web/client/components/map/openlayers/__tests__/LegacyVectorStyle-test.js
Labels: BackportNeeded, C039-2020-HALLIBURTON-Quickplates, bug

#6324 [Backport for 2021.01.xx]: #6318: Shape upload polygon fill opacity fix
  web/client/components/map/openlayers/LegacyVectorStyle.js
  web/client/components/map/openlayers/__tests__/LegacyVectorStyle-test.js
Labels: Backport, C039-2020-HALLIBURTON-Quickplates, bug

#6327 Fix back-end resources service
  backend/pom.xml
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/TestUtils.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/style.css
  backend/src/test/resources/test.jpg
  backend/src/test/resources/test.png
Labels: BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker, bug

#6329 [Backport 2021.01.xx] #6326: Fix back-end resources service (#6327)
  backend/pom.xml
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/TestUtils.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  backend/src/test/resources/style.css
  backend/src/test/resources/test.jpg
  backend/src/test/resources/test.png
Labels: Backport, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker, bug

#6332 https://github.com/geosolutions-it/internal/issues/61: prevent loadin…
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  web/pom.xml
Labels: BackportNeeded

#6325 #6321 fix editing of features with "type" in properties that was causing problems
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV, bug

#6334 Backport to 2021.01.xx - #6321 fix editing of features with "type" in properties that was causing problems (#6325)
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: Backport

#6261 New Charts features for Widgets section
  docs/user-guide/img/button/autoscale_chart.jpg
  docs/user-guide/img/button/download_png.jpg
  docs/user-guide/img/button/pan_chart.jpg
  docs/user-guide/img/button/reset_axes_chart.jpg
  docs/user-guide/img/button/toggle_lines_chart.jpg
  docs/user-guide/img/button/zoom_chart.jpg
  docs/user-guide/img/button/zoom_in_chart.jpg
  docs/user-guide/img/button/zoom_out_chart.jpg
  docs/user-guide/img/widgets/advanced_options.jpg
  docs/user-guide/img/widgets/bar_charts.jpg
  docs/user-guide/img/widgets/chart-ex.jpg
  docs/user-guide/img/widgets/chart-types.jpg
  docs/user-guide/img/widgets/configure-chart.jpg
  docs/user-guide/img/widgets/label_tooltips.gif
  docs/user-guide/img/widgets/legend_name.jpg
  docs/user-guide/img/widgets/widget-info.jpg
  docs/user-guide/img/widgets/xaxis_options.jpg
  docs/user-guide/img/widgets/yaxis_options.jpg
  docs/user-guide/widgets.md
Labels: BackportNeeded, C117-UNESCO-2019-GEONODE, Documentation, User Guide

#6059 Table of Contents section
  docs/user-guide/img/button/compare_tool_button.jpg
  docs/user-guide/img/button/configure_button.jpg
  docs/user-guide/img/button/dropdown_menu_button.jpg
  docs/user-guide/img/button/spy_button.jpg
  docs/user-guide/img/button/swipe_button.jpg
  docs/user-guide/img/toc/layer-toolbar.jpg
  docs/user-guide/img/toc/spy_on_map.jpg
  docs/user-guide/img/toc/swipe_on_map.jpg
  docs/user-guide/toc.md
Labels: BackportNeeded, Documentation, User Guide

#6160 Text Editor Toolbar section
  docs/user-guide/img/text-editor-toolbar/hyperlink_menu.jpg
  docs/user-guide/text-editor-toolbar.md
Labels: BackportNeeded, C039-2020-HALLIBURTON-SUPPORT, Documentation, GeoStory, User Guide

#6040 Layer Settings, Catalog Services and Adding Annotations sections
  docs/user-guide/annotations.md
  docs/user-guide/catalog.md
  docs/user-guide/img/button/add_fill_button.jpg
  docs/user-guide/img/button/add_icon_button.jpg
  docs/user-guide/img/button/add_line_button.jpg
  docs/user-guide/img/button/add_mark_button.jpg
  docs/user-guide/img/button/add_text_button.jpg
  docs/user-guide/img/button/classification_style_button.jpg
  docs/user-guide/img/button/filter_white_button.jpg
  docs/user-guide/img/button/options_button.jpg
  docs/user-guide/img/button/pattern_icon_style_button.jpg
  docs/user-guide/img/button/pattern_mark_style_button.jpg
  docs/user-guide/img/button/scale_denominator_button.jpg
  docs/user-guide/img/button/visual_editor_style_button.jpg
  docs/user-guide/img/catalog/advanced_settings.jpg
  docs/user-guide/img/layer-settings/classification_styl_panel.jpg
  docs/user-guide/img/layer-settings/classification_style_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_style_panel.jpg
  docs/user-guide/img/layer-settings/classify_mark_ex.jpg
  docs/user-guide/img/layer-settings/classify_mark_panel.jpg
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/img/layer-settings/ex_fill_style.gif
  docs/user-guide/img/layer-settings/ex_line_style.gif
  docs/user-guide/img/layer-settings/ex_text_style.gif
  docs/user-guide/img/layer-settings/filter_builder.jpg
  docs/user-guide/img/layer-settings/icon_panel.jpg
  docs/user-guide/img/layer-settings/line_panel.jpg
  docs/user-guide/img/layer-settings/mark_panel.jpg
  docs/user-guide/img/layer-settings/mark_style_ex.jpg
  docs/user-guide/img/layer-settings/scale_denominator_filter.jpg
  docs/user-guide/img/layer-settings/style_options.jpg
  docs/user-guide/img/layer-settings/text_panel.jpg
  docs/user-guide/img/layer-settings/visual_editor_style.jpg
  docs/user-guide/layer-settings.md
Labels: BackportNeeded, Documentation, Priority: High, User Guide

#6218 Attribute Table and Filtering layers sections
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/drawing-line-shape.gif
  docs/user-guide/img/attributes-table/drawing-point-shape.gif
  docs/user-guide/img/attributes-table/drawing-polygon-shape.gif
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/missing-geometry.jpg
  docs/user-guide/img/attributes-table/multiple_features.gif
  docs/user-guide/img/attributes-table/show_hide_columns.gif
  docs/user-guide/img/attributes-table/update-polygon-shape.gif
  docs/user-guide/img/button/customize_attribute_table.jpg
  docs/user-guide/img/button/download_attribute_table.jpg
  docs/user-guide/img/button/export_data.jpg
  docs/user-guide/img/filtering-layers/filter_geometries.gif
  docs/user-guide/img/filtering-layers/filter_geometry.gif
  docs/user-guide/img/home-page/filter_geometry.gif
Labels: BackportNeeded, C155-IBF-2020-MeteoBlue, Documentation, User Guide

#6337 [Backport for 2021.01.xx]: #6197: Style list can not be loaded from this service
  web/client/epics/__tests__/styleeditor-test.js
  web/client/epics/styleeditor.js
Labels: Backport, bug

#6336 Backport of https://github.com/geosolutions-it/internal/issues/61: pr…
  backend/src/main/java/it/geosolutions/mapstore/ConfigController.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  web/pom.xml
Labels: Backport, C169-Rennes-Métropole-2019-GeOrchestra

#6315 feat: #6102 support for multiple string and number values in attribute filter
  web/client/components/data/featuregrid/filterRenderers/NumberFilter.jsx
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: BackportNeeded, C040-2020-COMUNE_GE-SUPPORT, Priority: Medium, enhancement

#6341 #6338 - fix thematic layer color ramps not applied correctly
  web/client/api/SLDService.js
  web/client/api/__tests__/SLDService-test.js
Labels: BackportNeeded, C040-2020-COMUNE_GE-SUPPORT, bug

#6345 Backport 2021.01.xx - #6338 - fix thematic layer color ramps not applied correctly (#6341)
  web/client/api/SLDService.js
  web/client/api/__tests__/SLDService-test.js
Labels: Backport, C040-2020-COMUNE_GE-SUPPORT

#6348 Fix directory traversal with no data dir set
  backend/src/main/java/it/geosolutions/mapstore/utils/ResourceUtils.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/utils/ResourceUtilsTest.java
Labels: BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker

#6347 Backport 2021.01.xx - #6102: support for multiple string and number values in attribute filter (#6315)
  web/client/components/data/featuregrid/filterRenderers/NumberFilter.jsx
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: Backport, C040-2020-COMUNE_GE-SUPPORT

#6344 [Backport for 2021.01.xx]: #5947: User Guide - Update on Interactions in the GeoStory sections
  docs/user-guide/text-editor-toolbar.md
Labels: Backport, C039-2020-HALLIBURTON-SUPPORT, User Guide

#6349 [Backport 2021.01.xx] Backport #6348 + Minor release for backend fixes
  backend/pom.xml
  backend/src/main/java/it/geosolutions/mapstore/utils/ResourceUtils.java
  backend/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  backend/src/test/java/it/geosolutions/mapstore/utils/ResourceUtilsTest.java
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
  web/pom.xml
Labels: Backport, C169-Rennes-Métropole-2019-GeOrchestra, Priority: Blocker

#6351 [Backport for 2021.01.xx]: #6131: User Guide - Update the Attribute Table section
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/drawing-line-shape.gif
  docs/user-guide/img/attributes-table/drawing-point-shape.gif
  docs/user-guide/img/attributes-table/drawing-polygon-shape.gif
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/missing-geometry.jpg
  docs/user-guide/img/attributes-table/multiple_features.gif
  docs/user-guide/img/attributes-table/show_hide_columns.gif
  docs/user-guide/img/attributes-table/update-polygon-shape.gif
  docs/user-guide/img/button/customize_attribute_table.jpg
  docs/user-guide/img/button/download_attribute_table.jpg
  docs/user-guide/img/button/export_data.jpg
  docs/user-guide/img/filtering-layers/filter_geometries.gif
  docs/user-guide/img/filtering-layers/filter_geometry.gif
  docs/user-guide/img/home-page/filter_geometry.gif
Labels: Backport, C155-IBF-2020-MeteoBlue, Documentation, User Guide

#6343 [Backport for 2021.01.xx]: #6219: User Guide - Update the Widgets section with new charts features
  docs/user-guide/img/button/autoscale_chart.jpg
  docs/user-guide/img/button/download_png.jpg
  docs/user-guide/img/button/pan_chart.jpg
  docs/user-guide/img/button/reset_axes_chart.jpg
  docs/user-guide/img/button/toggle_lines_chart.jpg
  docs/user-guide/img/button/zoom_chart.jpg
  docs/user-guide/img/button/zoom_in_chart.jpg
  docs/user-guide/img/button/zoom_out_chart.jpg
  docs/user-guide/img/widgets/advanced_options.jpg
  docs/user-guide/img/widgets/bar_charts.jpg
  docs/user-guide/img/widgets/chart-ex.jpg
  docs/user-guide/img/widgets/chart-types.jpg
  docs/user-guide/img/widgets/configure-chart.jpg
  docs/user-guide/img/widgets/label_tooltips.gif
  docs/user-guide/img/widgets/legend_name.jpg
  docs/user-guide/img/widgets/widget-info.jpg
  docs/user-guide/img/widgets/xaxis_options.jpg
  docs/user-guide/img/widgets/yaxis_options.jpg
  docs/user-guide/widgets.md
Labels: Backport, C117-UNESCO-2019-GEONODE, Documentation, User Guide

#6353 [Backport for 2021.01.xx]: #5887: User Guide - Exploring Maps section updating
  docs/user-guide/annotations.md
  docs/user-guide/catalog.md
  docs/user-guide/img/button/add_fill_button.jpg
  docs/user-guide/img/button/add_icon_button.jpg
  docs/user-guide/img/button/add_line_button.jpg
  docs/user-guide/img/button/add_mark_button.jpg
  docs/user-guide/img/button/add_text_button.jpg
  docs/user-guide/img/button/filter_white_button.jpg
  docs/user-guide/img/button/options_button.jpg
  docs/user-guide/img/button/scale_denominator_button.jpg
  docs/user-guide/img/button/visual_editor_style_button.jpg
  docs/user-guide/img/catalog/advanced_settings.jpg
  docs/user-guide/img/layer-settings/classification_styl_panel.jpg
  docs/user-guide/img/layer-settings/classification_style_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_style_panel.jpg
  docs/user-guide/img/layer-settings/classify_mark_ex.jpg
  docs/user-guide/img/layer-settings/classify_mark_panel.jpg
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/img/layer-settings/ex_fill_style.gif
  docs/user-guide/img/layer-settings/ex_line_style.gif
  docs/user-guide/img/layer-settings/ex_text_style.gif
  docs/user-guide/img/layer-settings/filter_builder.jpg
  docs/user-guide/img/layer-settings/icon_panel.jpg
  docs/user-guide/img/layer-settings/line_panel.jpg
  docs/user-guide/img/layer-settings/mark_panel.jpg
  docs/user-guide/img/layer-settings/mark_style_ex.jpg
  docs/user-guide/img/layer-settings/scale_denominator_filter.jpg
  docs/user-guide/img/layer-settings/style_options.jpg
  docs/user-guide/img/layer-settings/text_panel.jpg
  docs/user-guide/img/layer-settings/visual_editor_style.jpg
  docs/user-guide/layer-settings.md
Labels: Backport, Documentation, User Guide

#6355 [Backport for 2021.01.xx]: #6048: User Guide - MapSwipe tool
  docs/user-guide/img/button/compare_tool_button.jpg
  docs/user-guide/img/button/configure_button.jpg
  docs/user-guide/img/button/dropdown_menu_button.jpg
  docs/user-guide/img/button/spy_button.jpg
  docs/user-guide/img/button/swipe_button.jpg
  docs/user-guide/img/toc/layer-toolbar.jpg
  docs/user-guide/img/toc/spy_on_map.jpg
  docs/user-guide/img/toc/swipe_on_map.jpg
  docs/user-guide/toc.md
Labels: Backport, Documentation, User Guide
