Repository geosolutions-it/MapStore2, pull requests merged in 2020-07, with the labels that each got.

#5568 #5567 - fix translations of geostory
  web/client/components/mediaEditor/MediaEditor.jsx
  web/client/reducers/mediaEditor.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, Priority: High

#5570 Backport 2020.02.xx - #5567 - fix translations of geostory #5568
  web/client/components/mediaEditor/MediaEditor.jsx
  web/client/reducers/mediaEditor.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, Priority: High

#5587 #5583 fix about window on small screens & make it draggable
  web/client/product/components/viewer/about/About.jsx
  web/client/themes/default/less/panels.less
Labels: BackportNeeded, Priority: Blocker, bug

#5586 backport 2020.02.xx - #5581 update binary for stable branch
  release/data/geostore.h2.db
Labels: Backport, Priority: Blocker, bug

#5593 #5588 show details in featured card
  web/client/components/maps/enhancers/__tests__/featuredMaps-test.jsx
  web/client/components/maps/enhancers/featuredMaps.js
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/test-resources/geostore/extjs/search/list
Labels: BackportNeeded, Priority: Blocker, bug

#5585 #5581 update db for binary on master branch
  release/data/geostore.h2.db
Labels: Priority: Blocker, bug

#5591 #5590: Excluded edit button from context editor map identify tool
  web/client/components/contextcreator/ContextCreator.jsx
Labels: BackportNeeded, bug

#5595 Backport 2020.02.xx - #5588 show details in featured card (#5593)
  web/client/components/maps/enhancers/__tests__/featuredMaps-test.jsx
  web/client/components/maps/enhancers/featuredMaps.js
  web/client/components/maps/modals/MetadataModal.jsx
  web/client/test-resources/geostore/extjs/search/list
Labels: Backport

#5594 #5590: [Backport] Excluded edit button from context editor map identify tool (#5591)
  web/client/components/contextcreator/ContextCreator.jsx
Labels: Backport

#5589 #5582 - Fix scroll made by tutorial inside map viewer
  web/client/components/tutorial/Tutorial.jsx
  web/client/plugins/Tutorial.jsx
Labels: BackportNeeded, Priority: Blocker, bug

#5597 Backport 2020.02.xx - #5582 - Fix scroll made by tutorial inside map viewer (#5589)
  web/client/components/tutorial/Tutorial.jsx
  web/client/plugins/Tutorial.jsx
Labels: Backport

#5596 Backport 2020.02.xx - #5583 fix about window on small screens & make it draggable (#5587)
  web/client/product/components/viewer/about/About.jsx
  web/client/themes/default/less/panels.less
Labels: Backport

#5598 #5588 details can be added also from section contents of map cards
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: BackportNeeded

#5599 Backport 2020.02.xx - #5588 details can be added also from section contents of map cards (#5598)
  web/client/epics/__tests__/maps-test.js
  web/client/epics/maps.js
Labels: Backport

#5609 [2020.02.xx] #3688: json-patch format overrides support for dynamically loaded configuration files (#5266)
  backend/src/main/java/it/geosolutions/mapstore/UploadPluginController.java
  backend/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
Labels: Backport

#5550 German wording corrections
  web/client/translations/data.de-DE.json
Labels: Project: C125

#5480 Fix #5467 MapTemplate Issue
  web/client/epics/maptemplates.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: BackportNeeded, Priority: High, bug

#5617 Fix 5616 Color picker does not update the target container node
  web/client/components/style/ColorPicker.jsx
  web/client/components/style/__tests__/ColorPiker-test.jsx
  web/client/components/styleeditor/FilterBuilder.jsx
  web/client/components/styleeditor/Popover.jsx
  web/client/components/styleeditor/ScaleDenominator.jsx
  web/client/components/styleeditor/__tests__/Popover-test.jsx
Labels: Priority: High, StyleEditor, bug

#5630 #5629 - Fix problems with localized groups
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Project: C028

#5631 Backport 2020.02.xx Porting #5629 groups localized 2020 02 xx (#5630)
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Backport, Project: C028

#5632 Backport 2020.01.xx - Porting #5629 groups localized (#5630)
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
  web/client/utils/LayersUtils.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: Backport, Project: C028

#5634 #5633 - Geodesic circles are edited accordingly from QueryPanel
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: BackportNeeded, Project: C028, bug

#5635 Backport 2020.02.xx - #5633 - Geodesic circles are edited accordingly from QueryPanel (#5634)
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: Backport, Project: C028, bug

#5636 Backport 2020.01.xx - #5633 - Geodesic circles are edited accordingly from QueryPanel (#5634)
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: Backport, Project: C028, bug

#5642 #5641: Thematic layer not added when the layer is not wfs
  web/client/plugins/ThematicLayer.jsx
  web/client/plugins/tocitemssettings/__tests__/deafaultSettingsTabs-test.js
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
Labels: BackportNeeded, bug

#5643 #5641: Thematic layer not added when the layer is not wfs (#5642)
  web/client/plugins/ThematicLayer.jsx
  web/client/plugins/tocitemssettings/__tests__/deafaultSettingsTabs-test.js
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
Labels: Backport, bug

#5645 #5644 Fixed elevation activation regression
  web/client/plugins/Map.jsx
  web/client/plugins/map/__tests__/selector-test.jsx
  web/client/plugins/map/selector.js
  web/client/selectors/map.js
Labels: BackportNeeded, bug

#5647 #5644 Fixed elevation activation regression (#5645)
  web/client/plugins/Map.jsx
  web/client/plugins/map/__tests__/selector-test.jsx
  web/client/plugins/map/selector.js
  web/client/selectors/map.js
Labels: Backport

#5640 Backport 2020.02.xx - Fix #5512. add object handler extractTileMatrixFromSources #5546
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: AppContext, Backport, Priority: High, bug

#5655 Backport #5543 to 2020.02.xx
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/__tests__/MeasurementSupport-test.jsx
Labels: Backport

#5541 5515. fix wrong group name toc from localconfig
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Priority: High, bug

#5606 #5505. add MapExport plugin
  web/client/components/contextcreator/ContextCreator.jsx
Labels: BackportNeeded, Priority: Low, enhancement

#5579 #5353 improve featuregrid toolbar doc
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/plugins/FeatureGrid.jsx
Labels: BackportNeeded, Documentation

#5614 #5611 crs selector translations
  web/client/components/mapcontrols/crsselectormenu/CrsSelectorMenu.jsx
  web/client/plugins/CRSSelector.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: BackportNeeded, enhancement

#5652 Extensions section on Dev guide index
  mkdocs.yml
Labels: BackportNeeded, Dev Guide, Documentation

#5637 #5569 add story section URL
  web/client/actions/__tests__/geostory-test.js
  web/client/actions/geostory.js
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/localConfig.json
  web/client/plugins/Share.jsx
  web/client/product/appConfig.js
  web/client/product/pages/GeoStory.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: BackportNeeded, GeoStory, Priority: High, Project: C039, enhancement

#5659 #5615 fixed CRSSelector bug by holding a state in MousePosition.jsx
  web/client/plugins/MousePosition.jsx
Labels: BackportNeeded, Good first issue, Priority: High, bug, user feedback

#5664 Backport 2020.02.xx - #5651 Extensions section on Dev guide index (#5652)
  mkdocs.yml
Labels: Backport

#5661 Backport 2020.02.xx - #5611 crs selector translations (#5614)
  web/client/components/mapcontrols/crsselectormenu/CrsSelectorMenu.jsx
  web/client/plugins/CRSSelector.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: Backport

#5662 Backport 2020.02.xx - #5515 Wrong group name in TOC
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Backport, Priority: High, bug

#5663 Backport 2020.02.xx - #5505 Export Tool for app context wizard (#5606)
  web/client/components/contextcreator/ContextCreator.jsx
Labels: Backport, Priority: Low, enhancement

#5670 Backport 2020.02.xx - #5615 Mouse CRS selector issue
  web/client/plugins/MousePosition.jsx
Labels: Backport, Good first issue, Priority: High, bug, user feedback

#5605 #5510. Console error while opening Context list
  web/client/plugins/manager/ManagerMenu.jsx
Labels: AppContext, BackportNeeded, Priority: Medium, bug

#5639 #5638 Circle steps now uses the right number of decimals
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/data/query/__tests__/GeometryDetails-test.jsx
Labels: BackportNeeded, Priority: High, Project: C028, bug

#5668 Backport 2020.02.xx - #5569 add story section URL (#5637)
  web/client/actions/__tests__/geostory-test.js
  web/client/actions/geostory.js
  web/client/components/geostory/navigation/Navigation.jsx
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/localConfig.json
  web/client/plugins/Share.jsx
  web/client/product/appConfig.js
  web/client/product/pages/GeoStory.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: Backport, GeoStory, Priority: High, Project: C039, enhancement

#5676 #5674. Add documentation to configure local environment with Tomcat
  docs/developer-guide/developing.md
Labels: BackportNeeded, Documentation, Priority: High

#5612 #5519. add merged options for setSelectedMethods
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/epics/wfsdownload.js
Labels: BackportNeeded, Priority: Low, bug

#5673 #4875. Improve WMTS multidim URL recognition
  web/client/api/MultiDim.js
  web/client/api/__tests__/MultiDim-test.js
  web/client/epics/dimension.js
Labels: BackportNeeded, Priority: Medium, bug

#5684 [Backport] #4875. Improve WMTS multidim URL recognition (#5673)
  web/client/api/MultiDim.js
  web/client/api/__tests__/MultiDim-test.js
  web/client/epics/dimension.js
Labels: Backport

#5675 Backport 2020.02.xx - #5510 Console error while opening Context list (#5605)
  web/client/plugins/manager/ManagerMenu.jsx
Labels: AppContext, Backport, Priority: Medium, bug

#5682 Tiny change in markdown syntax: Newline required for list
  docs/developer-guide/mapstore-projects.md
Labels: Documentation

#5665 Fix 5646 Number inputs are not customizable in the classification style
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/api/__tests__/classifyRaterResponse.json
  web/client/api/__tests__/classifyVectorResponse.json
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/PropertyField.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: Priority: High, Project: C183, StyleEditor, bug

#5688 Backport 2020.02.xx - #5519. WFS Download formats are not properly matching (#5612)
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/epics/wfsdownload.js
Labels: Backport, Priority: Low, bug

#5693 [Backport] #4686 add message on error dashboard editor (#5393)
  web/client/components/catalog/CompactCatalog.jsx
Labels: Backport

#5686 #5685: Include pluginsConfig in standard project template
  project/standard/templates/pluginsConfig.json
Labels: BackportNeeded, bug

#5678 Backport 2020.02.xx - #5676 Add documentation to configure local environment with Tomcat
  docs/developer-guide/developing.md
Labels: Backport

#5692 #5575 removed GeometryCollection creation for MultiPoint features
  web/client/components/map/openlayers/DrawSupport.jsx
Labels: BackportNeeded, Priority: High, bug

#5694 Backport 2020.02.xx - #5685: Include pluginsConfig in standard project template (#5686)
  project/standard/templates/pluginsConfig.json
Labels: Backport

#5534 5506. add page reload if location the same. 5503. Issue with Map Catalog
  web/client/components/mapcatalog/MapCatalogPanel.jsx
  web/client/components/mapcatalog/__tests__/MapCatalogPanel-test.jsx
  web/client/plugins/MapCatalog.jsx
Labels: AppContext, BackportNeeded, Priority: High, bug

#5679 #5654 Undescore is not allowed for User password
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/manager/users/__tests__/UserDialog-test.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: BackportNeeded, Good first issue, Priority: High, bug

#5697 Plugins howto minor improvents
  docs/developer-guide/plugins-howto.md
Labels: BackportNeeded

#5700 Backport 2020.02.xx - #5506 add page reload if location the same. #5503 Issue with Map Catalog (#5534)
  web/client/components/mapcatalog/MapCatalogPanel.jsx
  web/client/components/mapcatalog/__tests__/MapCatalogPanel-test.jsx
  web/client/plugins/MapCatalog.jsx
Labels: AppContext, Backport, Priority: High, bug

#5696 Backport 2020.02.xx - #5575 removed GeometryCollection creation for MultiPoint features
  web/client/components/map/openlayers/DrawSupport.jsx
Labels: Backport, Priority: High, bug

#5687 Stories- Media content - Map #5592
  web/client/themes/default/less/modal.less
Labels: BackportNeeded, GeoStory, Priority: High, bug

#5683 #5569. shareUrl parsing fixed
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/utils/GeoStoryUtils.js
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: BackportNeeded, GeoStory, Priority: High, Project: C039, enhancement

#5706 Backport 2020 02 xx - #5592 Stories- Media content - Map
  web/client/themes/default/less/modal.less
Labels: Backport, GeoStory, Priority: High, bug

#5705 Fix the print icon on User Guide
  docs/user-guide/img/button/print-button.JPG
  docs/user-guide/img/button/print_button.jpg
  docs/user-guide/print.md
Labels: BackportNeeded, Documentation, User Guide, bug

#5704 5654 backport 2020 02 xx - #5654 Undescore is not allowed for User password
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/manager/users/__tests__/UserDialog-test.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: Backport, Good first issue, Priority: High, bug

#5708 Backport 2020.02.xx - #5569 add story section URL (#5637) - fixes
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/utils/GeoStoryUtils.js
  web/client/utils/ShareUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
  web/client/utils/__tests__/ShareUtils-test.js
Labels: Backport, GeoStory, Priority: High, Project: C039, enhancement

#5689 MapTemplate plugin should be usable in localConfig (#5564)
  web/client/actions/maptemplates.js
  web/client/epics/__tests__/maptemplates-test.js
  web/client/epics/maptemplates.js
  web/client/plugins/MapTemplates.jsx
  web/client/reducers/maptemplates.js
  web/client/selectors/__tests__/maptemplates-test.js
  web/client/selectors/maptemplates.js
Labels: BackportNeeded, Priority: High, Project: C169, bug, geOrchestra

#5711 Backport 2020 02 xx - #5564: MapTemplate plugin should be usable in localConfig
  web/client/actions/maptemplates.js
  web/client/epics/__tests__/maptemplates-test.js
  web/client/epics/maptemplates.js
  web/client/plugins/MapTemplates.jsx
  web/client/reducers/maptemplates.js
  web/client/selectors/__tests__/maptemplates-test.js
  web/client/selectors/maptemplates.js
Labels: Backport, Priority: High, Project: C169, bug, geOrchestra

#5713 Mobile - Dashboard display problem(#4385)
  web/client/plugins/QueryPanel.jsx
Labels: BackportNeeded, Mobile, Priority: High, bug

#5716 Backport 2020 02 xx - #4385: Mobile - Dashboard display problem
  web/client/plugins/QueryPanel.jsx
Labels: Backport, Mobile, Priority: High, bug

#5710 #5571. add background restoration
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/mediaEditor/MediaModal.jsx
  web/client/plugins/mediaEditor/__tests__/MediaModal-test.jsx
  web/client/reducers/__tests__/mediaEditor-test.js
  web/client/reducers/mediaEditor.js
Labels: BackportNeeded, GeoStory, Priority: Medium, enhancement

#5714 Fix 5681 Add standard deviation method to classfication rule
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/SLDService-test.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/epics/__tests__/styleeditor-test.js
  web/client/epics/styleeditor.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: Project: C183, StyleEditor, enhancement

#5717 Backport 2020.02.xx - #5571 Restore an empty background for Story section (#5710)
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
  web/client/plugins/mediaEditor/MediaModal.jsx
  web/client/plugins/mediaEditor/__tests__/MediaModal-test.jsx
  web/client/reducers/__tests__/mediaEditor-test.js
  web/client/reducers/mediaEditor.js
Labels: Backport, GeoStory, Priority: Medium, enhancement

#5718 #5574. fix navBar geostory selector. update geostory tests
  web/client/components/geostory/builder/__tests__/Builder-test.jsx
  web/client/components/geostory/builder/__tests__/SectionsPreview-test.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/components/geostory/navigation/__tests__/ScrollMenu-test.jsx
  web/client/epics/__tests__/geostory-test.js
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
  web/client/test-resources/geostory/sampleStory_1.json
Labels: GeoStory, Priority: Medium, enhancement
