Repository geosolutions-it/MapStore2, pull requests merged in 2021-06, with the labels that each got.

#6936 #6869 fixes showing empty identify popup window
  web/client/components/data/identify/DefaultViewer.jsx
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#6940 6938: Add toolbar icons are not visible when a GeoStory is empty
  web/client/components/geostory/common/ToolbarPopover.jsx
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, bug, geonode_integration

#6943 [Backport geonode-mapstore-2.1.x]: Add toolbar icons are not visible when a GeoStory is empty #6940
  web/client/components/geostory/common/ToolbarPopover.jsx
Labels: Backport, C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, bug, geonode_integration

#6945 Smal review of doc landing page
  docs/index.md
Labels: Documentation, Priority: Medium, User Guide

#6944 #6941 Fix issue with context manager and user session
  web/client/actions/config.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/config.js
  web/client/epics/contextcreator.js
Labels: C169-Rennes-Métropole-2019-GeOrchestra, bug

#6948 #6946: Update style packages dependencies
  package.json
  web/client/themes/default/bootstrap-theme.less
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/drawer-menu.less
  web/client/themes/default/less/rulesmanager.less
  web/client/themes/default/less/toc.less
  web/client/themes/default/variables.less
Labels: BackportNeeded, C182-SPC-2020-PACIFIC, geonode_integration

#6949 [Backport geonode-mapstore-client-2.1.x] #6946: Update style packages dependencies
  package.json
  web/client/themes/default/bootstrap-theme.less
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/drawer-menu.less
  web/client/themes/default/less/rulesmanager.less
  web/client/themes/default/less/toc.less
  web/client/themes/default/variables.less
Labels: Backport, C182-SPC-2020-PACIFIC, geonode_integration

#6950 [Backport 2021.01.xx] #6941 Fix issue with context manager and user session (#6944)
  web/client/actions/config.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/config.js
  web/client/epics/contextcreator.js
Labels: Backport, C169-Rennes-Métropole-2019-GeOrchestra

#6953 #6951: Custom option in label property of Text Symbolizer freezes the application
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/SelectInput.jsx
  web/client/components/styleeditor/__tests__/SelectInput-test.jsx
Labels: BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV, bug, geonode_integration

#6954 [Backport geonode-mapstore-client-2.1.x] #6951: Custom option in label property of Text Symbolizer freezes the application (#6953)
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/SelectInput.jsx
  web/client/components/styleeditor/__tests__/SelectInput-test.jsx
Labels: Backport, C183-ALMAVIVA-2020-GeoNode-DEV, bug, geonode_integration

#6893 #6892 Fix geometry type bug in wfs layer style panel
  web/client/plugins/tocitemssettings/SimpleVectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/__tests__/deafaultSettingsTabs-test.js
  web/client/plugins/tocitemssettings/__tests__/defaultSettingsTabs-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, Internal, bug

#6966 Backport 2021.01.xx - #6892 Fix geometry type bug in wfs layer style panel (#6893)
  web/client/plugins/tocitemssettings/SimpleVectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/__tests__/deafaultSettingsTabs-test.js
  web/client/plugins/tocitemssettings/__tests__/defaultSettingsTabs-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#6910 Add embedded to local dev environment by default
  build/webpack.config.js
Labels: Internal

#6965 Backport 2021.01.xx - #6874 fix doc url (#6875)
  docs/developer-guide/index.md
Labels: Backport

#6963 #6946: Minor style fixes due to latest less update
  web/client/themes/default/less/geostory.less
  web/client/themes/default/less/maps-properties.less
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/query-panel.less
  web/client/themes/default/less/react-select.less
  web/client/themes/default/less/react-widgets.less
  web/client/themes/default/less/switch.less
  web/client/themes/default/less/switchpanel.less
  web/client/themes/default/less/toc.less
  web/client/themes/default/ms2-theme.less
Labels: C182-SPC-2020-PACIFIC, bug, geonode_integration

#6971 Add link to migration guidelines in project update section
  docs/developer-guide/project-creation-script.md
Labels: Dev Guide, Documentation

#6979 Update mkdocs.yml
  mkdocs.yml
Labels: BackportNeeded, Documentation

#6981 [Backport 2021.01.xx] #6974 Update mkdocs.yml (#6979)
  mkdocs.yml
Labels: Backport

#6959 #6869_identify_popup
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/epics/identify.js
  web/client/product/apiPlugins.js
  web/client/selectors/__tests__/mousePosition-test.js
  web/client/selectors/mousePosition.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#6978 #6890_cesium_credit
  web/client/components/map/cesium/Map.jsx
  web/client/configs/localConfig.json
  web/client/themes/default/less/cesium.less
Labels: Good first issue, Internal, Priority: High, bug

#6973 #6871 - Auto-opening of details panel
  web/client/epics/__tests__/details-test.js
  web/client/epics/details.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#6976 #6970: Resolved URL update issue on geostory.
  web/client/actions/geostory.js
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
Labels: bug

#6985 #6894 Externalize Sync map tool for feature Grid
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/reducers/query.js
  web/client/selectors/__tests__/mousePosition-test.js
  web/client/selectors/mousePosition.js
Labels: BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#6991 backport 2021.01.xx - #6894 Externalize Sync map tool for feature Grid (#6985)
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/reducers/query.js
Labels: Backport, C040-COMUNE_GE-2021-SUPPORT, enhancement

#6994 backport 2021.01.xx - #6871 - Auto-opening of details panel (#6973)
  web/client/epics/__tests__/details-test.js
  web/client/epics/details.js
Labels: Backport, Good first issue, Internal, Priority: High, bug

#6996 #6995 fix build config proxy urls for QA
  build/buildConfig.js
Labels: Backport, bug

#6999 #6833 fix time range
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/dimension.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#7001 #6992 reset to click method for mapInfo
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#7005 backport 2021.01.xx - #6833 fix time range (#6999)
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/dimension.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
Labels: Backport, Good first issue, Internal, Priority: High, bug

#7003 backport 2021.01.xx - #6992 reset to click method for mapInfo (#7001)
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: Backport, Good first issue, Internal, Priority: High, bug

#7004 #6889 background layer
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/plugins/Map.jsx
  web/client/reducers/__tests__/maptype-test.js
  web/client/reducers/maptype.js
  web/client/selectors/__tests__/backgroundselector-test.js
  web/client/selectors/__tests__/maptype-test.js
  web/client/selectors/backgroundselector.js
  web/client/selectors/maptype.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High

#7010 #6889 fix tests for background layers in 3D
  web/client/components/search/__tests__/SearchBarInput-test.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/Map-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/selectors/__tests__/backgroundselector-test.js
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#7009 backport 2021.01.xx - #6889 background layer (#7004)
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/search/__tests__/SearchBarInput-test.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/Map-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/reducers/__tests__/maptype-test.js
  web/client/reducers/maptype.js
  web/client/selectors/__tests__/backgroundselector-test.js
  web/client/selectors/__tests__/maptype-test.js
  web/client/selectors/backgroundselector.js
  web/client/selectors/maptype.js
Labels: Backport, Good first issue, Internal, Priority: High, bug

#7012 Adding github actions for testing
  .github/workflows/tests.yml
Labels: BackportNeeded, Priority: High

#7015 [Backport 2021.01.xx] Adding github actions for testing (#7012, #7016 )
  .github/workflows/tests.yml
Labels: Backport

#7021 attempt to add coveralls to GH tests workflow
  .github/workflows/tests.yml
Labels: BackportNeeded, Environment

#7022 6882: Fix Time filter panel for many dates is not completely visible
  web/client/components/data/query/DateField.jsx
  web/client/themes/default/less/query-panel.less
Labels: Good first issue, Internal, Priority: High, bug

#7025 [Backport 2021.01.xx] #7019: Update README.md (#7023)
  README.md
Labels: Backport

#7024 [Backport 2021.01.xx] #7019 attempt to add coveralls to GH tests workflow (#7021)
  .github/workflows/tests.yml
Labels: Backport

#7008 #6853 Fix crash when using an unescaped template
  web/client/components/data/identify/viewers/TemplateViewer.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/__tests__/TemplateUtils-test.js
Labels: Good first issue, Internal, Priority: High, bug

#7029 backport 2021.01.xx - #6853 Fix crash when using an unescaped template (#7008)
  web/client/components/data/identify/viewers/TemplateViewer.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/__tests__/TemplateUtils-test.js
Labels: Backport, Good first issue, Internal, Priority: High, bug

#7031 #6853 Fix style of pre tag in template gfi
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, Good first issue, Internal, Priority: High, bug

#7030 backport 2021.01.xx - #6853 Fix style of pre tag in template gfi
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#7034 6878: Add documentation for activateRemoveGroup in TOC
  web/client/plugins/TOC.jsx
Labels: Documentation, Good first issue, Internal, Priority: Medium

#7028 6879: Remove floppy save icon
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/__tests__/TOCItemsSettings-test.jsx
  web/client/components/TOC/enhancers/__tests__/tocitemssettings-test.js
  web/client/components/TOC/enhancers/tocItemsSettings.js
Labels: Good first issue, Internal, Priority: Medium, enhancement, geonode_integration

#6969 Add toggle button to switch between visual and code style editors
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/plugins/styleeditor/__tests__/StyleCodeEditor-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, enhancement, geonode_integration

#7041 #6987: Theme switch mechanism/workflow for context pages
  build/buildConfig.js
  package.json
  web/client/components/theme/ContextTheme.jsx
  web/client/components/theme/Theme.jsx
  web/client/components/theme/__tests__/ContextTheme-test.jsx
  web/client/components/theme/__tests__/Theme-test.jsx
  web/client/product/pages/Context.jsx
  web/client/selectors/__tests__/context-test.js
  web/client/selectors/context.js
Labels: AppContext, C124-BRGM-2021-SUPPORT, New Feature, Priority: High
