Repository geosolutions-it/MapStore2, pull requests merged in 2021-09, with the labels that each got.

#7259 Update localConfig.json for QA
  web/client/configs/localConfig.json
Labels: Priority: High

#7255 backport 2021.02.xx - #7111 Prevent marker display when Idenitify is disabled
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/controls-test.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/controls.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  webapps/mapstore/geostore.h2.db
Labels: bug, Priority: High, Internal, Good first issue, Backport

#7270 #7268 improvements for geolocate tool
  web/client/components/mapcontrols/locate/LocateTool.jsx
  web/client/map/leaflet/locate.js
  web/client/plugins/Locate.jsx
  web/client/utils/leaflet/LLocate.js
  web/client/utils/leaflet/__tests__/LLocate-test.js
  web/client/utils/openlayers/OlLocate.js
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7274 Backport 2021.02.xx - #7268 #7185 Geolocation orientation in mobile for OL and Leaflet map (#7264)
  package.json
  web/client/components/mapcontrols/locate/LocateTool.jsx
  web/client/map/leaflet/locate.js
  web/client/map/openlayers/locate.js
  web/client/plugins/Locate.jsx
  web/client/utils/LocateUtils.js
  web/client/utils/leaflet/LLocate.js
  web/client/utils/leaflet/__tests__/LLocate-test.js
  web/client/utils/openlayers/OlLocate.js
  web/client/utils/openlayers/__tests__/OlLocate-test.js
Labels: Priority: Medium, Backport, New Feature, C040-COMUNE_GE-2021-SUPPORT

#7273 Backport 2021.01.xx - #7185 Geolocation orientation in mobile for OL and Leaflet map (#7264)
  package.json
  web/client/components/mapcontrols/locate/LocateTool.jsx
  web/client/map/leaflet/locate.js
  web/client/map/openlayers/locate.js
  web/client/plugins/Locate.jsx
  web/client/utils/LocateUtils.js
  web/client/utils/leaflet/LLocate.js
  web/client/utils/leaflet/__tests__/LLocate-test.js
  web/client/utils/openlayers/OlLocate.js
  web/client/utils/openlayers/__tests__/OlLocate-test.js
Labels: Priority: Medium, Backport, New Feature, C040-COMUNE_GE-2021-SUPPORT

#7275 Update maps-configuration.md
  docs/developer-guide/maps-configuration.md
  web/client/api.html
  web/client/apiTemplate.html
  web/client/dashboard-embedded-template.html
  web/client/dashboard-embedded.html
  web/client/embedded.html
  web/client/embeddedTemplate.html
  web/client/geostory-embedded-template.html
  web/client/geostory-embedded.html
  web/client/index.html
  web/client/indexTemplate.html
  web/client/simple.html
Labels: Priority: Medium, Documentation, Dev Guide, BackportNeeded

#7101 Theme and Edit Style options on User Guide
  docs/user-guide/application-context.md
  docs/user-guide/img/application-context/color_picker_theme.gif
  docs/user-guide/img/application-context/custom_variables.jpg
  docs/user-guide/img/application-context/cutom_context.jpg
  docs/user-guide/img/application-context/dark_context.jpg
  docs/user-guide/img/application-context/dark_theme.jpg
  docs/user-guide/img/application-context/default_theme.jpg
  docs/user-guide/img/application-context/es_steptwo.jpg
  docs/user-guide/img/application-context/extension-in-out.gif
  docs/user-guide/img/application-context/extensions-in-out.gif
  docs/user-guide/img/application-context/step_four.jpg
  docs/user-guide/img/application-context/stepone.jpg
  docs/user-guide/img/application-context/steptwo_part.jpg
  docs/user-guide/img/application-context/wizard.jpg
  docs/user-guide/img/application-context/wizard2.jpg
  docs/user-guide/img/application-context/www.jpg
  docs/user-guide/img/button/save_blue_button.jpg
  docs/user-guide/img/button/visual_editor_style_button.jpg
  docs/user-guide/img/layer-settings/classification_styl_panel.jpg
  docs/user-guide/img/layer-settings/classification_style_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_style_panel.jpg
  docs/user-guide/img/layer-settings/classify_mark_ex.jpg
  docs/user-guide/img/layer-settings/classify_mark_panel.jpg
  docs/user-guide/img/layer-settings/ex_fill_style.gif
  docs/user-guide/img/layer-settings/ex_line_style.gif
  docs/user-guide/img/layer-settings/ex_text_style.gif
  docs/user-guide/img/layer-settings/icon_panel.jpg
  docs/user-guide/img/layer-settings/line_panel.jpg
  docs/user-guide/img/layer-settings/ls-style.jpg
  docs/user-guide/img/layer-settings/mark_panel.jpg
  docs/user-guide/img/layer-settings/mark_style_ex.jpg
  docs/user-guide/img/layer-settings/text_panel.jpg
  docs/user-guide/img/layer-settings/visual_editor_style.jpg
Labels: Documentation, User Guide, C124-BRGM-2021-SUPPORT

#7278 backport 2021.02.xx - #7229 fix problem when only empty data are returned (#7230)
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: bug, Backport, C040-COMUNE_GE-2021-SUPPORT

#7279 Backport 2021.02.xx - #6302 google api doc and disable from html files
  docs/developer-guide/maps-configuration.md
  web/client/api.html
  web/client/apiTemplate.html
  web/client/dashboard-embedded-template.html
  web/client/dashboard-embedded.html
  web/client/embedded.html
  web/client/embeddedTemplate.html
  web/client/geostory-embedded-template.html
  web/client/geostory-embedded.html
  web/client/index.html
  web/client/indexTemplate.html
  web/client/simple.html
Labels: Backport

#7277 Backport 2021.01.xx - #7229 fix problem when only empty data are returned (#7230)
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: bug, Backport, C040-COMUNE_GE-2021-SUPPORT

#7189 #7188: Allow injection of FeatureEditor Toolbar buttons
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/FeatureEditorButton.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/LayerDownload.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/plugins/widgetbuilder/FeatureEditorButton.jsx
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
  web/client/selectors/featuregrid.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: C105-2021-EMSA-CGD

#7257 #5905 Prevent crash when configured background has no source/name
  web/client/components/catalog/RecordItem.jsx
  web/client/components/misc/cardgrids/__tests__/SideCard-test.jsx
Labels: bug, Priority: Medium, Internal, Background selector

#7281 #7280: Fix extensions file name
  java/web/src/main/resources/mapstore.properties
Labels: bug, Priority: Blocker, BackportNeeded

#7267 #7172: migration to GeoStore 1.8-SNAPSHOT to inherit latest spring co…
  docs/developer-guide/developing.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/requirements.md
  docs/quick-start.md
  java/pom.xml
  java/services/pom.xml
  java/services/src/main/java/it/geosolutions/mapstore/controllers/configs/ConfigsController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/LoadAssetsController.java
  java/web/pom.xml
  java/web/src/main/webapp/WEB-INF/web.xml
  package.json
  pom.xml
  product/config/db/geostore-spring-security-db.xml
  product/config/ldap/geostore-spring-security-ldap.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  release/bin-war/pom.xml
  release/pom.xml
  release/tomcat/bin/bootstrap.jar
  release/tomcat/bin/catalina-tasks.xml
  release/tomcat/bin/catalina.bat
  release/tomcat/bin/catalina.sh
  release/tomcat/bin/commons-daemon.jar
  release/tomcat/bin/setclasspath.bat
  release/tomcat/bin/setclasspath.sh
  release/tomcat/bin/tomcat-juli.jar
  release/tomcat/conf/catalina.policy
  release/tomcat/conf/catalina.properties
  release/tomcat/conf/jaspic-providers.xml
  release/tomcat/conf/jaspic-providers.xsd
  release/tomcat/conf/logging.properties
  release/tomcat/conf/server.xml
  release/tomcat/conf/tomcat-users.xml
  release/tomcat/conf/tomcat-users.xsd
  release/tomcat/conf/web.xml
  web/client/api/GeoStoreDAO.js
  web/src/config/db/geostore-spring-security-db.xml
  web/src/config/ldap/geostore-spring-security-ldap.xml
Labels: enhancement, investigation, Priority: High

#7223 Add docker-compose
  Dockerfile
  README.md
  docker-compose.yml
  docker/mapstore.conf
  docker/postgres/01-init-user.sh
  docker/postgres/Dockerfile
  docker/wait-for-postgres.sh
Labels: DevOps

#7282 [Backport 2021.02.xx] #7280: Update mapstore.properties (#7281)
  java/web/src/main/resources/mapstore.properties
Labels: bug, Priority: Blocker, Backport

#7252 #7117: Updated migration guidelines.
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/mapstore-projects.md
  docs/developer-guide/project-creation-script.md
Labels: Documentation, BackportNeeded

#7290 #6302 Prevent google layers in old maps to make mapstore crash
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/GoogleLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/GoogleLayer.js
Labels: bug, Priority: Blocker, BackportNeeded

#7253 #7132: Clean up and sort-up feature editor documentation
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/featuregrid/editors/customEditors.jsx
  web/client/plugins/FeatureEditor.jsx
Labels: Documentation

#7295 #7293 fixes the printing profile build
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: bug, Priority: High, BackportNeeded

#7286 #7172: migration to GeoStore 1.8-SNAPSHOT to inherit latest spring co…
  docs/developer-guide/developing.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/requirements.md
  docs/quick-start.md
  java/pom.xml
  java/services/pom.xml
  java/services/src/main/java/it/geosolutions/mapstore/controllers/configs/ConfigsController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/LoadAssetsController.java
  java/web/pom.xml
  java/web/src/main/webapp/WEB-INF/web.xml
  package.json
  pom.xml
  product/config/db/geostore-spring-security-db.xml
  product/config/ldap/geostore-spring-security-ldap.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  release/bin-war/pom.xml
  release/pom.xml
  release/tomcat/bin/bootstrap.jar
  release/tomcat/bin/catalina-tasks.xml
  release/tomcat/bin/catalina.bat
  release/tomcat/bin/catalina.sh
  release/tomcat/bin/commons-daemon.jar
  release/tomcat/bin/setclasspath.bat
  release/tomcat/bin/setclasspath.sh
  release/tomcat/bin/tomcat-juli.jar
  release/tomcat/conf/catalina.policy
  release/tomcat/conf/catalina.properties
  release/tomcat/conf/jaspic-providers.xml
  release/tomcat/conf/jaspic-providers.xsd
  release/tomcat/conf/logging.properties
  release/tomcat/conf/server.xml
  release/tomcat/conf/tomcat-users.xml
  release/tomcat/conf/tomcat-users.xsd
  release/tomcat/conf/web.xml
  web/client/api/GeoStoreDAO.js
  web/src/config/db/geostore-spring-security-db.xml
  web/src/config/ldap/geostore-spring-security-ldap.xml
Labels: enhancement, Priority: High

#7269 #7090 Fix dropdown that displays uuid instead of labels
  web/client/actions/__tests__/layers-test.js
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/widgets/builder/wizard/map/__tests__/MapOptions-test.jsx
  web/client/selectors/__tests__/layers-test.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue

#7297 [Backport 2021.02.xx] #6302 Prevent google layers in old maps to make mapstore crash (#7290)
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/GoogleLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/GoogleLayer.js
Labels: Backport

#7305 [Backport 2021.02.xx] #5905 Prevent crash when configured background has no source/name
  web/client/components/catalog/RecordItem.jsx
  web/client/components/misc/cardgrids/__tests__/SideCard-test.jsx
Labels: bug, Priority: Medium, Internal, Good first issue, Background selector, Backport

#7291 #7037 Fix group title returning as undefined even though it's present
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue, AppContext

#7299 Fixed and improved TOC documentation
  web/client/plugins/TOC.jsx
Labels: Priority: Low, Documentation, BackportNeeded

#7315 #7314 fix icon style for paged combobox
  web/client/themes/default/less/autocomplete.less
Labels: BackportNeeded

#7316 [Backport 2021.02.xx] Fixed and improved TOC documentation (#7299)
  web/client/plugins/TOC.jsx
Labels: Backport

#7313 backport 2021.02.xx - #7190: Edit feature icon visibility fix (#7222)
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/__tests__/FeatureEditor-test.jsx
Labels: bug, Priority: Medium, Internal, Backport

#7318 [Backport 2021.02.xx] #7314 fix icon style for paged combobox (#7315)
  web/client/themes/default/less/autocomplete.less
Labels: Backport

#7310 #7309 Use only the state of feature grid to define the layer to use in grid
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/wfsquery.js
Labels: enhancement, BackportNeeded

#7323 [Backport 2021.02.xx] #7132: Clean up and sort-up feature editor documentation (#7253)
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/featuregrid/editors/customEditors.jsx
  web/client/plugins/FeatureEditor.jsx
Labels: Documentation, Backport

#7322 [Backport 2021.02.xx] #7117: Updated migration guidelines. (#7252)
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/mapstore-projects.md
  docs/developer-guide/project-creation-script.md
Labels: Documentation, Backport, ms-project

#7327 [Backport 2021.02.xx] #7037 Fix group title returning as undefined even though it's present
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue, Backport, AppContext

#7326 [Backport 2021.02.xx] #7090 abstracted function to replace characters in title
  web/client/actions/__tests__/layers-test.js
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/widgets/builder/wizard/map/__tests__/MapOptions-test.jsx
  web/client/selectors/__tests__/layers-test.js
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#7324 Translation typo fix
  web/client/translations/data.en-US.json
Labels: enhancement, BackportNeeded

#7329 backport 2021.02.xx -#7293: fixes the printing profile build (backport)
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: Backport

#7220 #6886: Configurable CSW filters
  docs/developer-guide/local-config.md
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CSWFilters-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Priority: High, Good first issue, BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra

#7311 #7304 Aligned standard template to latest changes
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/configs-servlet.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/extensions-servlet.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/loadAssets-servlet.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
Labels: Priority: Blocker

#7330 [Backport 2021.02.xx] #7082: Map template background duplicate fix (#7212)
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, Priority: High, Good first issue, Background selector, Backport, C169-Rennes-Métropole-2019-GeOrchestra

#7340 #7317 Made default locale loading action environment independent
  web/client/actions/__tests__/locale-test.js
Labels: BackportNeeded

#7341 #7294 loading too many extension crashes
  build/createExtensionWebpackConfig.js
Labels: bug

#7343 [Backport 2021.02.xx] #7294: loading too many extension crashes (#7341)
  build/createExtensionWebpackConfig.js
Labels: bug, Backport

#7333 Update data.sv-SE.json
  web/client/translations/data.sv-SE.json
Labels: BackportNeeded

#7344 [Backport 2021.02.xx] Update data.sv-SE.json (#7333)
  web/client/translations/data.sv-SE.json
Labels: Backport

#7339 Create new dashboard, the warning tooltip is shown for a very short time
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
Labels: bug, BackportNeeded

#7355 #7354 fix geolocation heading with ol
  web/client/map/openlayers/locate.js
Labels: bug, OpenLayers, BackportNeeded

#7356 backport 2021.01.xx - #7354 fix geolocation heading with ol (#7355)
  web/client/map/openlayers/locate.js
Labels: bug, OpenLayers, Backport

#7357 backport 2021.02.xx - #7354 fix geolocation heading with ol (#7355)
  web/client/map/openlayers/locate.js
Labels: bug, OpenLayers, Backport

#7351 [Backport 2021.02.xx] #7335: Create new dashboard, the warning tooltip is shown for a very short time (#7339)
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
Labels: bug, Backport, C182-SPC-2020-PACIFIC

#7352 [Backport 2021.02.xx] #6886: Configurable CSW filters (#7220)
  docs/developer-guide/local-config.md
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CSWFilters-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Priority: High, Good first issue, Backport, C169-Rennes-Métropole-2019-GeOrchestra

#7346 [Backport 2021.02.xx] #7317 Made default locale loading action environment independent (#7340)
  web/client/actions/__tests__/locale-test.js
Labels: Backport

#7360 #7266: Feature editor virtual scroll fix
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/__tests__/FeatureEditor-test.jsx
Labels: bug, Priority: Blocker, Internal, Good first issue

#7300 Add external layer from url via action
  docs/developer-guide/map-query-parameters.md
  web/client/actions/catalog.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
Labels: geOrchestra, New Feature

#7372 [Backport 2021.02.xx] #7266: Feature editor virtual scroll fix (#7360)
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/__tests__/FeatureEditor-test.jsx
Labels: bug, Priority: Blocker, Internal, Good first issue, Backport

#7375 #7231 fix issue with map sync not being active
  web/client/plugins/FeatureEditor.jsx
Labels: bug, Priority: High, Internal, Good first issue, BackportNeeded

#7383 backport 2021.01.xx - #6960: Map error when default_map_backgrounds is missing. (#6968)
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
Labels: Backport

#7387 Issue #7361; feature info selector fixed
  web/client/components/TOC/TOCItemsSettings.jsx
  web/client/utils/TOCUtils.js
  web/client/utils/__tests__/TOCUtils-test.js
Labels: bug, Priority: Blocker
