Repository geosolutions-it/MapStore2, pull requests merged in 2021-11, with the labels that each got.

#7483 backport 2021.02.xx - Update release procedure (#7482)
  docs/developer-guide/release.md
Labels: Documentation, Backport

#7389 #7369: Query tool string notEqualTo operator support
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/GroupField-test.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7397 #7370: enableInfoForSelectedLayers configuration for Identify plugin
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7417 #7368: Horizontal and vertical size for Webpage section in Geostory
  web/client/components/geostory/common/ToolbarDropdownButton.jsx
  web/client/components/geostory/common/__tests__/ToolbarDropdownButton-test.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/contents/__tests__/Column-test.jsx
  web/client/themes/default/less/geostory.less
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7490 #7429: Charts improvement and fixes
  package.json
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
Labels: enhancement, C040-COMUNE_GE-2021-SUPPORT

#7495 #7432 Empty feature grid when switching between layers
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
Labels: bug, Priority: Medium, Internal, Good first issue

#7460 #7459: Async state update on unmounted plugins triggers react warning
  web/client/map/hooks/useMapTool.js
  web/client/plugins/Map.jsx
Labels: enhancement, Priority: High, geonode_integration, BackportNeeded, C182-SPC-2020-PACIFIC

#7436 [Backport 2021.02.xx] #7300 Add external layer from url via action
  docs/developer-guide/map-query-parameters.md
  web/client/actions/catalog.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
Labels: enhancement, geOrchestra, Backport

#7461 #7458: Review the UI and config of feature editor table
  web/client/components/data/featuregrid/Header.jsx
  web/client/components/data/featuregrid/__tests__/Header-test.jsx
  web/client/components/data/featuregrid/toolbars/TButton.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/themes/default/less/react-data-grid.less
Labels: enhancement, Priority: High, geonode_integration, BackportNeeded, C182-SPC-2020-PACIFIC

#7485 #7428 Some typos in the User Session reset
  web/client/epics/__tests__/usersession-test.js
  web/client/epics/usersession.js
Labels: bug, Priority: High, Good first issue, BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra

#7476 #7171 Allow jumping from one wizard steps to another in editing
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/misc/Stepper.jsx
  web/client/components/misc/__tests__/Stepper-test.jsx
  web/client/plugins/ContextCreator.jsx
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: enhancement, Priority: High, Internal, Good first issue, BackportNeeded

#7497 Map infobox styling issue fixes. Resolves #7083
  web/client/components/details/DetailsPanel.jsx
  web/client/themes/default/less/details.less
  web/client/themes/default/less/maps-properties.less
Labels: enhancement, Priority: Medium, Internal, Good first issue

#7510 Backport 2021.02.xx - Map infobox styling issue fixes. (#7497)
  web/client/components/details/DetailsPanel.jsx
  web/client/themes/default/less/details.less
  web/client/themes/default/less/maps-properties.less
Labels: enhancement, Priority: Medium, Internal, Good first issue, Backport

#7501 [Backport 2021.02.xx] #7171: Allow jumping from one wizard steps to another in editing (#7476)
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/misc/Stepper.jsx
  web/client/components/misc/__tests__/Stepper-test.jsx
  web/client/plugins/ContextCreator.jsx
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: enhancement, Priority: High, Internal, Good first issue, Backport

#7509 [Backport 2021.02.xx] #7428: Some typos in the User Session reset (#7485)
  web/client/epics/__tests__/usersession-test.js
  web/client/epics/usersession.js
Labels: bug, Priority: High, Good first issue, Backport, C169-Rennes-Métropole-2019-GeOrchestra

#7505 [Backport 2021.02.xx] #7261 [Style Editor] Some attributes are not visible inside the attribute select box (#7365)
  web/client/actions/layerCapabilities.js
  web/client/components/styleeditor/hint/geocss.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: bug, Backport, C145-MAPSTAND-2021-SUPPORT

#7359 [Backport 2021.02.xx] #7188: Allow injection of FeatureEditor Toolbar buttons (#7189)
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/FeatureEditorButton.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/LayerDownload.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/plugins/widgetbuilder/FeatureEditorButton.jsx
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
  web/client/selectors/featuregrid.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: Blocked, Backport, C105-2021-EMSA-CGD

#7517 #7258: WPS export error when a layer has an ilike filter attribute (#7353)
  web/client/epics/layerdownload.js
Labels: bug, Backport, C145-MAPSTAND-2021-SUPPORT

#7518 #7516: bearer authentication for OL and Cesium WMS
  docs/developer-guide/mapstore-migration-guide.md
  package.json
  project/custom/templates/index.html
  project/standard/templates/index.html
  project/standard/templates/indexTemplate.html
  web/client/components/map/cesium/__tests__/Layer-test-chrome.jsx
  web/client/components/map/cesium/__tests__/Map-test-chrome.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/index.html
  web/client/indexTemplate.html
  web/client/utils/SecurityUtils.js
  web/client/utils/cesium/BILTerrainProvider.js
Labels: enhancement, C039-2021-HALLIBURTON-SUPPORT

#7520 [Backport 2021.02.xx] #7458: Review the UI and config of feature editor table (#7461)
  web/client/components/data/featuregrid/Header.jsx
  web/client/components/data/featuregrid/__tests__/Header-test.jsx
  web/client/components/data/featuregrid/toolbars/TButton.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/themes/default/less/react-data-grid.less
Labels: enhancement, geonode_integration, Backport, C182-SPC-2020-PACIFIC

#7519 [Backport 2021.02.xx] #7454: Style editor shows not found error if the put request fails (#7471)
  web/client/reducers/__tests__/styleeditor-test.js
  web/client/reducers/styleeditor.js
Labels: bug, Backport

#7528 #7527: Cannot scroll a geostory on mobile when the map takes all the viewport
  web/client/components/geostory/media/Map.jsx
  web/client/components/geostory/media/__tests__/Map-test.jsx
  web/client/themes/default/less/geostory.less
Labels: bug, Priority: High, geonode_integration, BackportNeeded

#7382 #7381 Fix zoom to extent for search info
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
Labels: bug, BackportNeeded, C105-2021-EMSA-CGD

#7533 [Backport 2021.02.xx] #7381 Fix zoom to extent for search info (#7382)
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
Labels: Backport

#7535 #7534 changes to the buildConfig calls
  build/prod-webpack.config.js
  build/webpack.config.js
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
Labels: enhancement, BackportNeeded

#7539 [Backport ] #7527: Cannot scroll a geostory on mobile when the map takes all the viewport (#7528)
  web/client/components/geostory/media/Map.jsx
  web/client/components/geostory/media/__tests__/Map-test.jsx
  web/client/themes/default/less/geostory.less
Labels: Backport

#7531 #7508 Annotation plugin crash because of invalid geometry
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/GeometryEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/epics/annotations.js
  web/client/plugins/Annotations.jsx
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/themes/default/less/annotations.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.sv-SE.json
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: bug, Internal, annotations, Good first issue, BackportNeeded

#7522 #7287: Debounce attribute filter evaluation and validation
  web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/data/featuregrid/filterRenderers/NumberFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/NumberFilter-test.jsx
  web/client/components/widgets/enhancers/tableWidget.js
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
  web/client/themes/default/less/widget.less
Labels: bug, Priority: High, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7538 Issue #7486 background selector missing translation
  web/client/components/background/BackgroundDialog.jsx
Labels: bug, Priority: Low, Internal, Good first issue, BackportNeeded

#7514 #7368: Fix column content style of webpage
  web/client/themes/default/less/geostory.less
Labels: bug, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7546 [Backport 2021.02.xx] #7369: Query tool string notEqualTo operator support (#7389)
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/GroupField-test.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: enhancement, Backport, C040-COMUNE_GE-2021-SUPPORT

#7547 [Backport 2021.02.xx] #7370: enableInfoForSelectedLayers configuration for Identify plugin
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/mapInfo.js
Labels: enhancement, Backport, C040-COMUNE_GE-2021-SUPPORT

#7544 [Backport 2021.02.xx] #7429: Charts improvement and fixes (#7490)
  package.json
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
Labels: enhancement, Backport, C040-COMUNE_GE-2021-SUPPORT

#7541 Geometries become invisible when Marker or Text element is being added #7511
  web/client/epics/annotations.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
Labels: bug, Priority: High, Internal, annotations, Good first issue

#7492 Fixed cql_filter parsing for double quotes
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/wfsquery.js
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
Labels: BackportNeeded, C105-2021-EMSA-CGD

#7385 #7384 Feature grid enhancements
  web/client/actions/featuregrid.js
  web/client/actions/wfsquery.js
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
  web/client/plugins/FeatureEditor.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/featuregrid.js
Labels: enhancement, BackportNeeded, C105-2021-EMSA-CGD

#7556 [Backport 2021.02.xx] #7368: Sizing tool for Webpage section in Geostory (#7417)(#7514)
  web/client/components/geostory/common/ToolbarDropdownButton.jsx
  web/client/components/geostory/common/__tests__/ToolbarDropdownButton-test.jsx
  web/client/components/geostory/contents/Column.jsx
  web/client/components/geostory/contents/ToolbarButtons.jsx
  web/client/components/geostory/contents/__tests__/Column-test.jsx
  web/client/themes/default/less/geostory.less
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: enhancement, Backport, C040-COMUNE_GE-2021-SUPPORT

#7550 backport 2021.02.xx - #7486 Missing translation string in background selector (#7538)
  web/client/components/background/BackgroundDialog.jsx
Labels: bug, Internal, Blocked, Backport

#7557 Updated getComponents function to properly work with null geometry.
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: bug, Priority: High, Internal, annotations, Good first issue, BackportNeeded

#7558 [Backport 2021.02.xx] #6430 Use only the state of feature grid to define the layer to use in grid (#7310)
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/wfsquery.js
Labels: enhancement, Backport, C105-2021-EMSA-CGD

#7559 [Backport 2021.02.xx] #7384 Feature grid enhancements (#7385)
  web/client/actions/featuregrid.js
  web/client/actions/wfsquery.js
  web/client/components/data/featuregrid/FeatureGrid.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
  web/client/plugins/FeatureEditor.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/featuregrid.js
Labels: enhancement, Backport, C105-2021-EMSA-CGD

#7563 7508 - Crash on geometry removal while selected geometry is in invalid state
  web/client/epics/annotations.js
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: bug, Priority: High, Internal, annotations, Good first issue

#7570 [Backport 2021.02.xx] Fix for annotations crash because of invalid geometry (#7508)
  web/client/actions/__tests__/annotations-test.js
  web/client/actions/annotations.js
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/GeometryEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/AnnotationsEditor-test.js
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
  web/client/components/misc/coordinateeditors/CoordinatesRow.jsx
  web/client/epics/annotations.js
  web/client/plugins/Annotations.jsx
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/themes/default/less/annotations.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.sv-SE.json
  web/client/utils/AnnotationsUtils.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: bug, Priority: High, Internal, annotations, Good first issue

#7561 Issue #7487 - on TOC, change layer name in settings only if supported
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
Labels: bug, Priority: Low, Internal, Good first issue, BackportNeeded

#7571 #7567 Fixed issue with extensions. Ported also #7568
  java/services/src/main/java/it/geosolutions/mapstore/controllers/configs/ConfigsController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/extensions/ExtensionsController.java
  java/services/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  java/services/src/test/java/it/geosolutions/mapstore/ExtensionsControllerTest.java
  java/services/src/test/java/it/geosolutions/mapstore/LoadAssetControllerTest.java
Labels: bug, Priority: Blocker

#7569 #7568 Fix issue with data dir
  docs/developer-guide/mapstore-migration-guide.md
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/services/src/main/java/it/geosolutions/mapstore/controllers/configs/ConfigsController.java
  java/services/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  java/services/src/test/java/it/geosolutions/mapstore/ExtensionsControllerTest.java
  java/services/src/test/java/it/geosolutions/mapstore/LoadAssetControllerTest.java
  java/web/pom.xml
  java/web/src/main/resources/applicationContext.xml
  pom.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
Labels: bug, Priority: Blocker

#7562 Updated migration guidelines
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation

#7573 [Backport 2021.02.xx] Geometries become invisible when Marker or Text element is being added #7511
  web/client/reducers/__tests__/annotations-test.js
  web/client/utils/__tests__/AnnotationsUtils-test.js
Labels: bug, Priority: High, Internal, annotations, Good first issue, Backport

#7503 [Backport 2021.02.xx] #7432: Empty feature grid when switching between layers (#7495)
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#7537 backport 2021.02.xx - #7534 changes to the buildConfig calls (#7535)
  build/prod-webpack.config.js
  build/webpack.config.js
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
Labels: enhancement, Backport

#7540 #7502 - Removed CSS fixed heights properties and allowed text wrap in modal headers
  web/client/themes/default/less/modal.less
Labels: bug, Priority: Medium, Internal, Good first issue

#7574 [Backport 2021.02.xx] #7287: Debounce attribute filter evaluation and validation (#7522)
  web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/data/featuregrid/filterRenderers/NumberFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/NumberFilter-test.jsx
  web/client/components/widgets/enhancers/tableWidget.js
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
  web/client/themes/default/less/widget.less
Labels: bug, Priority: High, Backport, C040-COMUNE_GE-2021-SUPPORT

#7545 Issue #7523 - Geocarousel improve markers viz
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/sections/GeoCarousel.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/plugins/GeoStory.jsx
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: enhancement, Priority: Medium, Good first issue, BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV

#7584 Issue #7566 - cookies policy modal, close button CSS fix
  web/client/components/cookie/Cookie.jsx
  web/client/themes/default/less/cookie.less
Labels: bug, Good first issue, BackportNeeded

#7578 backport 2021.02.xx - #7487 - on TOC, change layer name in settings only if supported (#7561)
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
Labels: bug, Priority: Low, Internal, Good first issue, Backport

#7494 Coordinate editor minor fixes
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
  web/client/components/misc/coordinateeditors/enhancers/__tests__/decimalToAeronautical-test.js
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
Labels: enhancement, BackportNeeded, C105-2021-EMSA-CGD

#7575 C027 Issue 72 - layer name parsing
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement, Priority: Medium, Project: C027, BackportNeeded, DevOps

#7582 7265 layers order at export
  web/client/utils/LayersUtils.js
  web/client/utils/ogc/__tests__/WMC-test.js
Labels: bug, Priority: High, Internal, Good first issue

#7592 [Backport 2021.02.xx] Fixed inability to store sub-groups order properly #7265
  web/client/utils/LayersUtils.js
  web/client/utils/ogc/__tests__/WMC-test.js
Labels: bug, Priority: High, Internal, Good first issue, Backport

#7588 backport 2021.01.xx - #7587 Parsing layer name and metadata entries from csw (#7575)
  web/client/api/usersession/server.js
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement, Priority: Medium, Project: C027, Backport

#7589 backport 2021.02.xx - #7587 Parsing layer name and metadata entries from csw (#7575)
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement, Priority: Medium, Project: C027, Backport

#7590 backport 2021.02.xx - #7566 cookies policy modal, close button CSS fix (#7584)
  web/client/components/cookie/Cookie.jsx
  web/client/themes/default/less/cookie.less
Labels: bug, Good first issue, Backport

#7591 backport 2021.02.xx - #7523 Geocarousel improve markers viz (#7545)
  web/client/components/geostory/layouts/Cascade.jsx
  web/client/components/geostory/layouts/sections/GeoCarousel.jsx
  web/client/components/geostory/layouts/sections/Section.jsx
  web/client/plugins/GeoStory.jsx
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: enhancement, Priority: Medium, Good first issue, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7593 #7565: Set layer visibility limits from Catalog
  docs/developer-guide/local-config.md
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/VisibilityLimitsForm-test.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/TMSAdvancedEditor.jsx
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CatalogUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, geOrchestra, BackportNeeded

#7599 #7598: avoid geostory loading a story configuration twice
  web/client/epics/__tests__/geostory-test.js
  web/client/epics/geostory.js
Labels: bug, C039-2021-HALLIBURTON-SUPPORT

#7601 [Backport 2021.02.xx] #7565: Set layer visibility limits from Catalog (#7593)
  docs/developer-guide/local-config.md
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/VisibilityLimitsForm-test.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/TMSAdvancedEditor.jsx
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CatalogUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, geOrchestra, Backport

#7604 #7177 - Avoid horizontal scroll in text widgets
  web/client/themes/default/less/widget.less
Labels: bug, enhancement, Priority: Low, Internal, Good first issue

#7605 [Backport 2021.02.xx] #7177 - Avoid horizontal scroll in text widgets. (#7604)
  web/client/themes/default/less/widget.less
Labels: bug, enhancement, Priority: Low, Internal, Good first issue, Backport

#7611 Remove --max_old_space_size=3072 directive
  package.json
Labels: bug, Priority: Blocker, BackportNeeded
