Repository geosolutions-it/MapStore2, pull requests merged in 2021-12, with the labels that each got.

#7613 [Backport 2021.02.xx] #7609 Remove --max_old_space_size=3072 directive (#7611)
  package.json
Labels: bug, Priority: Blocker, Backport

#7603 #7602 Google Street view plugin
  build/docma-config.json
  package.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/StreetView/StreetView.jsx
  web/client/plugins/StreetView/actions/streetView.js
  web/client/plugins/StreetView/api/gMaps.js
  web/client/plugins/StreetView/components/EmptyStreetView.js
  web/client/plugins/StreetView/components/GStreetView.jsx
  web/client/plugins/StreetView/constants.js
  web/client/plugins/StreetView/containers/GStreetViewPanel.jsx
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
  web/client/plugins/StreetView/css/style.css
  web/client/plugins/StreetView/epics/streetView.js
  web/client/plugins/StreetView/googleMapsUtils.js
  web/client/plugins/StreetView/index.js
  web/client/plugins/StreetView/reducers/streetview.js
  web/client/plugins/StreetView/selectors/streetView.js
  web/client/product/plugins.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, New Feature, C169-Rennes-Métropole-2019-GeOrchestra

#7616 #6313 - Avoid icon to become opaque when opacity is set to 0.0
  package.json
Labels: bug, Priority: High, BackportNeeded

#7532 #7526 Attempt fix to issue with properties placeholder configurer order
  java/web/src/main/resources/applicationContext.xml
  project/standard/templates/web/src/main/resources/applicationContext.xml
Labels: bug, Priority: High, BackportNeeded

#7615 #7614 fixes for brgm
  web/client/actions/additionallayers.js
  web/client/components/misc/GridCard.jsx
  web/client/reducers/additionallayers.js
Labels: enhancement, C124-BRGM-2021-SUPPORT

#7512 #7474: The GeoCasousel section and the Paragraph section are not highlighted in the navigation toolbar
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
Labels: bug, Priority: Medium, Internal, GeoStory, Good first issue

#7529 #7416: Filter not applied correctly in attribute table
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
  web/client/observables/wfs.js
  web/client/utils/ogc/WFS/RequestBuilder.js
Labels: bug, Priority: High, Internal, Good first issue

#7621 6614 warnings on the local development environment
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/geostory/common/VisibilityContainer.jsx
  web/client/components/geostory/common/map/FitBounds.jsx
  web/client/components/geostory/common/map/LocalDrawSupport.jsx
  web/client/components/geostory/layouts/sections/Background.jsx
  web/client/components/geostory/media/Image.jsx
  web/client/components/home/Home.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/misc/PaginationToolbar.jsx
  web/client/components/resources/modals/Save.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/tutorial/Tutorial.jsx
  web/client/components/widgets/enhancers/tools/withInfo.js
  web/client/plugins/BurgerMenu.jsx
  web/client/plugins/CreateNewMap.jsx
  web/client/plugins/containers/ToolsContainer.jsx
  web/client/plugins/manager/ManagerMenu.jsx
  web/client/utils/ShareUtils.js
Labels: enhancement, Priority: Low, Internal, Good first issue, QF

#7623 [Backport 2021.02.xx] #7493 Coordinate editor minor fixes (#7494)
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
  web/client/components/misc/coordinateeditors/enhancers/__tests__/decimalToAeronautical-test.js
  web/client/components/misc/coordinateeditors/enhancers/decimalToAeronautical.js
Labels: enhancement, Backport, C105-2021-EMSA-CGD

#7542 7489 Current group selection in TOC is not "always" the destination of layers when added to the map
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
Labels: bug, Priority: Medium, Internal, Good first issue

#7626 backport 2021.02.xx - #7502 Removed CSS fixed heights properties and allowed text wrap in modal headers (#7540)
  web/client/themes/default/less/modal.less
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#7475 #7470 use max length url from localConfig setting
  docs/developer-guide/local-config.md
  web/client/components/map/openlayers/plugins/WMSLayer.js
Labels: geOrchestra, BackportNeeded

#7631 [Backport 2021.02.xx] #7526 properties placeholder configurer order (#7532)
  java/web/src/main/resources/applicationContext.xml
  project/standard/templates/web/src/main/resources/applicationContext.xml
Labels: bug, Backport

#7618 [Backport 2021.02.xx] #7602 Google Street view plugin (#7603)
  build/docma-config.json
  package.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/StreetView/StreetView.jsx
  web/client/plugins/StreetView/actions/streetView.js
  web/client/plugins/StreetView/api/gMaps.js
  web/client/plugins/StreetView/components/EmptyStreetView.js
  web/client/plugins/StreetView/components/GStreetView.jsx
  web/client/plugins/StreetView/constants.js
  web/client/plugins/StreetView/containers/GStreetViewPanel.jsx
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
  web/client/plugins/StreetView/css/style.css
  web/client/plugins/StreetView/epics/streetView.js
  web/client/plugins/StreetView/googleMapsUtils.js
  web/client/plugins/StreetView/index.js
  web/client/plugins/StreetView/reducers/streetview.js
  web/client/plugins/StreetView/selectors/streetView.js
  web/client/product/plugins.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport

#7627 [Backport 2021.02.xx] #7474: The GeoCasousel section and the Paragraph section are not highlighted in the navigation toolbar
  web/client/components/geostory/navigation/ScrollMenu.jsx
  web/client/selectors/__tests__/geostory-test.js
  web/client/selectors/geostory.js
Labels: bug, Priority: Medium, Internal, GeoStory, Good first issue, Backport

#7628 [Backport 2021.02.xx] #7489: Current group selection in TOC is not "always" the destination of layers when added to the map (#7542)
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#7629 [Backport 2021.02.xx] #7416: Filter not applied correctly in attribute table (#7529)
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
  web/client/observables/wfs.js
  web/client/utils/ogc/WFS/RequestBuilder.js
Labels: bug, Priority: High, Internal, Good first issue, Backport

#7624 #7126 - share tool visibility is configurable at Home page elements grid
  web/client/plugins/Dashboards.jsx
  web/client/plugins/FeaturedMaps.jsx
  web/client/plugins/GeoStories.jsx
  web/client/plugins/Maps.jsx
Labels: Priority: Low, Internal, Good first issue, New Feature

#7580 User Guide - Add catalog Catalog tool for Dashboard
  docs/user-guide/adding-widgets.md
  docs/user-guide/img/adding-widgets/default-services.jpg
Labels: Priority: High, Documentation, Dashboard, User Guide

#7581 User Guide - Note on invalid vertices on annotations
  docs/user-guide/annotations.md
  docs/user-guide/img/annotations/invalid_vertex.jpg
  docs/user-guide/img/annotations/invalid_vertex2.gif
  docs/user-guide/img/annotations/polygon_annotation_drawing.gif
Labels: Documentation, annotations, User Guide

#7579 User Guide - Change size button for Web Page section on GeoStory
  docs/user-guide/content-web-toolbar.md
  docs/user-guide/img/button/change-size-horizontal.jpg
  docs/user-guide/img/button/change-size-vertical.jpg
  docs/user-guide/img/web-section/add-section.jpg
  docs/user-guide/img/web-section/web-page.jpg
  docs/user-guide/img/web-section/web-toolbar.jpg
Labels: Documentation, User Guide, GeoStory, C040-COMUNE_GE-2021-SUPPORT

#7622 #7241 - Removed duplicated keys from translation files
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: bug, Priority: Low, Internal, Good first issue

#7638 [Backport 2021.02.xx] #6313 - Avoid icon to become opaque when opacity is set to 0.0 (#7616)
  package.json
Labels: bug, Priority: High, Backport

#7641 [Backport 2021.02.xx] 6614 warnings on the local development environment (#7621)
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/geostory/common/VisibilityContainer.jsx
  web/client/components/geostory/common/map/FitBounds.jsx
  web/client/components/geostory/common/map/LocalDrawSupport.jsx
  web/client/components/geostory/layouts/sections/Background.jsx
  web/client/components/geostory/media/Image.jsx
  web/client/components/home/Home.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/misc/PaginationToolbar.jsx
  web/client/components/resources/modals/Save.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/tutorial/Tutorial.jsx
  web/client/components/widgets/enhancers/tools/withInfo.js
  web/client/plugins/BurgerMenu.jsx
  web/client/plugins/CreateNewMap.jsx
  web/client/plugins/containers/ToolsContainer.jsx
  web/client/plugins/manager/ManagerMenu.jsx
  web/client/utils/ShareUtils.js
Labels: enhancement, Priority: Low, Internal, Good first issue, Backport, QF

#7530 #7504 - Share map modal window - changed base component from Dialog to ResizableModal
  web/client/components/misc/ResizableModal.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/themes/default/less/share.less
Labels: bug, Priority: Medium, Internal, Good first issue, BackportNeeded

#7596 #7585: refactor of the Print plugin as a plugins container
  web/client/actions/print.js
  web/client/components/print/PrintPreview.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/plugins/__tests__/pluginsTestUtils.js
  web/client/plugins/print/ActionButton.jsx
  web/client/plugins/print/Layout.jsx
  web/client/plugins/print/LegendOptions.jsx
  web/client/plugins/print/MapPreview.jsx
  web/client/plugins/print/Null.jsx
  web/client/plugins/print/Option.jsx
  web/client/plugins/print/Resolution.jsx
  web/client/plugins/print/TextInput.jsx
  web/client/plugins/print/index.js
  web/client/reducers/__tests__/print-test.js
  web/client/reducers/print.js
  web/client/utils/PluginsUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: enhancement, C231-GEOINFO_CO-2021-AIT

#7655 backport 2021.02.xx - #7504 - Share map modal window - changed base component from Dialog to Resizable Modal (#7530)
  web/client/components/misc/ResizableModal.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/themes/default/less/share.less
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#7645 [Backport 2021.02.xx] #7576 User Guide - Add new tool for Web Page section on GeoStory (#7579)
  docs/user-guide/content-web-toolbar.md
  docs/user-guide/img/button/change-size-horizontal.jpg
  docs/user-guide/img/button/change-size-vertical.jpg
  docs/user-guide/img/web-section/add-section.jpg
  docs/user-guide/img/web-section/web-page.jpg
  docs/user-guide/img/web-section/web-toolbar.jpg
Labels: Documentation, User Guide, GeoStory, Backport, C040-COMUNE_GE-2021-SUPPORT

#7644 [Backport 2021.02.xx] #7543 User guide - Catalog tool for Dashboard (#7580)
  docs/user-guide/adding-widgets.md
  docs/user-guide/img/adding-widgets/default-services.jpg
Labels: Priority: High, Documentation, Dashboard, User Guide, Backport

#7583 User Guide - Filters for CSW services
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/csw_dynamic_filters.jpg
  docs/user-guide/img/catalog/csw_static_filters.jpg
Labels: Priority: High, Documentation, User Guide, C169-Rennes-Métropole-2019-GeOrchestra

#7642 [Backport 2021.02.xx] #7499 User Guide - Update Advanced Settings for CSW catalog (#7583)
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/csw_dynamic_filters.jpg
  docs/user-guide/img/catalog/csw_static_filters.jpg
Labels: Priority: High, Documentation, User Guide, Backport, C169-Rennes-Métropole-2019-GeOrchestra

#7643 [Backport 2021.02.xx] #7577 User Guide - Add new editing capabilities for annotations (#7581)
  docs/user-guide/annotations.md
  docs/user-guide/img/annotations/invalid_vertex.jpg
  docs/user-guide/img/annotations/invalid_vertex2.gif
  docs/user-guide/img/annotations/polygon_annotation_drawing.gif
Labels: Documentation, annotations, User Guide, Backport

#7659 [Backport 2021.02.xx] #7241 Removed duplicated keys from translation files. (#7622)
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: bug, Priority: Low, Internal, Good first issue, Backport

#7647 #7350: Document how to add GeoPackage format to layer wps downlaod default configuration
  web/client/plugins/LayerDownload.jsx
Labels: enhancement, Documentation, BackportNeeded

#7664 #7607: The size of the background does not change
  web/client/components/geostory/contents/ToolbarButtons.jsx
Labels: bug, Priority: Blocker, GeoStory, BackportNeeded

#7663 Log4j dependency replaced with custom one
  java/services/pom.xml
Labels: Priority: Blocker, BackportNeeded

#7648 #7536: WPS export payload requests must include mimeType inside wps:Output
  web/client/components/data/download/ExportDataResults.jsx
  web/client/observables/wps/__tests__/download-test.js
  web/client/observables/wps/download.js
Labels: bug, geonode_integration, BackportNeeded

#7665 [Backport 2021.02.xx] #7350: Document how to add GeoPackage format to layer wps downlaod default configurationion (#7647)
  web/client/plugins/LayerDownload.jsx
Labels: enhancement, Documentation, Backport

#7525 #6935 Updated documentation for requirements
  docs/developer-guide/requirements.md
Labels: Documentation, BackportNeeded

#7669 [Backport 2021.02.xx] #6935 Updated documentation for requirements (#7525)
  docs/developer-guide/requirements.md
Labels: Documentation, Backport

#7662 #7653: Share panel advanced settings fix
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
Labels: bug, Priority: Blocker, Dashboard, BackportNeeded

#7667 Aligned migration guidelines
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation

#7673 [Backport 2021.02.xx] #7653: Share panel advanced settings fix (#7662)
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
Labels: bug, Priority: Blocker, Dashboard, Backport

#7674 [Backport 2021.02.xx] #7607: The size of the background does not change (#7664)
  web/client/components/geostory/contents/ToolbarButtons.jsx
Labels: bug, Priority: Blocker, GeoStory, Backport

#7675 [Backport 2021.02.xx] #7536: WPS export payload requests must include mimeType inside wps:Output (#7648)
  web/client/components/data/download/ExportDataResults.jsx
  web/client/observables/wps/__tests__/download-test.js
  web/client/observables/wps/download.js
Labels: bug, geonode_integration, Backport

#7666 Mapstore log4j fixes update on stable branch
  docs/developer-guide/mapstore-migration-guide.md
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
Labels: Priority: Blocker, Backport

#7677 #7676 add application/gml+xml mime type to the proxy
  java/web/src/main/resources/proxy.properties
  project/custom/templates/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
Labels: enhancement

#7679 Backport 2021.02.xx - #7676 add application/gml+xml mime type to the proxy (#7677)
  java/web/src/main/resources/proxy.properties
  project/custom/templates/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
Labels: enhancement, Backport

#7657 #7606: Print plugin customizable spec creation chain
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/plugins/print/Layout.jsx
  web/client/plugins/print/LegendOptions.jsx
  web/client/plugins/print/MapPreview.jsx
  web/client/plugins/print/Null.jsx
  web/client/plugins/print/Option.jsx
  web/client/plugins/print/Resolution.jsx
  web/client/plugins/print/TextInput.jsx
  web/client/selectors/print.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: enhancement, C231-GEOINFO_CO-2021-AIT

#7683 Delete pluginsConfig.patch.json
  web/client/configs/pluginsConfig.patch.json
Labels: BackportNeeded

#7630 Issue #7594 - Charts widget colour coded classification
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/components/misc/popover/DisposablePopover.jsx
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/styleeditor/ColorRamp.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/__tests__/ChartWizard-test.jsx
  web/client/components/widgets/builder/wizard/chart/ColorClassModal.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ColorClassModal-test.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/sample_data.js
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/WPSWidgetOptions-test.jsx
  web/client/components/widgets/enhancers/__tests__/wfsChart-test.js
  web/client/components/widgets/enhancers/__tests__/wpsChart-test.js
  web/client/components/widgets/enhancers/wfsChart.js
  web/client/components/widgets/enhancers/wpsChart.js
  web/client/observables/wps/aggregate.js
  web/client/product/assets/css/viewer.css
  web/client/test-resources/widgetbuilder/aggregate
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, New Feature, BackportNeeded, C070-NPA-CGG-2021-DEV

#7688 #7687 fix print for new created project
  docs/developer-guide/printing-module.md
  project/standard/templates/web/pom.xml
Labels: bug

#7684 backport 2021.02.xx - Delete pluginsConfig.patch.json (#7683)
  web/client/configs/pluginsConfig.patch.json
Labels: Backport

#7650 #7649 Set proper trigger for useEffect on plugin initialization
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/__tests__/FeatureEditor-test.jsx
Labels: bug, Priority: High, BackportNeeded

#7686 Fixed jsdoc failure
  web/client/utils/PrintUtils.js
Labels: Documentation
