Repository geosolutions-it/MapStore2, pull requests merged in 2021-03, with the labels that each got.

#6551 fix catalog loading error when no style defined
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/WMTSUtils-test.js
Labels: bug

#6562 #6561: SearchServicesConfig toggle button is visible in the search bar even if the plugin is not in localConfig
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/SearchServicesConfig.jsx
Labels: BackportNeeded, bug, geonode_integration

#6597 6597 : Lower case coordinate systems in WMS capabilities are not supported
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/test-resources/wms/GetCapabilities-1.3.0-lowercase-espg.xml
Labels: BackportNeeded, Internal, Priority: Medium, bug

#6595 [Backport 2021.01.xx] #6593 make endianess configurable for the elevation layer (#6579)
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/plugins/Map.jsx
  web/client/utils/ElevationUtils.js
  web/client/utils/cesium/BILTerrainProvider.js
Labels: Backport, BackportNeeded, C169-Rennes-Métropole-2020-GeOrchestra2

#6422 Minor improvements to module federation, removing more warnings
  build/createExtensionWebpackConfig.js
  build/moduleFederation.js
  package.json
Labels: BackportNeeded, enhancement

#6598 6539: Not proper validation for HTML featureinfo response
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
Labels: BackportNeeded, Internal, Priority: Medium, bug

#6603 BackReport 6597 : Lower case coordinate systems in WMS capabilities are not supp…
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/test-resources/wms/GetCapabilities-1.3.0-lowercase-espg.xml
Labels: Backport, Internal, bug

#6600 #6589 - Measure draw fail fix when overriding default state
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/measurement.js
Labels: BackportNeeded, bug

#6608 backport 2021.01.xx - fix catalog loading error when no style defined (#6551)
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/WMTSUtils-test.js
Labels: Backport, bug

#6613 [BackReport 2021.01.xx]: Not proper validation for HTML FeatureInfo response.
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
Labels: Backport, Internal, bug

#6607 [Backport 2021.01.xx] #6528 fix polygon external internal (#6554)
  web/client/utils/ogc/GML/index.js
  web/client/utils/ogc/__tests__/GML-test.js
Labels: Internal, bug

#6605 [Backport 2021.01.xx] #6604 Minor improvements to module federation, removing more warnings (#6422)
  build/createExtensionWebpackConfig.js
  build/moduleFederation.js
  package.json
Labels: Backport, enhancement

#6616 [Backport 2021.01.xx] #6589 - Measure draw fail fix when overriding default state #6600
  web/client/reducers/__tests__/measurement-test.js
  web/client/reducers/measurement.js
Labels: Backport

#6612 6592: Compare tool Problem
  web/client/components/map/openlayers/swipe/EffectSupport.jsx
Labels: BackportNeeded, Internal, Priority: Medium, bug

#6617 #6610 Fixed BILTerrainProvider with proxy
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/utils/cesium/BILTerrainProvider.js
  web/src/main/resources/proxy.properties
Labels: bug

#6620 [Backreport 2021.01.xx] #6592: Compare tool Problem (#6612)
  web/client/components/map/openlayers/swipe/EffectSupport.jsx
Labels: Backport, Internal, Priority: Medium, bug

#6624 #6610: Fixed proxy configuration. Disabled unnecessary functionalities
  project/custom/templates/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
  web/client/utils/cesium/BILTerrainProvider.js
  web/src/main/resources/proxy.properties
Labels: BackportNeeded

#6577 6556 Configure fixed scales for MapStore scale widget
  web/client/components/map/enhancers/__tests__/withScalesDenominators-test.js
  web/client/components/map/enhancers/withScalesDenominators.js
  web/client/components/widgets/widget/MapView.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/geostory/MediaViewer.js
Labels: BackportNeeded, C098-REGIONE_TOSCANA-2020-GEOPORTALE, enhancement

#6627 [Backport 2021.01.xx] #6610: Fixed proxy configuration. Disabled unnecessary functionalities
  project/custom/templates/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
  web/client/utils/cesium/BILTerrainProvider.js
  web/src/main/resources/proxy.properties
Labels: Backport

#6628 #6369 The GFI highlighting feature is not disabled after closing the panel
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
Labels: BackportNeeded, Internal, Priority: Low, bug

#6629 [Backport 2021.01.xx] #6369 The GFI highlighting feature is not disabled after closing the panel
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
Labels: Backport, Internal, bug

#6630 [ Backport 2021.01.xx ]6556 Configure fixed scales for MapStore scale widget (#6577)
  web/client/components/map/enhancers/__tests__/withScalesDenominators-test.js
  web/client/components/map/enhancers/withScalesDenominators.js
  web/client/components/widgets/widget/MapView.jsx
  web/client/plugins/Map.jsx
  web/client/plugins/geostory/MediaViewer.js
Labels: Backport, C098-REGIONE_TOSCANA-2020-GEOPORTALE, enhancement

#6623 6115 Widget tool button should be hidden when a raster layer is selected #6115
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
Labels: BackportNeeded, Internal, Priority: Low, enhancement

#6599 2973: Cross Layer Filter limits should be well notified to the user
  web/client/components/data/query/CrossLayerFilter.jsx
  web/client/components/data/query/__tests__/CrossLayerFilter-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: BackportNeeded, Internal, Priority: Medium, bug

#6596 #6560: Show messages in widget other than hover
  web/client/components/data/featuregrid/EmptyRowsView.jsx
  web/client/components/widgets/enhancers/__tests__/emptyChartState-test.jsx
  web/client/components/widgets/enhancers/emptyChartState.js
  web/client/components/widgets/enhancers/emptyLegendState.js
  web/client/components/widgets/enhancers/emptyTextState.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/WidgetEmptyMessage.jsx
  web/client/components/widgets/widget/__tests__/CounterView-test.jsx
  web/client/components/widgets/widget/__tests__/WidgetEmptyMessage-test.jsx
  web/client/themes/default/less/widget.less
Labels: BackportNeeded, Internal, enhancement

#6631 #6523: Sync timeline guide layers
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/__tests__/playback-test.js
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/__tests__/widgetsTray-test.js
  web/client/epics/timeline.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/__tests__/Timeline-test.jsx
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
  web/client/selectors/__tests__/timeline-test.js
  web/client/selectors/dimension.js
Labels: BackportNeeded, Internal, Priority: Medium, enhancement

#6641 Update Map Configuration documentation #6637
  docs/developer-guide/maps-configuration.md
Labels: C098-REGIONE_TOSCANA-2020-GEOPORTALE, Documentation

#6646 [Backreport 2021.01.xx] #6115 Widget tool button should be hidden when a raster layer is selected #6115
  web/client/components/TOC/Toolbar.jsx
  web/client/components/TOC/__tests__/Toolbar-test.jsx
Labels: Backport, Internal, enhancement

#6601 3245: Failed password change attempts are not reported to the user
  web/client/actions/security.js
  web/client/api/GeoStoreDAO.js
  web/client/components/security/modals/PasswordResetModal.jsx
  web/client/components/security/modals/__tests__/PasswordResetModal-test.jsx
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/security-test.js
  web/client/reducers/security.js
Labels: BackportNeeded, Internal, Priority: Medium, bug

#6650 [Backport 2021.01.xx] #6523: Sync timeline guide layers (#6631)
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/__tests__/playback-test.js
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/__tests__/widgetsTray-test.js
  web/client/epics/timeline.js
  web/client/plugins/Timeline.jsx
  web/client/plugins/__tests__/Timeline-test.jsx
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
  web/client/selectors/__tests__/timeline-test.js
  web/client/selectors/dimension.js
Labels: Backport, Internal, Priority: Medium, Timeline, enhancement

#6626 6127 : Ensure Http urls added in Catalog conform to Mapstore Http protocol
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.zh-ZH.json
Labels: BackportNeeded, Internal, Priority: Low, enhancement

#6669 [Backreport 2021.01.xx] Failed password change attempts are not reported to the user #3245
  web/client/actions/security.js
  web/client/api/GeoStoreDAO.js
  web/client/components/security/modals/PasswordResetModal.jsx
  web/client/components/security/modals/__tests__/PasswordResetModal-test.jsx
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/security-test.js
  web/client/reducers/security.js
Labels: Backport, Internal, Priority: Medium, bug

#6674 [Backport 2021.01.xx] : Ensure Http urls added in Catalog conform to Mapstore Http protocol
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.zh-ZH.json
Labels: Backport, Internal, Priority: Low, enhancement

#6670 #6665: getConfiguredPlugin fails due to lazy loading
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: C182-SPC-2020-PACIFIC, Priority: High, enhancement

#6671 #6666: MousePosition plugins returns and error with lazy loading
  web/client/plugins/MousePosition.jsx
Labels: C182-SPC-2020-PACIFIC, Priority: High, enhancement

#6648 Update timeline.md
  docs/user-guide/timeline.md
Labels: BackportNeeded, Documentation

#6678 [Backport for 2021.01.xx] Update timeline.md (#6648)
  docs/user-guide/timeline.md
Labels: Documentation

#6673 Update documentation footer
  docs/theme/partials/footer.html
  mkdocs.yml
Labels: BackportNeeded, Documentation, Internal, enhancement

#6455 #5224: ldap security configuration and related docs improved
  docs/developer-guide/integrations/users/ldap.md
  web/pom.xml
  web/src/config/db/geostore-spring-security-db.xml
  web/src/config/ldap/geostore-spring-security-ldap.xml
  web/src/main/resources/applicationContext.xml
  web/src/main/resources/ldap.properties
Labels: Documentation, Priority: Medium, enhancement

#6677 #6675 fix localization issue with MapTemplates
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/misc/transfer/Transfer.jsx
Labels: BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, bug

#6663 5138: Exported measurements issues with import/styling #5138
  web/client/components/import/style/StylePanel.jsx
  web/client/components/import/style/__tests__/StylePanel-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ImporterUtils.js
  web/client/utils/__tests__/ImportUtils-test.js
Labels: Internal, Priority: Medium, enhancement

#6683 #6682 Fix infinite loading in map templates
  web/client/components/maptemplates/__tests__/MapTemplatesPanel-test.jsx
  web/client/epics/__tests__/maptemplates-test.js
  web/client/epics/maptemplates.js
  web/client/plugins/__tests__/MapTemplates-test.jsx
Labels: BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, bug

#6649 #6524: Snap time on guide layer select
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/timeline.js
Labels: BackportNeeded, Internal, Priority: Medium, Timeline, enhancement

#6667 #6651 fix localStorage error that causes infinite loading in embedded…
  web/client/api/userPersistedStorage/__tests__/index-test.js
  web/client/api/userPersistedStorage/index.js
  web/client/api/usersession/__tests__/serverbackup-test.js
  web/client/api/usersession/browser.js
  web/client/components/cookie/Cookie.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/epics/__tests__/cookies-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/cookies.js
  web/client/epics/tutorial.js
  web/client/jsapi/MapStore2.js
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/reducers/featuregrid.js
  web/client/reducers/tutorial.js
  web/client/stores/StandardStore.js
  web/client/utils/AgentUtils.js
Labels: BackportNeeded, Internal, bug

#6672 5111: Tooltips on map widget TOC
  web/client/components/widgets/builder/wizard/map/TOC.jsx
Labels: Internal, Priority: Low, bug

#6697 backport 2021.01.xx - #6651 fix localStorage error that causes infinite loading in embedded (#6667)
  web/client/api/userPersistedStorage/__tests__/index-test.js
  web/client/api/userPersistedStorage/index.js
  web/client/api/usersession/__tests__/serverbackup-test.js
  web/client/api/usersession/browser.js
  web/client/components/cookie/Cookie.jsx
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/mapcontrols/annotations/AnnotationsEditor.jsx
  web/client/epics/__tests__/cookies-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/cookies.js
  web/client/epics/tutorial.js
  web/client/jsapi/MapStore2.js
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/reducers/__tests__/annotations-test.js
  web/client/reducers/annotations.js
  web/client/reducers/featuregrid.js
  web/client/reducers/tutorial.js
  web/client/stores/StandardStore.js
  web/client/utils/AgentUtils.js
Labels: Backport, Internal, bug

#6698 [Backport 2021.01.xx] #6675 fix localization issue with MapTemplates (#6677)
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/misc/transfer/Transfer.jsx
Labels: Backport

#6699 [Backport 2021.01.xx] #6682 Fix infinite loading in map templates (#6683)
  web/client/components/maptemplates/__tests__/MapTemplatesPanel-test.jsx
  web/client/epics/__tests__/maptemplates-test.js
  web/client/epics/maptemplates.js
  web/client/plugins/__tests__/MapTemplates-test.jsx
Labels: Backport

#6690 [Backport 2021.01.xx] #6524: Snap time on guide layer select #6649
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/timeline.js
Labels: Backport, Internal, Priority: Medium, Timeline, enhancement

#6619 #6522 - Fetch formats of the service for use in layer settings
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/FeatureInfo.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/RecordGrid.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/catalog.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CatalogUtils.js
Labels: BackportNeeded, Internal, Priority: Medium, enhancement

#6647 #6635: Fix Issue with Virtual Scroll
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/maps/enhancers/enhancers.js
Labels: BackportNeeded, Dashboard, Internal, Priority: High, bug

#6700 #6689: Improve localized numeric field
  package.json
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/I18N/__tests__/IntlNumberFormatControl-test.jsx
  web/client/components/misc/coordinateeditors/editors/DecimalCoordinateEditor.jsx
  web/client/libs/numeric-input/NumericInput.jsx
Labels: BackportNeeded, Internal, Priority: Medium, bug, enhancement

#6703 6639: Can not close Filter panel when WFS services are not available
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/__tests__/QueryBuilder-test.jsx
  web/client/plugins/QueryPanel.jsx
Labels: Internal, Priority: Low, bug

#6676 #6609: Identify behavior for single layer from Search tool
  docs/user-guide/img/menu-bar/launch-info-panel.jpg
  docs/user-guide/menu-bar.md
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, Internal, Priority: Medium, enhancement

#6640 Loading problem with video added in story, with mp4 format (autoplay + audio)
  web/client/components/geostory/media/Video.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, C190-OAW-2020-SUPPORT, bug, geonode_integration

#6710 [Backport 2021.01.xx] #6637 Update Map Configuration documentation (#6641)
  docs/developer-guide/maps-configuration.md
Labels: Backport, C098-REGIONE_TOSCANA-2020-GEOPORTALE, Documentation

#6709 [Backport 2021.01.xx] #6609: Identify behavior for single layer from Search tool (#6676)
  docs/user-guide/img/menu-bar/launch-info-panel.jpg
  docs/user-guide/menu-bar.md
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, Internal, Priority: Medium, enhancement

#6686 #5584: update tomcat version to avoid errors during startup
  release/bin-war/pom.xml
  release/pom.xml
Labels: Binary Package, Priority: Medium, bug

#6714 [Backport 2021.01.xx] #6561: SearchServicesConfig toggle button is visible in the search bar even if the plugin is not in localConfig (#6562)
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/plugins/Search.jsx
  web/client/plugins/SearchServicesConfig.jsx
Labels: Backport, bug, geonode_integration

#6716 Firefox Fix - Loading problem with video added in story, with mp4 format (autoplay + audio)
  web/client/components/geostory/media/Video.jsx
Labels: BackportNeeded, C190-OAW-2020-SUPPORT, bug, geonode_integration
