Repository geosolutions-it/MapStore2, pull requests merged in 2021-05, with the labels that each got.

#6824 #6823 Fix references to old dev url
  build/buildConfig.js
  docs/developer-guide/map-query-parameters.md
  docs/user-guide/attributes-table.md
  web/client/product/api.jsx
Labels: bug

#6679 #6664: Catalog service selector for dashboards
  web/client/actions/dashboard.js
  web/client/components/catalog/CatalogForm.jsx
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/CatalogServiceSelector.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/TMSAdvancedEditor.jsx
  web/client/configs/localConfig.json
  web/client/epics/dashboard.js
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/plugins/widgetbuilder/ChartBuilder.jsx
  web/client/plugins/widgetbuilder/CounterBuilder.jsx
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/plugins/widgetbuilder/MapLayerSelector.jsx
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/plugins/widgetbuilder/enhancers/catalogEditorEnhancer.js
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/plugins/widgetbuilder/enhancers/manageLayers.js
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/catalog.js
  web/client/reducers/dashboard.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/widgets.js
Labels: Internal, New Feature, Priority: Medium

#6795 6688: Update default width and height configurations for Share Embed
  web/client/components/share/ShareEmbed.jsx
  web/client/components/share/__tests__/ShareEmbed-test.jsx
  web/client/configs/localConfig.json
Labels: Internal, enhancement

#6802 6687: Fix Toc cover zoom controls
  web/client/embedded.html
  web/client/product/appConfigEmbedded.js
  web/client/product/components/viewer/MapViewerCmp.jsx
  web/client/themes/default/less/leaflet.less
Labels: Internal, Priority: Medium, bug

#6816 #6522: Pass format option from WMS service when adding layer to TOC
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
Labels: Internal, Priority: Medium, bug

#6827 6796: Identify Popup as default for Embedded Maps
  web/client/configs/localConfig.json
  web/client/plugins/Identify.jsx
Labels: Internal, Priority: Medium, enhancement

#6782 2972: Add autocomplete in cross layer filter
  web/client/actions/__tests__/queryform-test.js
  web/client/actions/queryform.js
  web/client/components/data/query/AutocompleteField.jsx
  web/client/components/data/query/AutocompleteFieldHOC.jsx
  web/client/components/data/query/ComboField.jsx
  web/client/components/data/query/CrossLayerFilter.jsx
  web/client/components/data/query/FilterField.jsx
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/SimpleFilterField.jsx
  web/client/epics/autocomplete.js
  web/client/plugins/QueryPanel.jsx
  web/client/reducers/__tests__/queryform-test.js
  web/client/reducers/queryform.js
Labels: Internal, Priority: High, enhancement

#6836 #6758 Fixed default custom editors and FeatureEditor config in context
  web/client/plugins/FeatureEditor.jsx
  web/client/utils/featuregrid/EditorRegistry.jsx
  web/client/utils/featuregrid/__tests__/EditorRegistry-test.js
Labels: BackportNeeded, bug

#6839 [Backport 2021.01.xx] #6758 Fixed default custom editors and FeatureEditor config in context (#6836)
  web/client/plugins/FeatureEditor.jsx
  web/client/utils/featuregrid/EditorRegistry.jsx
  web/client/utils/featuregrid/__tests__/EditorRegistry-test.js
Labels: Backport, C169-Rennes-Métropole-2019-GeOrchestra, bug

#6834 #6772 created custom template for tooltip of chart
  web/client/components/charts/WidgetChart.jsx
Labels: Internal, bug

#6844 #6732: Map decentering on scale zoom fix
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/maplayout.js
  web/client/reducers/maplayout.js
Labels: C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug, user feedback

#6757 Capacity to create more than one feature (featuregrid)
  web/client/reducers/featuregrid.js
Labels: enhancement

#6855 #6127 fixed regression for URLs without FQDN
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/catalog/editor/__tests__/MainFormUtils-test.js
Labels: BackportNeeded, C169-Rennes-Métropole-2019-GeOrchestra, bug

#6856 #6838 Changed cesium URL with the one with valid certificates
  project/custom/templates/index.html
  project/standard/templates/index.html
  project/standard/templates/indexTemplate.html
  web/client/examples/api/index.html
  web/client/index.html
  web/client/indexTemplate.html
Labels: BackportNeeded, bug

#6857 #6838. Add documentation for migration guidelines
  docs/developer-guide/mapstore-migration-guide.md
Labels: BackportNeeded, Documentation

#6858 [Backport 2021.01.xx] #6127 fixed regression for URLs without FQDN (#6855)
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/catalog/editor/__tests__/MainFormUtils-test.js
Labels: Backport, bug

#6859 [Backports 2021.01.xx] #6838 Changed cesium URL with the one with valid certificates (#6856)(#6857)
  project/custom/templates/index.html
  project/standard/templates/index.html
  project/standard/templates/indexTemplate.html
  web/client/examples/api/index.html
  web/client/index.html
  web/client/indexTemplate.html
Labels: Backport

#6863 #6862 fix getWPSURL when passing an array of values
  web/client/observables/wps/__tests__/common-test.js
  web/client/observables/wps/common.js
Labels: BackportNeeded, C039-2020-HALLIBURTON-SUPPORT, bug

#6866 geostore/#223: added link to the geostore H2ToPgSQLExport utility doc…
  docs/developer-guide/database-setup.md
Labels: C063-UNEP-2021-SUPPORT, Priority: High, enhancement

#6818 Fix 6813 filter request layers only
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: Internal, Priority: High, geonode_integration

#6864 backport 2021.01.xx - #6862 fix getWPSURL when passing an array of values (#6863)
  web/client/observables/wps/__tests__/common-test.js
  web/client/observables/wps/common.js
Labels: Backport, C039-2020-HALLIBURTON-SUPPORT

#6873 #6832: Catalog CSW crs fix
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/test-resources/csw/getRecordsResponseDC.xml
Labels: BackportNeeded, C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug, user feedback

#6875 6874 fix doc url
  docs/developer-guide/index.md
Labels: BackportNeeded, Documentation

#6872 #6732: Map decentering on scale zoom fix
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/maplayout.js
  web/client/reducers/maplayout.js
Labels: BackportNeeded, C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug

#6861 6817: Hide full screen when sharing links
  web/client/components/share/ShareEmbed.jsx
  web/client/components/share/__tests__/ShareEmbed-test.jsx
  web/client/configs/localConfig.json
  web/client/utils/ShareUtils.js
Labels: Internal, Priority: Medium, bug

#6876 #6729: Limit user input to max field value (Aeronautical)
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
Labels: BackportNeeded, C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug, user feedback

#6841 #6797: Unique interval classification for styles
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/api/__tests__/classifyVectorResponse.json
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/Rule.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/Symbolizer.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/epics/thematic.js
  web/client/plugins/StyleEditor.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, StyleEditor, enhancement

#6845 improve french (and english) localization
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, C169-Rennes-Métropole-2020-GeOrchestra2, Priority: High

#6881 [Backport geonode-mapstore-client-2.1.x] #6797: Unique interval classification for styles #6841
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/api/__tests__/classifyVectorResponse.json
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/Rule.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/Symbolizer.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/epics/thematic.js
  web/client/plugins/StyleEditor.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: Backport, C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, StyleEditor, enhancement

#6877 [Backport #6818] 6813: Filter request layers only
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: Backport, geonode_integration

#6884 Integration for #6883 making tooltips show
  web/client/plugins/MapExport.jsx
  web/client/plugins/MapImport.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/translations/data.en-US.json
Labels: BackportNeeded

#6883 [Backport 2021.01.xx] improve french (and english) localization (#6845)
  web/client/plugins/MapExport.jsx
  web/client/plugins/MapImport.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#6887 Tooltip for map catalog
  web/client/plugins/MapCatalog.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, enhancement

#6888 [Backport 2021.01.xx] Tooltip for map catalog (#6887)
  web/client/plugins/MapCatalog.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#6894 Fixed translations for catalog, history and map templates
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded

#6897 [Backport 2021.01.xx] Fixed translations for catalog, history and map templates (#6894)
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#6891 #6819: Enhance SLD parser for IconSymbolizer
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, bug

#6905 [Backport geonode-mapstore-client-2.1.x] #6819: Enhance SLD parser for IconSymbolizer (#6891)
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: Backport, C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, StyleEditor, enhancement

#6898 [Backport 2021.01.xx] #6729: Limit user input of max value (#6876)
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
Labels: Backport, C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug

#6895 [Backport] #6832: Catalog CSW crs fix (#6873)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/test-resources/csw/getRecordsResponseDC.xml
Labels: Backport, C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug

#6896 [Backport Mapstore2] #6729: Limit user input of max value (#6876)
  web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx
  web/client/components/misc/coordinateeditors/editors/__tests__/AeronauticalCoordinateEditor-test.jsx
Labels: Backport, C125-2020-AUSTROCONTROL-Map2Imp, Priority: High, bug

#6904 #5666: Modify classification rules
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C183-ALMAVIVA-2020-GeoNode-DEV, Priority: High, StyleEditor, enhancement

#6880 #6870 The Identify panel opens when it shouldn't in one use case
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/plugins/Identify.jsx
Labels: Good first issue, Internal, Priority: High, bug

#6907 #6730 fix zoom to extent triggered by epic when hooks are not yet registered
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
Labels: BackportNeeded, C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug

#6908 #6906: FeatureList default prop updated
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
Labels: BackportNeeded, C125-2020-AUSTROCONTROL-Map2Imp, Priority: Medium, bug, user feedback

#6921 backport c125_search_gfi - #6730 fix zoom to extent triggered by epic when hooks are not yet registered (#6907)
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
Labels: Backport, C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug

#6920 backport 2021.01.xx - #6730 fix zoom to extent triggered by epic when hooks are not yet registered (#6907)
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/openlayers/Map.jsx
Labels: Backport, C125-2017-AUSTROCONTROL-SUPPORT, Priority: High, bug

#6852 User guide update
  docs/user-guide/catalog.md
  docs/user-guide/img/share/embed.jpg
  docs/user-guide/img/share/embed_maps_size.jpg
  docs/user-guide/img/share/embed_maps_toc.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/share.md
Labels: Documentation, User Guide

#6923 Improve geoserver integration documentation
  docs/developer-guide/integrations/users/geoserver.md
Labels: Documentation, Priority: Medium

#6924 [Backport Mapstore2] #6906: FeatureList default prop updated (#6908)
  web/client/components/mapcontrols/annotations/FeaturesList.jsx
  web/client/components/mapcontrols/annotations/__tests__/FeatureList-test.js
Labels: Backport, C125-2020-AUSTROCONTROL-Map2Imp, Priority: Medium, bug

#6922 #6870 remove marker after toggling from hover to click
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/plugins/Identify.jsx
Labels: Good first issue, Internal, Priority: High, bug

#6903 #6871 fixing the visibility of map detail panel which toggling 3D
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/details.js
  web/client/epics/globeswitcher.js
  web/client/epics/tutorial.js
Labels: Good first issue, Internal, Priority: High, bug

#6912 #6911: Share coordinates fix
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/maplayout.js
  web/client/epics/queryparams.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: BackportNeeded, C125-2017-AUSTROCONTROL-SUPPORT, Priority: Medium, bug

#6929 backport_2021.01.xx - #6870 The Identify panel opens when it shouldn't in one use case (#6880)
  web/client/components/misc/FeatureInfoTriggerSelector.jsx
  web/client/plugins/Identify.jsx
Labels: Backport, Good first issue, Internal, Priority: High, bug

#6931 [Backport 2021.01.xx] #6911: Share coordinates fix (#6912)
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/maplayout.js
  web/client/epics/queryparams.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Backport, C125-2017-AUSTROCONTROL-SUPPORT, Priority: Medium, bug

#6932 [Backport Mapstore2] #6911: Share coordinates fix (#6912)
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/maplayout.js
  web/client/epics/queryparams.js
  web/client/plugins/Identify.jsx
  web/client/plugins/Share.jsx
  web/client/plugins/__tests__/Share-test.jsx
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Backport, C125-2017-AUSTROCONTROL-SUPPORT, Priority: Medium, bug

#6926 backport 2021.01.xx - #6871 fixing the visibility of map detail panel which toggling 3D (#6903)
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/details.js
  web/client/epics/globeswitcher.js
  web/client/epics/tutorial.js
Labels: Backport, Good first issue, Internal, Priority: High
