Repository geosolutions-it/MapStore2, pull requests merged in 2021-08, with the labels that each got.

#7179 [Backport 2021.01.xx] #7086: Fix error on fontawsome load (#7164)
  web/client/plugins/Map.jsx
Labels: Backport, C040-COMUNE_GE-2021-SUPPORT, Priority: Blocker, bug

#7180 Correct translations for SecondaryColor tooltip
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: AppContext, C124-BRGM-2021-SUPPORT, Priority: High, enhancement

#7184 Fix typo in plugins-howto.md
  docs/developer-guide/plugins-howto.md
Labels: Documentation

#6964 #6810: Raster symbolizer classification
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: enhancement, Priority: Low, RasterStyler, C183-ALMAVIVA-2020-GeoNode-DEV

#7192 #7191: Extend props of LocalDrawSupport component
  web/client/components/geostory/common/map/LocalDrawSupport.jsx
Labels: enhancement, BackportNeeded, C182-SPC-2020-PACIFIC

#7193 [Backport 2021.02.xx] #7191: Extend props of LocalDrawSupport component (#7192)
  web/client/components/geostory/common/map/LocalDrawSupport.jsx
Labels: enhancement, Backport, C182-SPC-2020-PACIFIC

#7196 #7195: Improve dialog positioning of Layer Download plugin for custom project
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/ExportDataResultsComponent.jsx
  web/client/epics/layerdownload.js
Labels: enhancement, BackportNeeded, C182-SPC-2020-PACIFIC

#7198 [Backport 2021.02.xx] #7195: Improve dialog positioning of Layer Download plugin for custom project project
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/ExportDataResultsComponent.jsx
  web/client/epics/layerdownload.js
Labels: enhancement, Backport, C182-SPC-2020-PACIFIC

#7200 #7143: Marker popup fix for leaflet map
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/leaflet/__tests__/Feature-test.jsx
  web/client/themes/default/less/map-popup.less
Labels: bug, Priority: Medium, GeoStory, BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV

#7199 #7104: Fix GFI popup viewer in embedded mode
  web/client/components/common/enhancers/withIdentifyPopup.jsx
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/PopupViewer.jsx
  web/client/components/data/identify/__tests__/DefaultViewer-test.jsx
  web/client/components/geostory/common/enhancers/withPopupSupport.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/map-test.js
Labels: bug, Priority: High, Internal

#7209 #7208 Fullscreen button custom query selector doesn't work
  web/client/actions/__tests__/fullscreen-test.js
  web/client/actions/fullscreen.js
Labels: bug, BackportNeeded, C182-SPC-2020-PACIFIC

#7203 #7201 Nested services does not show the correct label
  web/client/themes/default/less/map-search-bar.less
Labels: bug, BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV

#7211 [Backport 2021.02.xx] #7208 Fullscreen button custom query selector doesn't work
  web/client/actions/__tests__/fullscreen-test.js
  web/client/actions/fullscreen.js
Labels: bug, Backport, C182-SPC-2020-PACIFIC

#7210 [Backport 2021.02.xx] #7201: Nested services does not show the correct label (#7203)
  web/client/themes/default/less/map-search-bar.less
Labels: bug, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7206 [Backport 2021.02.xx]#7143: Marker popup fix for leaflet map (#7200)
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/leaflet/__tests__/Feature-test.jsx
  web/client/themes/default/less/map-popup.less
Labels: bug, Priority: Medium, GeoStory, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7207 #7142: Carousel viewer slider
  web/client/components/geostory/contents/carousel/ViewerSlider.jsx
  web/client/components/geostory/contents/carousel/__tests__/ViewerSlider-test.jsx
  web/client/components/geostory/layouts/sections/GeoCarousel.jsx
  web/client/components/geostory/layouts/sections/__tests__/GoeCarousel-test.jsx
  web/client/themes/default/less/geostory.less
Labels: enhancement, Priority: High, GeoStory, BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV

#7158 #6798 widget error message when layer is not available
  web/client/components/misc/EmptyView.jsx
  web/client/components/widgets/enhancers/__tests__/errorChartState-test.jsx
  web/client/components/widgets/enhancers/errorChartState.js
  web/client/components/widgets/widget/WidgetEmptyMessage.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Priority: Medium, Internal, Good first issue, BackportNeeded

#7213 [Backport 2021.02.xx] #7104: Fix GFI popup viewer in embedded mode #7199
  web/client/components/common/enhancers/withIdentifyPopup.jsx
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/PopupViewer.jsx
  web/client/components/data/identify/__tests__/DefaultViewer-test.jsx
  web/client/components/geostory/common/enhancers/withPopupSupport.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
  web/client/selectors/__tests__/map-test.js
Labels: bug, Priority: High, Internal, Backport

#6930 #5619: Classification url style service configuration
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/SLDService-test.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/plugins/StyleEditor.jsx
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
Labels: enhancement, Priority: Medium, StyleEditor, BackportNeeded, C183-ALMAVIVA-2020-GeoNode-DEV

#7219 #7217 Add support arrays in query form
  web/client/components/data/query/FilterField.jsx
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/GroupField-test.jsx
  web/client/utils/FeatureTypeUtils.js
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: New Feature, C039-2021-HALLIBURTON-SUPPORT

#7215 [Backport 2021.02.xx] #7142: Carousel viewer slider #7207
  web/client/components/geostory/contents/carousel/ViewerSlider.jsx
  web/client/components/geostory/contents/carousel/__tests__/ViewerSlider-test.jsx
  web/client/components/geostory/layouts/sections/GeoCarousel.jsx
  web/client/components/geostory/layouts/sections/__tests__/GoeCarousel-test.jsx
  web/client/themes/default/less/geostory.less
Labels: enhancement, Priority: High, GeoStory, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7216 [Backport 2021.02.xx] #6810: Raster symbolizer classification (#6964)
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: enhancement, Priority: Low, GeoStory, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7221 #5619: Classification url style service configuration (#6930)
  web/client/api/SLDService.js
  web/client/api/StyleEditor.js
  web/client/api/__tests__/SLDService-test.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/plugins/StyleEditor.jsx
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
Labels: enhancement, Priority: Medium, StyleEditor, Backport, C183-ALMAVIVA-2020-GeoNode-DEV

#7232 #7231 make synch to map always active if configured so
  web/client/plugins/FeatureEditor.jsx
Labels: Priority: High, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7248 backport 2021.02.xx - #7240 add support for Swedish language (#7239)
  web/client/components/I18N/__tests__/LangSelector-test.jsx
  web/client/components/I18N/images/flags/sv-SE.png
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/epics/__tests__/localconfig-test.js
  web/client/translations/data.sv-SE.json
  web/client/translations/fragments/cookie/cookieDetails-sv-SE.html
  web/client/utils/LocaleUtils.js
Labels: Backport

#7243 #7111: Do not display marker when Identify plugin is not present
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/components/data/identify/enhancers/__tests__/identify-test.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/controls-test.js
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/controls.js
  web/client/selectors/__tests__/mapInfo-test.js
  web/client/selectors/controls.js
  web/client/selectors/mapInfo.js
  webapps/mapstore/geostore.h2.db
Labels: bug, Priority: High, Internal, Good first issue
