Repository geosolutions-it/MapStore2, pull requests merged in 2022-11, with the labels that each got.

#8753 #8752 Single widget layout - make sure that chart widget properly merge options passed from enhancer and from widget configuration itself
  web/client/components/widgets/enhancers/__tests__/chartWidget-test.jsx
  web/client/components/widgets/enhancers/chartWidget.js
Labels: bug, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8756 #8757 Test related to Cesium map is failing randomly
  web/client/components/map/cesium/__tests__/Map-test.jsx
Labels: bug, Internal, BackportNeeded

#8732 [Backport 2022.02.xx] #8723 Fix for WMTS background issues due to `attribution` parameter; #8724 WMTS request identify flow fixes (#8725)
  web/client/components/data/identify/viewers/row/RowViewer.jsx
  web/client/utils/leaflet/WMTS.js
  web/client/utils/mapinfo/__tests__/wmts-test.js
  web/client/utils/mapinfo/wmts.js
Labels: bug, Backport, C044-VLAANDEREN-2021-SUPPORT

#8733 [Backport 2022.01.xx] #8723 Fix for WMTS background issues due to `attribution` parameter; #8724 WMTS request identify flow fixes (#8725)
  web/client/components/data/identify/viewers/row/RowViewer.jsx
  web/client/utils/leaflet/WMTS.js
  web/client/utils/mapinfo/__tests__/wmts-test.js
  web/client/utils/mapinfo/wmts.js
Labels: bug, Backport, C044-VLAANDEREN-2021-SUPPORT

#8758 [Backport 2022.02.xx] #8718 Slipping of points when depth test is active (a) (#8720)
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/MultiInput.jsx
  web/client/components/styleeditor/__tests__/MultiInput-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/VectorStyleUtils.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: Priority: Medium, Backport, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8762 [Backport 2022.02.xx] #8706 Point and Line layers make it difficult to use Identify (#8700)
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/cesium/ClickUtils.js
  web/client/utils/mapinfo/__tests__/wfs-test.js
  web/client/utils/mapinfo/wfs.js
Labels: bug, Priority: Medium, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8759 #8238 Save dialog is not properly displayed in certain cases
  web/client/components/home/Home.jsx
Labels: bug, Internal, Layout

#8763 [Backport 2022.02.xx] #8726 The new widgets on the map are under the TOC (#8751)
  web/client/configs/localConfig.json
  web/client/plugins/Widgets.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
Labels: bug, Widgets, Backport, Regression, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8765 [Backport 2022.02.xx] #8740 Move the mouse on 3D Tiles (#8748)
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/utils/cesium/ClickUtils.js
Labels: bug, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8764 ensure jackson version is 2.13.1
  java/services/pom.xml
Labels: Priority: Medium, dependencies, BackportNeeded

#8770 [Backport 2022.02.xx] #8706 Restore multiple features selection on map click in 3D viewer (#8750)
  build/testConfig.js
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/CesiumSimulate.js
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/VectorStyleUtils-test.js
Labels: bug, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8769 [2022.02.xx backport] ensure jackson version is 2.13.1 (#8764)
  java/services/pom.xml
Labels: dependencies, Backport

#8779 Update User Guide - Change Side Bar title (with no conflicts)
  docs/user-guide/img/navigation-toolbar/3D-mode.jpg
  docs/user-guide/img/navigation-toolbar/aeronautical_coordinates_editor.gif
  docs/user-guide/img/navigation-toolbar/areonautical-ex.gif
  docs/user-guide/img/navigation-toolbar/coordinate.jpg
  docs/user-guide/img/navigation-toolbar/decimal-ex.gif
  docs/user-guide/img/navigation-toolbar/decimal_coordinates_editor.gif
  docs/user-guide/img/navigation-toolbar/edit_identify.gif
  docs/user-guide/img/navigation-toolbar/format-options.jpg
  docs/user-guide/img/navigation-toolbar/format_example.jpg
  docs/user-guide/img/navigation-toolbar/get_feature_info.jpg
  docs/user-guide/img/navigation-toolbar/highlight_features.jpg
  docs/user-guide/img/navigation-toolbar/hightlight-point1.gif
  docs/user-guide/img/navigation-toolbar/hover-over-map.gif
  docs/user-guide/img/navigation-toolbar/html_info.jpg
  docs/user-guide/img/navigation-toolbar/identify-tool.jpg
  docs/user-guide/img/navigation-toolbar/info_formats.jpg
  docs/user-guide/img/navigation-toolbar/layer.gif
  docs/user-guide/img/navigation-toolbar/layers.jpg
  docs/user-guide/img/navigation-toolbar/more-info.jpg
  docs/user-guide/img/navigation-toolbar/more_info.jpg
  docs/user-guide/img/navigation-toolbar/position.jpg
  docs/user-guide/img/navigation-toolbar/setting-hover.jpg
  docs/user-guide/img/navigation-toolbar/settings.jpg
  docs/user-guide/img/navigation-toolbar/side-bar-1.jpg
  docs/user-guide/img/navigation-toolbar/side-bar.jpg
  docs/user-guide/img/navigation-toolbar/sidebar.jpg
  docs/user-guide/navigation-toolbar.md
  mkdocs.yml
Labels: Documentation, Internal, User Guide, BackportNeeded

#8777 #8729 add menu item in sidebar and improve behaviour of map views
  web/client/epics/__tests__/mapviews-test.js
  web/client/epics/mapviews.js
  web/client/plugins/MapViews.jsx
  web/client/plugins/SidebarMenu.jsx
Labels: bug, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8754 #8523 Add alwaysRender property
  docs/developer-guide/plugins-howto.md
  web/client/plugins/Measure.jsx
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8773 #8652 Cesium query parameters support
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: Medium, New Feature, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8782 [Backport 2022.02.xx] #8779 Update User Guide - Change Side Bar title (with no conflicts) (#8696)
  docs/user-guide/img/navigation-toolbar/3D-mode.jpg
  docs/user-guide/img/navigation-toolbar/aeronautical_coordinates_editor.gif
  docs/user-guide/img/navigation-toolbar/areonautical-ex.gif
  docs/user-guide/img/navigation-toolbar/coordinate.jpg
  docs/user-guide/img/navigation-toolbar/decimal-ex.gif
  docs/user-guide/img/navigation-toolbar/decimal_coordinates_editor.gif
  docs/user-guide/img/navigation-toolbar/edit_identify.gif
  docs/user-guide/img/navigation-toolbar/format-options.jpg
  docs/user-guide/img/navigation-toolbar/format_example.jpg
  docs/user-guide/img/navigation-toolbar/get_feature_info.jpg
  docs/user-guide/img/navigation-toolbar/highlight_features.jpg
  docs/user-guide/img/navigation-toolbar/hightlight-point1.gif
  docs/user-guide/img/navigation-toolbar/hover-over-map.gif
  docs/user-guide/img/navigation-toolbar/html_info.jpg
  docs/user-guide/img/navigation-toolbar/identify-tool.jpg
  docs/user-guide/img/navigation-toolbar/info_formats.jpg
  docs/user-guide/img/navigation-toolbar/layer.gif
  docs/user-guide/img/navigation-toolbar/layers.jpg
  docs/user-guide/img/navigation-toolbar/more-info.jpg
  docs/user-guide/img/navigation-toolbar/more_info.jpg
  docs/user-guide/img/navigation-toolbar/position.jpg
  docs/user-guide/img/navigation-toolbar/setting-hover.jpg
  docs/user-guide/img/navigation-toolbar/settings.jpg
  docs/user-guide/img/navigation-toolbar/side-bar-1.jpg
  docs/user-guide/img/navigation-toolbar/side-bar.jpg
  docs/user-guide/img/navigation-toolbar/sidebar.jpg
  docs/user-guide/navigation-toolbar.md
  mkdocs.yml
Labels: Documentation, Internal, User Guide, Backport

#8775 [Backport 2022.02.xx-c040] #8757 Increase waitFor timeout in cesium map test (#8771)
  web/client/components/map/cesium/__tests__/Map-test.jsx
Labels: bug, Internal, Backport

#8774 #8729 Map views plugin dev documentation
  docs/developer-guide/maps-configuration.md
  web/client/plugins/MapViews.jsx
Labels: Documentation, Dev Guide, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8784 [Backport 2022.02.xx-c040] #8729 add menu item in sidebar and improve behaviour of map views (#8777)
  web/client/epics/__tests__/mapviews-test.js
  web/client/epics/mapviews.js
  web/client/plugins/MapViews.jsx
  web/client/plugins/SidebarMenu.jsx
Labels: bug, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8785 [Backport 2022.02.xx-c040] #8523 Add alwaysRender property (#8754)
  docs/developer-guide/plugins-howto.md
  web/client/plugins/Measure.jsx
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: bug, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8780 #8761 Geostory Advanced Map Editor button should be provided properly
  web/client/components/geostory/common/MapEditor.jsx
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/plugins/GeoStory.jsx
  web/client/plugins/MapEditor.jsx
Labels: enhancement, C242-UNIPI-2021-SCORE

#8789 #8781 Attribute table does not draw new features on layers with point geometries
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: bug, Priority: High, Internal, BackportNeeded, Regression

#8760 #8745 Date-time picker for date-time/date/time attributes on feature editor
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/editors/__tests__/DateTimeEditor-test.jsx
  web/client/components/data/featuregrid/editors/index.jsx
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/components/misc/datetimepicker/Hours.js
  web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js
Labels: enhancement, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8776 #8734 Add dev documentation for model symbolizer
  docs/developer-guide/maps-configuration.md
Labels: Documentation, Dev Guide, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8791 [Backport 2022.02.xx] #8761 Geostory Advanced Map Editor button should be provided properly
  web/client/components/geostory/common/MapEditor.jsx
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/plugins/GeoStory.jsx
  web/client/plugins/MapEditor.jsx
Labels: enhancement, C242-UNIPI-2021-SCORE

#8807 #8806 Create a filter by viewport icon
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/viewport-filter.svg
Labels: enhancement, C070-CGG-2022-DEV

#8809 [Backport 2022.02.xx] #8781 Attribute table does not draw new features on layers with point geometries (#8789)
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: bug, Priority: High, Internal, Backport, Regression

#8810 [Backport 2022.02.xx-c040] #8781 Attribute table does not draw new features on layers with point geometries (#8789)
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
Labels: bug, Priority: High, Internal, Backport, Regression

#8788 #8766: Timeline plugin configuration of snap and mode on startup
  docs/user-guide/img/button/reset.jpg
  docs/user-guide/img/button/timeline-range.jpg
  docs/user-guide/img/button/timeline-sync-button.jpg
  docs/user-guide/img/button/viewport-filter.jpg
  docs/user-guide/img/timeline/timeline-animation-buttons.jpg
  docs/user-guide/img/timeline/timeline-base.jpg
  docs/user-guide/img/timeline/timeline-current-time-range.jpg
  docs/user-guide/img/timeline/timeline-current-time.jpg
  docs/user-guide/img/timeline/timeline-histogram.jpg
  docs/user-guide/img/timeline/timeline-sync-example.jpg
  docs/user-guide/timeline.md
  web/client/actions/__tests__/timeline-test.js
  web/client/actions/dimension.js
  web/client/actions/timeline.js
  web/client/epics/__tests__/dimension-test.js
  web/client/epics/__tests__/playback-test.js
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/dimension.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/observables/multidim.js
  web/client/plugins/Timeline.jsx
  web/client/reducers/__tests__/dimension-test.js
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
  web/client/selectors/__tests__/dimension-test.js
  web/client/selectors/dimension.js
  web/client/selectors/timeline.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C070-CGG-2022-DEV

#8793 #8778 Feature Grid filter by viewport
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C070-CGG-2022-DEV

#8814 8794 Customize query panels
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/__tests__/QueryBuilder-test.jsx
  web/client/plugins/QueryPanel.jsx
  web/client/plugins/querypanel/AttributeFilter.jsx
  web/client/plugins/querypanel/CrossLayerFilter.jsx
  web/client/plugins/querypanel/SpatialFilter.jsx
  web/client/plugins/querypanel/index.js
Labels: C070-CGG-2022-DEV

#8819 #8808 Modifying test to make it stable
  web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js
Labels: bug, Priority: High, C040-COMUNE_GE-2022-SUPPORT

#8826 [ stable branch ] Update Changelog and java modules versions
  CHANGELOG.md
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Task

#8825 Update Changelog
  CHANGELOG.md
Labels: Task

#8829 Backport #8745 #8808 2022.02.xx-c040 Date-time picker for date-time/date/time attributes on feature editor
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/editors/__tests__/DateTimeEditor-test.jsx
  web/client/components/data/featuregrid/editors/index.jsx
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/components/misc/datetimepicker/Hours.js
  web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js
Labels: C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8830 [Backport 2022.02.xx-c040] #8652 Cesium query parameters support (#8773)
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: Medium, Backport, New Feature, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8822 #8821 Add tooltip for layer titles in legend widgets and make them responsive
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/plugins/Dashboard.jsx
  web/client/themes/default/less/widget.less
  web/client/themes/default/less/wizard.less
Labels: enhancement, Dashboard, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8834 [Backport 2022.02.xx-c040] #8821 Add tooltip for layer titles in legend widgets and make them responsive (#8822)
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/LegendView.jsx
  web/client/plugins/Dashboard.jsx
  web/client/themes/default/less/widget.less
  web/client/themes/default/less/wizard.less
Labels: enhancement, Dashboard, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8835 Update versions to 1.4-SNAPSHOT. package.json updated
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  package.json
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Task

#8836 [Backport 2022.02.xx] #8652 Cesium query parameters support (#8773)
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: Medium, Backport, New Feature, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8832 #8831 Date formats in attributes table
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/utils/FeatureGridUtils.js
Labels: enhancement, Priority: Medium, C040-COMUNE_GE-2022-SUPPORT

#8840 [Backport 2022.02.xx-c040] 8341 Leader line property - a line that connect the mark, icon, model or label to ground in 3D view (#8797)
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/components/styleeditor/config/blocks.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/MapInfoUtils.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: StyleEditor, Backport, New Feature, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8841 [Backport 2022.02.xx-c040] #8831 Date formats in attributes table (#8832)
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/utils/FeatureGridUtils.js
Labels: enhancement, Backport, C040-COMUNE_GE-2022-SUPPORT

#8845 Fixed devServer configuration to work better with dev
  build/devServer.js
Labels: BackportNeeded

#8844 #8745 Fixed date/time/date-time editor for feature grid
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/editors/__tests__/DateTimeEditor-test.jsx
  web/client/components/data/featuregrid/editors/index.jsx
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js
  web/client/components/misc/enhancers/__tests__/utcDateWrapper-test.jsx
  web/client/components/misc/enhancers/utcDateWrapper.js
  web/client/utils/FeatureGridUtils.js
Labels: Priority: High, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT
