Repository geosolutions-it/MapStore2, pull requests merged in 2022-09, with the labels that each got.

#8533 backport 2022.02.xx - Revert "#8082 normalize longitude (#8325)" (#8512)
  web/client/actions/__tests__/draw-test.js
  web/client/actions/draw.js
  web/client/reducers/__tests__/draw-test.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: Backport

#8514 #8513 Properly pass epic name into isolation function, so that muteState has all the epics listed correctly.
  web/client/utils/StateUtils.js
  web/client/utils/__tests__/StateUtils-test.js
Labels: bug, Priority: Blocker, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8528 #8458 adding first commit creation in createproject.js script
  createProject.js
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/release.md
  utility/projects/projectLib.js
Labels: bug, Priority: High, BackportNeeded

#8546 #8458 restore old release since it's not out yet
  docs/developer-guide/project-creation-script.md
Labels: bug, Priority: High, BackportNeeded

#8538 #8534 Making MAP_CONFIG_LOADED action dispatched once all plugins are loaded
  web/client/components/plugins/enhancers/withModulePlugins.js
  web/client/containers/MapViewer.jsx
  web/client/containers/Page.jsx
  web/client/product/components/viewer/MapViewerCmp.jsx
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
  web/client/product/pages/Context.jsx
  web/client/product/pages/ContextCreator.jsx
  web/client/product/pages/Dashboard.jsx
  web/client/product/pages/GeoStory.jsx
  web/client/product/pages/Maps.jsx
Labels: bug, Priority: Blocker, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8549 Backport 2022.02.xx - #8458 adding first commit creation in createproject.js script (#8528)
  createProject.js
  docs/developer-guide/project-creation-script.md
  docs/developer-guide/release.md
  utility/projects/projectLib.js
Labels: bug, Priority: High, Backport

#8553 #8551 fix dashboard embedded crash error
  project/standard/templates/dashboard-embedded-template.html
  web/client/components/widgets/enhancers/wfsTable/describeFetch.js
  web/client/dashboard-embedded-template.html
  web/client/product/main.jsx
Labels: bug, Priority: Blocker, BackportNeeded, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#8544 #8543 Make tutorial compatible with being module plugin.
  web/client/actions/__tests__/storemanager-test.js
  web/client/actions/storemanager.js
  web/client/components/app/withExtensions.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/tutorial.js
  web/client/hooks/useModulePlugins.js
  web/client/utils/StateUtils.js
  web/client/utils/__tests__/StateUtils-test.js
Labels: bug, Priority: High, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#8556 [C105 branch] Fixed layerdownload for wps
  web/client/epics/layerdownload.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: C105-2021-EMSA-CGD

#8550 #8483 Properly mute epics with nested PluginsContainer
  web/client/hooks/__tests__/useModulePlugins-test.js
  web/client/hooks/useModulePlugins.js
  web/client/test-resources/module-plugins/dummy2.js
Labels: bug, GeoStory, AppContext, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#8539 #8529 maxItems is now used from Identify plugin
  web/client/components/data/identify/enhancers/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: enhancement, BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#8557 Dynamic modules documentation
  build/docma-config.json
  docs/developer-guide/extensions.md
  docs/developer-guide/writing-epics.md
  web/client/utils/StateUtils.js
Labels: Documentation, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8565 #8564 Reduce amount of plugins initially loaded on the context page
  web/client/components/plugins/enhancers/__tests__/withModulePlugins-test.js
  web/client/components/plugins/enhancers/withModulePlugins.js
  web/client/product/pages/Context.jsx
  web/client/selectors/__tests__/context-test.js
  web/client/selectors/context.js
Labels: bug, Priority: Blocker, BackportNeeded, AppContext, C169-Rennes-Métropole-2021-GeOrchestra3

#8555 #8520: Reduce dashboards clutter and widget update
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/widgets/builder/wizard/map/MapSwitcher.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
  web/client/plugins/Dashboard.jsx
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/widget.less
  web/client/themes/default/less/wizard.less
Labels: enhancement, Priority: High, C040-COMUNE_GE-2022-SUPPORT

#8568 [Backport 2022.02.xx] Dynamic modules documentation (#8557)
  build/docma-config.json
  docs/developer-guide/extensions.md
  docs/developer-guide/writing-epics.md
  web/client/utils/StateUtils.js
Labels: Priority: High, Documentation, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8567 Backport 2022.02.xx - #8562 Fixing printing version in migration guidelines (#8563)
  docs/developer-guide/mapstore-migration-guide.md
Labels: bug, Documentation, Backport

#8572 #8571 Dynamic import of plugins - migration guideline
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8577 [Backport 2022.02.xx] #8571 Dynamic import of plugins - migration guideline (#8572)
  docs/developer-guide/mapstore-migration-guide.md
Labels: Priority: High, Documentation, C169-Rennes-Métropole-2021-GeOrchestra3

#8575 update keycloak documentation
  docs/developer-guide/integrations/users/keycloak.md
  docs/developer-guide/integrations/users/openId.md
Labels: Priority: High, Documentation, BackportNeeded, C211-GEOFIT-2022-OPENID

#8581 #8580 Register context manager epics by "Contexts" plugin
  web/client/plugins/Contexts.jsx
Labels: bug, BackportNeeded, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#8582 [Backport 2022.02.xx] #8580 Register context manager epics by "Contexts" plugin (#8581)
  web/client/plugins/Contexts.jsx
Labels: bug, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#8583 #8580 Unmute epics on plugin registration
  web/client/components/app/withExtensions.js
  web/client/hooks/useModulePlugins.js
  web/client/utils/StateUtils.js
Labels: bug, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8585 [Backport 2022.02.xx] #8580 Unmute epics on plugin registration (#8583)
  web/client/components/app/withExtensions.js
  web/client/hooks/useModulePlugins.js
  web/client/utils/StateUtils.js
Labels: bug, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8587 #8586 Make eager option configurable for extensions shared libraries
  build/createExtensionWebpackConfig.js
Labels: enhancement, BackportNeeded, Extensions

#8598 #8520: Widget title ellipsis
  web/client/themes/default/less/widget.less
Labels: bug, Priority: High, C040-COMUNE_GE-2022-SUPPORT

#8593 User guide update - Print Format and Coordinate System options
  docs/user-guide/img/print/first-layout-print.jpg
  docs/user-guide/img/print/first-legend-options.jpg
  docs/user-guide/img/print/print-page.jpg
  docs/user-guide/img/print/print.gif
  docs/user-guide/print.md
Labels: Documentation, User Guide, BackportNeeded

#8590 #8573 Fix permissions dropdowns
  web/client/components/resources/modals/fragments/PermissionEditor.jsx
  web/client/components/resources/modals/fragments/__tests__/PermissionEditor-test.jsx
  web/client/themes/default/less/maps-properties.less
Labels: bug, Priority: High, Internal, BackportNeeded

#8420 User Guide update - 3D Styling for vector data
  docs/user-guide/img/layer-settings/bring-to-front.jpg
  docs/user-guide/img/layer-settings/clamp-to-ground.jpg
  docs/user-guide/img/layer-settings/polygon-type.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, StyleEditor, User Guide, BackportNeeded, C125-AUSTROCONTROL-2022-MS_3D_PILOT

#8584 #8559: Feature grid aliases and tooltips for columns
  web/client/components/data/featuregrid/AttributeTable.jsx
  web/client/components/data/featuregrid/__tests__/AttributeTable-test.jsx
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/enhancers/utils.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/wfsTable-test.js
  web/client/components/widgets/enhancers/wfsTable/index.js
  web/client/components/widgets/enhancers/wfsTable/noPaginationFetch.js
  web/client/components/widgets/enhancers/wfsTable/virtualScrollFetch.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/plugins/widgets/getWidgetFilterRenderers.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: enhancement, Priority: High, C040-COMUNE_GE-2022-SUPPORT

#8605 #8559: Wizard table option with fixed column size
  web/client/components/data/featuregrid/AttributeTable.jsx
  web/client/themes/default/less/wizard.less
Labels: bug, Priority: High, BackportNeeded, C040-COMUNE_GE-2022-SUPPORT

#8606 [Backport 2022.01.xx-c040] #8559: Feature grid aliases and tooltips for columns (#8584)
  web/client/components/data/featuregrid/AttributeTable.jsx
  web/client/components/data/featuregrid/__tests__/AttributeTable-test.jsx
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/enhancers/utils.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/wfsTable-test.js
  web/client/components/widgets/enhancers/wfsTable/index.js
  web/client/components/widgets/enhancers/wfsTable/noPaginationFetch.js
  web/client/components/widgets/enhancers/wfsTable/virtualScrollFetch.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/plugins/widgets/getWidgetFilterRenderers.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
  web/client/themes/default/less/wizard.less
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: enhancement, Priority: High, Backport, C040-COMUNE_GE-2022-SUPPORT

#8610 #8609 Update terrain/elevation layer documentation
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/mapstore-migration-guide.md
Labels: Priority: High, Documentation, BackportNeeded

#8417 Update User Guide - GeoStory and Dashboard Options menu
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/exploring-stories.md
  docs/user-guide/img/exploring-dashboards/options-menu.jpg
  docs/user-guide/img/exploring-dashboards/version-panel.jpg
  docs/user-guide/img/exploring-stories/story-workspace.jpg
Labels: Documentation, Internal, Dashboard, User Guide, BackportNeeded

#8611 [Backport 2022.02.xx] #8609 Update terrain/elevation layer documentation (#8610)
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/mapstore-migration-guide.md
Labels: Priority: High, Documentation, Backport

#8494 User Guide Update - Annotations button
  docs/user-guide/annotations.md
  docs/user-guide/img/annotations/add_vertex_button.gif
  docs/user-guide/img/annotations/add_vertex_button.jpg
  docs/user-guide/img/annotations/annotation1.jpg
  docs/user-guide/img/annotations/annotation2.jpg
  docs/user-guide/img/annotations/annotation_form_filled.jpg
  docs/user-guide/img/annotations/annotation_tool.jpg
  docs/user-guide/img/annotations/annotation_toolbar.jpg
  docs/user-guide/img/annotations/annotations_main_panel.jpg
  docs/user-guide/img/annotations/annotations_on_toc.jpg
  docs/user-guide/img/annotations/coordinates_format_switcher.gif
  docs/user-guide/img/annotations/coordinates_format_switcher.jpg
  docs/user-guide/img/annotations/editing_annotations.gif
  docs/user-guide/img/annotations/invalid_vertex.jpg
  docs/user-guide/img/annotations/invalid_vertex2.gif
  docs/user-guide/img/annotations/polygon_annotation_drawing.gif
  docs/user-guide/img/button/annotations2.jpg
  docs/user-guide/img/button/circle2.jpg
  docs/user-guide/img/button/line2.jpg
  docs/user-guide/img/button/marker2.jpg
  docs/user-guide/img/button/polygon2.jpg
  docs/user-guide/img/button/text2.jpg
  docs/user-guide/img/button/white-zoom.jpg
  docs/user-guide/img/button/x2.jpg
  mkdocs.yml
Labels: Documentation, annotations, User Guide, BackportNeeded

#8612 Backport 2022.02.xx - #8466 User guide - Print Format and Coordinate System options (#8593)
  docs/user-guide/img/print/first-layout-print.jpg
  docs/user-guide/img/print/first-legend-options.jpg
  docs/user-guide/img/print/print-page.jpg
  docs/user-guide/img/print/print.gif
  docs/user-guide/print.md
Labels: Documentation, User Guide, Backport

#8613 Backport 2022.02.xx - #8414 User Guide - 3D Styling for vector data (#8420)
  docs/user-guide/img/layer-settings/bring-to-front.jpg
  docs/user-guide/img/layer-settings/clamp-to-ground.jpg
  docs/user-guide/img/layer-settings/polygon-type.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, StyleEditor, User Guide, Backport, C125-AUSTROCONTROL-2022-MS_3D_PILOT

#8616 Backport 2022.02.xx - #8426 User guide - Annotations button (#8494)
  docs/user-guide/annotations.md
  docs/user-guide/img/annotations/add_vertex_button.gif
  docs/user-guide/img/annotations/add_vertex_button.jpg
  docs/user-guide/img/annotations/annotation1.jpg
  docs/user-guide/img/annotations/annotation2.jpg
  docs/user-guide/img/annotations/annotation_form_filled.jpg
  docs/user-guide/img/annotations/annotation_tool.jpg
  docs/user-guide/img/annotations/annotation_toolbar.jpg
  docs/user-guide/img/annotations/annotations_main_panel.jpg
  docs/user-guide/img/annotations/annotations_on_toc.jpg
  docs/user-guide/img/annotations/coordinates_format_switcher.gif
  docs/user-guide/img/annotations/coordinates_format_switcher.jpg
  docs/user-guide/img/annotations/editing_annotations.gif
  docs/user-guide/img/annotations/invalid_vertex.jpg
  docs/user-guide/img/annotations/invalid_vertex2.gif
  docs/user-guide/img/annotations/polygon_annotation_drawing.gif
  docs/user-guide/img/button/annotations2.jpg
  docs/user-guide/img/button/circle2.jpg
  docs/user-guide/img/button/line2.jpg
  docs/user-guide/img/button/marker2.jpg
  docs/user-guide/img/button/polygon2.jpg
  docs/user-guide/img/button/text2.jpg
  docs/user-guide/img/button/white-zoom.jpg
  docs/user-guide/img/button/x2.jpg
  mkdocs.yml
Labels: Documentation, annotations, User Guide, Backport

#8615 Backport 2022.02.xx - #8415 User guide - Cesium viewer settings (#8418)
  docs/user-guide/img/menu-bar/cesium-settings.jpg
  docs/user-guide/menu-bar.md
Labels: Documentation, Internal, User Guide, Backport, 3D

#8594 #8570 fallback for Attribute Table
  web/client/components/data/featuregrid/FeatureEditorFallback.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/themes/default/less/featuregrid.less
Labels: bug, Priority: High, Internal

#8619 [Backport 2022.02.xx] #8174 Update User Guide - Options Bar (conflict-free) (#8618)
  docs/user-guide/background.md
  docs/user-guide/catalog.md
  docs/user-guide/exploring-maps.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/button/about2.jpg
  docs/user-guide/img/button/catalog2.jpg
  docs/user-guide/img/button/delete2.jpg
  docs/user-guide/img/button/details2.jpg
  docs/user-guide/img/button/doc2.jpg
  docs/user-guide/img/button/export2.jpg
  docs/user-guide/img/button/homepage.jpg
  docs/user-guide/img/button/import2.jpg
  docs/user-guide/img/button/measurament.jpg
  docs/user-guide/img/button/print2.jpg
  docs/user-guide/img/button/save2.jpg
  docs/user-guide/img/button/saveas2.jpg
  docs/user-guide/img/button/settings2.jpg
  docs/user-guide/img/button/share2.jpg
  docs/user-guide/img/button/street-view-button.jpg
  docs/user-guide/img/button/tutorial2.jpg
  docs/user-guide/img/button/version.jpg
  docs/user-guide/img/exploring-maps/gui.jpg
  docs/user-guide/img/exploring-maps/map-viewer.jpg
  docs/user-guide/img/menu-bar/about.jpg
  docs/user-guide/img/menu-bar/menu-bar.jpg
  docs/user-guide/img/menu-bar/options-menu.jpg
  docs/user-guide/img/menu-bar/performed-search.jpg
  docs/user-guide/img/menu-bar/rome.jpg
  docs/user-guide/img/menu-bar/settings-panel.jpg
  docs/user-guide/img/menu-bar/settings.jpg
  docs/user-guide/import.md
  docs/user-guide/layer-settings.md
  docs/user-guide/mapstore-toolbars.md
  docs/user-guide/measure.md
  docs/user-guide/print.md
  docs/user-guide/resources-properties.md
  docs/user-guide/share.md
  docs/user-guide/side-bar.md
  docs/user-guide/street-view.md
  docs/user-guide/widgets.md
  mkdocs.yml
Labels: Documentation, User Guide, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8623 backport 2022.01.xx - #8529 maxItems is now used from Identify plugin (#8539)
  web/client/components/data/identify/enhancers/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: enhancement, Backport, C044-VLAANDEREN-2021-SUPPORT

#8625 #8624 Increase package.json version of master branch
  package.json
Labels: Task, current-release

#8626 #8624 Updated changelog (master)
  CHANGELOG.md
Labels: current-release

#8627 #8624 Updated changelog (stable)
  CHANGELOG.md
Labels: Task

#8628 #8624 Update master java package versions to 1.5-SNAPSHOT
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
Labels: Task

#8629 Fixed mvn packages versions to 1.4.0
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
Labels: Task

#8592 #8591 Fix chart legend ordering matching colorCatagories order
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/translations/data.en-US.json
Labels: bug, Priority: Medium, C040-COMUNE_GE-2022-SUPPORT

#8631 [Backport 2022.01.xx] #8576 No feedback loading while query 3D Tiles layers (Identify) (#8602)
  web/client/actions/maplayout.js
  web/client/components/map/cesium/Map.jsx
  web/client/containers/MapViewer.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/epics/maplayout.js
  web/client/plugins/TOC.jsx
  web/client/plugins/map/selector.js
  web/client/reducers/mapInfo.js
  web/client/selectors/layers.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/cesium/ClickUtils.js
Labels: enhancement, Backport, C027-COMUNE_FI-2021-SUPPORT

#8617 #8597 Simplifying query params
  docs/developer-guide/map-query-parameters.md
  web/client/actions/__tests__/backgroundselector-test.js
  web/client/actions/__tests__/search-test.js
  web/client/actions/backgroundselector.js
  web/client/actions/search.js
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/catalog.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8589 backport 2022.02.xx - #8529 maxItems is now used from Identify plugin (#8539)
  web/client/components/data/identify/enhancers/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: enhancement, Backport, C044-VLAANDEREN-2021-SUPPORT

#8632 [Backport 2022.02.xx] #8576 No feedback loading while query 3D Tiles layers (Identify) (#8602)
  web/client/actions/maplayout.js
  web/client/components/map/cesium/Map.jsx
  web/client/containers/MapViewer.jsx
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
  web/client/epics/maplayout.js
  web/client/plugins/TOC.jsx
  web/client/plugins/map/selector.js
  web/client/reducers/mapInfo.js
  web/client/selectors/layers.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/cesium/ClickUtils.js
Labels: enhancement, Backport, C027-COMUNE_FI-2021-SUPPORT

#8636 [Backport 2022.02.xx] #8573 Fix permissions dropdowns (#8590)
  web/client/components/resources/modals/fragments/PermissionEditor.jsx
  web/client/components/resources/modals/fragments/__tests__/PermissionEditor-test.jsx
  web/client/themes/default/less/maps-properties.less
Labels: bug, Priority: High, Internal, Backport

#8635 [Backport 2022.02.xx] #8570 fallback for Attribute Table #8594
  web/client/components/data/featuregrid/FeatureEditorFallback.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/themes/default/less/featuregrid.less
Labels: bug, Priority: High, Internal, Backport

#8638 [Backport 2022.01.xx-c040] #8591 Fix chart legend ordering matching colorCatagories order (#8592)
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/translations/data.en-US.json
Labels: bug, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8639 [Backport 2022.02.xx] #8591 Fix chart legend ordering matching colorCatagories order (#8592)
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/translations/data.en-US.json
Labels: bug, Priority: High, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT
