Repository geosolutions-it/MapStore2, pull requests merged in 2022-10, with the labels that each got.

#8641 #8603 Error downloading filtered dataset, where filter is based on another layer
  web/client/observables/wps/__tests__/common-test.js
  web/client/observables/wps/common.js
Labels: bug, Priority: High, C145-MAPSTAND-2022-SUPPORT

#8607 #8545 LayerDownload: service selector
  web/client/actions/__tests__/layerdownload-test.js
  web/client/actions/layerdownload.js
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadDialog-test.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/epics/__tests__/data/download-estimation.xml.js
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
  web/client/plugins/LayerDownload.jsx
  web/client/reducers/__tests__/layerdownload-test.js
  web/client/reducers/layerdownload.js
  web/client/selectors/layerdownload.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, Priority: Medium, Internal, Good first issue, BackportNeeded

#8646 #8644 Resolving race condition that was preventing mapInfo parameter to work in some cases
  docs/developer-guide/map-query-parameters.md
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
Labels: bug, Priority: High, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8650 [Backport 2022.02.xx] Error downloading filtered dataset, where filter is based on another layer (#8603)
  web/client/observables/wps/__tests__/common-test.js
  web/client/observables/wps/common.js
Labels: bug, Backport, C145-MAPSTAND-2022-SUPPORT

#8656 #8644 Default service for background addition, documentation update, actions whitelist extension
  docs/developer-guide/map-query-parameters.md
  web/client/actions/search.js
  web/client/epics/__tests__/queryparam-test.js
  web/client/utils/QueryParamsUtils.js
Labels: bug, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8645 #7165 externalize datadir
  .github/workflows/tests.yml
  CONTRIBUTING.md
  README.md
  build.sh
  build/buildConfig.js
  build/devServer.js
  build/generateChangelog.js
  build/karma.conf.single-run.js
  build/tests-firefox.webpack.js
  docs/developer-guide/building-and-deploying.md
  docs/developer-guide/developing.md
  docs/developer-guide/documentation-guidelines.md
  docs/developer-guide/index.md
  docs/developer-guide/main-scripts.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/project-structure.md
  docs/developer-guide/release.md
  docs/developer-guide/writing-actions-reducers.md
  mkdocs.yml
  package.json
  product/pom.xml
  project/standard/templates/README.md
  project/standard/templates/build.sh
  project/standard/templates/web/pom.xml
  utility/projects/projectScripts.json
  web/client/configs/localConfig.json
  web/client/plugins/__tests__/TOC-test.jsx
  web/client/plugins/mapEditor/__tests__/MapEditorModal-test.jsx
Labels: enhancement, Priority: High, Internal, BackportNeeded, QF, DevOps

#8659 [Backport 2022.02.xx] #8597 Simplifying query parameters
  docs/developer-guide/map-query-parameters.md
  web/client/actions/__tests__/backgroundselector-test.js
  web/client/actions/__tests__/search-test.js
  web/client/actions/backgroundselector.js
  web/client/actions/search.js
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/catalog.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: High, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8643 #8642 Fixed mkdocs build
  docs/developer-guide/documentation-guidelines.md
  docs/developer-guide/map-plugin.md
  docs/requirements.txt
  docs/user-guide/application-context.md
  docs/user-guide/configure-map.md
  docs/user-guide/measure.md
  mkdocs.yml
Labels: bug, Priority: Medium, BackportNeeded

#8661 [Backport 2022.02.xx] #8520: Reduce dashboards clutter and widget update (#8555)
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/widgets/builder/wizard/map/MapSwitcher.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
  web/client/plugins/Dashboard.jsx
  web/client/themes/default/bootstrap-variables.less
  web/client/themes/default/less/widget.less
  web/client/themes/default/less/wizard.less
Labels: bug, enhancement, Backport, C040-COMUNE_GE-2022-SUPPORT

#8662 [Backport 2022.02.xx] #8559: Feature grid aliases and tooltips for columns (#8584)
  web/client/components/data/featuregrid/AttributeTable.jsx
  web/client/components/data/featuregrid/__tests__/AttributeTable-test.jsx
  web/client/components/data/featuregrid/__tests__/FeatureGrid-test.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/enhancers/utils.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/wfsTable-test.js
  web/client/components/widgets/enhancers/wfsTable/index.js
  web/client/components/widgets/enhancers/wfsTable/noPaginationFetch.js
  web/client/components/widgets/enhancers/wfsTable/virtualScrollFetch.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/plugins/widgetbuilder/TableBuilder.jsx
  web/client/plugins/widgets/getWidgetFilterRenderers.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
  web/client/themes/default/less/wizard.less
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: bug, enhancement, Backport, C040-COMUNE_GE-2022-SUPPORT

#8665 [Backport 2022.02.xx] #8642 Fixed mkdocs build
  docs/developer-guide/documentation-guidelines.md
  docs/developer-guide/map-plugin.md
  docs/requirements.txt
  docs/user-guide/application-context.md
  docs/user-guide/configure-map.md
  docs/user-guide/layer-settings.md
  docs/user-guide/measure.md
  mkdocs.yml
Labels: Documentation

#8649 [Backport 2022.01.xx] Error downloading filtered dataset, where filter is based on another layer (#8603)
  web/client/observables/wps/__tests__/common-test.js
  web/client/observables/wps/common.js
Labels: bug, Backport, C145-MAPSTAND-2022-SUPPORT

#8666 #8465 Imrpoving API and preventing issues from geostore
  build/devServer.js
  docs/developer-guide/developing.md
  product/pom.xml
Labels: enhancement, BackportNeeded

#8622 #8621 Widgets on map mobile view
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/LegendWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/SingleWidgetControls.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/TextWidget.jsx
  web/client/components/widgets/widget/WidgetContainer.jsx
  web/client/components/widgets/widget/__tests__/SingleWidgetControls-test.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
  web/client/plugins/widgets/withContainerDimensions.jsx
  web/client/themes/default/less/widget.less
Labels: enhancement, Priority: High, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8657 #8306 TOC - legend for WFS and Vector layers
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/__tests__/DefaultLayer-test.jsx
  web/client/components/TOC/fragments/MarkIcon.jsx
  web/client/components/TOC/fragments/StyleBasedLegend.jsx
  web/client/components/TOC/fragments/__tests__/MarkIcon-test.jsx
  web/client/components/TOC/fragments/__tests__/StyleBasedLegend-test.jsx
  web/client/themes/default/less/toc.less
  web/client/utils/VectorStyleUtils.js
Labels: Priority: Medium, Internal, StyleEditor, New Feature

#8676 8675 Query parameters documentation and `lon,lat` order unification
  docs/developer-guide/map-query-parameters.md
  web/client/epics/__tests__/queryparam-test.js
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8677 [Backport 2022.02.xx] #8545 LayerDownload: service selector
  web/client/actions/__tests__/layerdownload-test.js
  web/client/actions/layerdownload.js
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadDialog-test.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/epics/__tests__/data/download-estimation.xml.js
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
  web/client/plugins/LayerDownload.jsx
  web/client/reducers/__tests__/layerdownload-test.js
  web/client/reducers/layerdownload.js
  web/client/selectors/layerdownload.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, Priority: Medium, Internal, Backport

#8681 [Backport 2022.02.xx] #8675 Query parameters documentation and `lon,lat` order unification (#8676)
  docs/developer-guide/map-query-parameters.md
  web/client/epics/__tests__/queryparam-test.js
  web/client/utils/QueryParamsUtils.js
Labels: enhancement, Priority: High, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8682 Update User Guide - WFS and WPS for layer downloads
  docs/user-guide/export-data.md
  docs/user-guide/img/export_data/export_data_ex.jpg
  docs/user-guide/img/export_data/wfs-export-data.jpg
Labels: Documentation, Internal, User Guide

#8683 [Backport 2022.02.xx] #8654 Update User Guide - WFS and WPS for layer downloads (#8682)
  docs/user-guide/export-data.md
  docs/user-guide/img/export_data/export_data_ex.jpg
  docs/user-guide/img/export_data/wfs-export-data.jpg
Labels: Documentation, User Guide, Backport

#8689 User guide reupdate - Cesium viewer settings
  docs/user-guide/mapstore-toolbars.md
Labels: Documentation, Internal, User Guide, 3D

#8690 [Backport 2022.02.xx] #8415 User guide reupdate - Cesium viewer settings (#8689)
  docs/user-guide/mapstore-toolbars.md
Labels: Documentation, Internal, User Guide, Backport, 3D

#8687 #8686 Snapshot plugin refactoring
  web/client/components/mapcontrols/Snapshot/SnapshotPanel.jsx
  web/client/components/mapcontrols/Snapshot/css/snapshot.css
  web/client/plugins/Snapshot.jsx
Labels: enhancement, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8699 Produce build artifacts
  .github/workflows/build.yml
Labels: enhancement

#8678 8536 Resolving measure plugin draw conflicts
  web/client/components/map/leaflet/MeasurementSupport.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
Labels: bug, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8673 #8578 SEARCH_WITH_FILTER action: add popup support
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
Labels: bug, Priority: Medium, Internal

#8701 [Backport 2022.02.xx] #8686 Snapshot plugin refactoring (#8687)
  web/client/components/mapcontrols/Snapshot/SnapshotPanel.jsx
  web/client/components/mapcontrols/Snapshot/css/snapshot.css
  web/client/plugins/Snapshot.jsx
Labels: enhancement, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8688 #8621 Mobile widgets view minor improvements
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/LegendWidget.jsx
  web/client/components/widgets/widget/SingleWidgetControls.jsx
  web/client/plugins/Widgets.jsx
Labels: enhancement, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8704 #8536 Resolving measure plugin draw conflicts (#8678)
  web/client/components/map/leaflet/MeasurementSupport.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
Labels: bug, Priority: High, Backport, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8705 #8693 Register background selector epics with the map
  web/client/plugins/Map.jsx
Labels: bug, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8707 [Backport 2022.02.xx] #8693 Register catalog and background epics with the map (#8705) (#8703)
  web/client/plugins/Map.jsx
Labels: bug, Priority: High, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8708 #8695 Move Identify plugin into main bundle
  web/client/product/plugins.js
Labels: bug, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8710 [Backport 2022.02.xx] #8578 SEARCH_WITH_FILTER action: add popup support #8673
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
Labels: bug, Priority: Medium, Internal, Backport

#8601 #8600 BIL Terrain is not visible after switching between 3D/2D/3D
  web/client/utils/cesium/GeoServerBILTerrainProvider.js
Labels: bug, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8712 Update README file to point to docs.mapstore.geosolutionsgroup.com
  README.md
Labels: Priority: Low, Documentation

#8711 [Backport 2022.02.xx] #708 Move Identify plugin into main bundle; #8490 Fix issues for OpenID Login due to modularization; Add measure reducer into appReducers list
  web/client/product/main.jsx
  web/client/product/plugins.js
Labels: bug, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8709 #7934 fix some remaining zombie config and improved migration guideline
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: enhancement, Priority: Low, Documentation, BackportNeeded

#8379 Mobile override shallow merge fix
  web/client/stores/__tests__/StandardStore-test.js
  web/client/stores/defaultOptions.js
Labels: Mobile, External Contribution

#8714 #8588: Fix - Map config load on no widget config
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
Labels: bug, Priority: High, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8717 backport 2022.02.xx - #7934 fix some remaining zombie config and improved migration guideline (#8709)
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: Backport

#8715 [Backport 2022.02.xx] #8621 Widgets on mobile view; #8679 Custom colors are not applied in the widget
  web/client/components/widgets/widget/ChartWidget.jsx
  web/client/components/widgets/widget/CounterWidget.jsx
  web/client/components/widgets/widget/LegendWidget.jsx
  web/client/components/widgets/widget/MapWidget.jsx
  web/client/components/widgets/widget/SingleWidgetControls.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/TextWidget.jsx
  web/client/components/widgets/widget/WidgetContainer.jsx
  web/client/components/widgets/widget/__tests__/SingleWidgetControls-test.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
  web/client/plugins/widgets/withContainerDimensions.jsx
  web/client/themes/default/less/widget.less
Labels: enhancement, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8721 #8588: Fix - Effective handle of widget conversion
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
  web/client/utils/WidgetsUtils.js
Labels: bug, Priority: High, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8725 #8723 Fix for WMTS background issues due to `attribution` parameter; #8724 WMTS request identify flow fixes
  web/client/components/data/identify/viewers/row/RowViewer.jsx
  web/client/utils/leaflet/WMTS.js
  web/client/utils/mapinfo/__tests__/wmts-test.js
  web/client/utils/mapinfo/wmts.js
Labels: bug, BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#8700 #8706 get WFS feature from pick
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/cesium/ClickUtils.js
  web/client/utils/mapinfo/__tests__/wfs-test.js
  web/client/utils/mapinfo/wfs.js
Labels: bug, Priority: Medium, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8730 #8588: Multi-chart widget improvements
  docs/user-guide/img/widgets/chart-options.jpg
  docs/user-guide/widgets.md
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/chart/ChartSwitcher.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ChartSwitcher-test.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/widgetbuilder/ChartLayerSelector.jsx
  web/client/plugins/widgetbuilder/enhancers/chartLayerSelector.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: New Feature, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8737 [Backport 2022.02.xx] #8491 linter for markdown files
  .markdownlint.json
  .markdownlintignore
  docma-template/README.md
  docs/developer-guide/API-usage.md
  docs/developer-guide/code-conventions.md
  docs/developer-guide/configuration-files.md
  docs/developer-guide/custom-dependencies.md
  docs/developer-guide/customize-theme.md
  docs/developer-guide/dev-faq.md
  docs/developer-guide/dev-how-to.md
  docs/developer-guide/extensions.md
  docs/developer-guide/how-to-use-a-cdn.md
  docs/developer-guide/integrations/users/geoserver.md
  docs/developer-guide/integrations/users/ldap.md
  docs/developer-guide/integrations/users/openId.md
  docs/developer-guide/internationalization.md
  docs/developer-guide/local-config.md
  docs/developer-guide/map-query-parameters.md
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/plugins-architecture.md
  docs/developer-guide/plugins-documentation.md
  docs/developer-guide/plugins-howto.md
  docs/developer-guide/requirements.md
  docs/developer-guide/writing-epics.md
  docs/index.md
  docs/quick-start.md
  docs/user-guide/adding-widgets.md
  docs/user-guide/application-context.md
  docs/user-guide/attributes-table.md
  docs/user-guide/banner-section.md
  docs/user-guide/catalog.md
  docs/user-guide/configure-map.md
  docs/user-guide/connecting-widgets.md
  docs/user-guide/content-image-toolbar.md
  docs/user-guide/content-map-toolbar.md
  docs/user-guide/content-video-toolbar.md
  docs/user-guide/extension-library.md
  docs/user-guide/footer.md
  docs/user-guide/geocarousel-section.md
  docs/user-guide/home-page.md
  docs/user-guide/immersive-section.md
  docs/user-guide/managing-contexts.md
  docs/user-guide/managing-groups.md
  docs/user-guide/managing-users-and-groups.md
  docs/user-guide/managing-users.md
  docs/user-guide/map-catalog.md
  docs/user-guide/map-templates.md
  docs/user-guide/media-editor-window.md
  docs/user-guide/media-section.md
  docs/user-guide/paragraph-section.md
  docs/user-guide/print.md
  docs/user-guide/side-bar.md
  docs/user-guide/story-setting.md
  docs/user-guide/text-editor-toolbar.md
  docs/user-guide/timeline.md
  docs/user-guide/title-section.md
  docs/user-guide/toc.md
  docs/user-guide/web-section.md
  package.json
Labels: Priority: Medium, Documentation, Internal, Backport

#8720 #8718 geostyler: 3D - elevation properties
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/MultiInput.jsx
  web/client/components/styleeditor/__tests__/MultiInput-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/VectorStyleUtils.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: Priority: Medium, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8744 #8743 Frontend test and build github actions are failing
  web/client/components/misc/enhancers/utcDateWrapper.js
Labels: bug, Priority: Blocker

#8746 Backport 2022.02.xx - #8743 Frontend test and build github actions are failing (#8744)
  web/client/components/misc/enhancers/utcDateWrapper.js
Labels: Priority: Blocker, Backport

#8747 Backport 2022.01.xx - #8743 Frontend test and build github actions are failing (#8744)
  web/client/components/misc/enhancers/utcDateWrapper.js
Labels: Priority: Blocker, Backport

#8748 #8740 Move the mouse on 3D Tiles
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/utils/cesium/ClickUtils.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8751 #8726 The new widgets on the map are under the TOC
  web/client/configs/localConfig.json
  web/client/plugins/Widgets.jsx
  web/client/plugins/widgets/WidgetsTray.jsx
Labels: bug, Widgets, Regression, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8750 #8706 Restore multiple features selection on map click in 3D viewer
  build/testConfig.js
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/VectorStyleUtils-test.js
Labels: bug, C040-COMUNE_GE-2022-CUSTOM-SUPPORT
