Repository geosolutions-it/MapStore2, pull requests merged in 2022-04, with the labels that each got.

#8020 [Backport 2022.01.xx] #7106 Make map in GeoStory updated on the fly without need to save it (#7859)
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
Labels: enhancement, Priority: Low, Internal, Good first issue, Backport

#8038 set params endpoint
  docs/developer-guide/map-query-parameters.md
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsController.java
  java/services/src/test/java/it/geosolutions/mapstore/SetParamsControllerTest.java
Labels: enhancement, Priority: High, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#7898 7871 delete map plugin
  web/client/configs/localConfig.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/DeleteMap.jsx
  web/client/plugins/__tests__/DeleteMap-test.jsx
  web/client/product/plugins.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Medium, New Feature, BackportNeeded

#8039 8006 Extend queryparams API
  docs/developer-guide/map-query-parameters.md
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/config.js
  web/client/epics/identify.js
  web/client/epics/queryparams.js
  web/client/utils/IdentifyUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Priority: High, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8028 Issue #7983 - GeoStories - support of WMTS layers with tileMatrix configuration
  web/client/plugins/geostory/MediaViewer.js
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
Labels: bug, Priority: High, GeoStory, BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#8021 Issue #8004 - WMTS Background layers attributions handling
  web/client/components/background/BackgroundDialog.jsx
  web/client/components/background/BackgroundSelector.jsx
  web/client/components/background/__tests__/BackgroundDialog-test.jsx
  web/client/components/background/css/backgrounddialog.css
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/WMTSLayer.js
  web/client/components/map/leaflet/Layer.jsx
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/leaflet/plugins/WMTSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
Labels: enhancement, Priority: High, BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#8032 #7997 Fixed migration guidelines
  docs/developer-guide/mapstore-migration-guide.md
  project/custom/templates/backend/pom.xml
  project/standard/templates/backend/pom.xml
Labels: Documentation, BackportNeeded

#8031 [Backport 2022.01.xx] #7997 Fixed migration guidelines
  docs/developer-guide/mapstore-migration-guide.md
  project/custom/templates/backend/pom.xml
  project/standard/templates/backend/pom.xml
Labels: Documentation, Backport

#8056 backport 2022.01.xx - #7871 delete map plugin (#7898)
  web/client/configs/localConfig.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/DeleteMap.jsx
  web/client/plugins/__tests__/DeleteMap-test.jsx
  web/client/product/plugins.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/controls.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Medium, Backport, New Feature

#8051 [Backport 2022.01.xx] #7869 - Snap interaction (#7947, #8042, #8049)
  web/client/actions/__tests__/draw-test.js
  web/client/actions/draw.js
  web/client/components/data/featuregrid/toolbars/TSplitButton.jsx
  web/client/components/data/featuregrid/toolbars/TSplitButton.less
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/TSplitButton-test.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/components/data/featuregrid/toolbars/toolbar.css
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/draw-test.js
  web/client/reducers/draw.js
  web/client/selectors/__tests__/draw-test.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/draw.js
  web/client/selectors/layers.js
  web/client/themes/default/less/react-data-grid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, Backport, New Feature, C169-Rennes-Métropole-2021-GeOrchestra3

#8047 #8010: 3D Tiles Styling
  build/docma-config.json
  web/client/api/ThreeDTiles.js
  web/client/api/__tests__/ThreeDTiles-test.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/components/map/ErrorPanel.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/styleeditor/Editor.jsx
  web/client/components/styleeditor/FilterBuilder.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/Map.jsx
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/plugins/styleeditor/VectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
  web/client/utils/styleparser/ThreeDTilesStyleParser.js
  web/client/utils/styleparser/__tests__/ThreeDTilesStyleParser-test.js
Labels: enhancement, Priority: High, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7845 #1945 Make FeatureGrid attributes visibility selector counted when user exports grid data
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/FeatureEditorButton.jsx
  web/client/epics/layerdownload.js
  web/client/observables/wps/download.js
  web/client/plugins/LayerDownload.jsx
  web/client/plugins/widgetbuilder/FeatureEditorButton.jsx
  web/client/selectors/featuregrid.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: enhancement, Priority: Low, Good first issue, BackportNeeded

#8066 #8010: Disable undo and redo editor functionality for new vector style
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#8068 #8063 Document strategy of merging the map object with the current map
  docs/developer-guide/map-query-parameters.md
  web/client/epics/config.js
Labels: Priority: Medium, Documentation, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8070 backport 2022.01.xx - #8004 WMTS Background layers attributions handling (#8021)
  web/client/components/background/BackgroundDialog.jsx
  web/client/components/background/BackgroundSelector.jsx
  web/client/components/background/__tests__/BackgroundDialog-test.jsx
  web/client/components/background/css/backgrounddialog.css
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/WMTSLayer.js
  web/client/components/map/leaflet/Layer.jsx
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/leaflet/plugins/WMTSLayer.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
Labels: enhancement, Priority: High, Backport, C044-VLAANDEREN-2021-SUPPORT

#8073 [Backport 2022.01.xx] #8010: 3D Tiles Styling
  build/docma-config.json
  web/client/api/ThreeDTiles.js
  web/client/api/__tests__/ThreeDTiles-test.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/components/map/ErrorPanel.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/styleeditor/Editor.jsx
  web/client/components/styleeditor/FilterBuilder.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/Map.jsx
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/plugins/styleeditor/VectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StyleEditorUtils.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
  web/client/utils/styleparser/ThreeDTilesStyleParser.js
  web/client/utils/styleparser/__tests__/ThreeDTilesStyleParser-test.js
Labels: enhancement, Backport, C040-COMUNE_GE-2021-SUPPORT

#8078 [Backport 2022.01.xx] #8065: Fix layer identification in applying capabilities (#8069)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/api/catalog/CSW.js
  web/client/api/catalog/__tests__/CSW-test.js
  web/client/test-resources/csw/getRecordsResponseDC.xml
  web/client/test-resources/csw/getRecordsWithDcURI.xml
Labels: bug, Priority: High, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8072 #8012: 3D Tiles documentation
  docs/developer-guide/local-config.md
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/plugins/Map.jsx
Labels: Documentation, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#8084 #8083: Add an empty renderer for geometry types
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
Labels: bug, BackportNeeded

#8059 [Backport 2022.01.xx] #8006 #8034 Extend the map viewer query parameter API (#8038 #8039)
  docs/developer-guide/map-query-parameters.md
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsController.java
  java/services/src/test/java/it/geosolutions/mapstore/SetParamsControllerTest.java
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/config.js
  web/client/epics/identify.js
  web/client/epics/queryparams.js
  web/client/utils/IdentifyUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Priority: High, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8089 [Backport 2022.01.xx] #8063 Document strategy of merging the map object with the current map (#8068)
  docs/developer-guide/map-query-parameters.md
  web/client/epics/config.js
Labels: Priority: Medium, Documentation, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8095 [Backport 2022.01.xx] #8087: 3D Tiles Styling with filter
  web/client/components/data/query/GroupField.jsx
  web/client/components/styleeditor/FilterBuilder.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/ThreeDTilesStyleParser.js
  web/client/utils/styleparser/__tests__/ThreeDTilesStyleParser-test.js
Labels: bug, Backport, C040-COMUNE_GE-2021-SUPPORT

#8092 Update release.md
  docs/developer-guide/release.md
Labels: Documentation, BackportNeeded

#8062 backport 2022.01.xx - #7983 - GeoStories - support of WMTS layers with tileMatrix configuration (#8028)
  web/client/plugins/geostory/MediaViewer.js
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
Labels: enhancement, Priority: High, GeoStory, Backport, C044-VLAANDEREN-2021-SUPPORT

#8096 #7810 forcing the usage of JAVA_HOME in the binary scripts
  release/bin/mapstore2-startup.bat
  release/bin/mapstore2-startup.sh
Labels: bug, Priority: High, Binary Package, BackportNeeded

#8104 #7984 extending geoserver integration documentation
  docs/developer-guide/integrations/users/geoserver.md
Labels: Priority: Medium, Documentation, Internal

#8107 #7972 clean up of code related to MailingLists plugin
  build/docma-config.json
  docs/developer-guide/mapstore-migration-guide.md
  package.json
  web/client/product/assets/img/groups_logo.png
  web/client/product/assets/img/groups_logo_sm.gif
  web/client/product/assets/img/linkedin_group.png
  web/client/product/components/home/Footer.jsx
  web/client/product/components/home/MailingLists.jsx
  web/client/product/plugins.js
  web/client/product/plugins/MailingLists.jsx
  web/client/test-resources/data.es-ES.json
  web/client/test-resources/mergeConfigs/04_full_localConfig.json
  web/client/test-resources/mergeConfigs/05_result_Config.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, Priority: Low, Internal, BackportNeeded

#8108 Backport 2022.01.xx - #7984 extending geoserver integration documentation (#8104)
  docs/developer-guide/integrations/users/geoserver.md
Labels: Priority: Medium, Documentation, Internal, Backport

#8098 #7981 datadir doc improved
  docs/developer-guide/externalized-configuration.md
Labels: Priority: Medium, Documentation, Internal, BackportNeeded

#8109 Backport 2022.01.xx - #7972 clean up of code related to MailingLists plugin (#8107)
  build/docma-config.json
  docs/developer-guide/mapstore-migration-guide.md
  package.json
  web/client/product/assets/img/groups_logo.png
  web/client/product/assets/img/groups_logo_sm.gif
  web/client/product/assets/img/linkedin_group.png
  web/client/product/components/home/Footer.jsx
  web/client/product/components/home/MailingLists.jsx
  web/client/product/plugins.js
  web/client/product/plugins/MailingLists.jsx
  web/client/test-resources/data.es-ES.json
  web/client/test-resources/mergeConfigs/04_full_localConfig.json
  web/client/test-resources/mergeConfigs/05_result_Config.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, Priority: Low, Internal, Backport

#8110 Backport 2022.01.xx - #7981 datadir doc improved (#8098)
  docs/developer-guide/externalized-configuration.md
Labels: Priority: Medium, Documentation, Internal, Backport

#8111 Backport 2022.01.xx - #7810 forcing the usage of JAVA_HOME in the binary scripts (#8096)
  release/bin/mapstore2-startup.bat
  release/bin/mapstore2-startup.sh
Labels: bug, Priority: High, Binary Package, Backport

#8097 #7857 improving contributing guidelines
  CONTRIBUTING.md
Labels: Priority: Medium, Documentation, Internal, BackportNeeded

#8112 Backport 2022.01.xx - #7857 improving contributing guidelines (#8097)
  CONTRIBUTING.md
Labels: Priority: Medium, Documentation, Internal, Backport

#7901 Custom tileprovider losing attribution on map save
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue, BackportNeeded

#8114 #7948: Update map config with leaflet resolution
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
Labels: bug, Priority: Medium, Good first issue, BackportNeeded

#8116 Documentation update and typo fix
  docs/developer-guide/map-query-parameters.md
Labels: Documentation, C169-Rennes-Métropole-2021-GeOrchestra3

#8117 [Backport 2022.01.xx] #8116 Documentation update for query parameters API
  docs/developer-guide/map-query-parameters.md
Labels: Documentation, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8118 [Backport 2022.01.xx] #7860: Custom tileprovider losing attribution on map save (#7901)
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue, Backport

#8124 [Backport 2022.01.xx] #7948: Update map config with leaflet resolution (#8114)
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
Labels: bug, Priority: Medium, Good first issue, Backport

#8128 bump spring dependencies to 5.3.18
  java/pom.xml
  java/services/pom.xml
  java/web/pom.xml
Labels: Priority: High, Internal, dependencies

#8127 User Guide - Delete map plugin
  docs/user-guide/img/menu-bar/burger-menu.jpg
  docs/user-guide/menu-bar.md
Labels: Documentation, Internal, User Guide

#8122 User Guide - Editing with snapping
  docs/user-guide/attributes-table.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/add-new-snapping-geometry.gif
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/drawing-line-shape.gif
  docs/user-guide/img/attributes-table/drawing-point-shape.gif
  docs/user-guide/img/attributes-table/drawing-polygon-shape.gif
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/snap-new-layer.gif
  docs/user-guide/img/attributes-table/update-polygon-shape.gif
  docs/user-guide/img/button/snapping.jpg
Labels: Priority: High, Documentation, User Guide, BackportNeeded, C169-Rennes-Métropole-2021-GeOrchestra3

#8125 User Guide - WMTS Background layers attributions handling
  docs/user-guide/background.md
  docs/user-guide/img/background/add_wmts_background.jpg
  docs/user-guide/img/background/wmts-attribution.gif
Labels: Priority: High, Documentation, User Guide, C044-VLAANDEREN-2021-SUPPORT

#8123 User Guide - 3D Tiles tool
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/3dtiles_service.jpg
  docs/user-guide/img/layer-settings/3dtiles-style-panel.jpg
  docs/user-guide/img/layer-settings/3dtiles_style.jpg
  docs/user-guide/img/layer-settings/ex_3dtiles_style.gif
  docs/user-guide/img/layer-settings/filter_3dtiles_style.jpg
  docs/user-guide/img/layer-settings/point_3dtiles_text.jpg
  docs/user-guide/img/layer-settings/point_3dtiles_visual.jpg
  docs/user-guide/img/layer-settings/text-editor-3dtiles.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/side-bar.md
Labels: Priority: High, Documentation, User Guide, C040-COMUNE_GE-2021-SUPPORT

#8126 User Guide - No Save button on Map editing
  docs/user-guide/img/configure-map/configure-map.jpg
  docs/user-guide/img/configure-map/identify-format.jpg
  docs/user-guide/img/configure-map/layers-conf.jpg
  docs/user-guide/img/configure-map/position-zoom.jpg
  docs/user-guide/img/configure-map/setting-conf.jpg
Labels: Documentation, Internal, User Guide, BackportNeeded

#8129 backport 2022.01.xx - #8029 - Save button disappear on map Import (#8044)
  web/client/components/import/dragZone/enhancers/__tests__/useFiles-test.js
  web/client/components/import/dragZone/enhancers/processFiles.jsx
  web/client/components/import/dragZone/enhancers/useFiles.js
  web/client/plugins/import/Import.jsx
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: bug, Priority: High, Internal, Backport, Regression

#7977 User Guide - Layer Metadata tool
  docs/user-guide/img/button/info_button.jpg
  docs/user-guide/img/toc/layer_metadata_panel.jpg
  docs/user-guide/toc.md
Labels: Documentation, Internal, User Guide, BackportNeeded

#8132 [Backport 2022.01.xx] #8075 User Guide - Editing with snapping
  docs/user-guide/attributes-table.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/add-new-snapping-geometry.gif
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/drawing-line-shape.gif
  docs/user-guide/img/attributes-table/drawing-point-shape.gif
  docs/user-guide/img/attributes-table/drawing-polygon-shape.gif
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/snap-new-layer.gif
  docs/user-guide/img/attributes-table/update-polygon-shape.gif
  docs/user-guide/img/button/snapping.jpg
Labels: Priority: High, Documentation, User Guide, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8131 [Backport 2022.01.xx] #8080 User Guide - WMTS Background layers attributions handling
  docs/user-guide/background.md
  docs/user-guide/img/background/add_wmts_background.jpg
  docs/user-guide/img/background/wmts-attribution.gif
Labels: Priority: High, Documentation, User Guide, Backport, C044-VLAANDEREN-2021-SUPPORT

#8133 [Backport 2022.01.xx] #8074 User Guide - Delete map plugin
  docs/user-guide/img/menu-bar/burger-menu.jpg
  docs/user-guide/menu-bar.md
Labels: Documentation, Internal, User Guide, Backport

#8135 #8113: Allow unsecured source from catalog and force proxy
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/advanced_settings_wms.jpg
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/layer-settings.md
  web/client/api/catalog/WMS.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CommonAdvancedSettings-test.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/catalog/editor/__tests__/MainFormUtils-test.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/plugins/TOCItemsSettings.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Priority: High, New Feature, C098-REGIONE_TOSCANA-2022-SUPPORT

#8138 [Backport 2022.01.xx] #7442 User Guide - Layer Metadata tool
  docs/user-guide/img/button/info_button.jpg
  docs/user-guide/img/toc/layer_metadata_panel.jpg
  docs/user-guide/toc.md
Labels: Documentation, Internal, User Guide, Backport

#8140 [Backport 2022.01.xx] #8077 User Guide - No Save button on Map editing
  docs/user-guide/img/configure-map/configure-map.jpg
  docs/user-guide/img/configure-map/identify-format.jpg
  docs/user-guide/img/configure-map/layers-conf.jpg
  docs/user-guide/img/configure-map/position-zoom.jpg
  docs/user-guide/img/configure-map/setting-conf.jpg
Labels: Documentation, Internal, User Guide, Backport

#8139 [Backport 2022.01.xx] #8076 User Guide - 3D Tiles tool
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/3dtiles_service.jpg
  docs/user-guide/img/layer-settings/3dtiles-style-panel.jpg
  docs/user-guide/img/layer-settings/3dtiles_style.jpg
  docs/user-guide/img/layer-settings/ex_3dtiles_style.gif
  docs/user-guide/img/layer-settings/filter_3dtiles_style.jpg
  docs/user-guide/img/layer-settings/point_3dtiles_text.jpg
  docs/user-guide/img/layer-settings/point_3dtiles_visual.jpg
  docs/user-guide/img/layer-settings/text-editor-3dtiles.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/side-bar.md
Labels: Priority: High, Documentation, User Guide, Backport, C040-COMUNE_GE-2021-SUPPORT

#8146 [2022.01.xx backport] bump spring dependencies to 5.3.18 (#8128)
  java/pom.xml
  java/services/pom.xml
  java/web/pom.xml
Labels: Backport

#8147 Bump geostore version to 1.8.1
  java/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: dependencies

#8143 Fixes #8142 adding the @mapstore/patcher alias to karma config file
  project/standard/static/karma.conf.continuous-test.js
  project/standard/static/karma.conf.single-run.js
Labels: BackportNeeded

#8150 backport 2022.01.xx - #8142 adding the @mapstore/patcher alias to karma config file (#8143)
  project/standard/static/karma.conf.continuous-test.js
  project/standard/static/karma.conf.single-run.js
Labels: Backport
