Repository geosolutions-it/MapStore2, pull requests merged in 2022-03, with the labels that each got.

#7854 Issue #7853; 3D zoom to map via share URL
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/enhancers/onMapViewChanges.js
  web/client/components/share/SharePanel.jsx
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/plugins/Share.jsx
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: enhancement, Priority: Medium, C040-2020-COMUNE_GE-SUPPORT

#7886 7878 handles range colors in color Class Modal
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
  web/client/components/charts/__tests__/sample_data.js
  web/client/components/style/ThemaClassesEditor.jsx
  web/client/components/style/__tests__/ThemaClassesEditor-test.jsx
  web/client/components/widgets/builder/wizard/chart/ColorClassModal.jsx
  web/client/components/widgets/builder/wizard/chart/RangeAttributeClassForm.jsx
  web/client/components/widgets/builder/wizard/chart/TextAttributeClassForm.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ColorClassModal-test.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/sample_data.js
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/WPSWidgetOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, C070-NPA-CGG-2021-DEV

#7896 Issue #7895 Autocomplete drop down menu won't populate on first click
  web/client/observables/autocomplete.js
Labels: bug, Priority: Medium, Internal

#7904 Backport 2021.01.xx - #7800: Fix csw parsing (#7803)
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: bug, Priority: Blocker, Regression, C169-Rennes-Métropole-2021-GeOrchestra3

#7891 #7890: align applicationContext-print.xml to work with upgraded mapfi…
  docs/developer-guide/mapstore-migration-guide.md
  java/printing/pom.xml
  java/printing/webapp/applicationContext-print.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/printing/applicationContext-print.xml
Labels: enhancement, Priority: High, C231-GEOINFO_CO-2021-AIT

#7908 Issue #7907 - Undefined colorCategories results
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/__tests__/WidgetChart-test.js
Labels: bug

#7912 Revert "#7890: align applicationContext-print.xml to work with upgraded mapfi…"
  docs/developer-guide/mapstore-migration-guide.md
  java/printing/pom.xml
  java/printing/webapp/applicationContext-print.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/printing/applicationContext-print.xml
Labels: bug

#7913 Issue #7853; 3D zoom to map via share URL - fix after test
  web/client/components/share/SharePanel.jsx
Labels: enhancement, Priority: Medium, C040-COMUNE_GE-2021-SUPPORT

#7867 Issue #7866; updated UI enhancements in mobile maps
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/configs/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/product/assets/css/mobile.css
Labels: enhancement, Priority: Low, Mobile, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#7921 #7349 Updated dependencies and package versions for 2022.02.xx
  java/services/pom.xml
  java/web/pom.xml
  package.json
  project/standard/templates/web/pom.xml
Labels: Environment

#7925 Fixed versions for 2022.01.xx
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  release/bin-war/pom.xml
Labels: Environment

#7931 #7007: Fix cesium css import
  build/buildConfig.js
  build/karma.conf.continuous-test.js
  build/karma.conf.single-run.js
  build/testConfig.js
  web/client/components/map/cesium/Map.jsx
Labels: bug, BackportNeeded

#7929 [Backport 2022.01.xx] #7866; updated UI enhancements in mobile maps
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/configs/localConfig.json
  web/client/plugins/Identify.jsx
  web/client/product/assets/css/mobile.css
Labels: enhancement, Priority: Low, Mobile, Backport, C040-COMUNE_GE-2021-SUPPORT

#7927 Issue #7853 - fix regression that allowed heading, pitch, roll input numbers to exceed given range
  web/client/components/share/SharePanel.jsx
  web/client/reducers/map.js
  web/client/utils/CoordinatesUtils.js
Labels: enhancement, Priority: High, C040-COMUNE_GE-2021-SUPPORT

#7943 #7938 Fix version of proxy to 1.1-SNAPSHOT
  docs/developer-guide/mapstore-migration-guide.md
  java/web/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: bug

#7946 [Backport 2022.01.xx] #7853 - 3D Zoom to map via share URL
  web/client/components/share/SharePanel.jsx
  web/client/reducers/map.js
  web/client/utils/CoordinatesUtils.js
Labels: enhancement, Priority: High, Backport, New Feature, C040-COMUNE_GE-2021-SUPPORT

#7930 #7893: A wrong GML format is used for the WPS export spatial filter
  web/client/epics/layerdownload.js
Labels: bug

#7876 Issue #7868: fix error that throws error when click in empty space of map in mobile view
  web/client/epics/measurement.js
Labels: bug, Priority: High, Internal, BackportNeeded, Regression

#7955 [Backport 2022.01.xx] #7007: Fix cesium css import (#7931)
  build/buildConfig.js
  build/karma.conf.continuous-test.js
  build/karma.conf.single-run.js
  build/testConfig.js
  web/client/components/map/cesium/Map.jsx
Labels: bug, Backport

#7799 Updated german translations (de-DE)
  web/client/translations/data.de-DE.json
Labels: enhancement, Priority: Low, BackportNeeded

#7954 [Backport 2022.01.xx] #7007: fix cesium terrain layer and imagery positions (#7924)
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/utils/cesium/BILTerrainProvider.js
Labels: bug, enhancement, Internal, Backport, C040-COMUNE_GE-2021-SUPPORT

#7942 #7890: align applicationContext-print.xml to work with upgraded mapfish-print library
  docs/developer-guide/mapstore-migration-guide.md
  java/printing/assembly/mapstore-printing.xml
  java/printing/pom.xml
  java/printing/webapp/applicationContext-print.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  project/standard/templates/web/src/printing/applicationContext-print.xml
Labels: enhancement, Priority: High, C231-GEOINFO_CO-2021-AIT

#7956 [Backport 2022.01.xx] #7868: fix error that throws error when click in empty space of map in mobile
  web/client/epics/measurement.js
Labels: bug, Priority: High, Internal, Backport, Regression

#7959 [Backport 2022.01.xx] #7893: A wrong GML format is used for the WPS export spatial filter
  web/client/epics/layerdownload.js
Labels: bug, Priority: High, Backport

#7941 User Guide - 3D Zoom to via share URL
  docs/user-guide/img/share/share_3d_map.jpg
  docs/user-guide/img/share/share_window_3d_map_options.jpg
  docs/user-guide/share.md
Labels: C040-2020-COMUNE_GE-SUPPORT, Documentation, User Guide

#7968 [Backport 2022.01.xx] #7905 User Guide - 3D Zoom to via share URLs (#7941 )
  docs/user-guide/img/share/share_3d_map.jpg
  docs/user-guide/img/share/share_window_3d_map_options.jpg
  docs/user-guide/share.md
Labels: C040-2020-COMUNE_GE-SUPPORT, Documentation, User Guide, Backport

#7915 User Guide - Customize the Pie and Bar Charts in Widgets option
  docs/user-guide/custom_colors_settings.jpg
  docs/user-guide/img/button/custom-button.jpg
  docs/user-guide/img/widgets/add-new-entry-after.jpg
  docs/user-guide/img/widgets/add-new-entry-before.jpg
  docs/user-guide/img/widgets/alphanumeric.jpg
  docs/user-guide/img/widgets/bar_type.jpg
  docs/user-guide/img/widgets/classification-attribute.gif
  docs/user-guide/img/widgets/color-customization-alhanumeric-attribute.gif
  docs/user-guide/img/widgets/color-customization-numeric-attribute.gif
  docs/user-guide/img/widgets/custom_colors.gif
  docs/user-guide/img/widgets/custom_colors_settings.jpg
  docs/user-guide/img/widgets/default_class_label.jpg
  docs/user-guide/img/widgets/grouped_chart.jpg
  docs/user-guide/img/widgets/numeric.jpg
  docs/user-guide/img/widgets/stacked-chart.jpg
  docs/user-guide/widgets.md
Labels: Documentation, User Guide, BackportNeeded, C070-NPA-CGG-2021-DEV

#7971 Removed mailing list plugin from configuration
  web/client/configs/localConfig.json
Labels: Task

#7973 [Backport 2022.01.xx] #7903 User Guide - Customize the Pie and Bar Charts in Widgets option (#7915 )
  docs/user-guide/img/widgets/add-new-entry-after.jpg
  docs/user-guide/img/widgets/add-new-entry-before.jpg
  docs/user-guide/img/widgets/alphanumeric.jpg
  docs/user-guide/img/widgets/bar_type.jpg
  docs/user-guide/img/widgets/classification-attribute.gif
  docs/user-guide/img/widgets/color-customization-alhanumeric-attribute.gif
  docs/user-guide/img/widgets/color-customization-numeric-attribute.gif
  docs/user-guide/img/widgets/custom-button.jpg
  docs/user-guide/img/widgets/custom_colors.gif
  docs/user-guide/img/widgets/custom_colors_settings.gif
  docs/user-guide/img/widgets/custom_colors_settings.jpg
  docs/user-guide/img/widgets/default_class_label.jpg
  docs/user-guide/img/widgets/grouped_chart.jpg
  docs/user-guide/img/widgets/numeric.jpg
  docs/user-guide/img/widgets/stacked-chart.jpg
  docs/user-guide/widgets.md
Labels: Documentation, User Guide, Backport, C070-NPA-CGG-2021-DEV

#7974 [Backport 2022.01.xx] Removed mailing list plugin from configuration (#7971)
  web/client/configs/localConfig.json
Labels: Task

#7923 Updated CHANGELOG.md
  CHANGELOG.md
Labels: Documentation

#7922 Updated CHANGELOG.md (master)
  CHANGELOG.md
Labels: Documentation

#7899 wrong getCapabilities request sent for csw
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/test-resources/csw/getRecordsNoWMS.xml
  web/client/test-resources/csw/getRecordsWithDcURI.xml
Labels: bug, Priority: High, Internal, Good first issue, BackportNeeded

#7999 [Backport 2022.01.xx] #7849: wrong getCapabilities request sent for csw
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/test-resources/csw/getRecordsNoWMS.xml
  web/client/test-resources/csw/getRecordsWithDcURI.xml
Labels: bug, Internal, Good first issue, Backport

#7993 7991 fix query param issue regression
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
Labels: bug, Priority: High, Internal, BackportNeeded, Regression

#8001 #8000: fixes regression in Print plugin with the flag useFixedScales
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: bug, Priority: High, Internal, BackportNeeded

#7986 Add base support for 3d tiles layers
  java/web/src/main/resources/proxy.properties
  web/client/api/CSW.js
  web/client/api/WMS.js
  web/client/api/catalog/CSW.js
  web/client/api/catalog/TMS.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/WFS.js
  web/client/api/catalog/WMS.js
  web/client/api/catalog/WMTS.js
  web/client/api/catalog/__tests__/CSW-test.js
  web/client/api/catalog/__tests__/TMS-test.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/api/catalog/__tests__/WMTS-test.js
  web/client/api/catalog/backgrounds.js
  web/client/api/catalog/common.js
  web/client/api/catalog/index.js
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordGrid-test.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/buttons/AddTMS.jsx
  web/client/components/catalog/buttons/AddTileProvider.jsx
  web/client/components/catalog/buttons/__tests__/AddTMS-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/cesium/plugins/index.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
  web/client/utils/CatalogUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Priority: High, C040-COMUNE_GE-2021-SUPPORT

#8013 [Backport 2022.01.xx] #8009: Add base support for 3d tiles layers (#7986)
  java/web/src/main/resources/proxy.properties
  web/client/api/CSW.js
  web/client/api/WMS.js
  web/client/api/catalog/CSW.js
  web/client/api/catalog/TMS.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/WFS.js
  web/client/api/catalog/WMS.js
  web/client/api/catalog/WMTS.js
  web/client/api/catalog/__tests__/CSW-test.js
  web/client/api/catalog/__tests__/TMS-test.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/api/catalog/__tests__/WMTS-test.js
  web/client/api/catalog/backgrounds.js
  web/client/api/catalog/common.js
  web/client/api/catalog/index.js
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordGrid-test.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/buttons/AddTMS.jsx
  web/client/components/catalog/buttons/AddTileProvider.jsx
  web/client/components/catalog/buttons/__tests__/AddTMS-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/cesium/plugins/index.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
  web/client/utils/CatalogUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: Backport, C040-COMUNE_GE-2021-SUPPORT

#8011 #8008: Improve visibility of 3d tiles
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/test-resources/3dtiles/tileset.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Priority: High, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#8016 #8008: Improve update model matrix function
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#8015 [Backport 2022.01.xx] #8008: Improve visibility of 3d tiles (#8011)
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/test-resources/3dtiles/tileset.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: Backport, C040-COMUNE_GE-2021-SUPPORT

#8017 [Backport 2022.01.xx] #8008 improve update model matrix function (#8016)
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
Labels: bug, Backport, C040-COMUNE_GE-2021-SUPPORT

#7859 #7106 Make map in GeoStory updated on the fly without need to save it…
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/components/geostory/contents/ContentToolbar.jsx
Labels: enhancement, Priority: Low, Internal, Good first issue, BackportNeeded

#8003 Issue #7776; fix for overflowing display tab
  web/client/components/layout/BorderLayout.jsx
  web/client/components/misc/wizard/WizardContainer.jsx
  web/client/themes/default/less/toc.less
  web/client/themes/default/less/wizard.less
Labels: bug, Priority: Medium, Internal, Dashboard, GeoStory, Good first issue

#8019 #8018: Implement get feature info for 3D Tiles
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/mapinfo/__tests__/threeDTiles-test.js
  web/client/utils/mapinfo/threeDTiles.js
Labels: BackportNeeded, C040-COMUNE_GE-2021-SUPPORT

#8022 [Backport 2022.01.xx] #8018: Implement get feature info for 3D Tiles (#8019)
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/mapinfo/__tests__/threeDTiles-test.js
  web/client/utils/mapinfo/threeDTiles.js
Labels: C040-2020-COMUNE_GE-SUPPORT, Backport

#8025 Tentative fix of the build
  docs/requirements.txt
Labels: Documentation, BackportNeeded

#8026 Backport 2022.01.xx - Tentative fix of the build (#8025)
  docs/requirements.txt
Labels: Documentation, Backport

#8024 [Backport 2022.01.xx] #7776 - fix for overflowing display tab
  web/client/components/layout/BorderLayout.jsx
  web/client/components/misc/wizard/WizardContainer.jsx
  web/client/themes/default/less/toc.less
  web/client/themes/default/less/wizard.less
Labels: bug, Priority: Medium, Internal, Dashboard, GeoStory, Good first issue, Backport

#8007 [Backport 2022.01.00] #6998 Move JRE artifact (#7957)
  release/pom.xml
Labels: Backport

#8027 Update http_proxy dependency to 1.3-SNAPSHOT
  java/web/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: enhancement, Priority: High, Internal

#7947 #7869 Snapping interaction implementation
  web/client/actions/__tests__/draw-test.js
  web/client/actions/draw.js
  web/client/components/data/featuregrid/toolbars/TSplitButton.jsx
  web/client/components/data/featuregrid/toolbars/TSplitButton.less
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/TSplitButton-test.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/components/data/featuregrid/toolbars/toolbar.css
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/plugins/map/index.js
  web/client/reducers/__tests__/draw-test.js
  web/client/reducers/draw.js
  web/client/selectors/__tests__/draw-test.js
  web/client/selectors/__tests__/layers-test.js
  web/client/selectors/draw.js
  web/client/selectors/layers.js
  web/client/themes/default/less/react-data-grid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: High, New Feature, C169-Rennes-Métropole-2021-GeOrchestra3

#8035 #8030: Share panel orientation fix
  web/client/components/share/SharePanel.jsx
  web/client/reducers/map.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CoordinatesUtils.js
Labels: bug, Priority: High, Internal

#8037 [Backport 2022.01.xx] #8030: Share panel orientation fix
  web/client/components/share/SharePanel.jsx
  web/client/reducers/map.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/CoordinatesUtils.js
Labels: bug, Priority: High, Internal, Backport

#8040 Revert "Update http_proxy dependency to 1.3-SNAPSHOT"
  java/web/pom.xml
  project/custom/templates/web/pom.xml
  project/standard/templates/web/pom.xml
Labels: Priority: High

#8045 Fixed Mkdocs configuration
  mkdocs.yml
Labels: bug, Priority: Blocker, Documentation, BackportNeeded

#8046 [Backport 2022.01.xx] #8041: Fixed Mkdocs configuration (#8045)
  mkdocs.yml
Labels: Backport
