Repository geosolutions-it/MapStore2, pull requests merged in 2022-07, with the labels that each got.

#8353 #7934 add more info on deployed version
  build/prod-webpack.config.js
  build/webpack.config.js
  package.json
  project/standard/templates/prod-webpack.config.js
  project/standard/templates/webpack.config.js
  web/client/components/Version/VersionDialog.jsx
  web/client/components/Version/__tests__/VersionDialog-test.js
  web/client/configs/localConfig.json
  web/client/plugins/Version.jsx
  web/client/selectors/controls.js
  web/client/themes/default/less/version.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Priority: Low, Internal, Good first issue, New Feature

#8349 #8330 depthtest style option
  docs/developer-guide/maps-configuration.md
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/styleeditor/VectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: Priority: Medium, StyleEditor, New Feature, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8376 #8358: Bring back annotations to burger menu
  web/client/plugins/Annotations.jsx
Labels: bug, Priority: High, Regression

#8381 #8374: Request of BILTerrainProvider layer are not using proxy url
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/TerrainLayer.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/utils/cesium/BILTerrainProvider.js
Labels: bug, Priority: High, Internal, 3D

#8383 Issue #8283 - Error in parsring getCapabilities response for CSW `<dc:URI>` tags
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: bug, BackportNeeded

#8384 backport 2022.01.xx-c027 - #8382 Catalog component - CSW service - Importing a single <dc:URI> reference will fail parsing (#8383)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: bug, Backport, C027-COMUNE_FI-2021-SUPPORT

#8368 #8347: Fix time cursor when loading time layer
  web/client/reducers/__tests__/timeline-test.js
  web/client/reducers/timeline.js
Labels: bug, Priority: High, Internal

#8386 #8377: Make time slider expanded state configurable
  web/client/plugins/Timeline.jsx
  web/client/themes/default/less/timeline.less
Labels: enhancement, Priority: High

#8380 Revert "temporary fix issue with keycloak config"
  product/config/db/geostore-spring-security-db.xml
  product/config/ldap/geostore-spring-security-ldap.xml
  web/src/config/db/geostore-spring-security-db.xml
  web/src/config/ldap/geostore-spring-security-ldap.xml
Labels: C211-GEOFIT-2022-OPENID

#8390 [Backport geonode-3.3.x] #8377: Make time slider expanded state configurable (#8386)
  docs/requirements.txt
  mkdocs.yml
  web/client/plugins/Timeline.jsx
  web/client/themes/default/less/timeline.less
Labels: enhancement, Priority: High, Backport

#8387 Keycloak SSO
  docs/developer-guide/integrations/sso/img/configure-mapstore-client.jpg
  docs/developer-guide/integrations/sso/img/copy-mapstore-client-config.jpg
  docs/developer-guide/integrations/sso/img/copy-mapstore-client-config.png
  docs/developer-guide/integrations/sso/img/kc-create-client.jpg
  docs/developer-guide/integrations/sso/img/kc-create-mapstore-client.jpg
  docs/developer-guide/integrations/sso/keycloak-impl.md
  docs/developer-guide/integrations/sso/keycloak.md
  docs/developer-guide/integrations/users/openId.md
  mkdocs.yml
  web/client/actions/login.js
  web/client/components/security/modals/LoginModal.jsx
  web/client/epics/login.js
  web/client/plugins/__tests__/Login-test.js
  web/client/test-resources/js/keycloak.js
  web/client/test-resources/jwtSampleTokens.js
  web/client/utils/KeycloakUtils.js
  web/client/utils/__tests__/KeycloakUtils-test.js
Labels: C211-GEOFIT-2022-OPENID

#8396 Add default clamp to ground to billboard and labels
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, Priority: Low, Internal, StyleEditor, 3D

#8395 #8373: BILTerrainProvider enhancement of WMS parser
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/map/cesium/plugins/TerrainLayer.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/utils/cesium/BILTerrainProvider.js
  web/client/utils/cesium/WMSUtils.js
  web/client/utils/cesium/__tests__/WMSUtils-test.js
Labels: enhancement, Priority: High, BackportNeeded, C027-COMUNE_FI-2021-SUPPORT, 3D

#8392 #8336 clamp to ground for polylines on style editor
  docs/developer-guide/maps-configuration.md
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, Priority: Medium, Internal, StyleEditor, 3D

#8402 #8400: CSW - Manipulate getCapabilities based on capability flag
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: enhancement, Priority: High, BackportNeeded, C027-COMUNE_FI-2021-SUPPORT

#8401 8337 classification type option
  docs/developer-guide/maps-configuration.md
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, Priority: Low, Internal, StyleEditor, 3D

#8375 #8372: Fix export after setting up a filter in attribute table
  web/client/epics/layerdownload.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: bug, Priority: High, C040-COMUNE_GE-2022-SUPPORT

#8394 #8388 Making sure that numeric 0 values of query params are processed properly
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: bug, Priority: Medium

#8408 [Backport 2022.01.xx] #8373: BILTerrainProvider enhancement of WMS parser (#8395)
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/utils/cesium/BILTerrainProvider.js
  web/client/utils/cesium/WMSUtils.js
  web/client/utils/cesium/__tests__/WMSUtils-test.js
Labels: enhancement, Priority: High, Backport, C027-COMUNE_FI-2021-SUPPORT, 3D

#8410 [Backport 2022.01.xx] #8400: CSW - Manipulate getCapabilities based on capability flag (#8402)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
Labels: enhancement, Priority: High, Backport, C027-COMUNE_FI-2021-SUPPORT

#8409 Update Search.jsx documentation
  web/client/plugins/Search.jsx
Labels: Documentation

#8419 [#8413] Backend changes to /rest/config/setParams endpoint to support multiple embedded maps via POST on the same page
  docs/developer-guide/map-query-parameters.md
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsUUIDStrategy.java
  java/services/src/test/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsControllerTest.java
Labels: enhancement, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8412 #8393 Fetching parameters data from sessionStorage using inner object and unique identifier
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Priority: High, C169-Rennes-Métropole-2021-GeOrchestra3

#8430 [Backport 2022.01.xx-geOrchestra] #8393 Fetching parameters data from sessionStorage using unique identifier per request (#8412)(#8421)
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Priority: High, Backport

#8277 Fix tileprovider print requests for remote URLs containing a query
  web/client/test-resources/layers/tileprovider.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: External Contribution

#8432 [Backport 2022.01.xx-c040] #8330 & #8372: Depth style option update and attributes table export fix
  docs/developer-guide/maps-configuration.md
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/epics/layerdownload.js
  web/client/plugins/styleeditor/VectorStyleEditor.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, StyleEditor, Backport, New Feature, 3D, C040-COMUNE_GE-2022-SUPPORT, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8433 [C105 Branch] Aligned package.json with latest fixes on test libs and updates
  package.json
Labels: C105-2021-EMSA-CGD

#8431 [C105 Branch] - DrawSupport hole interaction
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/components/map/openlayers/hole/DrawHole.js
  web/client/components/map/openlayers/hole/ext.js
Labels: C105-2021-EMSA-CGD

#8438 [Backport 2022.01.xx-c040] #8336: Clamp to ground for polylines on style editor (#8392)
  docs/developer-guide/maps-configuration.md
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, StyleEditor, Backport, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8439 #8403: Fix - Map widget sync issue
  web/client/components/widgets/enhancers/__tests__/dependenciesToMapProp-test.jsx
  web/client/components/widgets/enhancers/dependenciesToMapProp.js
Labels: bug, Priority: High, Dashboard, C040-COMUNE_GE-2022-SUPPORT

#8399 CQL INCLUDE filter support for MapStore
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
  web/client/utils/ogc/Filter/fromObject.js
Labels: Priority: Low, C105-2021-EMSA-CGD

#8443 [Backport 2022.01.xx-c040] #8403: Fix - Map widget sync issue (#8439)
  web/client/components/widgets/enhancers/__tests__/dependenciesToMapProp-test.jsx
  web/client/components/widgets/enhancers/dependenciesToMapProp.js
Labels: bug, Priority: High, Dashboard, Backport, C040-COMUNE_GE-2022-SUPPORT

#8446 Allowing rest calls from app proxy and update of localConfig for new domain name of gs-stable GS
  java/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
  web/client/configs/localConfig.json
Labels: Priority: High, Internal, Regression

#8447 Documentation update: contexts and sidebar menu
  docs/developer-guide/mapstore-migration-guide.md
Labels: Priority: High, Documentation, Internal
