Repository geosolutions-it/MapStore2, pull requests merged in 2022-06, with the labels that each got.

#8224 fixes #7554 annotations circle radius changing
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
Labels: bug, Priority: Medium, Internal, Good first issue

#8281 backport #7554 Resolves changes to annotations circle radius
  web/client/epics/__tests__/annotations-test.js
  web/client/epics/annotations.js
Labels: bug, Priority: Medium, Internal, Good first issue

#8265 #8227 WFS identify in Cesium and layer settings
  web/client/components/TOC/fragments/settings/FeatureInfo.jsx
  web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/utils/IdentifyUtils.js
Labels: New Feature, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8285 #7918 Removing custom template from project creation script
  docs/developer-guide/project-creation-script.md
  project/custom/static/assets/css/mapstore2.css
  project/custom/static/assets/img/MapStore2.png
  project/custom/static/babel.config.js
  project/custom/static/config.json
  project/custom/static/configs/newgeostory.json
  project/custom/static/js/__tests__/app-test.js
  project/custom/static/js/app.jsx
  project/custom/static/js/appConfig.js
  project/custom/static/js/components/MapPlugin.jsx
  project/custom/static/js/components/__tests__/map-test.js
  project/custom/static/js/pages/Home.jsx
  project/custom/static/js/pages/Main.jsx
  project/custom/static/js/plugins.js
  project/custom/static/jsconfig.json
  project/custom/static/karma.conf.continuous-test.js
  project/custom/static/karma.conf.single-run.js
  project/custom/static/tests.webpack.js
  project/custom/static/updateDevDependencies.js
  project/custom/templates/.gitignore
  project/custom/templates/README.md
  project/custom/templates/backend/pom.xml
  project/custom/templates/backend/src/main/java/placeholder
  project/custom/templates/backend/src/main/resources/placeholder
  project/custom/templates/backend/src/test/java/placeholder
  project/custom/templates/backend/src/test/resources/placeholder
  project/custom/templates/build.sh
  project/custom/templates/index.html
  project/custom/templates/localConfig.json
  project/custom/templates/pom.xml
  project/custom/templates/prod-webpack.config.js
  project/custom/templates/web/pom.xml
  project/custom/templates/web/src/main/resources/geostore-datasource-ovr.properties
  project/custom/templates/web/src/main/resources/log4j.properties
  project/custom/templates/web/src/main/resources/mapstore.properties
  project/custom/templates/web/src/main/resources/proxy.properties
  project/custom/templates/web/src/main/resources/sample_categories.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
  project/custom/templates/web/src/main/webapp/WEB-INF/web.xml
  project/custom/templates/webpack.config.js
Labels: Priority: Medium, Internal, ms-project

#8309 [Backport 2022.01.xx] #8252 User Guide - Time Line support of time values as intervals
  docs/user-guide/img/timeline/snap-to-guide-layer.jpg
  docs/user-guide/img/timeline/time-interval-snap-point.gif
  docs/user-guide/img/timeline/timeline-animation-settings.jpg
  docs/user-guide/timeline.md
Labels: Documentation, Timeline, User Guide, Backport, C044-VLAANDEREN-2021-SUPPORT

#8279 #8266 Use mapType from state to properly display cesium sharing options
  web/client/plugins/Share.jsx
Labels: bug, Priority: High, Internal, Good first issue, 3D

#8317 #8310: Improving Cesium performance with explicit rendering
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
Labels: enhancement, Priority: High, C125-AUSTROCONTROL-2022-MS_3D_PILOT

#8323 Create terrain layer type
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/TerrainLayer.js
  web/client/components/map/cesium/plugins/index.js
Labels: investigation, New Feature, 3D, C125-AUSTROCONTROL-2022-MS_3D_PILOT

#8327 Update webpack-cli
  package.json
Labels: bug, Internal, dependencies, BackportNeeded

#8329 [Backport 2022.01.xx] Update webpack-cli
  package.json
Labels: Backport

#8320 #8319 Making POST method of getting query parameters work again on master
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/queryparams.js
  web/client/product/appConfigEmbedded.js
  web/client/product/main.jsx
  web/client/utils/QueryParamsUtils.js
Labels: bug, QueryParam, Regression

#7873 #7872 Client work on openID support
  docs/developer-guide/integrations/openId.md
  docs/developer-guide/mapstore-migration-guide.md
  java/web/src/main/resources/applicationContext.xml
  java/web/src/main/webapp/WEB-INF/web.xml
  mkdocs.yml
  product/config/db/geostore-spring-security-db.xml
  product/config/ldap/geostore-spring-security-ldap.xml
  project/standard/templates/web/src/main/resources/applicationContext.xml
  project/standard/templates/web/src/main/webapp/WEB-INF/web.xml
  web/client/actions/__tests__/login-test.js
  web/client/actions/login.js
  web/client/api/GeoStoreDAO.js
  web/client/components/security/UserMenu.jsx
  web/client/components/security/modals/LoginModal.jsx
  web/client/components/security/modals/__tests__/LoginModal-test.jsx
  web/client/components/security/modals/assets/google.svg
  web/client/epics/__tests__/login-test.js
  web/client/epics/login.js
  web/client/plugins/Login.jsx
  web/client/plugins/__tests__/Login-test.js
  web/client/plugins/login/index.js
  web/client/reducers/__tests__/security-test.js
  web/client/reducers/security.js
  web/client/selectors/security.js
  web/client/utils/CookieUtils.js
  web/client/utils/__tests__/CookieUtils-test.js
Labels: C044-VLAANDEREN-2020-DEV

#8325 #8082 normalize longitude
  web/client/actions/__tests__/draw-test.js
  web/client/actions/draw.js
  web/client/reducers/__tests__/draw-test.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
Labels: bug, Priority: Medium, Internal, Good first issue

#8351 #8294 Allow import/export on cesium viewer
  web/client/plugins/MapExport.jsx
  web/client/plugins/MapImport.jsx
Labels: bug, Priority: High, Internal, 3D

#8352 8295 annotation node visible in 3d
  web/client/plugins/TOC.jsx
  web/client/plugins/__tests__/TOC-test.jsx
Labels: bug, Priority: High, Internal, 3D

#8280 8106 cesium viewer settings
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/cesium/Map.jsx
  web/client/configs/localConfig.json
  web/client/plugins/Map.jsx
  web/client/plugins/Settings.jsx
  web/client/plugins/map/mapsettings/MapSettings.jsx
  web/client/reducers/__tests__/map-test.js
  web/client/reducers/map.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Priority: Medium, Internal, New Feature, 3D

#8344 [Backport 2022.01.xx-geOrchestra] #8225 Making annotations not toggled but forcefully activated whenever measurements are saved as annotation (#8226)
  web/client/epics/__tests__/measurement-test.jsx
  web/client/epics/measurement.js
Labels: bug, annotations, Backport, C169-Rennes-Métropole-2021-GeOrchestra3

#8350 #8348 Update "About" plugin configuration to make it visible in multiple containers by default
  web/client/configs/localConfig.json
Labels: bug, Priority: High, Internal

#8343 #8308 Moved paramActions variable into utils
  web/client/epics/queryparams.js
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Priority: Low, Internal, Good first issue

#8370 [Backport 2022.01.xx] Update package.json (#8367)
  package.json
Labels: Backport
