Repository geosolutions-it/MapStore2, pull requests merged in 2023-02, with the labels that each got.

#8947 [Backport C047-2021.02.xx] #8911 MapStore AvailableStyles component won't filter styles
  mkdocs.yml
  web/client/components/styleeditor/StyleList.jsx
  web/client/components/styleeditor/__tests__/StyleList-test.jsx
Labels: bug, Backport, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#8838 Update User Guide - 3d style update
  docs/user-guide/img/button/3D-model-button.jpg
  docs/user-guide/img/layer-settings/3d-model-style-ex.gif
  docs/user-guide/img/layer-settings/bring-to-front.jpg
  docs/user-guide/img/layer-settings/clamp-to-ground.jpg
  docs/user-guide/img/layer-settings/height-reference.jpg
  docs/user-guide/img/layer-settings/height.jpg
  docs/user-guide/img/layer-settings/leader-line.jpg
  docs/user-guide/img/layer-settings/polygon-type.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, 3D, C040-COMUNE_GE-2022-CUSTOM-SUPPORT

#8837 Update User Guide - 3D Measurement tools
  docs/user-guide/img/button/measure-angle-on-3d.jpg
  docs/user-guide/img/button/measure-area-on-3d.jpg
  docs/user-guide/img/button/measure-distance-on-3d.jpg
  docs/user-guide/img/button/measure-height-from-terrain-on-3d.jpg
  docs/user-guide/img/button/measure-point-coordinate-on-3d.jpg
  docs/user-guide/img/button/measure-slope-on-3d.jpg
  docs/user-guide/img/measure/add-as-annotation-ex.jpg
  docs/user-guide/img/measure/area-uom.jpg
  docs/user-guide/img/measure/distance-uom.jpg
  docs/user-guide/img/measure/measure-angle-3d-ex.gif
  docs/user-guide/img/measure/measure-area-3d-ex.gif
  docs/user-guide/img/measure/measure-area-ex.gif
  docs/user-guide/img/measure/measure-bearing-ex.gif
  docs/user-guide/img/measure/measure-distance-3d-ex.gif
  docs/user-guide/img/measure/measure-distance-ex.gif
  docs/user-guide/img/measure/measure-height-from-terrain-3d-ex.gif
  docs/user-guide/img/measure/measure-point-3d-ex.gif
  docs/user-guide/img/measure/measure-slope-3d-ex.gif
  docs/user-guide/img/measure/measure.jpg
  docs/user-guide/measure.md
Labels: Documentation, User Guide, New Feature, 3D

#8943 Update User Guide - Filter maps and contexts from Homepage
  docs/user-guide/home-page.md
  docs/user-guide/img/home-page/advanced-search-bar.jpg
  docs/user-guide/img/home-page/search-bar.jpg
Labels: Documentation, Internal, User Guide

#8949 #8936 Contexts do not load on mobile for DEV,QA
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/plugins/enhancers/withModulePlugins.js
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: bug, Internal, AppContext

#8951 User guide - Heading levels error
  docs/user-guide/measure.md
Labels: Documentation, User Guide

#8945 #8898 Add authkey to WMS BIL Terrain layers
  web/client/utils/cesium/GeoServerBILTerrainProvider.js
  web/client/utils/cesium/WMSUtils.js
Labels: enhancement, Internal, Good first issue

#8954 #8909 There some warning in console when using catalog plugin
  web/client/components/catalog/editor/AdvancedSettings/WMSDomainAliases.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: bug, Internal

#8955 #8935 Improve UX of Visual Style Editor for WFS/Vector layers
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/ModelInput.jsx
  web/client/components/styleeditor/PropertyField.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/themes/default/less/style-editor.less
Labels: enhancement, Internal

#8946 #8795 Attribute table has highlighted boolean empty cells even if they are not changed
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/featuregrid/editors/index.jsx
  web/client/plugins/featuregrid/gridEvents.js
  web/client/utils/FeatureGridEditorUtils.js
  web/client/utils/__tests__/FeatureGridEditorUtils-test.js
Labels: bug, Internal, Good first issue

#8952 #8920 Leader line is not correctly positioned when relative from ground
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, C040-COMUNE_GE-2022-SUPPORT

#8960 #8959 Add hide options for service selector of LayerDownload plugin
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadDialog-test.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/plugins/LayerDownload.jsx
Labels: enhancement, Internal, geonode_integration, BackportNeeded

#8957 Layer filter improvements
  docs/developer-guide/LayerFilter.md
  docs/developer-guide/maps-configuration.md
  web/client/actions/__tests__/queryform-test.js
  web/client/actions/queryform.js
  web/client/components/data/query/QueryBuilder.jsx
  web/client/components/data/query/QueryToolbar.jsx
  web/client/components/data/query/__tests__/QueryToolbar-test.jsx
  web/client/epics/layerfilter.js
  web/client/plugins/QueryPanel.jsx
  web/client/reducers/__tests__/queryform-test.js
  web/client/reducers/query.js
  web/client/reducers/queryform.js
  web/client/selectors/__tests__/queryform-test.js
  web/client/selectors/queryform.js
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/filter/converters/__tests__/cql-test.js
  web/client/utils/filter/converters/__tests__/index-test.js
  web/client/utils/filter/converters/cql.js
  web/client/utils/filter/converters/index.js
Labels: C070-CGG-2022-DEV

#8962 [Backport c040-2022.02.xx] #8920 Leader line is not correctly positioned when relative from ground (#8952)
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, Backport, C040-COMUNE_GE-2022-SUPPORT

#8961 #8933 Search bar covers Identify header when vector layers are queried
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: bug, Internal, Good first issue

#8963 [Backport 2022.02.xx] #8959 Add hide options for service selector of LayerDownload plugin (#8960)
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/__tests__/DownloadDialog-test.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/plugins/LayerDownload.jsx
Labels: enhancement, Internal, geonode_integration, Backport

#8970 Update and rename tests.yml to CI.yml
  .github/workflows/CI.yml
  README.md
Labels: BackportNeeded

#8976 #8974 Measure plugin is not detecting the correct map type
  web/client/plugins/Measure.jsx
Labels: bug, Project: C027, BackportNeeded

#8977 #8973 It is not possible to close the Measure tool when burger menu is configured in a Context
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/MeasureToolbar.jsx
  web/client/plugins/__tests__/Measure-test.jsx
  web/client/plugins/measure/index.js
Labels: bug, Project: C027

#8975 #8972 Application crashes in mobile if dashboard maps are generated with an id starting with a number
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
Labels: bug, Project: C027, BackportNeeded

#8978 [Backport 2023.01.xx] Update and rename tests.yml to CI.yml (#8970)
  .github/workflows/CI.yml
  README.md
Labels: Backport

#8979 [Backport 2023.01.xx] #8974 Measure plugin is not detecting the correct map type (#8976)
  web/client/plugins/Measure.jsx
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#8980 [Backport 2023.01.xx] #8973 It is not possible to close the Measure tool when burger menu is configured in a Context (#8977)
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/mapcontrols/measure/MeasureToolbar.jsx
  web/client/plugins/__tests__/Measure-test.jsx
  web/client/plugins/measure/index.js
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#8981 [Backport 2023.01.xx] #8972 Application crashes in mobile if dashboard maps are generated with an id starting with a number (#8975)
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/__tests__/Map-test.jsx
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#8984 Update User Guide - Add Feature Grid filter by viewport
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/button/filter-by-viewport-button.jpg
  docs/user-guide/img/button/filter-by-viewport-enable.jpg
  docs/user-guide/img/filtering-layers/filter_viewport.gif
Labels: Documentation, User Guide, C070-CGG-2022-DEV

#8985 [Backport 2023.01.xx] #8984 User Guide - Add Feature Grid filter by viewport #8983
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/button/filter-by-viewport-button.jpg
  docs/user-guide/img/button/filter-by-viewport-enable.jpg
  docs/user-guide/img/filtering-layers/filter_viewport.gif
Labels: Documentation, User Guide, Backport, C070-CGG-2022-DEV

#8964 #8542 Update plugins dev documentation
  docs/developer-guide/mapstore-projects.md
  docs/developer-guide/plugins-architecture.md
  docs/developer-guide/plugins-howto.md
  docs/developer-guide/project-creation-script.md
  web/client/utils/PluginsUtils.js
Labels: Documentation, Internal
