Repository geosolutions-it/MapStore2, pull requests merged in 2023-12, with the labels that each got.

#9779 Fix #9551 Ability to move GLTF 3D models by given x/y
  docs/developer-guide/vector-style.md
  web/client/components/styleeditor/__tests__/VisualStyleEditor-test.js
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, 3D, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9675 Update User Guide - Add Point cloud shading options
  docs/user-guide/img/layer-settings/display-3d-tiles.jpg
  docs/user-guide/img/layer-settings/display-point-cloud.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, BackportNeeded, 3D, C027-COMUNE_FI-2023-SUPPORT

#9784 [Backport 2023.02.xx] #9764: Update User Guide - Add Format and Information sheet format fields
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/advanced_settings_csw.jpg
  docs/user-guide/img/catalog/advanced_settings_wms.jpg
Labels: Documentation, Support, User Guide, Backport, C027-COMUNE_FI-2023-SUPPORT, Interoperability, new

#9785 [Backport 2023.02.xx] #9482: Update User Guide - Note for COG layer
  docs/user-guide/catalog.md
Labels: Documentation, Internal, User Guide, Backport

#9777 Fix #9775 Visibility limits not working in 3D for detached layers
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/VisibilityLimitsForm-test.jsx
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/MarkerLayer.js
  web/client/components/map/cesium/plugins/OverlayLayer.js
  web/client/components/map/cesium/plugins/TerrainLayer.js
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
Labels: bug, BackportNeeded, 3D, C027-COMUNE_FI-2023-SUPPORT

#9770 #9751: Perform search using specific service from search menu
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/mapcontrols/searchservicesconfig/WFSOptionalProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/__tests__/WFSOptionalProps-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C268-DUBAI_MUNICIP-2023-SUPPORT

#9794 [Backport 2023.02.xx] Fix #9763. long string tooltip applied statically to components (#9793)
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9691 Fix #9685 Add possibility to use vector layers inside GeoProcessing tool
  web/client/actions/__tests__/geoProcessing-test.js
  web/client/actions/geoProcessing.js
  web/client/epics/__tests__/geoProcessing-test.js
  web/client/epics/geoProcessing.js
  web/client/observables/wps/collectGeometries.js
  web/client/plugins/GeoProcessing.jsx
  web/client/plugins/GeoProcessing/IntersectionLayer.jsx
  web/client/plugins/GeoProcessing/SourceLayer.jsx
  web/client/reducers/__tests__/geoProcessing-test.js
  web/client/reducers/geoProcessing.js
  web/client/selectors/__tests__/geoProcessing-test.js
  web/client/selectors/geoProcessing.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoProcessingUtils.js
  web/client/utils/__tests__/GeoProcessingUtils-test.js
Labels: BackportNeeded, C265-ATOLCD-2022-SUPPORT

#9800 [Backport C040-2023.02.xx] Fix #9763. long string tooltip applied statically to components (#9793)
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9796 #9792: fix z index order of catalog in app context wizard
  web/client/themes/default/less/dashboard.less
  web/client/themes/default/less/navbar.less
Labels: bug, Internal, Layout, AppContext, Regression

#9778 #9725: Fix expand layer legend arrows not aligned in TOC
  web/client/themes/default/less/toc.less
Labels: bug, annotations, C027-COMUNE_FI-2023-SUPPORT

#9787 #9783: implement zoom to record for parent table in dashboards
  web/client/components/widgets/enhancers/__tests__/tableWidget-test.jsx
  web/client/components/widgets/enhancers/dependenciesToExtent.js
  web/client/components/widgets/enhancers/tableWidget.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9812 [Backport 2023.02.xx] Fix #9775 Visibility limits not working in 3D for detached layers (#9777)
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/VisibilityLimitsForm-test.jsx
  web/client/components/map/cesium/Layer.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/MarkerLayer.js
  web/client/components/map/cesium/plugins/OverlayLayer.js
  web/client/components/map/cesium/plugins/TerrainLayer.js
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
Labels: bug, Backport, 3D, C027-COMUNE_FI-2023-SUPPORT

#9817 Fix #9814 Further issue with visibility limits in master
  web/client/components/map/cesium/Map.jsx
Labels: bug, 3D, C027-COMUNE_FI-2023-SUPPORT

#9781 #9697: fix spatial filter and widget connection issues
  web/client/components/widgets/enhancers/__tests__/emptyChartState-test.jsx
  web/client/components/widgets/enhancers/emptyChartState.js
  web/client/components/widgets/widget/CounterView.jsx
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
Labels: bug, C027-COMUNE_FI-2023-SUPPORT

#9818 #9783: resolve test review of not hiding zoom icon in tbl widget in case of removing connection from map widget to tbl widget
  web/client/components/widgets/enhancers/__tests__/tableWidget-test.jsx
  web/client/components/widgets/enhancers/tableWidget.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9805 #8997: fix map sync issue in feature grid
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/epics/featuregrid.js
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9820 [Backport 2023.02.xx] Fix #9814 Further issue with visibility limits in master (#9817)
  web/client/components/map/cesium/Map.jsx
Labels: bug, Backport, 3D, C027-COMUNE_FI-2023-SUPPORT

#9813 #9806: Do not visualize map sync popup by default for attribute table
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9804 #9739: Fix - Incorrect connection of the parent table with the map and other widget
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/map/MapCatalog.jsx
  web/client/components/widgets/enhancers/__tests__/dependenciesToWidget-test.jsx
  web/client/components/widgets/enhancers/dependenciesToWidget.js
  web/client/epics/widgets.js
  web/client/plugins/Dashboard.jsx
  web/client/plugins/widgetbuilder/ChartBuilder.jsx
  web/client/plugins/widgetbuilder/enhancers/chartLayerSelector.js
  web/client/plugins/widgetbuilder/enhancers/connection/withConnectButton.js
  web/client/selectors/widgets.js
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: bug, Internal, Dashboard, Widgets, Regression, Charts

#9809 Fix #9685 measurements issues and added some enhancements to it
  web/client/epics/__tests__/geoProcessing-test.js
  web/client/epics/geoProcessing.js
  web/client/epics/widgets.js
  web/client/plugins/GeoProcessing/IntersectionLayer.jsx
  web/client/plugins/GeoProcessing/SourceLayer.jsx
  web/client/reducers/config.js
  web/client/reducers/geoProcessing.js
  web/client/reducers/layers.js
  web/client/selectors/__tests__/geoProcessing-test.js
  web/client/selectors/geoProcessing.js
  web/client/selectors/layers.js
  web/client/utils/GeoProcessingUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/GeoProcessingUtils-test.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: enhancement, BackportNeeded, C265-ATOLCD-2022-SUPPORT

#9824 Added documentation for configuring session timeout
  docs/developer-guide/integrations/auth.md
Labels: Documentation, Support

#9832 [Backport 2022.02.xx] #9751: Perform search using specific service from search menu (#9770)
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/mapcontrols/searchservicesconfig/WFSOptionalProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/__tests__/WFSOptionalProps-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C268-DUBAI_MUNICIP-2023-SUPPORT

#9833 [Backport 2023.02.xx] #9806: Do not visualize map sync popup by default for attribute table (#9813)
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/components/data/featuregrid/toolbars/Toolbar.jsx
  web/client/components/data/featuregrid/toolbars/__tests__/Toolbar-test.jsx
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/featuregrid/toolbarEvents.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9836 [Backport 2023.02.xx] Added documentation for configuring session timeout (#9824)
  docs/developer-guide/integrations/auth.md
Labels: Documentation, Support, Backport

#9827 [Backport 2023.02.xx] #8997: fix map sync issue in feature grid (#9805)
  web/client/actions/__tests__/featuregrid-test.js
  web/client/actions/featuregrid.js
  web/client/epics/featuregrid.js
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
Labels: bug, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9844 Fix #9821 error loading 3Dtiles in csw catalog
  web/client/api/CSW.js
  web/client/api/ThreeDTiles.js
Labels: bug, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#9811 #9548: fix issue of 3D point measurement
  web/client/utils/cesium/ClickUtils.js
  web/client/utils/cesium/DrawGeometryInteraction.js
Labels: bug, 3D, new, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9845 Minor fixes to keycloak openid documentation
  docs/developer-guide/integrations/users/openId.md
Labels: BackportNeeded

#9846 [Backport 2023.02.xx] Minor fixes to keycloak openid documentation #9845
  docs/developer-guide/integrations/users/openId.md
Labels: Backport
