Repository geosolutions-it/MapStore2, pull requests merged in 2023-08, with the labels that each got.

#9298 #9251: Better handle of context access restriction
  docs/developer-guide/local-config.md
  web/client/actions/router.js
  web/client/components/errors/ResourceUnavailable.jsx
  web/client/components/errors/__tests__/ResourceUnavailable-test.jsx
  web/client/components/geostory/navigation/__tests__/Navigation-test.jsx
  web/client/components/home/Home.jsx
  web/client/components/home/__tests__/Home-test.jsx
  web/client/epics/__tests__/context-test.js
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/context.js
  web/client/epics/feedbackMask.js
  web/client/plugins/FeedbackMask.jsx
  web/client/plugins/Home.jsx
  web/client/reducers/__tests__/feedbackMask-test.js
  web/client/reducers/feedbackMask.js
  web/client/selectors/__tests__/context-test.js
  web/client/selectors/context.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ConfigUtils.js
  web/client/utils/__tests__/ConfigUtils-test.js
Labels: enhancement, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9315 #9250: Error handler updated for missing category
  docs/developer-guide/mapstore-migration-guide.md
  web/client/epics/permalink.js
Labels: enhancement, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9317 #9314: Fix - Enhance show/hide attribute edit option on Layer
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/plugins/__tests__/TOCItemsSettings-test.jsx
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/map.js
Labels: bug, Priority: High, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9327 #9326 Fixed propertyName override
  web/client/utils/ogc/Filter/FilterBuilder.js
  web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
  web/client/utils/ogc/Filter/fromObject.js
  web/client/utils/ogc/WFS/RequestBuilder.js
  web/client/utils/ogc/WFS/__tests__/RequestBuilder-test.js
Labels: bug, C105-2023-EMSA-CGD-2.2

#9324 fix #8913 commit link in projects.
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/localConfig.json
  web/client/configs/pluginsConfig.json
  web/client/product/components/viewer/about/VersionInfo.jsx
  web/client/product/components/viewer/about/__tests__/VersionInfo-test.js
  web/client/product/plugins/About.jsx
  web/client/reducers/version.js
  web/client/selectors/version.js
Labels: C027-COMUNE_FI-2023-SUPPORT

#9328 Update User Guide - Add Permalink tool
  docs/user-guide/img/button/generate_permalink.jpg
  docs/user-guide/img/share/embed-dash.jpg
  docs/user-guide/img/share/embed.jpg
  docs/user-guide/img/share/embed_maps_size.jpg
  docs/user-guide/img/share/embed_maps_toc.jpg
  docs/user-guide/img/share/permalink.jpg
  docs/user-guide/img/share/permalink_generated.jpg
  docs/user-guide/img/share/share_options.jpg
  docs/user-guide/img/share/share_window.jpg
  docs/user-guide/img/share/share_window_3d_map_options.jpg
  docs/user-guide/img/share/share_window_center_zoom.jpg
  docs/user-guide/img/share/share_window_map_options.jpg
  docs/user-guide/img/share/social.jpg
  docs/user-guide/share.md
Labels: Documentation, User Guide, New Feature, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9331 Add geoJSONtoWKT convert and fixed error in sidebar
  web/client/plugins/SidebarMenu.jsx
  web/client/utils/ogc/WKT/__tests__/index-test.js
  web/client/utils/ogc/WKT/__tests__/toGeoJSON-test.js
  web/client/utils/ogc/WKT/index.js
  web/client/utils/ogc/WKT/toWKT.js
Labels: C105-2023-EMSA-CGD-2.2

#9297 Minor improvements and updates to readthedocs.io and mkdocs configs
  .readthedocs.yaml
  docs/user-guide/measure.md
  mkdocs.yml
  readthedocs.yml
Labels: Documentation

#9321 Issue #9311 - populate search bar on select
  web/client/actions/__tests__/search-test.js
  web/client/actions/search.js
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
  web/client/reducers/__tests__/search-test.js
  web/client/reducers/search.js
Labels: New Feature, C027-COMUNE_FI-2023-SUPPORT

#9330 #9301 Support to configured formatters and quick filters in feature grid
  docs/developer-guide/maps-configuration.md
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/enhancers/filterRenderers.js
  web/client/components/data/featuregrid/filterRenderers/__tests__/index-test.jsx
  web/client/components/data/featuregrid/filterRenderers/index.js
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/data/featuregrid/renderers/__tests__/CellRenderer-test.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/plugins/featuregrid/panels/index.jsx
  web/client/plugins/widgets/getWidgetFilterRenderers.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: New Feature, C105-2023-EMSA-CGD-2.2

#9339 #9338 Add Google brand logo in addition to attribution for Photorealistic 3D Tiles
  web/client/components/map/cesium/img/google_on_non_white_hdpi.png
  web/client/components/map/cesium/img/google_on_white_hdpi.png
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/themes/default/less/cesium.less
Labels: enhancement, Priority: High, Internal

#9316 #9263 geoprocessing tools
  web/client/actions/__tests__/additionallayers-test.js
  web/client/actions/__tests__/geoProcessingTools-test.js
  web/client/actions/additionallayers.js
  web/client/actions/geoProcessingTools.js
  web/client/components/misc/switch/SwitchPanel.jsx
  web/client/components/misc/switch/SwitchToolbar.jsx
  web/client/configs/pluginsConfig.json
  web/client/epics/__tests__/geoProcessingTools-test.js
  web/client/epics/geoProcessingTools.js
  web/client/observables/wps/__tests__/buffer-test.js
  web/client/observables/wps/__tests__/collectGeometries-test.js
  web/client/observables/wps/__tests__/intersectionFeatureCollection-test.js
  web/client/observables/wps/buffer.js
  web/client/observables/wps/collectGeometries.js
  web/client/observables/wps/intersectionFeatureCollection.js
  web/client/plugins/GeoProcessingTools.jsx
  web/client/plugins/GeoProcessingTools/Buffer.jsx
  web/client/plugins/GeoProcessingTools/Intersection.jsx
  web/client/plugins/GeoProcessingTools/IntersectionLayer.jsx
  web/client/plugins/GeoProcessingTools/Main.jsx
  web/client/plugins/GeoProcessingTools/Panel.jsx
  web/client/plugins/GeoProcessingTools/SourceLayer.jsx
  web/client/plugins/longitudinalProfile/Menu.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/additionallayers-test.js
  web/client/reducers/__tests__/geoProcessingTools-test.js
  web/client/reducers/additionallayers.js
  web/client/reducers/geoProcessingTools.js
  web/client/selectors/__tests__/controls-test.js
  web/client/selectors/__tests__/geoProcessingTools-test.js
  web/client/selectors/__tests__/longitudinalProfile-test.js
  web/client/selectors/controls.js
  web/client/selectors/geoProcessingTools.js
  web/client/selectors/longitudinalProfile.js
  web/client/test-resources/wfs/describeLayer.xml
  web/client/test-resources/wfs/describeProcess_no_buffer.xml
  web/client/test-resources/wps/bufferGeom.json
  web/client/test-resources/wps/collectGeom.json
  web/client/themes/default/less/common.less
  web/client/themes/default/less/geo-processing-tools.less
  web/client/themes/default/less/mapstore.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/GeoProcessingToolsUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/GeoProcessingToolsUtils-test.js
  web/client/utils/ogc/WFS/__tests__/base-test.js
  web/client/utils/ogc/WFS/base.js
Labels: New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9334 Update database-setup.md
  docs/developer-guide/database-setup.md
Labels: Documentation, Dev Guide

#9345 #9313 Error when 3D Tiles layer are not visible
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
Labels: bug, 3D, C027-COMUNE_FI-2023-SUPPORT

#9350 #9348 Feature editor snapping not working
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/selectors/draw.js
  web/client/utils/openlayers/DrawSupportUtils.js
Labels: bug, OpenLayers, C027-COMUNE_FI-2023-SUPPORT

#9309 Adding reducer addTransformer feature to print module
  web/client/actions/__tests__/print-test.js
  web/client/actions/print.js
  web/client/epics/__tests__/print-test.js
  web/client/epics/print.js
  web/client/plugins/Print.jsx
  web/client/utils/PrintUtils.js
Labels: enhancement, Internal, Extensions

#9341 #9335: Fix - Default permalink resource type is missing
  web/client/components/permalink/Permalink.jsx
  web/client/components/permalink/__tests__/Permalink-test.jsx
Labels: bug, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 3

#9358 Fix for Longitudinal profile.
  web/client/plugins/longitudinalProfile/observables/wps/profile.js
Labels: C265-ATOLCD-2023-DEV_MS_CNR

#9372 Review User Guide - Parametric image to template
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, C265-ATOLCD-2023-DEV_MS_CNR

#9356 #9355 Review styling symbolizer to support missing annotations rules
  docs/developer-guide/maps-configuration.md
  docs/developer-guide/vector-style.md
  mkdocs.yml
  web/client/components/TOC/fragments/StyleBasedLegend.jsx
  web/client/components/TOC/fragments/__tests__/MarkIcon-test.jsx
  web/client/components/TOC/fragments/__tests__/StyleBasedLegend-test.jsx
  web/client/components/map/openlayers/plugins/VectorLayer.js
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/MarkSelector.jsx
  web/client/components/styleeditor/MarkerIconSelector.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/__tests__/MarkSelector-test.jsx
  web/client/components/styleeditor/__tests__/MarkerIconSelector-test.jsx
  web/client/components/styleeditor/__tests__/RulesEditor-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/components/styleeditor/config/wellKnownName.js
  web/client/epics/longitudinalProfile.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/DrawGeometryUtils.js
  web/client/utils/MarkerUtils.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/LeafletStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
  web/client/utils/styleparser/PrintStyleParser.js
  web/client/utils/styleparser/StyleParserUtils.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
  web/client/utils/styleparser/__tests__/LeafletStyleParser-test.js
  web/client/utils/styleparser/__tests__/OLStyleParser-test.js
  web/client/utils/styleparser/__tests__/PrintStyleParser-test.js
  web/client/utils/styleparser/__tests__/StyleParserUtils-test.js
Labels: enhancement, annotations, 3D, C027-COMUNE_FI-2023-SUPPORT

#9374 Updating thumb references for GS OSM backgrounds
  web/client/configs/config.json
  web/client/configs/localConfig.json
  web/client/configs/new.json
  web/client/product/assets/img/ne-political.jpg
  web/client/product/assets/img/osm-bright.jpg
  web/client/product/assets/img/osm-marine-dark.jpg
  web/client/product/assets/img/osm-simple-dark.jpg
  web/client/product/assets/img/osm-simple-light.jpg
Labels: Internal, Configuration

#9371 Update User Guide - Add WPS process doc on Longitudinal profile section
  docs/user-guide/longitudinal-profile.md
Labels: Documentation, User Guide, New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9377 [Backport 2023.02.xx] #9165 Update User Guide - Parametric image to template (#9372)
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, Backport, C265-ATOLCD-2023-DEV_MS_CNR
