Repository geosolutions-it/MapStore2, pull requests merged in 2023-05, with the labels that each got.

#9125 Implementation of alias editor and usage in feature grid
  web/client/components/I18N/LocalizedString.jsx
  web/client/components/I18N/__tests__/LocalizedString-test.jsx
  web/client/components/TOC/fragments/LayerFields/Fields.jsx
  web/client/components/TOC/fragments/LayerFields/__tests__/Fields-test.jsx
  web/client/components/TOC/fragments/LayerFields/__tests__/index-test.jsx
  web/client/components/TOC/fragments/LayerFields/index.jsx
  web/client/components/data/featuregrid/AttributeSelector.jsx
  web/client/components/data/featuregrid/__tests__/AttributeSelector-test.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/enhancers/headerRenderers/LocalizedHeaderRenderer.jsx
  web/client/components/data/featuregrid/enhancers/headerRenderers/__tests__/LocalizedHeaderRenderer-test.jsx
  web/client/components/data/featuregrid/enhancers/headerRenderers/index.js
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/plugins/featuregrid/__tests__/FeatureEditor-test.jsx
  web/client/plugins/featuregrid/panels/AttributeSelector.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/index.jsx
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/previews/responseHTML.txt
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/previews/responseJSON.txt
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/previews/responseText.txt
  web/client/plugins/tocitemssettings/tabs/Fields.jsx
  web/client/selectors/__tests__/featuregrid-test.js
  web/client/selectors/featuregrid.js
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: C206-DEUTSCHE_BAHN-2023-SUPPORT

#9137 #9136 Save layer's fields in map
  docs/developer-guide/maps-configuration.md
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, C206-DEUTSCHE_BAHN-2023-SUPPORT

#9138 #8998: Fix - Layers with visibility scale limits do not print if useFixedScales configured
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
Labels: bug, C169-Rennes-Métropole-2021-GeOrchestra3, Print

#9145 #9142 Support for alias in visual style editor
  web/client/components/styleeditor/MultiInput.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/SelectInput.jsx
  web/client/components/styleeditor/__tests__/MultiInput-test.jsx
  web/client/components/styleeditor/__tests__/SelectInput-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/StyleEditorUtils-test.js
Labels: C206-DEUTSCHE_BAHN-2023-SUPPORT

#9149 Fix #9141 Support for alias in feature info tool
  web/client/components/data/identify/viewers/row/PropertiesViewer.jsx
  web/client/components/data/identify/viewers/row/RowViewer.jsx
  web/client/components/data/identify/viewers/row/__tests__/PropertiesViewer-test.jsx
  web/client/components/data/identify/viewers/row/__tests__/RowViewer-test.jsx
  web/client/utils/mapinfo/__tests__/wfs-test.js
  web/client/utils/mapinfo/wfs.js
  web/client/utils/mapinfo/wms.js
Labels: enhancement, C206-DEUTSCHE_BAHN-2023-SUPPORT

#9151 Fix #9150. Support for alias in widgets
  web/client/components/data/featuregrid/AttributeTable.jsx
  web/client/components/widgets/builder/wizard/common/WPSWidgetOptions.jsx
  web/client/components/widgets/builder/wizard/common/__tests__/wfsChartOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/view/WidgetsView.jsx
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/epics/__tests__/widgets-test.js
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/widgets.js
  web/client/epics/widgetsbuilder.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C206-DEUTSCHE_BAHN-2023-SUPPORT

#9152 #8967 & #8968 3D Measurement to vector layer and export
  package.json
  utility/build/postInstall.js
  web/client/actions/mapInfo.js
  web/client/components/TOC/fragments/MarkIcon.jsx
  web/client/components/TOC/fragments/StyleBasedLegend.jsx
  web/client/components/import/style/StylePanel.jsx
  web/client/components/map/cesium/DrawGeometrySupport.jsx
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/__tests__/MeasurementSupport-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/components/map/leaflet/plugins/VectorLayer.jsx
  web/client/components/map/leaflet/plugins/WFSLayer.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/VectorStyle-test.js
  web/client/components/map/openlayers/plugins/VectorLayer.js
  web/client/components/map/openlayers/plugins/WFSLayer.js
  web/client/components/mapcontrols/measure/MeasureComponent.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/epics/__tests__/measurement-test.jsx
  web/client/epics/measurement.js
  web/client/plugins/measure/index.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/ImporterUtils.js
  web/client/utils/LayersUtils.js
  web/client/utils/MeasureUtils.js
  web/client/utils/MeasurementUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/StyleUtils.js
  web/client/utils/VectorStyleUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
  web/client/utils/__tests__/StyleUtils-test.js
  web/client/utils/__tests__/VectorStyleUtils-test.js
  web/client/utils/mapinfo/vector.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/GeometryFunctionsUtils.js
  web/client/utils/styleparser/LeafletStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
  web/client/utils/styleparser/PrintStyleParser.js
  web/client/utils/styleparser/StyleParserUtils.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
  web/client/utils/styleparser/__tests__/GeometryFunctionsUtils-test.js
  web/client/utils/styleparser/__tests__/LeafletStyleParser-test.js
  web/client/utils/styleparser/__tests__/OLStyleParser-test.js
  web/client/utils/styleparser/__tests__/PrintStyleParser-test.js
  web/client/utils/styleparser/__tests__/StyleParserUtils-test.js
Labels: enhancement, 3D, C027-COMUNE_FI-2023-SUPPORT

#9156 Fix empty alias defaults
  web/client/components/I18N/LocalizedString.jsx
  web/client/components/I18N/__tests__/LocalizedString-test.jsx
  web/client/components/data/featuregrid/AttributeSelector.jsx
  web/client/components/data/featuregrid/__tests__/AttributeSelector-test.jsx
  web/client/components/data/identify/viewers/row/PropertiesViewer.jsx
  web/client/components/widgets/builder/wizard/common/wfsChartOptions.js
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/utils/FeatureGridUtils.js
  web/client/utils/FeatureTypeUtils.js
  web/client/utils/StyleEditorUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
  web/client/utils/__tests__/FeatureTypeUtils-test.js
Labels: C206-DEUTSCHE_BAHN-2023-SUPPORT

#9167 [Backport 2023.01.xx] Fix #9159 Map views mask is not working (#9160)
  web/client/epics/__tests__/mapviews-test.js
  web/client/epics/mapviews.js
Labels: bug, Priority: High, Backport, Regression

#9169 #9166 Add search plugin to context creator map
  web/client/components/contextcreator/ContextCreator.jsx
Labels: enhancement

#9171 Update User Guide - Alias documentation
  docs/user-guide/img/button/clear_button.jpg
  docs/user-guide/img/button/localize_button.jpg
  docs/user-guide/img/button/reload_button.jpg
  docs/user-guide/img/layer-settings/GFI_template.jpg
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/img/layer-settings/fields_settings.jpg
  docs/user-guide/img/layer-settings/fields_toolbar.jpg
  docs/user-guide/img/layer-settings/lacalize-attribute-table.gif
  docs/user-guide/img/layer-settings/lacalize-layer-title.gif
  docs/user-guide/img/layer-settings/layer_general_settings.jpg
  docs/user-guide/img/layer-settings/localize-filter.gif
  docs/user-guide/img/layer-settings/localize-identify.gif
  docs/user-guide/img/layer-settings/localize-popup.jpg
  docs/user-guide/img/layer-settings/localize-style.gif
  docs/user-guide/img/layer-settings/localize-widget.gif
  docs/user-guide/img/layer-settings/ls-style.jpg
  docs/user-guide/img/layer-settings/panel_sections.jpg
  docs/user-guide/layer-settings.md
Labels: enhancement, Documentation, User Guide, C206-DEUTSCHE_BAHN-2023-SUPPORT

#9155 #9154 Fixed map crash when expanding timeline with time intervals
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/timeline.js
Labels: BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#9168 #9025 WMS caching with custom scales (projection resolutions strategy)
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/utils/CoordinatesUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/ProjectionUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
  web/client/utils/__tests__/ProjectionUtils-test.js
  web/client/utils/grids/MapGridsUtils.js
Labels: New Feature, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9175 [Backort] #9154 Fixed map crash when expanding timeline with time intervals (#9155)
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/timeline.js
Labels: Backport

#9178 [Backport 2022.02.xx-georchestra] #8998: Fix - Layers with visibility scale limits do not print if useFixedScales configured (#9138)
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
Labels: bug, Backport, C169-Rennes-Métropole-2021-GeOrchestra3, Print

#9181 [Backport 2023.01.xx] #8998: Fix - Layers with visibility scale limits do not print if useFixedScales configured (#9138)
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
Labels: bug, Backport, C169-Rennes-Métropole-2021-GeOrchestra3, Print

#9191 Fix #9189 3d height from terrain not working with cesium terrain provider
  web/client/components/map/cesium/DrawGeometrySupport.jsx
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, BackportNeeded, 3D

#9186 Fix #9164 Map views clipping throws error with geometry preview
  web/client/utils/MapViewsUtils.js
  web/client/utils/__tests__/MapViewsUtils-test.js
Labels: bug, 3D, C027-COMUNE_FI-2023-SUPPORT

#9184 Fix #9025 WMS caching with custom scales (custom resolutions strategy from WMTS)
  web/client/api/WMTS.js
  web/client/api/__tests__/WMTS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/WMSCacheOptions.jsx
  web/client/components/TOC/fragments/settings/__tests__/WMSCacheOptions-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/widgets/widget/InfoPopover.jsx
  web/client/epics/__tests__/layerinfo-test.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/less/toc.less
  web/client/themes/default/svg/grid-custom.svg
  web/client/themes/default/svg/grid-regular.svg
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/ProjectionUtils.js
  web/client/utils/WMSUtils.js
  web/client/utils/WMTSUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/ProjectionUtils-test.js
  web/client/utils/__tests__/WMSUtils-test.js
  web/client/utils/__tests__/WMTSUtils-test.js
Labels: New Feature, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9192 [Backport 2023.01.xx] Fix #9189 3d height from terrain not working with cesium terrain provider (#9191)
  web/client/components/map/cesium/DrawGeometrySupport.jsx
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, Backport, 3D

#9198 Fix #9197 Disable apply media editor button while loading a selected item
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
Labels: bug, geonode_integration, BackportNeeded

#9199 [Backport 2022.02.xx] Fix #9197 Disable apply media editor button while loading a selected item (#9198)
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
Labels: bug, geonode_integration, Backport

#9200 [Backport 2023.01.xx] Fix #9197 Disable apply media editor button while loading a selected item (#9198)
  web/client/selectors/__tests__/mediaEditor-test.js
  web/client/selectors/mediaEditor.js
Labels: bug, geonode_integration, Backport

#9196 Fix #9025 Available tile grids popup always reports mismatch in geostories and dashboards
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/components/widgets/builder/wizard/map/__tests__/NodeEditor-test.jsx
Labels: enhancement, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9195 Fix #9193 Add a cache options checks/info also for default WMS tile grid
  web/client/components/TOC/fragments/settings/WMSCacheOptions.jsx
  web/client/components/TOC/fragments/settings/__tests__/WMSCacheOptions-test.jsx
  web/client/jsapi/__tests__/MapStore2-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9207 Fix #9193 failing test
  web/client/components/widgets/builder/wizard/map/__tests__/NodeEditor-test.jsx
Labels: C047-CLEVELAND-METROPARKS-2022-SUPPORT
