Repository geosolutions-it/MapStore2, pull requests merged in 2023-07, with the labels that each got.

#9262 #9219: Feature grid in context creator
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/themes/default/less/featuregrid.less
Labels: enhancement, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 1

#9260 #9254 Add parametric image parsing to template viewer
  web/client/components/TOC/fragments/settings/FeatureInfoEditor.jsx
  web/client/components/TOC/fragments/settings/__tests__/FeatureInfoEditor-test.jsx
  web/client/components/data/identify/viewers/TemplateViewer.jsx
  web/client/components/mapviews/settings/CompactRichTextEditor.jsx
  web/client/themes/default/less/map-views.less
Labels: New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9270 #9248 - Import/export an application context
  docs/user-guide/application-context.md
  docs/user-guide/img/application-context/context_import_export.jpg
  web/client/actions/__tests__/contextcreator-test.js
  web/client/actions/contextcreator.js
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/contextcreator/__tests__/ContextCreator-test.jsx
  web/client/components/misc/Stepper.jsx
  web/client/configs/localConfig.json
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/plugins/ContextExport.jsx
  web/client/plugins/ContextImport.jsx
  web/client/plugins/__tests__/ContextExport-test.jsx
  web/client/plugins/__tests__/ContextImport-test.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9280 #9279 add icelandic and danish locale support
  web/client/components/I18N/__tests__/LangSelector-test.jsx
  web/client/components/I18N/images/flags/da-DK.png
  web/client/components/I18N/images/flags/da.png
  web/client/components/I18N/images/flags/is-IS.png
  web/client/components/I18N/images/flags/is.png
  web/client/components/I18N/images/flags/se.png
  web/client/epics/__tests__/localconfig-test.js
  web/client/translations/data.da-DK.json
  web/client/translations/data.is-IS.json
  web/client/translations/fragments/cookie/cookieDetails-da-DK.html
  web/client/translations/fragments/cookie/cookieDetails-is-IS.html
  web/client/utils/LocaleUtils.js
Labels: C076-IDS-2023-SUPPORT

#9290 #9287 Fix terser dependency
  package.json
Labels: BackportNeeded

#9291 [Backport 2023.01.xx] #9287 Fix terser dependency (#9290)
  package.json
Labels: Backport

#9286 [Backport 2023.01.xx] Fix #9272 fork me on github plugin restored (#9273)
  web/client/product/plugins/Fork.jsx
Labels: Backport

#9267 #8969 Update cesium to version 1.106.1
  build/buildConfig.js
  build/testConfig.js
  package.json
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/EmptyLayer.js
  web/client/components/map/cesium/plugins/GraticuleLayer.js
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/utils/cesium/GeoServerBILTerrainProvider.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: enhancement, 3D, C027-COMUNE_FI-2023-SUPPORT

#9296 #9241 fixed longitudinal profile
  web/client/plugins/longitudinalProfile/observables/wps/profile.js
Labels: C265-ATOLCD-2023-DEV_MS_CNR

#9288 #9250: Share plugin - Permalink functionality
  docs/developer-guide/mapstore-migration-guide.md
  java/web/src/main/resources/sample_categories.xml
  project/standard/templates/configs/pluginsConfig.json
  project/standard/templates/web/src/main/resources/sample_categories.xml
  web/client/actions/__tests__/permalink-test.js
  web/client/actions/permalink.js
  web/client/components/permalink/Permalink.jsx
  web/client/components/permalink/__tests__/Permalink-test.jsx
  web/client/components/resources/ResourceCard.jsx
  web/client/components/resources/forms/Metadata.jsx
  web/client/components/resources/forms/__tests__/Metadata-test.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/components/share/ShareLink.jsx
  web/client/components/share/SharePanel.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/configs/localConfig.json
  web/client/configs/pluginsConfig.json
  web/client/epics/__tests__/feedbackMask-test.js
  web/client/epics/__tests__/permalink-test.js
  web/client/epics/context.js
  web/client/epics/feedbackMask.js
  web/client/epics/permalink.js
  web/client/plugins/Permalink.jsx
  web/client/plugins/__tests__/Permalink-test.jsx
  web/client/product/appConfig.js
  web/client/product/pages/Permalink.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/permalink-test.js
  web/client/reducers/permalink.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/__tests__/permalink-test.js
  web/client/selectors/map.js
  web/client/selectors/permalink.js
  web/client/themes/default/less/mapstore.less
  web/client/themes/default/less/permalink.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9276 feat: can import geojson files as layer with query params
  docs/developer-guide/map-query-parameters.md
  web/client/api/catalog/GeoJSON.js
  web/client/api/catalog/index.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/test-resources/geojson/example.geojson
Labels: enhancement

#9294 Fix #9293 Update OpenLayers version 7.4.0
  package.json
  web/client/components/map/__tests__/BaseMap-test.jsx
  web/client/components/map/openlayers/DrawSupport.jsx
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/components/map/openlayers/__tests__/DrawSupport-test.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/map/openlayers/hole/DrawHole.js
  web/client/components/map/openlayers/hole/ext.js
  web/client/components/map/openlayers/plugins/GraticuleLayer.js
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/components/map/openlayers/snapshot/__tests__/Preview-test.jsx
  web/client/components/map/openlayers/swipe/EffectSupport.jsx
  web/client/components/map/openlayers/swipe/__tests__/EffectSupport-test.jsx
  web/client/themes/default/less/map-footer.less
  web/client/themes/default/less/ol.less
  web/client/utils/grids/MapGridsUtils.js
  web/client/utils/grids/__tests__/MapGridsUtils-test.js
  web/client/utils/openlayers/DrawSupportUtils.js
  web/client/utils/openlayers/Graticule.js
  web/client/utils/openlayers/OlLocate.js
Labels: enhancement, C027-COMUNE_FI-2023-SUPPORT

#9284 Update User Guide - Add parametric image parsing to template viewer
  docs/user-guide/img/button/image_button.jpg
  docs/user-guide/img/layer-settings/edit_custom_format.jpg
  docs/user-guide/img/layer-settings/image_on_template.gif
  docs/user-guide/layer-settings.md
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9283 Update User Guide - import/export an application context
  docs/user-guide/application-context.md
  docs/user-guide/img/application-context/export_context.gif
  docs/user-guide/img/application-context/import_context.gif
  docs/user-guide/img/application-context/stepone.jpg
  docs/user-guide/img/application-context/wizard2.jpg
  docs/user-guide/img/button/export_button.jpg
  docs/user-guide/img/button/import_button.jpg
Labels: Documentation, User Guide, New Feature, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9281 Update User Guide - Longitudinal profile plugin
  docs/user-guide/img/button/drawing-line.jpg
  docs/user-guide/img/button/import-file.jpg
  docs/user-guide/img/button/long-profile-button.jpg
  docs/user-guide/img/button/parameters-button.jpg
  docs/user-guide/img/button/selection-layer.jpg
  docs/user-guide/img/longitudinal-profile/bar_charts.jpg
  docs/user-guide/img/longitudinal-profile/chart-tab.jpg
  docs/user-guide/img/longitudinal-profile/chart-title.jpg
  docs/user-guide/img/longitudinal-profile/drawing-line.gif
  docs/user-guide/img/longitudinal-profile/dropdown-menu-long-profile.jpg
  docs/user-guide/img/longitudinal-profile/export-profile.jpg
  docs/user-guide/img/longitudinal-profile/import-file.gif
  docs/user-guide/img/longitudinal-profile/interact-with-chart.gif
  docs/user-guide/img/longitudinal-profile/profile-info.jpg
  docs/user-guide/img/longitudinal-profile/selection-layer.gif
  docs/user-guide/img/longitudinal-profile/setting-parameters.jpg
  docs/user-guide/longitudinal-profile.md
  mkdocs.yml
Labels: Documentation, User Guide, New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9002 #9001 Made project branch parametric
  createProject.js
  docs/developer-guide/project-creation-script.md
  utility/projects/projectLib.js
Labels: Task

#9308 #9250: Save permalink description as metadata
  web/client/components/permalink/Permalink.jsx
  web/client/components/permalink/__tests__/Permalink-test.jsx
  web/client/epics/__tests__/context-test.js
  web/client/epics/context.js
Labels: New Feature, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 2

#9300 #9285 support for CQL function parsing and XML conversion
  docs/developer-guide/LayerFilter.md
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/FilterBuilder.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
  web/client/utils/ogc/Filter/fromObject.js
  web/client/utils/ogc/Filter/operators.js
  web/client/utils/ogc/WFS/RequestBuilder.js
  web/client/utils/ogc/WKT/__tests__/toGeoJSON-test.js
  web/client/utils/ogc/WKT/index.js
  web/client/utils/ogc/WKT/toGeoJSON.js
Labels: C105-2023-EMSA-CGD-2.2

#9307 #9306 Support for CQL_FILTER in LayerDownload plugin
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
Labels: bug, C105-2023-EMSA-CGD-2.2
