Repository geosolutions-it/MapStore2, pull requests merged in 2023-06, with the labels that each got.

#9209 Fix #9208 Timeline map sync does not update for time ranges visualization
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/dimension.js
  web/client/epics/timeline.js
  web/client/selectors/__tests__/timeline-test.js
  web/client/selectors/timeline.js
Labels: bug, BackportNeeded, C044-VLAANDEREN-2021-SUPPORT

#9214 Fix #9147 Issue in chart creation from feature grid.
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/widgetsbuilder.js
Labels: bug, BackportNeeded, Regression

#9217 [Backport 2023.02.xx] Fix #9147 Issue in chart creation from feature grid. (#9214)
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/widgetsbuilder.js
Labels: bug, Internal, Backport, Regression

#9187 Fix #9176 Make Map Views tool progress bar more evident
  web/client/components/mapviews/MapViewsProgressBar.jsx
  web/client/components/mapviews/MapViewsSupport.jsx
  web/client/components/mapviews/__tests__/MapViewsProgressBar-test.jsx
  web/client/themes/default/less/map-views.less
Labels: enhancement, 3D

#9213 #9025 add caching options to wms background settings
  web/client/components/TOC/fragments/settings/WMSCacheOptions.jsx
  web/client/components/TOC/fragments/settings/__tests__/WMSCacheOptions-test.jsx
  web/client/components/background/BackgroundDialog.jsx
  web/client/components/background/BackgroundSelector.jsx
  web/client/components/background/__tests__/BackgroundDialog-test.jsx
  web/client/plugins/BackgroundSelector.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/__tests__/LayersUtils-test.js
Labels: enhancement, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9221 [Backport 2023.01.xx] Fix #9176 Make Map Views tool progress bar more evident (#9187)
  web/client/components/mapviews/MapViewsProgressBar.jsx
  web/client/components/mapviews/MapViewsSupport.jsx
  web/client/components/mapviews/__tests__/MapViewsProgressBar-test.jsx
  web/client/themes/default/less/map-views.less
Labels: enhancement, Backport, 3D

#9223 Fix #9203 Swipe tool UI to be fixed
  web/client/themes/default/less/swipe.less
Labels: bug, Internal, Regression

#9206 Update User Guide - Add the custom tile grids
  docs/user-guide/background.md
  docs/user-guide/img/background/add-new-bck.jpg
  docs/user-guide/img/button/info_ion.jpg
  docs/user-guide/img/button/tile_grid.jpg
  docs/user-guide/img/button/tile_grid_green.jpg
  docs/user-guide/img/button/update_button.jpg
  docs/user-guide/img/layer-settings/default_gridset_info.jpg
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/img/layer-settings/green_info.jpg
  docs/user-guide/img/layer-settings/warning_info.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9226 #9219 - Allow to configure hidden columns in featuregrid
  web/client/epics/__tests__/context-test.js
  web/client/epics/config.js
  web/client/epics/context.js
  web/client/reducers/__tests__/featuregrid-test.js
  web/client/reducers/featuregrid.js
  web/client/selectors/__tests__/mapsave-test.js
  web/client/selectors/__tests__/usersession-test.js
  web/client/selectors/mapsave.js
  web/client/selectors/usersession.js
Labels: New Feature, C169-Rennes-Métropole-2023-GeOrchestra4

#9228 [Backport 2023.01.xx] Fix #9203 Swipe tool UI to be fixed (#9223)
  web/client/themes/default/less/swipe.less
Labels: bug, Internal, Backport, Regression

#9230 #9139: Fix - New WFS layers no longer visible in dashboards
  web/client/plugins/widgetbuilder/enhancers/__tests__/handleMapZoomLayer-test.js
  web/client/plugins/widgetbuilder/enhancers/__tests__/layerSelector-test.js
  web/client/plugins/widgetbuilder/enhancers/handleMapZoomLayer.js
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
Labels: bug, Internal, Regression

#9174 Fix #9172 add flag to always select first layer in toc in identify results
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/LayerSelector.jsx
  web/client/components/data/identify/enhancers/identify.js
  web/client/plugins/Identify.jsx
  web/client/reducers/__tests__/mapInfo-test.js
  web/client/reducers/mapInfo.js
Labels: enhancement, C265-ATOLCD-2023-DEV_MS_CNR

#9233 [Backport 2023.01.xx] #9139: Fix - New WFS layers no longer visible in dashboards (#9230)
  web/client/plugins/widgetbuilder/enhancers/__tests__/handleMapZoomLayer-test.js
  web/client/plugins/widgetbuilder/enhancers/__tests__/layerSelector-test.js
  web/client/plugins/widgetbuilder/enhancers/handleMapZoomLayer.js
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
Labels: bug, Internal, Backport, Regression

#9235 [Backport 2023.01.xx] #9225 Documentation for Contexts plugin (#9234)
  build/docma-config.json
  web/client/plugins/Contexts.jsx
Labels: Documentation, Backport

#9227 #9180: Layer setting - Feature editing option with permission
  web/client/components/TOC/fragments/settings/General.jsx
  web/client/components/TOC/fragments/settings/__tests__/General-test.jsx
  web/client/plugins/TOCItemsSettings.jsx
Labels: enhancement, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 1

#9236 #9219: Fix - Session restoration on reload by statically loading FeatureEditor
  web/client/plugins/FeatureEditor.jsx
  web/client/plugins/__tests__/FeatureEditor-test.jsx
  web/client/plugins/featuregrid/FeatureEditor.jsx
  web/client/product/plugins.js
Labels: bug, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 1

#9238 [Backport 2023.01.xx] #9165 Update User Guide - Height offset option on display tan for the 3D Tiles (#9177)
  docs/user-guide/img/layer-settings/display-3d-tiles.jpg
  docs/user-guide/layer-settings.md
Labels: Priority: High, Documentation, User Guide, Backport

#9245 [Release 2023.01.02] Fixed versions for backend modules
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Task

#9240 Update User Guide - Add Attribute Table in read only mode
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, C169-Rennes-Métropole-2023-GeOrchestra4, Phase 1

#9253 #9241 long profile tool
  build/docma-config.json
  docs/developer-guide/maps-configuration.md
  package.json
  web/client/actions/__tests__/longitudinalPfofile-test.js
  web/client/actions/longitudinalProfile.js
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/misc/Button.jsx
  web/client/configs/pluginsConfig.json
  web/client/epics/longitudinalProfile.js
  web/client/plugins/LongitudinalProfileTool.jsx
  web/client/plugins/longitudinalProfile/Chart.jsx
  web/client/plugins/longitudinalProfile/Dock.jsx
  web/client/plugins/longitudinalProfile/HelpInfo.jsx
  web/client/plugins/longitudinalProfile/Import.jsx
  web/client/plugins/longitudinalProfile/ImportContent.jsx
  web/client/plugins/longitudinalProfile/ImportSelectCRS.jsx
  web/client/plugins/longitudinalProfile/Main.jsx
  web/client/plugins/longitudinalProfile/Menu.jsx
  web/client/plugins/longitudinalProfile/Properties.jsx
  web/client/plugins/longitudinalProfile/SettingsPanel.jsx
  web/client/plugins/longitudinalProfile/__tests__/ImportContent-test.js
  web/client/plugins/longitudinalProfile/constants.js
  web/client/plugins/longitudinalProfile/enhancers/processFile.js
  web/client/plugins/longitudinalProfile/enhancers/useFile.js
  web/client/plugins/longitudinalProfile/observables/wps/profile.js
  web/client/product/plugins.js
  web/client/reducers/longitudinalProfile.js
  web/client/selectors/controls.js
  web/client/selectors/draw.js
  web/client/selectors/longitudinalProfile.js
  web/client/selectors/maplayout.js
  web/client/themes/dark/variables.less
  web/client/themes/default/less/longitudinal-profile.less
  web/client/themes/default/less/mapstore.less
  web/client/themes/default/ms-variables.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FileUtils.js
  web/client/utils/LongitudinalProfileUtils.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
Labels: New Feature, C265-ATOLCD-2023-DEV_MS_CNR

#9261 More doc for Gridset compatibility check
  docs/user-guide/layer-settings.md
Labels: Priority: Medium, Documentation, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#9264 #9241 fix doc of the longitudinal profile tool
  web/client/plugins/LongitudinalProfileTool.jsx
Labels: C265-ATOLCD-2023-DEV_MS_CNR
