Repository geosolutions-it/MapStore2, pull requests merged in 2023-03, with the labels that each got.

#8986 Format fixes for plugin general guidelines
  docs/developer-guide/plugins-howto.md
Labels: Documentation

#8987 #8982 Issues between charts and filters
  web/client/epics/dashboard.js
  web/client/epics/widgetsbuilder.js
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
Labels: bug, BackportNeeded, Regression

#8989 [Backport 2023.01.xx] Update plugins dev documentation #8542
  docs/developer-guide/mapstore-projects.md
  docs/developer-guide/plugins-architecture.md
  docs/developer-guide/plugins-howto.md
  docs/developer-guide/project-creation-script.md
  web/client/utils/PluginsUtils.js
Labels: Documentation, Backport

#8991 [Backport 2023.01.xx] #8982 Issues between charts and filters (#8987)
  web/client/epics/dashboard.js
  web/client/epics/widgetsbuilder.js
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/widgets-test.js
  web/client/selectors/widgets.js
Labels: bug, Backport, Regression

#8971 Bump mapstore versions to latest master branches
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  package.json
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Task

#9003 Release 2023.01.00
  CHANGELOG.md
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
  utility/projects/projectLib.js
Labels: Task

#9005 Restored snapshots on 2023.01.xx
  binary/bin-war/pom.xml
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  package.json
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Task

#9004 Update CHANGELOG.md
  CHANGELOG.md
Labels: Task

#9000 Adding new issue templates
  .github/ISSUE_TEMPLATE/qa_test_run
  .github/ISSUE_TEMPLATE/release_steps
  docs/developer-guide/release.md
Labels: Internal

#9010 [Backport 2023.01.xx] #9008 Update CI.yml (#9009)
  .github/workflows/CI.yml
Labels: Backport

#9013 #9011 Persist 3D map orientation after saving a map
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/configs/localConfig.json
  web/client/epics/__tests__/maptype-test.js
  web/client/epics/maptype.js
  web/client/plugins/Share.jsx
  web/client/test-resources/mergeConfigs/04_full_localConfig.json
  web/client/test-resources/mergeConfigs/05_result_Config.json
  web/client/utils/MapTypeUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, 3D, C027-COMUNE_FI-2023-SUPPORT

#9023 Update building-and-deploying.md
  docs/developer-guide/building-and-deploying.md
Labels: Documentation

#9026 Update layer-settings.md
  docs/user-guide/layer-settings.md
Labels: Documentation, BackportNeeded

#9028 #9016: Fix - Catalog panel mode reset on changing map
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
Labels: bug

#9032 [Backport 2023.01.xx]Update building-and-deploying.md (#9023)
  docs/developer-guide/building-and-deploying.md
Labels: Backport

#9037 #9036: Fix - Catalog mode and result retention
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/__tests__/MetadataExplorer-test.jsx
Labels: bug, Internal, BackportNeeded

#9022 #8905 Allow to set singletile option on a wms catalog entry
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C276-CRAIG-2023-DEV

#9024 #9006 wms legend from mapserver not available in 3d mode because of wrong empty scale parameter
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/legend/__tests__/Legend-test.jsx
Labels: enhancement, C276-CRAIG-2023-DEV

#9038 [Backport 2023.01.xx] #9014: Fix - Crash on new context when expanding search service option
  web/client/plugins/SearchServicesConfig.jsx
  web/client/plugins/__tests__/SearchServicesConfig-test.jsx
Labels: bug, Backport, Regression

#9045 [Backport 2023.01.xx] #9036: Fix - Catalog mode and result retention (#9037)
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/__tests__/MetadataExplorer-test.jsx
Labels: bug, Internal, Backport

#9051 Fix #9050. Handle filters array on LOAD_FITLTER action
  web/client/reducers/__tests__/queryform-test.js
  web/client/reducers/queryform.js
Labels: BackportNeeded, C070-CGG-2022-DEV

#9048 add serverType option to wms & csw catalog entries #8167
  docs/developer-guide/local-config.md
  web/client/api/catalog/WMS.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/utils/LayersUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: BackportNeeded, C276-CRAIG-2023-DEV

#9021 #8055 allow to load 3dtiles tileset via viewer parameters
  docs/developer-guide/map-query-parameters.md
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/components/catalog/Catalog.jsx
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/catalog.js
  web/client/epics/queryparams.js
Labels: enhancement, BackportNeeded, C276-CRAIG-2023-DEV

#9055 #8905 Add missing translations
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, C276-CRAIG-2023-DEV

#9054 #9031 GetMap format list in GetCapabilities not respected
  web/client/actions/catalog.js
  web/client/actions/layerCapabilities.js
  web/client/api/CSW.js
  web/client/api/WMS.js
  web/client/api/WMTS.js
  web/client/api/__tests__/CSW-test.js
  web/client/api/__tests__/WMS-test.js
  web/client/api/catalog/WMS.js
  web/client/api/catalog/WMTS.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/RecordGrid.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/widgets/builder/wizard/map/enhancers/withCapabilitiesRetrieval.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/catalog.js
  web/client/epics/layerinfo.js
  web/client/epics/layers.js
  web/client/epics/styleeditor.js
  web/client/observables/rulesmanager.js
  web/client/observables/wms.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/catalog.js
  web/client/test-resources/wmc/config.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/utils/LayersUtils.js
  web/client/utils/WMSUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/WMSUtils-test.js
  web/client/utils/ogc/MS.js
  web/client/utils/ogc/WCS.js
  web/client/utils/ogc/WMC/index.js
  web/client/utils/ogc/WMS.js
Labels: enhancement, C276-CRAIG-2023-DEV, Interoperability

#9044 #9034: Fix - Spinner no longer appear when saving a resource
  web/client/components/resources/modals/Save.jsx
  web/client/components/resources/modals/__tests__/Save-test.jsx
  web/client/themes/default/less/loaders.less
Labels: bug, Internal, BackportNeeded, Regression

#9059 [Backport 2023.01.xx] #9030 improve metadata display interoperability with mapserver/mapproxy (#7865)
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/epics/layers.js
  web/client/test-resources/csw/3bedb35a-a9ba-4f48-8796-de127becd578.xml
  web/client/test-resources/csw/mapserver-metadata.xml
  web/client/test-resources/wms/getCapabilities-mapproxy-singlelayer.xml
  web/client/test-resources/wms/getCapabilities-mapserver.xml
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/ogc/MS.js
  web/client/utils/ogc/WMS.js
Labels: enhancement, Internal, Backport, C276-CRAIG-2023-DEV

#9061 [Backport 2023.01.xx] #8905 Allow to set singletile option on a wms catalog entry (#9022)
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C276-CRAIG-2023-DEV

#9062 [Backport 2023.01.xx] #9006 wms legend from mapserver not available in 3d mode because of wrong empty scale parameter (#9024)
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/TOC/fragments/legend/__tests__/Legend-test.jsx
Labels: enhancement, Backport, C276-CRAIG-2023-DEV

#9060 [Backport 2023.01.xx] #8055 allow to load 3dtiles tileset via viewer parameters (#9021)
  docs/developer-guide/map-query-parameters.md
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/__tests__/ThreeDTiles-test.js
  web/client/components/catalog/Catalog.jsx
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/__tests__/queryparam-test.js
  web/client/epics/catalog.js
  web/client/epics/queryparams.js
Labels: enhancement, Backport, C276-CRAIG-2023-DEV

#9063 [Backport 2023.01.xx] #8167 add serverType option to wms & csw catalog entries (#9048)
  docs/developer-guide/local-config.md
  web/client/api/catalog/WMS.js
  web/client/api/catalog/__tests__/WMS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/leaflet/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Backport, C276-CRAIG-2023-DEV

#9064 [Backport 2023.01.xx] #9034: Fix - Spinner no longer appear when saving a resource (#9044)
  web/client/components/resources/modals/Save.jsx
  web/client/components/resources/modals/__tests__/Save-test.jsx
  web/client/themes/default/less/loaders.less
Labels: bug, Internal, Backport, Regression
