Repository geosolutions-it/MapStore2, pull requests merged in 2023-11, with the labels that each got.

#9557 #9510: Improving GeoFence rule filtering capabilities
  web/client/actions/rulesmanager.js
  web/client/api/geofence/RuleService.js
  web/client/components/manager/rulesmanager/rulesgrid/enhancers/rulesgrid.js
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/LayersFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/RequestsFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/RolesFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/ServicesFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/UsersFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/WorkspacesFilter.jsx
  web/client/components/misc/__tests__/PagedCombobox-test.jsx
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/reducers/__tests__/rulesmanager-test.js
  web/client/reducers/rulesmanager.js
  web/client/selectors/__tests__/rulesmanager-test.js
  web/client/selectors/rulesmanager.js
  web/client/themes/default/less/autocomplete.less
  web/client/themes/default/less/react-data-grid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9680 Fixed Issue #9627 and associated PR comments
  web/client/components/mapviews/settings/CompactRichTextEditor.jsx
  web/client/components/widgets/builder/wizard/text/TextOptions.jsx
  web/client/components/widgets/builder/wizard/text/__tests__/TextOptions-test.jsx
Labels: enhancement, Dashboard, Widgets

#9664 Fix #9622 add possibility to configure a fine grid for widgets in the viewer
  web/client/actions/__tests__/widgets-test.js
  web/client/actions/widgets.js
  web/client/plugins/Widgets.jsx
  web/client/plugins/widgets/autoDisableWidgets.js
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
Labels: enhancement, Widgets, C027-COMUNE_FI-2023-SUPPORT

#9678 Fix #9609 missing disabled prop to be passed to the ProperyField comp
  web/client/components/styleeditor/PropertySelector.jsx
Labels: bug, StyleEditor, C027-COMUNE_FI-2023-SUPPORT

#9674 #9216: handle fixing not visibility of spatial filter for widgets created by attribute table
  web/client/actions/__tests__/wfsquery-test.js
  web/client/actions/wfsquery.js
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
  web/client/epics/widgetsbuilder.js
Labels: bug, Internal

#9608 #9567: handle functionality of zoom to record in table widgets
  web/client/components/map/enhancers/__tests__/onMapViewChanges-test.js
  web/client/components/map/enhancers/onMapViewChanges.js
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
  web/client/components/widgets/builder/wizard/table/TableOptions.jsx
  web/client/components/widgets/enhancers/__tests__/dependenciesToExtent-test.jsx
  web/client/components/widgets/enhancers/__tests__/tableWidget-test.jsx
  web/client/components/widgets/enhancers/dependenciesToExtent.js
  web/client/components/widgets/enhancers/tableWidget.js
  web/client/components/widgets/widget/TableWidget.jsx
  web/client/components/widgets/widget/__tests__/TableWidget-test.jsx
  web/client/configs/localConfig.json
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/Widgets.jsx
  web/client/plugins/featuregrid/gridTools.jsx
  web/client/selectors/widgets.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/MapUtils.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9694 Update README.md
  README.md
Labels: Documentation

#9684 #9592 - COG option hidden in catalog from default
  docs/user-guide/catalog.md
  web/client/plugins/MetadataExplorer.jsx
Labels: enhancement, Internal, BackportNeeded

#9700 Fix #9622 adjusted rowHeight usage
  web/client/configs/localConfig.json
  web/client/plugins/Widgets.jsx
Labels: enhancement, C027-COMUNE_FI-2023-SUPPORT

#9693 Fix #9692 making sure that new projects will create mapstore.war
  project/standard/templates/web/pom.xml
  web/client/product/pages/RulesManager.jsx
Labels: enhancement, Internal, BackportNeeded

#9704 [Backport 2023.02.xx] #9216: Handle fixing not visibility of spatial filter for widgets created by attribute table (#9674)
  web/client/actions/__tests__/wfsquery-test.js
  web/client/actions/wfsquery.js
  web/client/epics/__tests__/wfsquery-test.js
  web/client/epics/__tests__/widgetsbuilder-test.js
  web/client/epics/featuregrid.js
  web/client/epics/wfsquery.js
  web/client/epics/widgetsbuilder.js
Labels: bug, Internal, Backport

#9687 #9590: COG download metadata by default with abort fetch
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/api/catalog/COG.js
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/epics/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Internal, BackportNeeded

#9705 #9600 - Link release version in MapStore Documentation in home page
  .github/ISSUE_TEMPLATE/release_steps.md
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Documentation

#9699 [Backport 2023.02.xx] #9592 - COG option hidden in catalog from default (#9684)
  docs/user-guide/catalog.md
  web/client/plugins/MetadataExplorer.jsx
Labels: enhancement, Internal, Backport

#9715 #9510: Improving GeoFence rule filtering capabilities [fix rule manager roles filter]
  web/client/api/geofence/RuleService.js
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/RolesFilter.jsx
  web/client/reducers/rulesmanager.js
  web/client/selectors/__tests__/rulesmanager-test.js
  web/client/selectors/rulesmanager.js
  web/client/themes/default/less/autocomplete.less
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9714 [Backport 2023.02.xx] #9600 - Link release version in MapStore Documentation in home page (#9705)
  .github/ISSUE_TEMPLATE/release_steps.md
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Documentation, Backport

#9713 [Backport 2023.02.xx] #9590: COG download metadata by default with abort fetch (#9687)
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/api/catalog/COG.js
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/epics/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Internal, Backport

#9703 backport 2023.02.xx - Fix #9692 making sure that new projects will create mapstore.war (#9693)
  project/standard/templates/web/pom.xml
  web/client/product/pages/RulesManager.jsx
Labels: enhancement, Backport

#9690 #9589: Notify data projection not compatible / available for COG
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/__tests__/DefaultLayer-test.jsx
  web/client/components/TOC/fragments/LayersTool.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/map/openlayers/plugins/COGLayer.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, BackportNeeded

#9701 #9553: Improving readability of long attribute values in attribute table and table widgets
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/misc/enhancers/__tests__/handleLongTextEnhancer-test.jsx
  web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9716 [Backport 2023.02.xx]: #9510: Improving GeoFence rule filtering capabilities (#9715,#9715)
  web/client/actions/rulesmanager.js
  web/client/api/geofence/RuleService.js
  web/client/components/manager/rulesmanager/rulesgrid/enhancers/rulesgrid.js
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/LayersFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/RequestsFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/RolesFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/ServicesFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/UsersFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/WorkspacesFilter.jsx
  web/client/components/misc/__tests__/PagedCombobox-test.jsx
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/reducers/__tests__/rulesmanager-test.js
  web/client/reducers/rulesmanager.js
  web/client/selectors/__tests__/rulesmanager-test.js
  web/client/selectors/rulesmanager.js
  web/client/themes/default/less/autocomplete.less
  web/client/themes/default/less/react-data-grid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9689 #9683: add Details Panel for MS dashboard
  web/client/actions/__tests__/details-test.js
  web/client/actions/details.js
  web/client/components/details/DetailsPanel.jsx
  web/client/components/layout/BorderLayout.jsx
  web/client/components/resources/ResourceGrid.jsx
  web/client/components/resources/modals/enhancers/handleSave.js
  web/client/configs/localConfig.json
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/dashboard-test.js
  web/client/epics/__tests__/details-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/config.js
  web/client/epics/dashboard.js
  web/client/epics/details.js
  web/client/epics/tutorial.js
  web/client/plugins/AddWidgetDashboard.jsx
  web/client/plugins/Dashboard.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/DashboardSave.jsx
  web/client/plugins/Details.jsx
  web/client/plugins/MapConnectionDashboard.jsx
  web/client/plugins/SidebarMenu.jsx
  web/client/plugins/__tests__/DashboardSave-test.jsx
  web/client/plugins/__tests__/SidebarMenu-test.jsx
  web/client/plugins/sidebarmenu/sidebarmenu.less
  web/client/product/plugins.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
  web/client/reducers/details.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/details.js
  web/client/selectors/sidebarmenu.js
  web/client/themes/default/less/dashboard.less
  web/client/themes/default/less/details.less
  web/client/themes/default/less/navbar.less
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9717 [Backport 2023.02.xx] #9589: Notify data projection not compatible / available for COG (#9690)
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/__tests__/DefaultLayer-test.jsx
  web/client/components/TOC/fragments/LayersTool.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/components/map/openlayers/plugins/COGLayer.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport

#9696 Fix #9627 replace quill editor with draftjs editor in dashboard text widget
  web/client/plugins/WidgetsBuilder.jsx
  web/client/themes/default/less/common.less
  web/client/themes/default/less/wizard.less
Labels: enhancement, Dashboard, Widgets, BackportNeeded

#9719 [Backport 2023.02.xx] #9553: Improving readability of long attribute values in attribute table and table widgets (#9701)
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/misc/enhancers/__tests__/handleLongTextEnhancer-test.jsx
  web/client/components/misc/enhancers/handleLongTextEnhancer.jsx
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9712 Fix #9295 added better handling of format in csw service
  web/client/actions/catalog.js
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/TMSAdvancedEditor.jsx
  web/client/components/catalog/editor/AdvancedSettings/WMSDomainAliases.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/misc/popover/DisposablePopover.jsx
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/reducers/catalog.js
  web/client/selectors/catalog.js
  web/client/themes/default/less/catalog.less
  web/client/themes/default/less/common.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: bug, Support, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT, Interoperability, new

#9724 [Backport 2022.02.xx] Fix #9627 Replace Quill editor with Draftjs editor in Dashboard's Text widget
  package.json
  web/client/components/mapviews/settings/CompactRichTextEditor.jsx
  web/client/components/widgets/builder/wizard/text/TextOptions.jsx
  web/client/plugins/WidgetsBuilder.jsx
  web/client/themes/default/less/common.less
Labels: enhancement, Dashboard, Widgets, Backport

#9607 Added fix for #9606
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
Labels: bug, annotations

#9722 [Backport 2023.02.xx] Fix #9624 Point cloud shading options (#9666)
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/PointCloudShadingSettings.jsx
  web/client/components/TOC/fragments/settings/ThreeDTilesSettings.jsx
  web/client/components/TOC/fragments/settings/__tests__/PointCloudShadingSettings-test.jsx
  web/client/components/TOC/fragments/settings/__tests__/ThreeDTilesSettings-test.jsx
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/PropertyField.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/themes/default/less/common.less
  web/client/themes/default/less/react-select.less
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: enhancement, Backport, 3D, C027-COMUNE_FI-2023-SUPPORT

#9720 #9702: Fix - Background selector in contexts won't retain thumbnail in view mode
  web/client/epics/__tests__/config-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/config.js
Labels: bug, Support, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#9727 [Backport 2023.02.xx] Fix #9606 Error with circle annotations + radius selection (#9607)
  web/client/components/mapcontrols/annotations/CoordinatesEditor.jsx
  web/client/components/mapcontrols/annotations/__tests__/CoordinatesEditor-test.js
Labels: bug, Backport

#9730 #9683: add Details Panel for MS dashboard [adding missing plugins in sidebar menu]
  web/client/plugins/AddWidgetDashboard.jsx
  web/client/plugins/DashboardExport.jsx
  web/client/plugins/DashboardImport.jsx
  web/client/plugins/DeleteDashboard.jsx
  web/client/plugins/MapConnectionDashboard.jsx
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9731 fix #9728 queryform misalignment issue
  web/client/components/misc/combobox/PagedCombobox.jsx
Labels: bug, BackportNeeded, Regression, C027-COMUNE_FI-2023-SUPPORT

#9738 Upgrade moment version
  package.json
Labels: dependencies, C206-DEUTSCHE_BAHN-2023-SUPPORT

#9733 Fix #9729 fixed formats in catalog used in dashboard
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/catalog.js
  web/client/epics/config.js
  web/client/plugins/widgetbuilder/enhancers/catalogEditorEnhancer.js
  web/client/selectors/catalog.js
Labels: bug, Widgets, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#9732 backport 2023.02.xx - Fix #9295 added better handling of format in csw service (#9712)
  web/client/actions/catalog.js
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/TMSAdvancedEditor.jsx
  web/client/components/catalog/editor/AdvancedSettings/WMSDomainAliases.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/misc/popover/DisposablePopover.jsx
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/reducers/catalog.js
  web/client/selectors/catalog.js
  web/client/themes/default/less/catalog.less
  web/client/themes/default/less/common.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: bug, Support, Backport, C027-COMUNE_FI-2023-SUPPORT, Interoperability, new

#9744 [Backport 2023.02.xx] #9702: Fix - Background selector in contexts won't retain thumbnail in view mode (#9720)
  web/client/epics/__tests__/config-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/config.js
Labels: bug, Support, Backport, C027-COMUNE_FI-2023-SUPPORT

#9742 backport 2023.02.xx - #9728 fix misalignement issue (#9731)
  web/client/components/misc/combobox/PagedCombobox.jsx
Labels: bug, Backport, Regression, C027-COMUNE_FI-2023-SUPPORT

#9747 backport 2023.02.xx - Fix #9729 fixed formats in catalog used in dashboard (#9733)
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/catalog.js
  web/client/epics/config.js
  web/client/plugins/widgetbuilder/enhancers/catalogEditorEnhancer.js
  web/client/selectors/catalog.js
Labels: bug, Widgets, Backport, C027-COMUNE_FI-2023-SUPPORT

#9745 #9711: Fix - WFS layer filter triggers infinite requests
  web/client/components/map/openlayers/plugins/WFSLayer.js
Labels: bug, C027-COMUNE_FI-2023-SUPPORT

#9741 Fix #9734 dashboard querypanel z_index
  web/client/plugins/QueryPanel.jsx
Labels: bug, Widgets, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9682 Fix #9623 widgets font customizations
  web/client/components/charts/WidgetChart.jsx
  web/client/components/widgets/builder/wizard/ChartWizard.jsx
  web/client/components/widgets/builder/wizard/CounterWizard.jsx
  web/client/components/widgets/builder/wizard/chart/ChartAxisOptions.jsx
  web/client/components/widgets/builder/wizard/chart/ChartLayoutOptions.jsx
  web/client/components/widgets/builder/wizard/chart/ChartTraceEditSelector.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ChartAxisOptions-test.jsx
  web/client/components/widgets/builder/wizard/chart/__tests__/ChartLayoutOptions-test.jsx
  web/client/components/widgets/builder/wizard/common/CounterAdvancedOptions.jsx
  web/client/components/widgets/builder/wizard/common/Font.jsx
  web/client/components/widgets/builder/wizard/common/PieChartAdvancedOptions.jsx
  web/client/components/widgets/widget/CounterView.jsx
  web/client/themes/default/less/wizard.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/WidgetsUtils.js
Labels: enhancement, Widgets, C027-COMUNE_FI-2023-SUPPORT

#9753 #9752: enhance geofence attribute rule editor
  web/client/components/manager/rulesmanager/AttributeAccessSelect.jsx
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/AttributesEditor-test.jsx
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/plugins/manager/RulesEditor.jsx
  web/client/themes/default/less/react-data-grid.less
  web/client/themes/default/less/rulesmanager.less
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9676 OpenStreetMap : use HTTPS and endpoint fixes
  web/client/utils/ConfigProvider.js
Labels: BackportNeeded

#9755 [Backport C040-2023.02.xx] #9752: enhance geofence attribute rule editor: (#9753)
  web/client/components/manager/rulesmanager/AttributeAccessSelect.jsx
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/AttributesEditor-test.jsx
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/plugins/manager/RulesEditor.jsx
  web/client/themes/default/less/react-data-grid.less
  web/client/themes/default/less/rulesmanager.less
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9736 #9589: Save layer sourceMetadata info
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Internal, BackportNeeded

#9756 [Backport 2023.02.xx] OpenStreetMap : use HTTPS and endpoint fixes (#9676)
  web/client/utils/ConfigProvider.js
Labels: Backport

#9758 backport c040-2023.02.xx - Fix #9734 dashboard querypanel z_index (#9741)
  web/client/plugins/QueryPanel.jsx
Labels: bug, backlog, Widgets, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9762 #9761: capitalize the login plugin content in sidebar
  web/client/themes/default/less/dropdown-menu.less
Labels: bug, enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9759 Backport to 2022.02.xx ref to PR 9686
  web/client/actions/geostory.js
  web/client/plugins/GeoStory.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
Labels: Backport

#9767 #9765: fix issue of not saving edits of attribute rules in rules manager
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
Labels: bug, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9769 [Backport 2023.02.xx] #9589: Save layer sourceMetadata info (#9736)
  web/client/utils/LayersUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
Labels: bug, Internal, Backport

#9771 #9761: fix style bug - capitalize the login plugin content in sidebar
  web/client/themes/default/less/dropdown-menu.less
Labels: bug, enhancement, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9772 #9765: fix issue of not saving edits of attribute rules in rules manager
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
Labels: bug, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9773 [Backport 2023.02.xx] #9761: fix style bug - capitalize the login plugin content in sidebar (#9771)
  web/client/themes/default/less/dropdown-menu.less
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9774 Fix #9653 force load of font when fontAwesome css is loaded
  package.json
  web/client/utils/styleparser/StyleParserUtils.js
Labels: bug, annotations, C027-COMUNE_FI-2023-SUPPORT

#9776 Fix #9653 with cesium marker
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/LeafletStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
  web/client/utils/styleparser/StyleParserUtils.js
  web/client/utils/styleparser/__tests__/StyleParserUtils-test.js
Labels: bug, annotations, C027-COMUNE_FI-2023-SUPPORT
