Repository geosolutions-it/MapStore2, pull requests merged in 2024-05, with the labels that each got.

#10274 update dev
  web/client/api/ArcGIS.js
  web/client/api/catalog/ArcGIS.js
  web/client/components/map/openlayers/plugins/ArcGISLayer.js
Labels: New Feature, C130-TOTAL-2024-GeoNode-DEV

#10271 [Backport 2024.01.xx] #10242: Fix - Viewer widgets state not aligned (#10254)
  web/client/epics/__tests__/widgets-test.js
  web/client/epics/widgets.js
Labels: bug, Internal, Backport, Regression

#10239 Fix #10238 Change Math.random with an alternative solution - C039
  web/client/components/TOC/fragments/legend/Legend.jsx
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/maps/forms/Thumbnail.jsx
  web/client/components/style/vector/marker/SymbolLayout.jsx
  web/client/utils/ColorUtils.js
  web/client/utils/RandomUtils.js
  web/client/utils/__tests__/RandomUtils-test.js
  web/client/utils/cesium/__tests__/MathUtils-test.js
Labels: enhancement, C039-2024-HALLIBURTON-SUPPORT

#10277 #9932: On Binary dashboard public dashboard have + button
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
Labels: bug, Internal, BackportNeeded

#10280 Fix #10237 On Dashboard and Geostory it is no longer possible to interact with layer filter
  web/client/plugins/FilterLayer/index.jsx
  web/client/plugins/TOC/components/DefaultLayer.jsx
  web/client/plugins/TOC/components/FilterNodeTool.jsx
  web/client/plugins/TOC/components/__tests__/FilterNodeTool-test.jsx
Labels: bug, Internal, Regression

#10278 Fix #10246 Issue adding layer when a group is present on TOC
  web/client/plugins/__tests__/AddGroup-test.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
Labels: bug, Internal

#10283 Fix #10237 hide filter button from dashboard legend
  web/client/components/widgets/widget/LegendView.jsx
  web/client/plugins/TOC/components/DefaultLayer.jsx
  web/client/plugins/TOC/components/TOC.jsx
  web/client/plugins/TOC/components/__tests__/DefaultLayer-test.jsx
  web/client/plugins/TOC/index.js
Labels: bug, Internal, BackportNeeded, Regression

#10284 [Backport 2024.01.xx] Fix #10246 Issue adding layer when a group is present on TOC (#10278)
  web/client/plugins/__tests__/AddGroup-test.jsx
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
Labels: bug, Internal, Backport

#10285 [Backport 2024.01.xx] Fix #10237 On Dashboard and Geostory it is no longer possible to interact with layer filter
  web/client/components/widgets/widget/LegendView.jsx
  web/client/plugins/FilterLayer/index.jsx
  web/client/plugins/TOC/components/DefaultLayer.jsx
  web/client/plugins/TOC/components/FilterNodeTool.jsx
  web/client/plugins/TOC/components/TOC.jsx
  web/client/plugins/TOC/components/__tests__/DefaultLayer-test.jsx
  web/client/plugins/TOC/components/__tests__/FilterNodeTool-test.jsx
  web/client/plugins/TOC/index.js
Labels: bug, Internal, Backport, Regression

#10286 Fix #10112 Review class name for symbolizer field
  web/client/components/styleeditor/Fields.jsx
  web/client/themes/default/less/style-editor.less
Labels: bug, Internal, BackportNeeded

#10292 [Backport 2024.01.xx] Update proxy.properties
  java/web/src/main/resources/proxy.properties
  project/standard/templates/web/src/main/resources/proxy.properties
Labels: Backport

#10291 #10144 Add to project proxy.properties filter for ifc files
  project/standard/templates/web/src/main/resources/proxy.properties
Labels: Task

#10269 #10213: fix When the TOC opens the navigation toolbar change position
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: bug, Internal, BackportNeeded

#10297 [Backport 2024.01.xx] #9932: On Binary dashboard public dashboard have + button (#10277)
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/dashboard.js
Labels: bug, Internal, Backport

#10296 [Backport 2024.01.xx] #10193: Issue with WFS added via Query params (#10195)
  web/client/api/WFS.js
  web/client/api/__tests__/WFS-test.js
Labels: bug, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10298 [Backport 2024.01.xx] #10262: Map (created with context) crashes if the export plugin is set up to be hidden to certain groups and the user is not logged in (#10270)
  web/client/utils/PluginsUtils.js
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#10301 Fix User Guide for 2024.01.00
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/filtering-layers/quick_date_ranges.mp4
  docs/user-guide/img/filtering-layers/time_range_picker_example.mp4
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, BackportNeeded

#10302 #10264: Layer visibility limits may prevent the Info panel of search results from opening
  web/client/epics/__tests__/search-test.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
Labels: enhancement, BackportNeeded, C206-DEUTSCHE_BAHN-2024-SUPPORT

#10276 #10214: Mobile issue - Overlay of tools and info
  web/client/plugins/widgets/WidgetsTray.jsx
  web/client/themes/default/less/leaflet.less
Labels: bug, Internal, BackportNeeded

#10307 [Backport 2024.01.xx] - Fix User Guide for 2024.01.00
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/filtering-layers/quick_date_ranges.mp4
  docs/user-guide/img/filtering-layers/time_range_picker_example.mp4
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, Backport

#10306 Update User Guide - Counter Widget options and 3D models options
  docs/user-guide/img/layer-settings/3d-model-style-ex.mp4
  docs/user-guide/img/widgets/counter-panel.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/widgets.md
Labels: Documentation, User Guide, BackportNeeded

#10309 [Backport 2024.01.xx] User Guide - Counter Widget options and 3D models options
  docs/user-guide/img/layer-settings/3d-model-style-ex.mp4
  docs/user-guide/img/widgets/counter-panel.jpg
  docs/user-guide/layer-settings.md
  docs/user-guide/widgets.md
Labels: Documentation, User Guide, Backport

#10305 #10136: Search for Map CRS coordinates
  web/client/components/mapcontrols/searchcoordinates/CoordinatesSearch.js
  web/client/components/mapcontrols/searchcoordinates/CurrentMapCRSCoordSearch.js
Labels: enhancement, BackportNeeded, C277-REGION_DE_MURCIA-2024-SUPPORT

#10313 [Backport 2024.01.xx] #10213: fix When the TOC opens the navigation toolbar change position (#10269)
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
Labels: bug, Internal, Backport

#10319 Fix #10318 fix details load if value is NODATA
  web/client/epics/config.js
Labels: bug, BackportNeeded, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10317 [Backport 2024.01.xx]: #10136: Search for Map CRS coordinates (#10220, #10305)
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/components/mapcontrols/searchcoordinates/CoordinatesSearch.js
  web/client/components/mapcontrols/searchcoordinates/CurrentMapCRSCoordSearch.js
  web/client/components/misc/coordinateeditors/CoordinateEntry.jsx
  web/client/components/misc/coordinateeditors/editors/CRSCoordinateEditor.jsx
  web/client/plugins/Search.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C277-REGION_DE_MURCIA-2024-SUPPORT

#10320 backport c040-2024.01.xx - Fix #10318 fix details load if value is NODATA (#10319)
  web/client/epics/config.js
Labels: Backport

#10187 [Backport 2024.01.xx] #9527 support loading COG layers from query params (#9531)
  docs/developer-guide/map-query-parameters.md
  web/client/api/catalog/COG.js
  web/client/epics/catalog.js
Labels: enhancement, Backport, External Contribution

#10324 [Backport 2024.01.xx] #10111: Enhance GeoFence attribute rule (#10145)
  web/client/api/geofence/RuleService.js
  web/client/api/geofence/__tests__/RuleService-test.js
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/AttributesEditor-test.jsx
Labels: enhancement, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10323 Backport 2024.01.xx - Fix #10318 fix details load if value is NODATA (#10319)
  web/client/epics/config.js
Labels: Backport, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10321 ArcGIS support, tests and docs
  web/client/api/ArcGIS.js
  web/client/api/__tests__/ArcGIS-test.js
  web/client/api/catalog/ArcGIS.js
  web/client/api/catalog/__tests__/ArcGIS-test.js
  web/client/test-resources/arcgis/arcgis-layer-test-data.json
  web/client/test-resources/arcgis/arcgis-test-data.json
  web/client/utils/mapinfo/__tests__/arcgis-test.js
  web/client/utils/mapinfo/arcgis.js
Labels: C130-TOTAL-2024-GeoNode-DEV

#10329 #10070 - Fix: Scroll bars for legend widgets won't move coherently with displayed data
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/withLegendScrollHandler.jsx
Labels: bug, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#10304 #10272: Choice of OGC service type for single layer in CSW catalog
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/api/catalog/CSW.js
  web/client/api/catalog/WFS.js
  web/client/api/catalog/__tests__/CSW-test.js
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#10316 #10308: Disable the marker when the search for map type is changed
  web/client/components/mapcontrols/search/SearchBar.jsx
Labels: bug, BackportNeeded, C277-REGION_DE_MURCIA-2024-SUPPORT

#10267 #10167: Set OL as default mapType also for 2D map in mobile
  web/client/themes/default/less/ol.less
  web/client/utils/MapTypeUtils.js
Labels: enhancement, Internal, BackportNeeded, Configuration

#10334 [Backport 2024.01.xx] #10272: Choice of OGC service type for single layer in CSW catalog (#10304)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/api/catalog/CSW.js
  web/client/api/catalog/WFS.js
  web/client/api/catalog/__tests__/CSW-test.js
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/__tests__/RecordItem-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C027-COMUNE_FI-2023-SUPPORT

#10332 [Backport 2024.01.xx] #10070 - Fix: Scroll bars for legend widgets won't move coherently with displayed data (#10329)
  web/client/components/charts/WidgetChart.jsx
  web/client/components/charts/withLegendScrollHandler.jsx
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#10336 [Backport 2024.01.xx] #10308: Disable the marker when the search for map type is changed (#10316)
  web/client/components/mapcontrols/search/SearchBar.jsx
Labels: bug, Backport, C277-REGION_DE_MURCIA-2024-SUPPORT

#10261 #10225: Enhance UX for simple 3D navigation in touch devices [Implementation via Config-level]
  web/client/components/buttons/ZoomToMaxExtentButton.jsx
  web/client/components/buttons/__tests__/ZoomToMaxExtentButton-test.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/plugins/Map.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
Labels: enhancement, BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10337 [Backport 2024.01.xx]: #10167: Set OL as default mapType also for 2D map in mobile (#10267)
  web/client/themes/default/less/ol.less
  web/client/utils/MapTypeUtils.js
Labels: enhancement, Internal, Backport, Configuration

#10312 #10289: Cursor position is shifted incorrectly in Localized number field component
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/I18N/__tests__/IntlNumberFormatControl-test.jsx
  web/client/libs/numeric-input/NumericInput.jsx
Labels: bug, Internal

#10331 Fix #10295 fixed measure tool rendering in map
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/MeasurementSupport-test.jsx
  web/client/plugins/Measure.jsx
  web/client/selectors/__tests__/measurement-test.js
  web/client/selectors/measurement.js
  web/client/themes/default/less/map-search-bar.less
  web/client/themes/default/less/measure.less
  web/client/utils/MeasurementUtils.js
Labels: bug, Internal, BackportNeeded

#10345 [Backport 2024.01.xx] #10264: Layer visibility limits may prevent the Info panel of search results from opening (#10302, #10325)
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/mapInfo.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/identify.js
  web/client/epics/search.js
  web/client/plugins/Search.jsx
Labels: enhancement, Backport, C206-DEUTSCHE_BAHN-2024-SUPPORT

#10346 [Backport 2024.01.xx] #10289: Cursor position is shifted incorrectly in Localized number field component (#10312)
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/I18N/__tests__/IntlNumberFormatControl-test.jsx
  web/client/libs/numeric-input/NumericInput.jsx
Labels: bug, Internal, Backport

#10338 Update User Guide - Add the possibility to choose the type of OGC service for single layer in CSW catalog
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/csw_with_more_ogc_service.mp4
Labels: Documentation, User Guide, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#10347 backport 2024.01.xx - Fix #10295 fixed measure tool rendering in map (#10331)
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/MeasurementSupport-test.jsx
  web/client/plugins/Measure.jsx
  web/client/selectors/__tests__/measurement-test.js
  web/client/selectors/measurement.js
  web/client/themes/default/less/map-search-bar.less
  web/client/themes/default/less/measure.less
  web/client/utils/MeasurementUtils.js
Labels: bug, Internal, Backport

#10330 #10040 ArcGIS Interoperability - ArcGIS MapServer Catalog and Layer support
  docs/developer-guide/maps-configuration.md
  package.json
  web/client/api/ArcGIS.js
  web/client/api/__tests__/ArcGIS-test.js
  web/client/api/catalog/ArcGIS.js
  web/client/api/catalog/Model.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/__tests__/ArcGIS-test.js
  web/client/api/catalog/index.js
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/geostory/contents/WebPageWrapper.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/ArcGISLayer.js
  web/client/components/map/cesium/plugins/index.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/ArcGISLayer.js
  web/client/components/map/leaflet/plugins/index.js
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/ArcGISLayer.js
  web/client/components/map/openlayers/plugins/index.js
  web/client/components/styleeditor/ModelInput.jsx
  web/client/epics/catalog.js
  web/client/epics/widgets.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/test-resources/arcgis/arcgis-layer-test-data.json
  web/client/test-resources/arcgis/arcgis-test-data.json
  web/client/test-resources/wmc/exported-context.wmc
  web/client/utils/CoordinatesUtils.js
  web/client/utils/LocaleUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/URLUtils.js
  web/client/utils/__tests__/CoordinatesUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
  web/client/utils/mapinfo/__tests__/arcgis-test.js
  web/client/utils/mapinfo/arcgis.js
Labels: New Feature, C130-TOTAL-2024-GeoNode-DEV

#10350 [Backport 2024.01.xx] - #10225: Enhance UX for simple 3D navigation in touch devices [Implementation via Config-level] (#10261)
  web/client/components/buttons/ZoomToMaxExtentButton.jsx
  web/client/components/buttons/__tests__/ZoomToMaxExtentButton-test.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/plugins/Map.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C299- POLITO -2023-MS_DigitalTwin

#10348 [Backport 2024.01.xx] User Guide - Add the possibility to choose the type of OGC service for single layer in CSW catalog
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/csw_with_more_ogc_service.mp4
Labels: Documentation, User Guide, Backport, C027-COMUNE_FI-2023-SUPPORT

#10349 #10281: Use Cache Options functionality extended to be applied on all the layers from a service
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10361 #10281: Use Cache Options functionality extended to be applied on all the layers from a service
  web/client/components/TOC/fragments/settings/WMSCacheOptions.jsx
  web/client/components/TOC/fragments/settings/__tests__/WMSCacheOptions-test.jsx
  web/client/epics/catalog.js
Labels: New Feature, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10363 [Backport 2024.01.xx]: #10281: Use Cache Options functionality extended to be applied on all the layers from a service (#10349, #10361)
  web/client/components/TOC/fragments/settings/WMSCacheOptions.jsx
  web/client/components/TOC/fragments/settings/__tests__/WMSCacheOptions-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport, New Feature, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10370 Fix #10368 fix positioning of groups generated from GPT tool
  web/client/reducers/layers.js
Labels: bug, BackportNeeded, Regression

#10376 [Backport 2024.01.xx] Fix #10112 Review class name for symbolizer field (#10286)
  web/client/components/styleeditor/Fields.jsx
  web/client/themes/default/less/style-editor.less
Labels: bug, Internal, Backport

#10327 Update User Guide - Search for Map CRS coordinates
  docs/user-guide/img/menu-bar/performed-search_by_crs.jpg
  docs/user-guide/img/menu-bar/search-types.jpg
  docs/user-guide/mapstore-toolbars.md
Labels: Documentation, User Guide, BackportNeeded, C277-REGION_DE_MURCIA-2024-SUPPORT

#10379 backport 2024.01.xx - Fix #10368 fix positioning of groups generated from GPT tool (#10370)
  web/client/reducers/layers.js
Labels: bug, Internal, Backport, Regression

#10362 Update User Guide - Use Cache Options from WMS service
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/advanced_settings_wms.jpg
Labels: Documentation, User Guide, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10378 Adding useCORS for maps.geosolutionsgroup.com geoserver names
  web/client/configs/localConfig.json
Labels: Internal, BackportNeeded, Configuration

#10328 User Guide - Update Attribute Table and Filter Layers sections
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/ar_sync.mp4
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-1.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-3.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/data_time_picker_example.mp4
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/filter_geometries.mp4
  docs/user-guide/img/attributes-table/filter_geometry.mp4
  docs/user-guide/img/attributes-table/filter_viewport.mp4
  docs/user-guide/img/attributes-table/filtered_features_grid.jpg
  docs/user-guide/img/attributes-table/filtered_quick_filter.mp4
  docs/user-guide/img/attributes-table/operations_drop_down_menu.jpg
  docs/user-guide/img/attributes-table/ordering_records.mp4
  docs/user-guide/img/attributes-table/show_hide_columns.mp4
  docs/user-guide/img/attributes-table/time_range_picker_example.mp4
  docs/user-guide/img/filtering-layers/ar_sync.mp4
  docs/user-guide/img/filtering-layers/filter_geometries.mp4
  docs/user-guide/img/filtering-layers/filter_geometry.mp4
  docs/user-guide/img/filtering-layers/filter_viewport.mp4
  docs/user-guide/img/filtering-layers/filtered_advanced_filtering.mp4
  docs/user-guide/img/filtering-layers/filtered_features_grid.jpg
  docs/user-guide/img/filtering-layers/get_filtered_features_info.mp4
Labels: Documentation, Internal, User Guide, BackportNeeded

#10380 [Backport 2024.01.xx] #10315 User Guide - Search for Map CRS coordinates
  docs/user-guide/img/menu-bar/performed-search_by_crs.jpg
  docs/user-guide/img/menu-bar/search-types.jpg
  docs/user-guide/mapstore-toolbars.md
Labels: Documentation, User Guide, Backport, C277-REGION_DE_MURCIA-2024-SUPPORT

#10381 [Backport 2024.01.xx] selected layers should not be considered when "enableInfoForSelectedLayers" is off (#10377)
  web/client/epics/identify.js
Labels: bug, Backport, External Contribution

#10382 [Backport 2024.01.xx] - User Guide - Update Attribute Table and Filter Layers sections
  docs/user-guide/attributes-table.md
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/attributes-table/add-new-feature-attributes.jpg
  docs/user-guide/img/attributes-table/ar_sync.mp4
  docs/user-guide/img/attributes-table/attribute-table-editing-layer.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-1.jpg
  docs/user-guide/img/attributes-table/attribute-table-quick-filter-3.jpg
  docs/user-guide/img/attributes-table/attributes-table-1.jpg
  docs/user-guide/img/attributes-table/data_time_picker_example.mp4
  docs/user-guide/img/attributes-table/edit-mode.jpg
  docs/user-guide/img/attributes-table/filter_geometries.mp4
  docs/user-guide/img/attributes-table/filter_geometry.mp4
  docs/user-guide/img/attributes-table/filter_viewport.mp4
  docs/user-guide/img/attributes-table/filtered_features_grid.jpg
  docs/user-guide/img/attributes-table/filtered_quick_filter.mp4
  docs/user-guide/img/attributes-table/operations_drop_down_menu.jpg
  docs/user-guide/img/attributes-table/ordering_records.mp4
  docs/user-guide/img/attributes-table/show_hide_columns.mp4
  docs/user-guide/img/attributes-table/time_range_picker_example.mp4
  docs/user-guide/img/filtering-layers/ar_sync.mp4
  docs/user-guide/img/filtering-layers/filter_geometries.mp4
  docs/user-guide/img/filtering-layers/filter_geometry.mp4
  docs/user-guide/img/filtering-layers/filter_viewport.mp4
  docs/user-guide/img/filtering-layers/filtered_advanced_filtering.mp4
  docs/user-guide/img/filtering-layers/filtered_features_grid.jpg
  docs/user-guide/img/filtering-layers/get_filtered_features_info.mp4
Labels: Documentation, Internal, User Guide, Backport

#10384 [Backport 2024.01.xx] - User Guide - Use Cache Options from WMS service
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/advanced_settings_wms.jpg
Labels: Documentation, User Guide, Backport, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10383 Fix #10373 Style layer - Property value cause an error on 3D view
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, Internal, BackportNeeded, Regression

#10386 [Backport 2024.01.xx] Adding useCORS for maps.geosolutionsgroup.com geoserver names (#10378)
  web/client/configs/localConfig.json
Labels: Internal, Configuration

#10388 [Backport 2024.01.xx] Fix #10373 Style layer - Property value cause an error on 3D view (#10383)
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/__tests__/CesiumStyleParser-test.js
Labels: bug, Internal, Backport, Regression

#10387 Fix #10371 TOC - Open on map initialization options does not work as expected
  web/client/plugins/TOC/index.js
  web/client/plugins/TOC/reducers/__tests__/toc-test.js
  web/client/plugins/TOC/reducers/toc.js
  web/client/product/plugins.js
Labels: bug, Internal, BackportNeeded

#10356 10294 fix arcgis layer grouping bug
  web/client/api/catalog/ArcGIS.js
  web/client/api/catalog/__tests__/ArcGIS-test.js
Labels: bug, Internal

#10393 [Backport 2024.01.xx] Fix #10371 TOC - Open on map initialization options does not work as expected (#10387)
  web/client/plugins/TOC/index.js
  web/client/plugins/TOC/reducers/__tests__/toc-test.js
  web/client/plugins/TOC/reducers/toc.js
  web/client/product/plugins.js
Labels: bug, Internal, Backport
