Repository geosolutions-it/MapStore2, pull requests merged in 2024-03, with the labels that each got.

#10003 #10002 Fix timeline snap issue
  web/client/epics/__tests__/timeline-test.js
  web/client/epics/playback.js
  web/client/epics/timeline.js
  web/client/observables/__tests__/multidim-test.js
  web/client/observables/multidim.js
  web/client/selectors/timeline.js
Labels: C105-2023-EMSA-SAR_DRIFT_DEMONSTRATOR

#10007 Updating the config.yaml file by adding support for A2 printing layout
  java/printing/resources/geoserver/print/config.yaml
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9981 9980 bugfix login collides with user guide
  web/client/components/tutorial/Tutorial.jsx
Labels: bug, External Contribution

#10013 Workflow fixes
  .github/ISSUE_TEMPLATE/release_steps.md
  .github/workflows/cut_major_branch.yml
Labels: Internal

#10016 Created actions to update gs versions
  .github/workflows/update_gs_versions.yml
Labels: Internal, BackportNeeded

#10017 Made the update versions to do a PR
  .github/workflows/update_gs_versions.yml
Labels: Internal, BackportNeeded

#10015 Dependency updates for mapstore-services and POMs refactoring
  .github/ISSUE_TEMPLATE/release_steps.md
  .github/workflows/cut_major_branch.yml
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
  .github/workflows/update_dependencies_versions.yml
  binary/bin-war/pom.xml
  binary/pom.xml
  docs/developer-guide/mapstore-migration-guide.md
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: dependencies, BackportNeeded, C125-AUSTROCONTROL-2023-MapStore

#9926 Update mapstore-migration-guide.md
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation

#10032 [Backport] Disable plugin SaveAs for non-ADMIN role users in Contexts
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: Task, C027-COMUNE_FI-2023-SUPPORT

#10037 Updating backgrounds to 512 tile size
  web/client/configs/localConfig.json
  web/client/configs/new.json
Labels: enhancement, Internal, Configuration

#10031 #9965 Mitigation of random test failures
  web/client/components/map/cesium/__tests__/Map-test.jsx
Labels: BackportNeeded

#10041 #8871 Improve getLegendGraphic compatibility for print
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: BackportNeeded, C125-AUSTROCONTROL-2023-MapStore

#10038 [Backport 2024.01.xx] #9965 Mitigation of random test failures (#10031)
  web/client/components/map/cesium/__tests__/Map-test.jsx
Labels: Backport

#10010 Fix #9999 Measures distance and area now supports all operations as geodesics features
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/plugins/Annotations/utils/AnnotationsUtils.js
  web/client/plugins/Annotations/utils/__tests__/AnnotationsUtils-test.js
  web/client/plugins/Annotations/utils/__tests__/resources.js
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/GeometryFunctionsUtils.js
  web/client/utils/styleparser/LeafletStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
  web/client/utils/styleparser/PrintStyleParser.js
  web/client/utils/styleparser/__tests__/LeafletStyleParser-test.js
Labels: New Feature, BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10036 GH actions update due to new project
  .github/ISSUE_TEMPLATE/release_steps.md
  .github/workflows/cut_major_branch.yml
  .github/workflows/update_dependencies_versions.yml
  docs/developer-guide/release.md
  project/standard/templates/backend/pom.xml
  project/standard/templates/backend/src/main/java/placeholder
  project/standard/templates/backend/src/main/resources/placeholder
  project/standard/templates/backend/src/test/java/placeholder
  project/standard/templates/backend/src/test/resources/placeholder
  project/standard/templates/build.sh
  project/standard/templates/pom.xml
  project/standard/templates/web/pom.xml
Labels: enhancement, Internal, BackportNeeded

#10019 [Backport 2024.01.xx] Action to update dependencies
  .github/workflows/update_gs_versions.yml
Labels: Backport

#10050 #10049 Add authenticationRules header method support
  docs/developer-guide/local-config.md
  web/client/libs/__tests__/ajax-test.js
  web/client/libs/ajax.js
  web/client/utils/SecurityUtils.js
  web/client/utils/__tests__/SecurityUtils-test.js
Labels: C105-2023-EMSA-SAR_DRIFT_DEMONSTRATOR

#10044 Remove xmldom
  package.json
  web/client/epics/catalog.js
Labels: Internal, BackportNeeded

#10054 Fix #10051 fix measurement perimeter label after editing geom
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
Labels: bug, annotations, BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10058 backport 2024.01.xx - Fix #9999 Measures distance and area now supports all operations as geodesics features (#10010)
  web/client/components/map/openlayers/MeasurementSupport.jsx
  web/client/plugins/Annotations/utils/AnnotationsUtils.js
  web/client/plugins/Annotations/utils/__tests__/AnnotationsUtils-test.js
  web/client/plugins/Annotations/utils/__tests__/resources.js
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
  web/client/utils/styleparser/CesiumStyleParser.js
  web/client/utils/styleparser/GeometryFunctionsUtils.js
  web/client/utils/styleparser/LeafletStyleParser.js
  web/client/utils/styleparser/OLStyleParser.js
  web/client/utils/styleparser/PrintStyleParser.js
  web/client/utils/styleparser/__tests__/LeafletStyleParser-test.js
Labels: Backport, New Feature, C299- POLITO -2023-MS_DigitalTwin

#10059 backport 2024.01.xx - Fix #10051 fix measurement perimeter label after editing geom (#10054)
  web/client/utils/MeasurementUtils.js
  web/client/utils/__tests__/MeasurementUtils-test.js
Labels: bug, annotations, Backport, C299- POLITO -2023-MS_DigitalTwin

#10057 [Backport #10037] Updating backgrounds to 512 tile size #9382
  web/client/configs/localConfig.json
  web/client/configs/new.json
Labels: enhancement, Internal, Backport, Configuration

#10052 [Backport 2024.01.xx] Remove xmldom (#10044)
  package.json
  web/client/epics/catalog.js
Labels: Backport

#10060 Updated migration guidelines to report print YAML changes
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, BackportNeeded, C125-AUSTROCONTROL-2023-MapStore

#10061 [Backport 2024.01.xx] Updated migration guidelines to report print YAML changes #10060
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, Backport, C125-AUSTROCONTROL-2023-MapStore

#9976 Update User Guide - Unadvertised resources
  .markdownlint.json
  docs/user-guide/img/resource-properties/edit-properties.jpg
  docs/user-guide/img/resource-properties/resource_creation.jpg
  docs/user-guide/img/resource-properties/resource_data.jpg
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10055 #10034: Include SortyBy parameter in the CSW catalog query
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature, C027-COMUNE_FI-2023-SUPPORT

#9907 Fix #9924 Improve and extend the configurability of ContextCreator
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/misc/Stepper.jsx
  web/client/components/misc/__tests__/Stepper-test.jsx
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/theme/ContextTheme.jsx
  web/client/epics/contextcreator.js
  web/client/epics/maptype.js
  web/client/plugins/ContextCreator.jsx
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
  web/client/utils/ContextCreatorUtils.js
  web/client/utils/__tests__/ContextCreatorUtils-test.js
Labels: enhancement, BackportNeeded, C130-TOTAL-2024-GeoNode-DEV

#10073 #9997 Fix async load for script in templates
  project/standard/templates/dashboard-embedded-template.html
  project/standard/templates/embeddedTemplate.html
  project/standard/templates/geostory-embedded-template.html
  project/standard/templates/indexTemplate.html
  web/client/dashboard-embedded-template.html
  web/client/embeddedTemplate.html
  web/client/geostory-embedded-template.html
  web/client/indexTemplate.html
Labels: BackportNeeded

#10074 [Backport 2024.01.xx] Fix #9924 Improve and extend the configurability of ContextCreator
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/misc/Stepper.jsx
  web/client/components/misc/__tests__/Stepper-test.jsx
  web/client/components/plugins/PluginsContainer.jsx
  web/client/components/theme/ContextTheme.jsx
  web/client/epics/contextcreator.js
  web/client/epics/maptype.js
  web/client/plugins/ContextCreator.jsx
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
  web/client/utils/ContextCreatorUtils.js
  web/client/utils/__tests__/ContextCreatorUtils-test.js
Labels: Backport, C130-TOTAL-2024-GeoNode-DEV

#10008 Advance project customization docs
  docs/developer-guide/advanced-project-customization.md
  mkdocs.yml
Labels: New Feature, BackportNeeded, C076-IDS-2023-SUPPORT

#10076 [Backport 2024.01.xx] Update User Guide - Add time range filtering for Attribute Table quick filter (#9977)
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/button/date_picker.jpg
  docs/user-guide/img/button/date_time_picker.jpg
  docs/user-guide/img/button/time_picker.jpg
  docs/user-guide/img/filtering-layers/attribute-table-quick-filter-1.jpg
  docs/user-guide/img/filtering-layers/attribute-table-quick-filter-3.jpg
  docs/user-guide/img/filtering-layers/data_time_picker_example.mp4
  docs/user-guide/img/filtering-layers/filtered_quick_filter.mp4
  docs/user-guide/img/filtering-layers/operations_drop_down_menu.jpg
Labels: Documentation, User Guide, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10067 [Backport 2024.01.xx] Update User Guide - Unadvertised resources (#9976)
  .markdownlint.json
  docs/user-guide/img/resource-properties/edit-properties.jpg
  docs/user-guide/img/resource-properties/resource_creation.jpg
  docs/user-guide/img/resource-properties/resource_data.jpg
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10068 [Backport 2024.01.xx] Update User Guide - Street Smart API support (#10021)
  docs/user-guide/img/button/cross-section-button.jpg
  docs/user-guide/img/button/cyclomedia-download-button.jpg
  docs/user-guide/img/button/cyclomedia-measurements-button.jpg
  docs/user-guide/img/button/display-button.jpg
  docs/user-guide/img/button/elevation-button.jpg
  docs/user-guide/img/button/image-info-button.jpg
  docs/user-guide/img/button/object-nformation-button.jpg
  docs/user-guide/img/button/oblique-viewer-button.jpg
  docs/user-guide/img/button/overlays-button.jpg
  docs/user-guide/img/button/point-cloud-button.jpg
  docs/user-guide/img/button/report-issue-button.jpg
  docs/user-guide/img/button/submit-button.jpg
  docs/user-guide/img/street-view/add-point.mp4
  docs/user-guide/img/street-view/credentials_api.jpg
  docs/user-guide/img/street-view/cyclomedia-popup.jpg
  docs/user-guide/img/street-view/cyclomedia_navigation_bar.jpg
  docs/user-guide/street-view.md
Labels: Documentation, User Guide, Backport, C027-COMUNE_FI-2023-SUPPORT

#10071 New Update User Guide - Add Details panel and new Side Bar for dashboards
  docs/user-guide/adding-widgets.md
  docs/user-guide/connecting-widgets.md
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/img/adding-widgets/legend-ex.jpg
  docs/user-guide/img/adding-widgets/legend-preview.jpg
  docs/user-guide/img/adding-widgets/select-map-connection.jpg
  docs/user-guide/img/adding-widgets/viewer-map.jpg
  docs/user-guide/img/button/geosolutions-link.jpg
  docs/user-guide/img/button/show-connections.jpg
  docs/user-guide/img/connecting-widgets/chart-map.mp4
  docs/user-guide/img/connecting-widgets/connection-options.jpg
  docs/user-guide/img/connecting-widgets/connections_widgets.mp4
  docs/user-guide/img/connecting-widgets/counter-map.mp4
  docs/user-guide/img/connecting-widgets/desktop.ini
  docs/user-guide/img/connecting-widgets/interaction_ab.mp4
  docs/user-guide/img/connecting-widgets/legend-map.jpg
  docs/user-guide/img/connecting-widgets/map-to-connect.mp4
  docs/user-guide/img/connecting-widgets/table-map.mp4
  docs/user-guide/img/connecting-widgets/widgets_interaction.mp4
  docs/user-guide/img/exploring-dashboards/dashboard-1.jpg
  docs/user-guide/img/exploring-dashboards/move-resize.mp4
  docs/user-guide/img/exploring-dashboards/options-menu.jpg
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10066 #9974: Add permission validation to manage catalog service
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/actions/dashboard.js
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CatalogForm.jsx
  web/client/components/catalog/CatalogServiceSelector.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/__tests__/Catalog-test.jsx
  web/client/components/catalog/__tests__/CatalogServiceSelector-test.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/__tests__/DashboardEditor-test.jsx
  web/client/plugins/__tests__/MetadataExplorer-test.jsx
  web/client/plugins/widgetbuilder/ChartLayerSelector.jsx
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/MapLayerSelector.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/catalog.js
  web/client/reducers/dashboard.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/catalog.js
  web/client/selectors/dashboard.js
Labels: New Feature, C027-COMUNE_FI-2023-SUPPORT

#10085 [Backport 2024.01.xx] Update User Guide - Support for IFC service (#9994)
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/ifc_service.jpg
  docs/user-guide/img/layer-settings/display-cog.jpg
  docs/user-guide/img/layer-settings/display-ifc.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10084 [Backport 2024.01.xx ] Update User Guide - Add Details panel and new Side Bar for dashboards (#10071)
  docs/user-guide/adding-widgets.md
  docs/user-guide/connecting-widgets.md
  docs/user-guide/exploring-dashboards.md
  docs/user-guide/img/adding-widgets/legend-ex.jpg
  docs/user-guide/img/adding-widgets/legend-preview.jpg
  docs/user-guide/img/adding-widgets/select-map-connection.jpg
  docs/user-guide/img/adding-widgets/viewer-map.jpg
  docs/user-guide/img/button/geosolutions-link.jpg
  docs/user-guide/img/button/show-connections.jpg
  docs/user-guide/img/connecting-widgets/chart-map.mp4
  docs/user-guide/img/connecting-widgets/connection-options.jpg
  docs/user-guide/img/connecting-widgets/connections_widgets.mp4
  docs/user-guide/img/connecting-widgets/counter-map.mp4
  docs/user-guide/img/connecting-widgets/desktop.ini
  docs/user-guide/img/connecting-widgets/interaction_ab.mp4
  docs/user-guide/img/connecting-widgets/legend-map.jpg
  docs/user-guide/img/connecting-widgets/map-to-connect.mp4
  docs/user-guide/img/connecting-widgets/table-map.mp4
  docs/user-guide/img/connecting-widgets/widgets_interaction.mp4
  docs/user-guide/img/exploring-dashboards/dashboard-1.jpg
  docs/user-guide/img/exploring-dashboards/move-resize.mp4
  docs/user-guide/img/exploring-dashboards/options-menu.jpg
  docs/user-guide/resources-properties.md
Labels: Documentation, User Guide, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10086 [Backport 2024.01.xx] Update User Guide - Visual Style Editor (#10028)
  docs/user-guide/img/button/configute_lite_button.jpg
  docs/user-guide/img/layer-settings/3dtiles_style.jpg
  docs/user-guide/img/layer-settings/bring-to-front.jpg
  docs/user-guide/img/layer-settings/classification_styl_panel.jpg
  docs/user-guide/img/layer-settings/classification_style_ex.jpg
  docs/user-guide/img/layer-settings/classify_icon_style_panel.jpg
  docs/user-guide/img/layer-settings/classify_mark_ex.jpg
  docs/user-guide/img/layer-settings/classify_mark_panel.jpg
  docs/user-guide/img/layer-settings/configure_popup.jpg
  docs/user-guide/img/layer-settings/ex_3dtiles_style.mp4
  docs/user-guide/img/layer-settings/ex_fill_style.mp4
  docs/user-guide/img/layer-settings/ex_line_style.jpg
  docs/user-guide/img/layer-settings/ex_text_style.mp4
  docs/user-guide/img/layer-settings/extrusion.jpg
  docs/user-guide/img/layer-settings/filter_3dtiles_style.jpg
  docs/user-guide/img/layer-settings/height-reference.jpg
  docs/user-guide/img/layer-settings/icon_panel.jpg
  docs/user-guide/img/layer-settings/leader-line.jpg
  docs/user-guide/img/layer-settings/line_panel.jpg
  docs/user-guide/img/layer-settings/mark_panel.jpg
  docs/user-guide/img/layer-settings/mark_style_ex.jpg
  docs/user-guide/img/layer-settings/properties_style.jpg
  docs/user-guide/img/layer-settings/property-value-example.mp4
  docs/user-guide/img/layer-settings/text_panel.jpg
  docs/user-guide/img/layer-settings/thematic-layer.mp4
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10088 [Backport 2024.01.xx] Update User Guide - Multivariable charts and the text configuration (#9677)
  docs/user-guide/filtering-layers.md
  docs/user-guide/img/filtering-layers/area-filter-dash.mp4
  docs/user-guide/img/filtering-layers/edit_geom.jpg
  docs/user-guide/img/filtering-layers/geom_filter.mp4
  docs/user-guide/img/filtering-layers/query-panel.jpg
  docs/user-guide/img/widgets/alphanumeric.jpg
  docs/user-guide/img/widgets/axes_tab.jpg
  docs/user-guide/img/widgets/bar_charts.jpg
  docs/user-guide/img/widgets/bar_type.jpg
  docs/user-guide/img/widgets/chart-ex.jpg
  docs/user-guide/img/widgets/chart-layer-selection.jpg
  docs/user-guide/img/widgets/chart-options.jpg
  docs/user-guide/img/widgets/counter-panel.jpg
  docs/user-guide/img/widgets/custom_colors.mp4
  docs/user-guide/img/widgets/custom_trace_value_tooltip.jpg
  docs/user-guide/img/widgets/default_class_label.jpg
  docs/user-guide/img/widgets/layout.jpg
  docs/user-guide/img/widgets/numeric.jpg
  docs/user-guide/img/widgets/percentages_in_legend.jpg
  docs/user-guide/img/widgets/trace_axes.jpg
  docs/user-guide/img/widgets/trace_classification_style.jpg
  docs/user-guide/img/widgets/trace_data.jpg
  docs/user-guide/img/widgets/trace_legend_options.jpg
  docs/user-guide/img/widgets/trace_simple_style.jpg
  docs/user-guide/img/widgets/trace_style.jpg
  docs/user-guide/img/widgets/trace_value_formatting.jpg
  docs/user-guide/img/widgets/traces_tab.jpg
  docs/user-guide/img/widgets/widget-info.jpg
  docs/user-guide/img/widgets/widget-options.jpg
  docs/user-guide/widgets.md
Labels: Documentation, Widgets, User Guide, Backport, C027-COMUNE_FI-2023-SUPPORT

#10087 [Backport 2024.01.xx] Update User Guide - New Annotations UI and 3D support (#9571)
  docs/user-guide/annotations.md
  docs/user-guide/img/annotations/3d_annotations.jpg
  docs/user-guide/img/annotations/3d_model_type.jpg
  docs/user-guide/img/annotations/add_vertex_button.mp4
  docs/user-guide/img/annotations/annotation2.jpg
  docs/user-guide/img/annotations/annotation3.jpg
  docs/user-guide/img/annotations/annotation_tool.jpg
  docs/user-guide/img/annotations/annotations_on_toc.jpg
  docs/user-guide/img/annotations/annotations_toolbar.jpg
  docs/user-guide/img/annotations/bring-to-front.jpg
  docs/user-guide/img/annotations/circle_style_editor.jpg
  docs/user-guide/img/annotations/clamp-to-ground.jpg
  docs/user-guide/img/annotations/coordinates_format_switcher.mp4
  docs/user-guide/img/annotations/extrusion-geometry.jpg
  docs/user-guide/img/annotations/geometries-tab.jpg
  docs/user-guide/img/annotations/height-reference.jpg
  docs/user-guide/img/annotations/height_switcher.mp4
  docs/user-guide/img/annotations/icon_style_editor.mp4
  docs/user-guide/img/annotations/invalid_vertex.jpg
  docs/user-guide/img/annotations/invalid_vertex2.mp4.mp4
  docs/user-guide/img/annotations/leader-line.jpg
  docs/user-guide/img/annotations/line_annotation_drawing.mp4
  docs/user-guide/img/annotations/marker_style_editor.jpg
  docs/user-guide/img/annotations/marker_type_selection.jpg
  docs/user-guide/img/annotations/polygon-type.jpg
  docs/user-guide/img/annotations/polygon_style_editor.jpg
  docs/user-guide/img/annotations/polyline_style_editor.jpg
  docs/user-guide/img/annotations/settings_tab.jpg
  docs/user-guide/img/annotations/start_point_option.mp4
  docs/user-guide/img/annotations/text_annotation_editor.jpg
  docs/user-guide/img/button/annotations2.jpg
  docs/user-guide/img/button/download_annotation_button.jpg
Labels: Documentation, annotations, User Guide, Backport, 3D, C027-COMUNE_FI-2023-SUPPORT

#10090 [Backport 2024.01.xx] #9974: Add permission validation to manage catalog service (#10066)
  web/client/actions/__tests__/catalog-test.js
  web/client/actions/catalog.js
  web/client/actions/dashboard.js
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CatalogForm.jsx
  web/client/components/catalog/CatalogServiceSelector.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/__tests__/Catalog-test.jsx
  web/client/components/catalog/__tests__/CatalogServiceSelector-test.jsx
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/__tests__/DashboardEditor-test.jsx
  web/client/plugins/__tests__/MetadataExplorer-test.jsx
  web/client/plugins/widgetbuilder/ChartLayerSelector.jsx
  web/client/plugins/widgetbuilder/LayerSelector.jsx
  web/client/plugins/widgetbuilder/MapLayerSelector.jsx
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/__tests__/dashboard-test.js
  web/client/reducers/catalog.js
  web/client/reducers/dashboard.js
  web/client/selectors/__tests__/catalog-test.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/catalog.js
  web/client/selectors/dashboard.js
Labels: Backport, New Feature, C027-COMUNE_FI-2023-SUPPORT

#10079 #10064: Limit group permission for anonymous user
  web/client/actions/users.js
  web/client/components/manager/users/GroupGrid.jsx
  web/client/components/manager/users/UserGroups.jsx
  web/client/components/resources/modals/fragments/PermissionEditor.jsx
  web/client/components/resources/modals/fragments/__tests__/PermissionEditor-test.jsx
  web/client/epics/permalink.js
  web/client/utils/SecurityUtils.js
Labels: bug, Internal, BackportNeeded

#10091 New Update measure.md including note for 3D measurement
  docs/user-guide/measure.md
Labels: Documentation, User Guide, BackportNeeded, 3D

#10089 #10083: Persistence of COG layer's metadata info in catalog service
  docs/developer-guide/local-config.md
  web/client/api/catalog/COG.js
  web/client/api/catalog/__tests__/COG-test.js
  web/client/epics/catalog.js
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement, Internal, BackportNeeded

#10093 [Backport 2024.01.xx] #10064: Limit group permission for anonymous user (#10079)
  web/client/actions/users.js
  web/client/components/manager/users/GroupGrid.jsx
  web/client/components/manager/users/UserGroups.jsx
  web/client/components/resources/modals/fragments/PermissionEditor.jsx
  web/client/components/resources/modals/fragments/__tests__/PermissionEditor-test.jsx
  web/client/epics/permalink.js
  web/client/utils/SecurityUtils.js
Labels: bug, Internal, Backport

#10077 #10034: Shown exception text from Catalog in the notification
  web/client/components/catalog/Catalog.jsx
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/utils/StringUtils.js
  web/client/utils/__tests__/StringUtils-test.js
Labels: enhancement, BackportNeeded, C027-COMUNE_FI-2023-SUPPORT

#10094 Fix #10062 show again map thumbnail in map viewer
  web/client/actions/__tests__/config-test.js
  web/client/actions/config.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/config.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: bug, Internal, BackportNeeded, Regression

#10095 [Backport 2024.01.xx] #10034: Include SortyBy parameter in the CSW catalog query (#10055)
  web/client/api/CSW.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/StringUtils.js
  web/client/utils/__tests__/StringUtils-test.js
Labels: Backport, New Feature, C027-COMUNE_FI-2023-SUPPORT

#10048 Fix #10000 adding geodesic lines to 3d measures
  web/client/components/map/cesium/DrawMeasureSupport.jsx
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/MeasurementSupport-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/cesium/DrawGeometryInteraction.js
Labels: BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10099 [Backport 2024.01.xx] Update User Guide - Include SortyBy parameter in the CSW Catalog (#10096)
  docs/user-guide/catalog.md
  docs/user-guide/img/catalog/advanced_settings_csw.jpg
Labels: Documentation, User Guide, Backport, C027-COMUNE_FI-2023-SUPPORT

#10098 [Backport 2024.01.xx] #10083: Persistence of COG layer's metadata info in catalog service (#10089)
  docs/developer-guide/local-config.md
  web/client/api/catalog/COG.js
  web/client/api/catalog/__tests__/COG-test.js
  web/client/epics/catalog.js
  web/client/utils/CatalogUtils.js
  web/client/utils/__tests__/CatalogUtils-test.js
Labels: enhancement, Internal, Backport

#10053 [Backport 2024.01.xx] Bump axios from 0.24.0 to 0.28.0 #9985
  package.json
Labels: Backport

#9857 #9588: Add support to multi-band color mapping for COG layers
  docs/developer-guide/maps-configuration.md
  web/client/api/catalog/COG.js
  web/client/api/catalog/__tests__/COG-test.js
  web/client/components/map/openlayers/plugins/COGLayer.js
  web/client/plugins/styleeditor/MultiBandEditor.jsx
  web/client/plugins/styleeditor/__tests__/MultiBandEditor-test.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/cog/LayerUtils.js
  web/client/utils/cog/__tests__/LayerUtils-test.jsx
Labels: enhancement, Internal, BackportNeeded

#10097 Backport Advance project customization docs (#10008)
  docs/developer-guide/advanced-project-customization.md
  mkdocs.yml
Labels: Backport, New Feature, C076-IDS-2023-SUPPORT

#10104 Fix #10000 position of total length for geodesic distance
  web/client/components/map/cesium/DrawMeasureSupport.jsx
Labels: enhancement, BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10106 backport 2024.01.xx - Fix #10062 show again map thumbnail in map viewer (#10094)
  web/client/actions/__tests__/config-test.js
  web/client/actions/config.js
  web/client/epics/__tests__/config-test.js
  web/client/epics/config.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
Labels: bug, Internal, Backport

#10102 Fix #10100 intersection advanced options
  web/client/epics/geoProcessing.js
Labels: bug, Internal, BackportNeeded

#10105 [Backport 2024.01.xx] Dependency updates for mapstore-services and POMs refactoring (#10015)
  .github/ISSUE_TEMPLATE/release_steps.md
  .github/workflows/CI.yml
  .github/workflows/cut_major_branch.yml
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
  .github/workflows/update_dependencies_versions.yml
  binary/bin-war/pom.xml
  binary/pom.xml
  docs/developer-guide/release.md
  java/pom.xml
  java/printing/pom.xml
  java/services/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/backend/pom.xml
  project/standard/templates/backend/src/main/java/placeholder
  project/standard/templates/backend/src/main/resources/placeholder
  project/standard/templates/backend/src/test/java/placeholder
  project/standard/templates/backend/src/test/resources/placeholder
  project/standard/templates/build.sh
  project/standard/templates/pom.xml
  project/standard/templates/web/pom.xml
Labels: Backport

#10107 [Backport 2024.01.xx] #9588: Add support to multi-band color mapping for COG layers (#9857)
  docs/developer-guide/maps-configuration.md
  web/client/api/catalog/COG.js
  web/client/api/catalog/__tests__/COG-test.js
  web/client/components/map/openlayers/plugins/COGLayer.js
  web/client/plugins/styleeditor/MultiBandEditor.jsx
  web/client/plugins/styleeditor/__tests__/MultiBandEditor-test.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/cog/LayerUtils.js
  web/client/utils/cog/__tests__/LayerUtils-test.jsx
Labels: enhancement, Internal, Backport

#10110 Backport 2024.01.xx - Fix #10000 adding geodesic lines to 3d measures
  web/client/components/map/cesium/DrawMeasureSupport.jsx
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/MeasurementSupport-test.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/cesium/DrawGeometryInteraction.js
Labels: Backport, New Feature, C299- POLITO -2023-MS_DigitalTwin

#10022 #9972 Fix cross layer filter persistence bug
  web/client/reducers/__tests__/queryform-test.js
  web/client/reducers/queryform.js
Labels: bug, Widgets, Charts, C179-PUBLIACQUA-2024-SUPPORT

#10113 backport 2024.01.xx - Fix #10100 intersection advanced options (#10102)
  web/client/epics/geoProcessing.js
Labels: Internal, Backport

#10116 Fix #10114 fix the crash when drawin a measure area
  web/client/components/map/cesium/DrawMeasureSupport.jsx
Labels: bug, BackportNeeded, 3D, measurement, C299- POLITO -2023-MS_DigitalTwin

#10122 Update mapstore-migration-guide.md
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, Internal

#10123 [Backport 2024.01.xx] Update mapstore-migration-guide.md (#10122)
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, Internal, Backport

#10120 Backport #9972 Fix cross layer filter persistence bug (#10022)
  web/client/reducers/__tests__/queryform-test.js
  web/client/reducers/queryform.js
Labels: bug, Widgets, Backport, Charts, C179-PUBLIACQUA-2024-SUPPORT

#10118 #10112 - Fix style editor for raster layer channel block
  web/client/components/styleeditor/Fields.jsx
  web/client/themes/default/less/style-editor.less
Labels: bug, Internal

#10133 [Baclport 2024.01.xx] #10117 Updated minimum java requirements (#10132)
  docs/developer-guide/requirements.md
Labels: Internal, Backport

#10135 [Backport 2024.01.xx] #10112 - Fix style editor for raster layer channel block (#10118)
  web/client/components/styleeditor/Fields.jsx
  web/client/themes/default/less/style-editor.less
Labels: bug, Internal, Backport

#10128 Fix #9982 dropdown style and toc configuration improvements
  web/client/configs/localConfig.json
  web/client/hooks/__tests__/usePluginItems-test.js
  web/client/hooks/usePluginItems.js
  web/client/themes/default/less/toc.less
Labels: bug, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10046 geosolutions-it#9688: Make DOMUtils tests less dependent on platform-varying browser default stylesheet
  web/client/utils/__tests__/DOMUtil-test.js
Labels: External Contribution
