Repository geosolutions-it/MapStore2, pull requests merged in 2024-08, with the labels that each got.

#10502 Switching to mapfish-print new official version 2.3.1
  pom.xml
  project/standard/templates/web/pom.xml
Labels: Internal

#10490 #10487: Custom Tile Grids settings for WMS service are not retained when adding a Background layer from Catalog
  web/client/epics/__tests__/backgroundselector-test.js
  web/client/epics/backgroundselector.js
  web/client/epics/catalog.js
  web/client/utils/WMSUtils.js
  web/client/utils/__tests__/WMSUtils-test.js
Labels: bug, C047-CLEVELAND-METROPARKS-2022-SUPPORT

#10438 Fix #10489 Problems with GeoStory map configurations merge process
  web/client/components/geostory/common/enhancers/__tests__/map-test.jsx
  web/client/components/geostory/common/enhancers/map.jsx
  web/client/plugins/TOC/components/StyleBasedWMSJsonLegend.jsx
  web/client/utils/GeoStoryUtils.js
  web/client/utils/__tests__/GeoStoryUtils-test.js
Labels: bug, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10485 Tomcat leak version
  Dockerfile
  binary/tomcat/conf/server.xml
Labels: Internal, DevOps, External Contribution

#10507 Fix #10506 Adding possibility to fetch legends images using Bearer token
  web/client/components/misc/SecureImage.jsx
  web/client/plugins/TOC/components/Legend.jsx
  web/client/plugins/TOC/components/__tests__/Legend-test.jsx
Labels: enhancement, C039-2024-HALLIBURTON-SUPPORT

#10517 Fix #10513 Print preview state is not aligned with TOC
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
Labels: bug, investigation, Internal

#10176 Fix #10175 : fix 2 services search test nondeterminism
  web/client/epics/__tests__/search-test.js
Labels: enhancement, External Contribution, C206-DEUTSCHE_BAHN-2023-SUPPORT

#10142 geosolutions-it#10127: update tests to enable react-redux 7.x upwards
  web/client/components/app/__tests__/StandardAppComponent-test.jsx
  web/client/components/app/__tests__/StandardContainer-test.jsx
  web/client/components/app/__tests__/StandardRouter-test.jsx
  web/client/components/buttons/__tests__/ZoomButton-test.jsx
  web/client/components/buttons/__tests__/ZoomToMaxExtentButton-test.jsx
  web/client/components/data/identify/viewers/__tests__/viewers-test.jsx
  web/client/components/home/__tests__/Home-test.jsx
  web/client/components/plugins/__tests__/PluginsContainer-test.jsx
  web/client/plugins/contextmanager/__tests__/PaginationToolbar-test.jsx
  web/client/plugins/contexts/__tests__/PaginationToolbar-test.jsx
  web/client/product/components/viewer/__tests__/MapViewer-test.jsx
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: enhancement, External Contribution, C206-DEUTSCHE_BAHN-2023-SUPPORT

#10525 #10521 - Update center comparison in OL map component
  web/client/components/map/openlayers/Map.jsx
  web/client/components/map/openlayers/__tests__/Map-test.jsx
Labels: enhancement, C039-2024-HALLIBURTON-SUPPORT
