Repository geosolutions-it/MapStore2, pull requests merged in 2024-12, with the labels that each got.

#10704 [Backport 2024.02.xx] Fix #10695 Handle empty values for and/or/not/nor filters (#10696)
  web/client/utils/ogc/Filter/FilterBuilder.js
  web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
  web/client/utils/ogc/Filter/__tests__/operators-test.js
  web/client/utils/ogc/Filter/operators.js
Labels: Backport

#10698 Fix #10697 parsing of CQL ILIKE filter
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
Labels: BackportNeeded

#10707 [Backport 2024.02.xx] Fix #10697 parsing of CQL ILIKE filter (#10698)
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
Labels: Backport

#10720 [Backport 2024.02.xx] - Dashboards - no longer shows counter widgets #10708 #10714
  web/client/components/widgets/enhancers/__tests__/wpsCounter-test.js
  web/client/components/widgets/enhancers/wfsTable/__tests__/triggerFetch-test.js
  web/client/components/widgets/enhancers/wfsTable/triggerFetch.js
  web/client/components/widgets/enhancers/wpsCounter.js
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/WidgetsUtils-test.js
Labels: bug, Internal, Backport, Regression

#10706 Fix #10692 print bug when trying to print
  web/client/components/print/PrintPreview.jsx
  web/client/themes/default/less/print.less
Labels: bug, Internal

#10723 #10717: Fix typo in localized component
  web/client/components/I18N/Localized.jsx
Labels: enhancement

#10715 #10711: Control loading FontAwesome for vector style
  web/client/utils/styleparser/StyleParserUtils.js
Labels: enhancement, BackportNeeded

#10700 Update plotlyJS and plotly-react.js to latest stable
  package.json
Labels: Internal
