Repository geosolutions-it/MapStore2, pull requests merged in 2024-02, with the labels that each got.

#9942 Fix #9941 The defaultPointType and defaultShape configurations are not working as expected on Annotations
  web/client/plugins/Annotations/containers/AnnotationsEditor.jsx
Labels: bug, Regression, C125-AUSTROCONTROL-2023-MapStore

#9948 Update mapstore-migration-guide.md
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation

#9943 Enable DeleteMap Plugin
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: bug, Internal, Regression

#9947 Fix #9944 Map connected to table with date attribute breaks the app
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/data/featuregrid/filterRenderers/__tests__/BaseDateTimeFilter-test.jsx
  web/client/components/data/featuregrid/filterRenderers/index.js
  web/client/themes/default/less/widget.less
Labels: bug, Dashboard, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9950 Fix #9945 WFS legacy style breaks the app in OpenLayers
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WFSLayer.js
Labels: bug, BackportNeeded, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9956 [Backport c040-2024.01.xx] Fix #9945 WFS legacy style breaks the app in OpenLayers (#9950)
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/plugins/WFSLayer.js
Labels: bug, Backport, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9955 [Backport c040-2024.01.xx] Fix #9944 Map connected to table with date attribute breaks the app (#9947)
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/data/featuregrid/filterRenderers/__tests__/BaseDateTimeFilter-test.jsx
  web/client/components/data/featuregrid/filterRenderers/index.js
  web/client/themes/default/less/widget.less
Labels: bug, Dashboard, Backport, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9952 Disable plugin SaveAs for non-ADMIN role users in Contexts
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: enhancement, investigation, C027-COMUNE_FI-2023-SUPPORT

#9957 Fix double calls when fetching map configuration data and attributes.
  web/client/epics/__tests__/config-test.js
  web/client/epics/config.js
Labels: bug, investigation, Internal

#9963 Fix #9959 Editing of date/time attributes is not working
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/themes/default/less/react-data-grid.less
Labels: bug, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9962 #9583 unadvertised resources
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
  web/client/components/resources/forms/Metadata.jsx
  web/client/components/resources/forms/__tests__/Metadata-test.jsx
  web/client/components/resources/modals/enhancers/handleResourceData.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9966 [Backport c040-2024.01.xx] Fix #9959 Editing of date/time attributes is not working (#9963)
  web/client/components/data/featuregrid/editors/DateTimeEditor.jsx
  web/client/components/data/featuregrid/enhancers/editor.js
  web/client/components/data/featuregrid/formatters/__tests__/index-test.jsx
  web/client/components/data/featuregrid/formatters/index.js
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/themes/default/less/react-data-grid.less
Labels: bug, Backport

#9917 9564 geojson mime type support
  docs/user-guide/catalog.md
  web/client/actions/mapInfo.js
  web/client/api/identify.jsx
  web/client/components/TOC/fragments/settings/FeatureInfo.jsx
  web/client/components/data/identify/DefaultViewer.jsx
  web/client/components/data/identify/viewers/ViewerPage.jsx
  web/client/components/misc/FeatureInfoFormatSelector.jsx
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/index.jsx
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
  web/client/utils/__tests__/WMSUtils-test.js
  web/client/utils/mapinfo/__tests__/wms-test.js
  web/client/utils/mapinfo/__tests__/wmts-test.js
Labels: enhancement, C044-VLAANDEREN-2023-SUPPORT

#9908 #9830: Support for IFC as a further 3D model managed by MapStore
  build/buildConfig.js
  build/testConfig.js
  docs/developer-guide/maps-configuration.md
  package.json
  web/client/api/Model.js
  web/client/api/__tests__/Model-test.jsx
  web/client/api/catalog/CSW.js
  web/client/api/catalog/Model.js
  web/client/api/catalog/__tests__/Model-test.js
  web/client/api/catalog/index.js
  web/client/components/TOC/DefaultLayer.jsx
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/ModelTransformation.jsx
  web/client/components/TOC/fragments/settings/__tests__/ModelTransformation-test.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/plugins/ModelLayer.js
  web/client/components/map/cesium/plugins/index.js
  web/client/epics/catalog.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/TOC.jsx
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/test-resources/ifcModels/ifcModel.ifc
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/utils/MapInfoUtils.js
  web/client/utils/mapinfo/__tests__/model-test.js
  web/client/utils/mapinfo/model.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9979 #9830: fix mardown linting error in DEV build due to web-ifc files in dist folder (fix_9830)
  .markdownlintignore
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9984 #9583 Fix SaveAs plugin showing persisted data
  web/client/plugins/SaveAs.jsx
  web/client/plugins/__tests__/SaveAs-test.jsx
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9968 Added creator/editor read-only fields in edit resource properties modal
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/resources/forms/Metadata.jsx
  web/client/components/resources/forms/__tests__/Metadata-test.jsx
  web/client/components/resources/modals/enhancers/handleResourceData.jsx
  web/client/components/resources/modals/fragments/MainForm.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9951 #9915: Ability to select quick date ranges for date filter fields in Filter Layer tool
  web/client/components/data/query/DateField.jsx
  web/client/components/data/query/GroupField.jsx
  web/client/components/data/query/__tests__/DateField-test.jsx
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/components/misc/datetimepicker/QuickTimeSelectors.jsx
  web/client/components/misc/datetimepicker/RangedDateTimePicker.js
  web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js
  web/client/components/misc/datetimepicker/__tests__/QuickTimeSelectors-test.js
  web/client/components/misc/datetimepicker/__tests__/RangedDateTimePicker-test.js
  web/client/plugins/QueryPanel.jsx
  web/client/themes/default/less/featuregrid.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FeatureGridUtils.js
  web/client/utils/TimeUtils.js
  web/client/utils/__tests__/TimeUtils-test.js
Labels: enhancement, Priority: High, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9973 #9383: Re-enable PDF generation
  docs/requirements.txt
  docs/theme/css/extra.css
  docs/theme/img/download-pdf-icon.png
  docs/theme/partials/tabs.html
  mkdocs.yml
  pdf_event_hook.py
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9987 #9830: enhance Support for IFC 3d model in MS
  web/client/api/Model.js
  web/client/api/__tests__/Model-test.jsx
  web/client/components/TOC/fragments/settings/ModelTransformation.jsx
  web/client/epics/catalog.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#9996 #9995: Fix features with no visibility prop when using print tool
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
Labels: bug, C169-Rennes-Métropole-2023-GeOrchestra4

#9971 Fix #9916: handle Stat Query Engine integration in Visual Style Editor
  web/client/api/StyleEditor.js
  web/client/api/__tests__/StyleEditor-test.js
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/misc/codeEditors/JSONEditor.jsx
  web/client/components/misc/toolbar/__tests__/Toolbar-test.jsx
  web/client/components/styleeditor/ClassificationLayerSettings.jsx
  web/client/components/styleeditor/ClassificationSymbolizer.jsx
  web/client/components/styleeditor/Fields.jsx
  web/client/components/styleeditor/RulesEditor.jsx
  web/client/components/styleeditor/SelectInput.jsx
  web/client/components/styleeditor/VisualStyleEditor.jsx
  web/client/components/styleeditor/__tests__/ClassificationLayerSettings-test.jsx
  web/client/components/styleeditor/config/blocks.js
  web/client/components/styleeditor/config/property.js
  web/client/epics/styleeditor.js
  web/client/plugins/styleeditor/StyleCodeEditor.jsx
  web/client/plugins/styleeditor/index.js
  web/client/themes/default/less/style-editor.less
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, new, C040-COMUNE_GE-2023-CUSTOM-SUPPORT
