Repository geosolutions-it/MapStore2, pull requests merged in 2024-07, with the labels that each got.

#10344 #10322: Fix scale selector to make it compatible with different projections
  web/client/actions/__tests__/print-test.js
  web/client/actions/print.js
  web/client/components/print/MapPreview.jsx
  web/client/components/print/__tests__/MapPreview-test.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/plugins/__tests__/print/Projection-test.jsx
  web/client/plugins/print/Projection.jsx
  web/client/reducers/__tests__/print-test.js
  web/client/reducers/print.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: bug, C277-REGION_DE_MURCIA-2024-SUPPORT

#10452 [Backport 2024.01.xx] - #10322: Fix scale selector to make it compatible with different projections (#10344)
  web/client/actions/__tests__/print-test.js
  web/client/actions/print.js
  web/client/components/print/MapPreview.jsx
  web/client/components/print/__tests__/MapPreview-test.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/plugins/__tests__/print/Projection-test.jsx
  web/client/plugins/print/Projection.jsx
  web/client/reducers/__tests__/print-test.js
  web/client/reducers/print.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: bug, Backport, C277-REGION_DE_MURCIA-2024-SUPPORT

#10453 [Backport 2024.01.xx] #10408 Available formats for background are not including image/vnd.jpeg-png8 (#10409)
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/components/background/BackgroundDialog.jsx
Labels: bug, Internal, Backport

#10150 geosolutions-it#6913: grid cards keyboard navigation
  web/client/components/misc/GridCard.jsx
  web/client/components/misc/__tests__/GridCard-test.jsx
  web/client/components/misc/style/gridcard.css
  web/client/themes/default/less/maps-properties.less
Labels: enhancement, Internal, External Contribution, C206-DEUTSCHE_BAHN-2023-SUPPORT

#10454 Fix #10434 update custom theme documentation
  docs/developer-guide/customize-theme.md
Labels: Documentation, Internal, BackportNeeded

#10456 [Backport 2024.01.xx] Fix #10434 update custom theme documentation (#10454)
  docs/developer-guide/customize-theme.md
Labels: Documentation, Internal, Backport

#10451 #10279: Show credits/attribution text in printed page
  docs/developer-guide/mapstore-migration-guide.md
  java/printing/resources/geoserver/print/config.yaml
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: New Feature, BackportNeeded, Print, C206-DEUTSCHE_BAHN-2024-SUPPORT

#10436 Update Dev Guide - Add new missing GeoServer Extensions
  docs/developer-guide/integrations/geoserver.md
  docs/developer-guide/integrations/img/mapstore-geoserver-users-integration.png
  mkdocs.yml
Labels: Documentation, Internal, Dev Guide

#10462 [Backport 2024.01.xx] #10430 Update Dev Guide - Add new missing GeoServer Extensions (#10436)
  docs/developer-guide/integrations/geoserver.md
  docs/developer-guide/integrations/img/mapstore-geoserver-users-integration.png
  mkdocs.yml
Labels: Documentation, Internal, Dev Guide, Backport

#10461 [Backport 2024.01.xx] - #10279: Show credits/attribution text in printed page (#10451)
  docs/developer-guide/mapstore-migration-guide.md
  java/printing/resources/geoserver/print/config.yaml
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: Backport, New Feature, Print, C206-DEUTSCHE_BAHN-2024-SUPPORT

#10446 Updating tomcat and java versions for binary package
  binary/bin-war/pom.xml
  binary/bin/mapstore2-shutdown.bat
  binary/bin/mapstore2-startup.bat
  binary/pom.xml
  binary/tomcat/bin/bootstrap.jar
  binary/tomcat/bin/catalina.bat
  binary/tomcat/bin/catalina.sh
  binary/tomcat/bin/ciphers.bat
  binary/tomcat/bin/ciphers.sh
  binary/tomcat/bin/commons-daemon.jar
  binary/tomcat/bin/configtest.bat
  binary/tomcat/bin/configtest.sh
  binary/tomcat/bin/daemon.sh
  binary/tomcat/bin/digest.bat
  binary/tomcat/bin/digest.sh
  binary/tomcat/bin/makebase.bat
  binary/tomcat/bin/makebase.sh
  binary/tomcat/bin/service.bat
  binary/tomcat/bin/setclasspath.bat
  binary/tomcat/bin/setclasspath.sh
  binary/tomcat/bin/tcnative-1.dll
  binary/tomcat/bin/tomcat-juli.jar
  binary/tomcat/bin/tomcat9.exe
  binary/tomcat/bin/tomcat9w.exe
  binary/tomcat/bin/tool-wrapper.bat
  binary/tomcat/bin/tool-wrapper.sh
  binary/tomcat/bin/version.bat
  binary/tomcat/bin/version.sh
  binary/tomcat/conf/catalina.policy
  binary/tomcat/conf/catalina.properties
  binary/tomcat/conf/context.xml
  binary/tomcat/conf/logging.properties
  binary/tomcat/conf/server.xml
  binary/tomcat/conf/web.xml
Labels: bug, Internal, BackportNeeded

#10459 Fix #4675 Remove ogc-schemas, w3c-schemas and jsonix dependencies
  build/buildConfig.js
  build/testConfig.js
  package.json
  web/client/api/CSW.js
  web/client/api/WFS.js
  web/client/api/__tests__/CSW-test.js
  web/client/components/catalog/editor/AdvancedSettings/CSWFilters.jsx
  web/client/utils/__tests__/SLDUtils-test.js
  web/client/utils/ogc/CSW.js
  web/client/utils/ogc/DC_1_1_full.js
  web/client/utils/ogc/Filter/index.js
  web/client/utils/ogc/WFS/index.js
  web/client/utils/ogc/__tests__/CSW-test.js
  web/client/utils/ogc/__tests__/Filter-test.js
Labels: enhancement, Internal, Performance

#10472 Improved documentation for autoDetectCORS, tileSize and singleTiles
  docs/developer-guide/local-config.md
  docs/developer-guide/maps-configuration.md
Labels: Documentation

#10468 Fix #10467 build markdown issue
  .markdownlintignore
  README.md
  package.json
Labels: bug, Internal

#10465 Improved doc for OIDC
  docs/developer-guide/integrations/users/openId.md
Labels: C206-DEUTSCHE_BAHN-2024-SUPPORT

#10471 Fix #10470 when CRS is only 1
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/test-resources/wms/GetCapabilities-1.3.0-minimal.xml
Labels: bug, Internal

#10500 Update data.de-DE.json
  web/client/translations/data.de-DE.json
Labels: C125-AUSTROCONTROL-2024-SUPPORT

#10482 NL translations update v2024.01.02
  web/client/translations/data.nl-NL.json
Labels: Internal, External Contribution

#10457 Fix #10455 Allow use of node version 20
  .github/workflows/CI.yml
  .github/workflows/build.yml
  .github/workflows/create_release.yml
  .github/workflows/pre_release.yml
  build/buildConfig.js
  build/testConfig.js
  docs/developer-guide/mapstore-migration-guide.md
  docs/developer-guide/requirements.md
  package.json
Labels: enhancement, Internal

#10496 #10488: 'ilike' as default operator for text field in attribute table quick filter
  web/client/components/data/featuregrid/filterRenderers/AttributeFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/BaseDateTimeFilter.js
  web/client/components/data/featuregrid/filterRenderers/StringFilter.jsx
  web/client/components/data/featuregrid/filterRenderers/__tests__/StringFilter-test.jsx
Labels: C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10498 Fix #10497. Fixed logic operators precedence in CQL filter parse
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/ogc/Filter/CQL/__tests__/parser-test.js
  web/client/utils/ogc/Filter/CQL/parser.js
  web/client/utils/ogc/Filter/__tests__/fromObject-test.js
Labels: C105-2024-EMSA-SC3-MAINT
