Repository geosolutions-it/MapStore2, pull requests merged in 2024-04, with the labels that each got.

#10143 backport 2024.01.xx - geosolutions-it#9688: Make DOMUtils tests less dependent on platform-varying browser default stylesheet (#10046)
  web/client/utils/__tests__/DOMUtil-test.js
Labels: Backport

#10149 Fix #10062 enhanced the way details are stored within app
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/details-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/config.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/details.js
  web/client/selectors/map.js
Labels: BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10147 Update German translation to resolve input field issue
  web/client/translations/data.de-DE.json
Labels: BackportNeeded, External Contribution

#10156 [Backport 2024.01.xx] minor changes in german translation; change of Lat and Lon (#10147)
  web/client/translations/data.de-DE.json
Labels: Backport, External Contribution

#10145 #10111: Enhance GeoFence attribute rule
  web/client/api/geofence/RuleService.js
  web/client/api/geofence/__tests__/RuleService-test.js
  web/client/components/manager/rulesmanager/ruleseditor/AttributesEditor.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/AttributesEditor-test.jsx
Labels: enhancement, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10164 #10125 Annotation click-right options in embedded mode
  web/client/plugins/TOC/containers/ZoomToLayersButton.jsx
  web/client/plugins/__tests__/TOC-test.jsx
Labels: bug, BackportNeeded, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10130 Fix #10121 moving the rendered measure as the normal one
  web/client/components/map/cesium/DrawMeasureSupport.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10160 Fix #10157 refactoring tests in a do while with 10 attempts max 10s
  web/client/components/map/cesium/__tests__/Map-test.jsx
Labels: Internal, BackportNeeded, ci/cd

#10166 #8953 Ability to expand the TOC at context loading
  web/client/plugins/TOC/index.js
Labels: Documentation, New Feature

#10173 [Backport 2024.01.xx] #8953 Ability to expand the TOC at context loading (#10166)
  web/client/plugins/TOC/index.js
Labels: Documentation, Backport, New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10174 [Backport 2024.01.xx] #10125 Annotation click-right options in embedded mode (#10164)
  web/client/plugins/TOC/containers/ZoomToLayersButton.jsx
  web/client/plugins/__tests__/TOC-test.jsx
Labels: bug, Backport, Regression, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10177 Fix #10168 JSDoc fix for mapType
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/Map.jsx
Labels: bug, Documentation, Internal, BackportNeeded

#10178 [Backport 2024.01.xx] Fix #10168 JSDoc fix for mapType (#10177)
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/Map.jsx
Labels: bug, Documentation, Internal, Backport

#10183 backport 2024.01.xx - Fix #10121 moving the rendered measure as the normal one (#10130)
  web/client/components/map/cesium/DrawMeasureSupport.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: enhancement, Backport, C299- POLITO -2023-MS_DigitalTwin

#10182 Fix #10153 fix wrong reset of details
  web/client/reducers/config.js
  web/client/reducers/details.js
Labels: BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#9531 support loading COG layers from query params
  docs/developer-guide/map-query-parameters.md
  web/client/api/catalog/COG.js
  web/client/epics/catalog.js
Labels: enhancement, External Contribution

#10186 backport 2024.01.xx - Fix #10153 enhanced the way details are stored within app
  web/client/epics/__tests__/config-test.js
  web/client/epics/__tests__/details-test.js
  web/client/epics/__tests__/tutorial-test.js
  web/client/epics/config.js
  web/client/epics/details.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/config.js
  web/client/reducers/details.js
  web/client/reducers/map.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/__tests__/dashboard-test.js
  web/client/selectors/__tests__/map-test.js
  web/client/selectors/dashboard.js
  web/client/selectors/details.js
  web/client/selectors/map.js
Labels: bug, Backport, C299- POLITO -2023-MS_DigitalTwin

#10181 Fix release github actions files
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
Labels: Internal, BackportNeeded

#10189 [Backport 2024.01.xx] Fix release github actions files (#10181)
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
Labels: Internal, Backport

#10171 Fix #10170 Allow to configure backend dev enviroment
  docs/developer-guide/developing.md
  product/pom.xml
Labels: BackportNeeded, C206-DEUTSCHE_BAHN-2023-SUPPORT

#10185 Fix #10121 improved geodesc measures
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/DrawGeometrySupport-test.jsx
  web/client/utils/cesium/DrawGeometryInteraction.js
  web/client/utils/cesium/MathUtils.js
  web/client/utils/cesium/__tests__/MathUtils-test.js
Labels: bug, BackportNeeded, C299- POLITO -2023-MS_DigitalTwin

#10194 backport 2024.01.xx - Fix #10121 improved geodesc measures (#10185)
  web/client/components/map/cesium/MeasurementSupport.jsx
  web/client/components/map/cesium/__tests__/DrawGeometrySupport-test.jsx
  web/client/utils/cesium/DrawGeometryInteraction.js
  web/client/utils/cesium/MathUtils.js
  web/client/utils/cesium/__tests__/MathUtils-test.js
Labels: Backport, C299- POLITO -2023-MS_DigitalTwin

#10199 Fix #10170 Update doc for developing
  docs/developer-guide/developing.md
Labels: Internal, BackportNeeded, C206-DEUTSCHE_BAHN-2023-SUPPORT

#10190 [Backport 2024.01.xx] Fix #10170 Allow to configure backend dev environment (#10171)
  docs/developer-guide/developing.md
  product/pom.xml
Labels: Backport

#10137 Update User Guide - Multi-band color mapping for COG layers and Raster layer section
  docs/user-guide/catalog.md
  docs/user-guide/img/layer-settings/band_styling.mp4
  docs/user-guide/img/layer-settings/cog-layer_style.jpg
  docs/user-guide/img/layer-settings/min-max-data-value.jpg
  docs/user-guide/img/layer-settings/pseudo_color_style.jpg
  docs/user-guide/img/layer-settings/rgb_band_style.jpg
  docs/user-guide/img/layer-settings/single_band_style.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, Internal, User Guide

#10139 Fix Migration guidelines format
  docs/developer-guide/mapstore-migration-guide.md
Labels: bug, Documentation

#10198 #10196 3D map context throws an error using browser history navigation
  web/client/components/map/cesium/Map.jsx
Labels: bug, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10169 Update User Guide - Add 3D geodesic length measure
  docs/user-guide/img/measure/measure-geodesic-ex.mp4
  docs/user-guide/measure.md
Labels: Documentation, User Guide, C299- POLITO -2023-MS_DigitalTwin

#10195 #10193: Issue with WFS added via Query params
  web/client/api/WFS.js
  web/client/api/__tests__/WFS-test.js
Labels: bug, BackportNeeded, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10203 [Backport 2024.01.xx] #10103 Update User Guide - Multi-band color mapping for COG layers and Raster layer section (#10137)
  docs/user-guide/catalog.md
  docs/user-guide/img/layer-settings/band_styling.mp4
  docs/user-guide/img/layer-settings/cog-layer_style.jpg
  docs/user-guide/img/layer-settings/min-max-data-value.jpg
  docs/user-guide/img/layer-settings/pseudo_color_style.jpg
  docs/user-guide/img/layer-settings/rgb_band_style.jpg
  docs/user-guide/img/layer-settings/single_band_style.jpg
  docs/user-guide/layer-settings.md
Labels: Documentation, Internal, User Guide, Backport

#10205 [Backport 2024.01.xx] #10124 Fix Migration guidelines format (#10139)
  docs/developer-guide/mapstore-migration-guide.md
Labels: bug, Documentation, Backport

#10204 [Backport 2024.01.xx] #10169 Update User Guide - Add 3D geodesic length measure (#10169)
  docs/user-guide/img/measure/measure-geodesic-ex.mp4
  docs/user-guide/measure.md
Labels: Documentation, User Guide, Backport, C299- POLITO -2023-MS_DigitalTwin

#10027 #9978: Add 360 photo support with Mapillary
  package.json
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/components/map/openlayers/plugins/WFSLayer.js
  web/client/plugins/StreetView/StreetView.jsx
  web/client/plugins/StreetView/actions/__tests__/streetView-test.js
  web/client/plugins/StreetView/actions/streetView.js
  web/client/plugins/StreetView/api/index.js
  web/client/plugins/StreetView/api/mapillary.js
  web/client/plugins/StreetView/components/CesiumMapLocationSupport.jsx
  web/client/plugins/StreetView/components/CyclomediaView/CyclomediaView.js
  web/client/plugins/StreetView/components/MapillaryView/MapillaryView.jsx
  web/client/plugins/StreetView/components/MapillaryView/__test__/MapillaryView-test.jsx
  web/client/plugins/StreetView/components/OLMapLocationSupport.jsx
  web/client/plugins/StreetView/components/__tests__/CesiumMapLocationSupport-test.jsx
  web/client/plugins/StreetView/components/__tests__/OLMapLocationSupport-test.jsx
  web/client/plugins/StreetView/components/img/marker.gltf.json
  web/client/plugins/StreetView/components/img/marker.svg
  web/client/plugins/StreetView/constants.js
  web/client/plugins/StreetView/containers/MapLocationSupport.jsx
  web/client/plugins/StreetView/containers/MapillaryViewPanel.jsx
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
  web/client/plugins/StreetView/epics/__tests__/streetview-test.js
  web/client/plugins/StreetView/epics/streetView.js
  web/client/plugins/StreetView/reducers/__tests__/streetview-test.js
  web/client/plugins/StreetView/reducers/streetview.js
  web/client/plugins/StreetView/selectors/streetView.js
  web/client/plugins/StreetView/utils/__tests__/mapillaryUtils/GeoJSONDataProvider-test.js
  web/client/plugins/StreetView/utils/__tests__/mapillaryUtils/tilemath-test.js
  web/client/plugins/StreetView/utils/__tests__/mapillaryUtils/utils-test.js
  web/client/plugins/StreetView/utils/mapillaryUtils/GeoJSONDataProvider.js
  web/client/plugins/StreetView/utils/mapillaryUtils/tilemath.js
  web/client/plugins/StreetView/utils/mapillaryUtils/utils.js
  web/client/test-resources/mapillary/output/run_04/index.json
  web/client/test-resources/mapillary/output/run_04/thumb/image01.png
  web/client/test-resources/mapillary/output/run_04/thumb/image02.png
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/VectorStyleUtils.js
  web/client/utils/WFSLayerUtils.js
Labels: New Feature, new, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10207 #10197: fix Skipping 'Configure Map' step breaks context configuration
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: bug, investigation, Internal, BackportNeeded

#10210 [Backport C040-2024.01.xx] #10197: fix Skipping 'Configure Map' step breaks context configuration (#10207)
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: bug, Internal, Backport

#10209 updated java url
  binary/pom.xml
Labels: bug, Binary Package, DevOps

#10215 #10196 fix context wizard error
  web/client/components/map/cesium/Map.jsx
Labels: bug, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10216 Improving migration giudelines for logging migration step
  docs/developer-guide/mapstore-migration-guide.md
Labels: Internal, BackportNeeded

#10217 [Backport 2024.01.xx] Update mapstore-migration-guide.md (#10216)
  docs/developer-guide/mapstore-migration-guide.md
Labels: bug, Documentation, Internal, Backport

#10218 Fix #10202 conversion of geodesic length into vector layer
  web/client/utils/MeasurementUtils.js
Labels: bug, BackportNeeded, 3D

#10223 backport 2024.01.xx - Fix #10202 conversion of geodesic length into vector layer (#10218)
  web/client/utils/MeasurementUtils.js
Labels: bug, Backport, C299- POLITO -2023-MS_DigitalTwin

#10039 Refactor and simplify the format validator utility logic
  web/client/utils/FeatureInfoUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/__tests__/FeatureInfoUtils-test.js
  web/client/utils/__tests__/MapInfoUtils-test.js
Labels: External Contribution

#10226 Fix #10222 remove node also clears selected ones
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
Labels: bug, Internal, BackportNeeded, Regression

#10229 backport 2024.01.xx - Fix #10222 remove node also clears selected ones (#10226)
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/layers.js
Labels: bug, Internal, Backport, Regression

#10230 backport 2024.01.xx - Fix #10201 clearing correctly details and showing only if they are different from NODATA (#10221)
  web/client/components/resources/modals/fragments/Details.jsx
  web/client/epics/details.js
  web/client/plugins/Details.jsx
Labels: bug, Backport, C299- POLITO -2023-MS_DigitalTwin

#10180 #10026: Interactive legend for TOC layers [WMS]
  web/client/api/WMS.js
  web/client/api/__tests__/WMS-test.js
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/styleeditor/StyleList.jsx
  web/client/components/styleeditor/WMSJsonLegendIcon.jsx
  web/client/components/styleeditor/__tests__/WMSJsonLegendIcon-test.jsx
  web/client/plugins/TOC/components/DefaultLayer.jsx
  web/client/plugins/TOC/components/StyleBasedWMSJsonLegend.jsx
  web/client/plugins/TOC/components/WMSLegend.jsx
  web/client/plugins/TOC/components/__tests__/Legend-test.jsx
  web/client/plugins/TOC/components/__tests__/StyleBasedWMSJsonLegend-test.jsx
  web/client/plugins/TOC/components/__tests__/WMSLegend-test.jsx
  web/client/plugins/styleeditor/index.js
  web/client/themes/default/less/toc.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: investigation, New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10253 Fix #10252 Mask property is not applied inside views
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/utils/cesium/GeoJSONStyledFeatures.js
Labels: bug, Internal, BackportNeeded

#10255 [Backport 2024.01.xx] #10250: Fix - Axios 0.28.0 missing paramsSerializer (#10251)
  package.json
Labels: enhancement, Backport, C130-TOTAL-2024-GeoNode-DEV

#10248 Fix #10243 removing toggle mode of non active longitudinal profile tool
  web/client/epics/longitudinalProfile.js
  web/client/plugins/StreetView/epics/streetView.js
Labels: bug, Internal, BackportNeeded

#10256 [Backport 2024.01.xx] Fix #10252 Mask property is not applied inside views (#10253)
  web/client/components/map/cesium/plugins/ThreeDTilesLayer.js
  web/client/utils/cesium/GeoJSONStyledFeatures.js
Labels: bug, Internal, Backport

#10249 #10026: fix functional tests for Interactive legend for TOC layers [WMS Support]
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/widgets/builder/wizard/map/NodeEditor.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/plugins/mapEditor/DefaultConfiguration.js
  web/client/utils/LayersUtils.js
Labels: New Feature, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10257 backport 2024.01.xx - Fix #10243 removing toggle mode of non active longitudinal profile tool (#10248)
  web/client/epics/longitudinalProfile.js
  web/client/plugins/StreetView/epics/streetView.js
Labels: bug, Internal, Backport

#10259 comment fix
  web/client/plugins/ContextCreator.jsx
Labels: BackportNeeded, External Contribution

#10263 backport 2024.01.xx - comment fix (#10259)
  web/client/plugins/ContextCreator.jsx
Labels: Backport, External Contribution

#10234 Fix #10233 Add support for HTML response for WFS layer
  web/client/api/WFS.js
  web/client/api/__tests__/WFS-test.js
  web/client/api/catalog/WFS.js
  web/client/components/TOC/fragments/settings/FeatureInfo.jsx
  web/client/components/TOC/fragments/settings/__tests__/FeatureInfo-test.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/plugins/tocitemssettings/tabs/FeatureInfo/index.jsx
  web/client/utils/mapinfo/__tests__/wfs-test.js
  web/client/utils/mapinfo/wfs.js
Labels: enhancement, C040-COMUNE_GE-2023-CUSTOM-SUPPORT

#10245 Fix #10238 Change Math.random with an alternative solution
  web/client/components/maps/forms/Thumbnail.jsx
  web/client/components/style/vector/marker/SymbolLayout.jsx
  web/client/plugins/TOC/components/Legend.jsx
  web/client/utils/ColorUtils.js
  web/client/utils/RandomUtils.js
  web/client/utils/WidgetsUtils.js
  web/client/utils/__tests__/RandomUtils-test.js
  web/client/utils/cesium/WMSUtils.js
  web/client/utils/styleparser/StyleParserUtils.js
Labels: C039-2024-HALLIBURTON-SUPPORT

#10254 #10242: Fix - Viewer widgets state not aligned
  web/client/epics/__tests__/widgets-test.js
  web/client/epics/widgets.js
Labels: bug, Internal, BackportNeeded, Regression

#10265 Init ArcGIS Support
  web/client/api/ArcGIS.js
  web/client/api/catalog/ArcGIS.js
  web/client/api/catalog/index.js
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/components/map/openlayers/plugins/ArcGISLayer.js
  web/client/components/map/openlayers/plugins/index.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/utils/LocaleUtils.js
  web/client/utils/MapInfoUtils.js
  web/client/utils/mapinfo/arcgis.js
Labels: New Feature, C130-TOTAL-2024-GeoNode-DEV
