Repository geosolutions-it/MapStore2, pull requests merged in 2024-11, with the labels that each got.

#10649 [Backport 2024.02.xx] #10503 - Home and Login Plugins do not appear on the page if the Burger Menu is activated in the context in 2024.01.01 version #10503 #10590
  web/client/plugins/Home.jsx
  web/client/plugins/Login.jsx
Labels: bug, Internal, Good first issue, Backport

#10647 [Backport 2024.02.xx]- #10355: Visibility limits - The resolution option is not retained as Limits type #10391
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/VisibilityLimitsForm.jsx
  web/client/components/TOC/fragments/settings/__tests__/VisibilityLimitsForm-test.jsx
Labels: bug, Internal, Good first issue, Backport

#10650 [Backport 2024.02.xx] Fix #10448 Map plugin should not initizialize invalid maps (#10449)
  web/client/plugins/Map.jsx
  web/client/plugins/__tests__/Map-test.jsx
Labels: enhancement, Internal, geonode_integration, Backport

#10651 #10648: Issue editing multiple fields in MapStore Attribute Table
  web/client/epics/__tests__/featuregrid-test.js
  web/client/epics/featuregrid.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: bug, C040-COMUNE_GE-2024-CUSTOM-SUPPORT

#10654 #10648: fix FE test failure for - Issue editing multiple fields in MapStore Attribute Table
  web/client/epics/__tests__/featuregrid-test.js
Labels: bug, C040-COMUNE_GE-2024-CUSTOM-SUPPORT

#10630 [Backport c027-2024-10-24] - #10622: Not possible to remove widget from Map - JavaScript error (#10623)
  web/client/components/geostory/common/enhancers/__tests__/withMediaVisibilityContainer-test.jsx
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/widgets.js
Labels: bug, Backport, C027-COMUNE_FI-2023-SUPPORT

#10653 [Backport 2024.02.xx] - #10648: Issue editing multiple fields in MapStore Attribute Table (#10651)
  web/client/epics/featuregrid.js
  web/client/utils/FeatureGridUtils.js
  web/client/utils/__tests__/FeatureGridUtils-test.js
Labels: bug, Backport, C040-COMUNE_GE-2024-CUSTOM-SUPPORT

#10661 #10660: Enhance About plugin to show/hide version/content sections
  web/client/product/components/viewer/about/About.jsx
  web/client/product/components/viewer/about/AboutContent.jsx
  web/client/product/components/viewer/about/VersionInfo.jsx
  web/client/product/components/viewer/about/__tests__/About-test.js
  web/client/product/plugins/About.jsx
  web/client/themes/default/less/version.less
Labels: enhancement, C040-COMUNE_GE-2024-CUSTOM-SUPPORT

#10665 Code quality and security improvements
  java/services/src/main/java/it/geosolutions/mapstore/controllers/configs/ConfigsController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/UploadPluginController.java
  java/services/src/main/java/it/geosolutions/mapstore/utils/ResourceUtils.java
  java/services/src/test/java/it/geosolutions/mapstore/ConfigControllerTest.java
  java/services/src/test/java/it/geosolutions/mapstore/TestUtils.java
  java/services/src/test/java/it/geosolutions/mapstore/UploadPluginControllerTest.java
  java/services/src/test/resources/extensionsWithNestedPlugin.json
  java/services/src/test/resources/pluginsConfigWithNestedPlugin.json
Labels: C039-2024-HALLIBURTON-SUPPORT

#10668 #10663: fix adding decimals in the aeronautical form in searcg by coordinates
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/I18N/__tests__/IntlNumberFormatControl-test.jsx
  web/client/libs/numeric-input/NumericInput.jsx
Labels: bug, BackportNeeded, C125-AUSTROCONTROL-2024-MapStore

#10672 Update release steps
  .github/ISSUE_TEMPLATE/release_steps.md
Labels: Internal

#10621 [Backport 2024.02.xx] Catalog editor i18n (#10571)
  web/client/components/catalog/__tests__/CatalogServiceEditor-test.jsx
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/catalog/editor/MainFormUtils.js
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: Backport, External Contribution

#10662 [Backport 2024.02.xx] #10660: Enhance About plugin to show/hide version/content sections (#10661)
  web/client/product/components/viewer/about/About.jsx
  web/client/product/components/viewer/about/AboutContent.jsx
  web/client/product/components/viewer/about/VersionInfo.jsx
  web/client/product/components/viewer/about/__tests__/About-test.js
  web/client/product/plugins/About.jsx
  web/client/themes/default/less/version.less
Labels: enhancement, Backport, C040-COMUNE_GE-2024-CUSTOM-SUPPORT

#10678 [Backport 2024.02.xx] Fix #10663: adding decimals in the aeronautical form in searcg by coordinates (#10668)
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/I18N/__tests__/IntlNumberFormatControl-test.jsx
  web/client/libs/numeric-input/NumericInput.jsx
Labels: bug, Backport, C125-AUSTROCONTROL-2024-MapStore

#10677 Returning wrong pixel xy value on mousemove for leaflet engine
  web/client/components/map/leaflet/Map.jsx
Labels: BackportNeeded, External Contribution

#10679 [Backport 2024.02.xx] Returning wrong pixel xy value on mousemove for leaflet engine (#10677)
  web/client/components/map/leaflet/Map.jsx
Labels: Backport

#10681 widgets in map wrongly align with a specific config #10676
  web/client/plugins/Widgets.jsx
Labels: bug, Regression

#10680 Layer selectable even if the group it belongs to is turned off #10632
  .gitignore
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: bug, Internal

#10685 Add documentation to identify plugin
  web/client/plugins/Identify.jsx
Labels: External Contribution

#10686 [Backport 2024.02.xx] Add documentation to identify plugin (#10685)
  web/client/plugins/Identify.jsx
Labels: Backport, External Contribution

#10688 Backport 2024.02.xx] - Layer selectable even if the group it belongs to is turned off #10632 #10680
  .gitignore
  web/client/epics/__tests__/identify-test.js
  web/client/epics/identify.js
Labels: bug, Internal, Backport

#10689 [Backport 2024.02.xx]- widgets in map wrongly align with a specific config #10676 #10681
  web/client/plugins/Widgets.jsx
Labels: bug, Backport, Regression

#10690 backport 2024.02.xx - Fix #10615 removed eval from marker utils (#10616)
  web/client/utils/MarkerUtils.js
Labels: Backport, C039-2024-HALLIBURTON-SUPPORT

#10656 Update for auth.md for refresh token and support to mermaid charts in pdf
  .gitignore
  docs/developer-guide/documentation-guidelines.md
  docs/developer-guide/integrations/auth.md
  docs/developer-guide/integrations/geoserver.md
  docs/developer-guide/integrations/img/mapStore-geoserver-mapstore-ldap-direct-geoserver-ldap.png
  docs/developer-guide/integrations/img/mapStore-geoserver-mapstore-ldap-geoserver-ldap.png
  docs/developer-guide/integrations/img/mapstore-geoserver-integration.png
  docs/developer-guide/integrations/img/mapstore-geoserver-users-integration.png
  docs/developer-guide/integrations/img/mapstore-ldap-mapstore-geoserver.png
  docs/developer-guide/integrations/img/openid-mapstore-login.png
  docs/developer-guide/integrations/img/standard-mapstore-login.png
  docs/developer-guide/integrations/infrastructure-setups.md
  docs/developer-guide/integrations/users/img/desired-workflow.png
  docs/developer-guide/integrations/users/img/initialization.png
  docs/developer-guide/integrations/users/img/keycloakjs-library.png
  docs/developer-guide/integrations/users/img/login-from-keycloak.png
  docs/developer-guide/integrations/users/openId.md
  docs/print_template/styles.scss
  docs/requirements.txt
  docs/theme/css/extra.css
  mkdocs.yml
Labels: C039-2024-HALLIBURTON-SUPPORT

#10696 Fix #10695 Handle empty values for and/or/not/nor filters
  web/client/utils/ogc/Filter/FilterBuilder.js
  web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
  web/client/utils/ogc/Filter/__tests__/operators-test.js
  web/client/utils/ogc/Filter/operators.js
Labels: Internal, BackportNeeded
