Repository geosolutions-it/MapStore2, pull requests merged in 2025-09, with the labels that each got.

#11399 Update geoserver.md
  docs/developer-guide/integrations/geoserver.md
Labels: BackportNeeded, External Contribution

#11422 [Backport 2025.01.xx] Fix #11419 fixed group translation files (#11420)
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#11427 [Backport - 2025.01.xx] - #11328: Fix YAML config issues for printing: North arrow URL format and A2 north arrow positioning (#11340)
  java/printing/resources/geoserver/print/config.yaml
Labels: bug

#11426 [Backport 2025.01.xx] Update geoserver.md (#11399)
  docs/developer-guide/integrations/geoserver.md
Labels: Backport

#11430 Missing flag when choosing catalan #11268
  web/client/translations/data.ca-ES.json
Labels: bug

#11444 fix 11441 build failure updating cesium 1.133.1
  package.json
Labels: bug, BackportNeeded, 3D

#11192 Update pom.xml of template to have version
  pom.xml
  product/pom.xml
  project/standard/templates/pom.xml
  project/standard/templates/web/pom.xml
Labels: BackportNeeded

#11432 Update Dev Guide - Add image
  docs/developer-guide/integrations/users/keycloak-sso-impl.md
Labels: Documentation, Dev Guide

#11490 Fix #11489 Number editor no use standard editor superclass
  web/client/components/data/featuregrid/editors/NumberEditor.jsx
  web/client/components/data/featuregrid/editors/__tests__/NumberEditor-test.jsx
Labels: BackportNeeded

#11491 [Backport 2025.01.xx] Fix #11459 unload resources at logout (#11480)
  web/client/plugins/ResourcesCatalog/DeleteResource.jsx
  web/client/plugins/ResourcesCatalog/ResourcesGrid.jsx
  web/client/plugins/ResourcesCatalog/actions/resources.js
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/epics/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/epics/resources.js
  web/client/plugins/ResourcesCatalog/reducers/resources.js
Labels: bug, Backport

#11484 Performance Optimization: Refactor Pending Changes Logic and Save Resource Selector #11476
  web/client/plugins/ResourcesCatalog/DeleteResource.jsx
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/Save.jsx
  web/client/plugins/ResourcesCatalog/SaveAs.jsx
  web/client/plugins/ResourcesCatalog/actions/save.js
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/hooks/__tests__/useComputedPendingChanges-test.js
  web/client/plugins/ResourcesCatalog/hooks/useComputedPendingChanges.js
  web/client/plugins/ResourcesCatalog/reducers/__tests__/save-test.js
  web/client/plugins/ResourcesCatalog/reducers/save.js
  web/client/plugins/ResourcesCatalog/selectors/__tests__/save-test.js
  web/client/plugins/ResourcesCatalog/selectors/save.js
  web/client/selectors/dashboardsave.js
  web/client/selectors/mapsave.js
  web/client/utils/GeostoreUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/GeostoreUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement

#11498 Fix #11465 Problem with feedback mask and user permissions
  web/client/components/misc/enhancers/__tests__/withMask-test.jsx
  web/client/components/misc/enhancers/withMask.js
  web/client/plugins/FeedbackMask.jsx
  web/client/plugins/ResourcesCatalog/selectors/__tests__/save-test.js
  web/client/plugins/ResourcesCatalog/selectors/save.js
Labels: bug, Regression

#11454 [Backport 2025.01.xx] Update User Guide - Terrain Collision detection settings option (#11433)
  docs/user-guide/img/menu-bar/cesium-settings.jpg
  docs/user-guide/mapstore-toolbars.md
Labels: Backport

#11488 #11469: Rule Manager: GeoFence error message in open layers DD in add new rule
  web/client/components/manager/rulesmanager/ruleseditor/EditMain.jsx
  web/client/components/manager/rulesmanager/ruleseditor/attributeselectors/GSInstance.jsx
  web/client/observables/rulesmanager.js
  web/client/plugins/manager/EditorEnhancer.js
  web/client/plugins/manager/RulesEditor.jsx
  web/client/utils/RulesEditorUtils.js
  web/client/utils/__tests__/RulesEditorUtils-test.js
Labels: bug, New SDI

#11505 [Backport c027-2025.01.xx]: #11469: Rule Manager: GeoFence error message in open layers DD in add new rule (#11488)
  web/client/components/manager/rulesmanager/ruleseditor/EditMain.jsx
  web/client/components/manager/rulesmanager/ruleseditor/attributeselectors/GSInstance.jsx
  web/client/observables/rulesmanager.js
  web/client/plugins/manager/EditorEnhancer.js
  web/client/plugins/manager/RulesEditor.jsx
  web/client/utils/RulesEditorUtils.js
  web/client/utils/__tests__/RulesEditorUtils-test.js
Labels: bug, Backport, New SDI

#11506 Fix #11497 Swipe state is not reset triggering pending changes in map viewer
  web/client/epics/swipe.js
  web/client/reducers/__tests__/swipe-test.js
  web/client/reducers/swipe.js
Labels: bug

#11515 [Backport 2025.01.xx] Fix #11497 Swipe state is not reset triggering pending changes in map
  web/client/epics/swipe.js
  web/client/reducers/__tests__/swipe-test.js
  web/client/reducers/swipe.js
Labels: Backport

#11517 [Backport 2025.01.xx] Fix #11468 Strange failure in one test context to investigate (#11499)
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: bug, Backport
