Repository geosolutions-it/MapStore2, pull requests merged in 2025-04, with the labels that each got.

#10963 Fix #10819 Manager menu is merged into Login/user menu and Manager menu is now deprecated
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/security/UserMenu.jsx
  web/client/configs/localConfig.json
  web/client/plugins/Login.jsx
  web/client/plugins/ResourcesCatalog/TagsManager.jsx
  web/client/plugins/__tests__/Login-test.js
  web/client/plugins/login/index.js
  web/client/plugins/login/login.css
  web/client/plugins/manager/ManagerMenu.jsx
Labels: enhancement

#10975 [Backport c027-2024.01.xx] #10937: Unable to visualize some 3D tiles data in MapStore (#10948)
  web/client/api/catalog/CSW.js
  web/client/api/catalog/__tests__/CSW-test.js
Labels: enhancement, Backport

#10972 Small update to LDAP doc
  docs/developer-guide/integrations/users/ldap.md
Labels: Documentation, Internal

#10925 #10923, #10924: Disabling GeoFence Rules and Add filter by IP for GeoFence rules
  web/client/api/geofence/RuleService.js
  web/client/api/geofence/__tests__/RuleService-test.js
  web/client/api/geoserver/geofence/RuleService.js
  web/client/api/geoserver/geofence/__tests__/RuleService-test.js
  web/client/components/data/grid/DataGrid.jsx
  web/client/components/manager/rulesmanager/ruleseditor/EditMain.jsx
  web/client/components/manager/rulesmanager/ruleseditor/__tests__/EditMain-test.jsx
  web/client/components/manager/rulesmanager/ruleseditor/attributeselectors/ValidityPeriod.jsx
  web/client/components/manager/rulesmanager/ruleseditor/attributeselectors/index.js
  web/client/components/manager/rulesmanager/rulesgrid/RulesGrid.jsx
  web/client/components/manager/rulesmanager/rulesgrid/enhancers/rulesgrid.js
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/DateFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/IPAddressFilter.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/__tests__/DateFilter-test.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/__tests__/IPAddressFilter-test.jsx
  web/client/components/manager/rulesmanager/rulesgrid/filterRenderers/index.js
  web/client/components/misc/combobox/PagedCombobox.jsx
  web/client/observables/rulesmanager.js
  web/client/reducers/rulesmanager.js
  web/client/themes/default/less/rulesmanager.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/utils/RuleServiceUtils.js
  web/client/utils/RulesEditorUtils.js
Labels: New Feature

#10875 Streetsmart openid master
  web/client/plugins/StreetView/StreetView.jsx
  web/client/plugins/StreetView/components/CyclomediaView/CyclomediaView.js
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
Labels: enhancement

#10988 #10983: handle add new X twitter icon instead of old icon in Share-->Social
  web/client/components/share/ShareSocials.jsx
Labels: enhancement, BackportNeeded

#10977 #10970: Add configuration support to open resource in target from homepage
  web/client/plugins/ResourcesCatalog/EditContext.jsx
  web/client/plugins/ResourcesCatalog/ResourcesGrid.jsx
  web/client/plugins/ResourcesCatalog/components/Menu.jsx
  web/client/plugins/ResourcesCatalog/components/MenuItem.jsx
  web/client/plugins/ResourcesCatalog/components/ResourceCard.jsx
  web/client/plugins/ResourcesCatalog/components/ResourceCardActionButtons.jsx
  web/client/plugins/ResourcesCatalog/components/ResourcesContainer.jsx
  web/client/plugins/ResourcesCatalog/components/ResourcesMenu.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/MenuItem-test.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcesGrid.jsx
Labels: enhancement, BackportNeeded, MapStore Homepage

#10978 Fix #10898 Removed dependency BrandNavbar from both ResourceDetails and Language while creating map context
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: enhancement

#10994 [Backport 2025.01.xx] Streetsmart openid master (#10875)
  web/client/plugins/StreetView/StreetView.jsx
  web/client/plugins/StreetView/components/CyclomediaView/CyclomediaView.js
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
Labels: Backport

#10995 [Backport 2025.01.xx]: #10983: handle add new X twitter icon instead of old icon in Share-->Social (#10988)
  web/client/components/share/ShareSocials.jsx
Labels: enhancement, Backport

#10993 #10986: Remove experimentalInteractiveLegend flag
  docs/developer-guide/local-config.md
  docs/user-guide/layer-settings.md
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CommonAdvancedSettings-test.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/epics/__tests__/styleeditor-test.js
  web/client/plugins/TOC/components/VectorLegend.jsx
  web/client/plugins/TOC/components/WMSLegend.jsx
  web/client/plugins/TOC/components/__tests__/VectorLegend-test.jsx
  web/client/plugins/TOC/components/__tests__/WMSLegend-test.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: enhancement, BackportNeeded

#10997 Menu divider border style
  web/client/themes/default/less/resources-catalog/_brand-navbar.less
Labels: enhancement, MapStore Homepage

#10996 Permission row style enhancement
  web/client/plugins/ResourcesCatalog/components/PermissionsRow.jsx
  web/client/themes/default/less/resources-catalog/_permissions.less
Labels: enhancement, MapStore Homepage

#10984 Fix #10819 Changed migration guide and jsdoc for rules manager.
  docs/developer-guide/mapstore-migration-guide.md
  web/client/product/pages/RulesManager.jsx
Labels: enhancement

#11000 [Backport 2025.01.xx]: #10986: Remove experimentalInteractiveLegend flag (#10993)
  docs/developer-guide/local-config.md
  docs/user-guide/layer-settings.md
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CommonAdvancedSettings-test.js
  web/client/components/catalog/editor/AdvancedSettings/__tests__/RasterAdvancedSettings-test.js
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/epics/__tests__/styleeditor-test.js
  web/client/plugins/TOC/components/VectorLegend.jsx
  web/client/plugins/TOC/components/WMSLegend.jsx
  web/client/plugins/TOC/components/__tests__/VectorLegend-test.jsx
  web/client/plugins/TOC/components/__tests__/WMSLegend-test.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: enhancement, Backport

#11001 [Backport 2025.01.xx]: #10898 : removed BrandNavbar from both ResourceDetails and Language in pluginsConfig (#10978)
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
Labels: enhancement, Backport

#11006 [Backport 2025.01.xx]: #10944 : Removed primary color and shadow from panels headers (#10956)
  web/client/components/TOC/__tests__/TOCItemsSettings-test.jsx
  web/client/components/TOC/fragments/LayerMetadataModal.jsx
  web/client/components/buttons/InfoButton.jsx
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/ExportDataResultsComponent.jsx
  web/client/components/data/identify/IdentifyContainer.jsx
  web/client/components/data/identify/__tests__/GeocodeViewer-test.jsx
  web/client/components/data/identify/__tests__/IdentifyContainer-test.jsx
  web/client/components/data/query/QueryPanelHeader.jsx
  web/client/components/details/DetailsPanel.jsx
  web/client/components/manager/users/GroupDialog.jsx
  web/client/components/manager/users/UserDialog.jsx
  web/client/components/misc/ConfirmDialog.jsx
  web/client/components/misc/ResizableModal.jsx
  web/client/components/misc/__tests__/ResizableModal-test.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/components/misc/panels/PanelHeader.jsx
  web/client/components/misc/panels/__tests__/DockPanel-test.jsx
  web/client/components/misc/panels/__tests__/PanelHeader-test.jsx
  web/client/components/share/__tests__/SharePanel-test.jsx
  web/client/components/widgets/builder/BuilderHeader.jsx
  web/client/components/widgets/builder/__tests__/BuilderHeader-test.jsx
  web/client/plugins/Annotations/containers/AnnotationsPanel.jsx
  web/client/plugins/GeoProcessing/Panel.jsx
  web/client/plugins/MapCatalog.jsx
  web/client/plugins/MapTemplates.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/ResourcesCatalog/components/FiltersForm.jsx
  web/client/plugins/SearchByBookmark.jsx
  web/client/plugins/SearchServicesConfig.jsx
  web/client/plugins/Settings.jsx
  web/client/plugins/StreetView/containers/StreetViewContainer.jsx
  web/client/plugins/TOC/index.js
  web/client/plugins/__tests__/Share-test.jsx
  web/client/plugins/drawer/Menu.jsx
  web/client/plugins/drawer/drawer.css
  web/client/plugins/longitudinalProfile/Dock.jsx
  web/client/plugins/longitudinalProfile/SettingsPanel.jsx
  web/client/plugins/mediaEditor/__tests__/MediaModal-test.jsx
  web/client/product/components/viewer/about/About.jsx
  web/client/themes/default/bootstrap-theme.less
  web/client/themes/default/less/annotations.less
  web/client/themes/default/less/drawer-menu.less
  web/client/themes/default/less/mixins/bootstrap.less
  web/client/themes/default/less/modal.less
  web/client/themes/default/less/panels.less
  web/client/themes/default/less/query-panel.less
  web/client/themes/default/less/resources-catalog/_utility.less
  web/client/themes/default/less/toc.less
Labels: enhancement, Backport

#11018 Fix: #10820 double close icon in add new group dialog
  web/client/components/manager/users/GroupDialog.jsx
Labels: enhancement

#11014 Fix #11011 MapCatalog infinite scroll request all the pages
  web/client/components/mapcatalog/MapCatalogPanel.jsx
Labels: bug, BackportNeeded

#11013 Fix #10774 Clear all filters inside the resource search bar
  web/client/plugins/ResourcesCatalog/ResourcesSearch.jsx
  web/client/plugins/ResourcesCatalog/__tests__/ResourcesSearch-test.jsx
Labels: enhancement, BackportNeeded

#11020 [Backport 2025.01.xx]: #10831: FIX- Improve how printing map preview is managed (#10957)
  web/client/plugins/Print.jsx
  web/client/plugins/print/Projection.jsx
Labels: enhancement, Backport, Print

#11019 [Backport 2025.01.xx] #10970: Add configuration support to open resource in target from homepage (#10977)
  web/client/plugins/ResourcesCatalog/EditContext.jsx
  web/client/plugins/ResourcesCatalog/ResourcesGrid.jsx
  web/client/plugins/ResourcesCatalog/components/Menu.jsx
  web/client/plugins/ResourcesCatalog/components/MenuItem.jsx
  web/client/plugins/ResourcesCatalog/components/ResourceCard.jsx
  web/client/plugins/ResourcesCatalog/components/ResourceCardActionButtons.jsx
  web/client/plugins/ResourcesCatalog/components/ResourcesContainer.jsx
  web/client/plugins/ResourcesCatalog/components/ResourcesMenu.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/MenuItem-test.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcesGrid.jsx
Labels: enhancement, Backport, MapStore Homepage

#11025 [Backport 2025.01.xx] #10820 : double close icon in add new group dialog (#11018)
  web/client/components/manager/users/GroupDialog.jsx
Labels: enhancement, Backport

#11004 Remove unused devDependency download-cli
  package.json
Labels: dependencies, External Contribution

#11039 Remove unused devDependency parallelshell
  package.json
Labels: dependencies, External Contribution

#11031 [Backport 2025.01.xx] Fix #10774 Review position of the filter button and search field in the homepage
  build/docma-config.json
  docs/developer-guide/mapstore-migration-guide.md
  web/client/actions/__tests__/maps-test.js
  web/client/actions/createnewmap.js
  web/client/actions/maps.js
  web/client/actions/security.js
  web/client/components/maps/search/AdvancedSearch.jsx
  web/client/components/maps/search/SearchBar.jsx
  web/client/components/maps/search/__tests__/AdvancedSearch-test.jsx
  web/client/components/maps/search/__tests__/SearchBar-test.jsx
  web/client/components/misc/NewMapDialog.jsx
  web/client/components/misc/PagedSelect.jsx
  web/client/components/misc/__tests__/NewMapDialog-test.jsx
  web/client/configs/localConfig.json
  web/client/epics/__tests__/widgets-test.js
  web/client/epics/createnewmap.js
  web/client/epics/details.js
  web/client/epics/tutorial.js
  web/client/epics/widgets.js
  web/client/plugins/CreateNewMap.jsx
  web/client/plugins/MapSearch.jsx
  web/client/plugins/ResourcesCatalog/ResourcesFiltersForm.jsx
  web/client/plugins/ResourcesCatalog/ResourcesSearch.jsx
  web/client/plugins/ResourcesCatalog/__tests__/ResourcesSearch-test.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcesFiltersFormButton.jsx
  web/client/plugins/ResourcesCatalog/index.js
  web/client/plugins/__tests__/MapSearch-test.jsx
  web/client/product/__tests__/main-test.jsx
  web/client/product/main.jsx
  web/client/product/pages/Maps.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/config-test.js
  web/client/reducers/__tests__/maps-test.js
  web/client/reducers/config.js
  web/client/reducers/createnewmap.js
  web/client/reducers/maps.js
  web/client/selectors/__tests__/maps-test.js
  web/client/selectors/createnewmap.js
  web/client/selectors/maps.js
  web/client/themes/default/less/createnewmap.less
  web/client/themes/default/less/mapstore.less
  web/client/themes/default/less/pagedselect.less
  web/client/themes/default/less/resources-catalog/_resources-search.less
  web/client/themes/default/less/resources-catalog/index.less
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/utils/__tests__/PluginsUtils-test.js
Labels: Backport, New Feature, MapStore Homepage

#11032 [Backport 2025.01.xx] Fix #11010 Vertical scrollbar on map viewer (#11015)
  web/client/product/assets/css/viewer.css
  web/client/themes/default/less/mouse-position.less
  web/client/themes/default/less/select.less
Labels: bug, Backport

#11033 [Backport 2025.01.xx] Fix #11011 MapCatalog infinite scroll request all the pages (#11014)
  web/client/components/mapcatalog/MapCatalogPanel.jsx
Labels: bug, Backport

#11059 Fix #11058 .prettierignore improvements and fixes
  .prettierignore
  tests/plugin.json
  web/client/api/__tests__/classifyRaterResponse.json
  web/client/api/__tests__/classifyVectorResponse.json
  web/client/plugins/StreetView/components/img/marker.gltf.json
  web/client/utils/font-awesome.json
Labels: BackportNeeded

#11034 #11021: Implement an option to have static WMS legends
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/plugins/TOC/components/StyleBasedWMSJsonLegend.jsx
  web/client/plugins/TOC/components/__tests__/WMSLegend-test.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/plugins/__tests__/TOCItemsSettings-test.jsx
  web/client/translations/data.ca-ES.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LegendUtils.js
  web/client/utils/__tests__/LegendUtils-test.js
Labels: enhancement, BackportNeeded, Regression
