Repository geosolutions-it/MapStore2, pull requests merged in 2025-06, with the labels that each got.

#11115 Update User Guide - User Session plugin
  docs/user-guide/img/button/user-session-button.jpg
  docs/user-guide/img/button/yes-button.jpg
  docs/user-guide/img/user-session/clear-part-user-session.mp4
  docs/user-guide/img/user-session/clear-user-session.mp4
  docs/user-guide/img/user-session/user-session-panel.jpg
  docs/user-guide/user-session.md
  mkdocs.yml
Labels: Documentation, User Guide

#11172 [Backport 2025.01.xx] Fix #10982 Side panels should be smaller
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/data/identify/coordinates/Viewer.jsx
  web/client/components/details/DetailsPanel.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/geoProcessing.js
  web/client/epics/identify.js
  web/client/epics/longitudinalProfile.js
  web/client/epics/maplayout.js
  web/client/plugins/Details.jsx
  web/client/plugins/GeoProcessing/Panel.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/MapCatalog.jsx
  web/client/plugins/MapTemplates.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/UserExtensions.jsx
  web/client/plugins/longitudinalProfile/Dock.jsx
  web/client/selectors/maplayout.js
  web/client/themes/default/less/get-feature.less
  web/client/themes/default/less/longitudinal-profile.less
  web/client/utils/LayoutUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/LayoutUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, Backport

#11159 Max zoom level configuration from localConfig for Coordinate Search #11154
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/plugins/Search.jsx
Labels: enhancement, BackportNeeded

#11180 backport 2025.01.xx - Fix #11176 adding version template and updated pom versions (#11178)
  .github/ISSUE_TEMPLATE/release_steps.md
  java/printing/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/pom.xml
  project/standard/templates/web/pom.xml
Labels: Backport

#11185 [Backport 2025.01.xx] Update User Guide - User Session plugin (#11115)
  docs/user-guide/img/button/user-session-button.jpg
  docs/user-guide/img/button/yes-button.jpg
  docs/user-guide/img/user-session/clear-part-user-session.mp4
  docs/user-guide/img/user-session/clear-user-session.mp4
  docs/user-guide/img/user-session/user-session-panel.jpg
  docs/user-guide/user-session.md
  mkdocs.yml
Labels: Documentation, User Guide, Backport

#11187 [Backport 2025.01.xx] Update User Guide - Static WMS legends #11107
  docs/user-guide/img/layer-settings/display.jpg
  docs/user-guide/img/layer-settings/dynamic-legend.mp4
  docs/user-guide/layer-settings.md
Labels: Documentation, User Guide, Backport

#11184 [Backport 2025.01.xx] Update User Guide - Configure the light on Cesium map (#11126)
  docs/user-guide/img/menu-bar/cesium-settings.jpg
  docs/user-guide/img/menu-bar/date-time-picker.mp4
  docs/user-guide/mapstore-toolbars.md
Labels: Documentation, User Guide, Backport

#11026 Update User Guide - Legend filtering for WMS layers
  docs/user-guide/toc.md
Labels: Documentation, User Guide

#11189 [Backport 2025.01.xx]: Update User Guide - Legend filtering for WMS layers #11026
  docs/user-guide/toc.md
Labels: Documentation, User Guide, Backport

#11190 User Guide - Add User Session plugin section
  mkdocs.yml
Labels: Documentation, User Guide

#11191 [Backport 2025.01.xx]: User Guide - Add User Session plugin section #11190
  mkdocs.yml
Labels: Documentation, User Guide, Backport

#11152 #11143: Use another layer as input for attribute table dropdown
  web/client/components/data/featuregrid/editors/CustomAutocompleteEditor.jsx
  web/client/components/data/featuregrid/editors/__tests__/CustomAutocompleteEditor-test.jsx
  web/client/components/data/featuregrid/editors/customEditors.jsx
  web/client/observables/__tests__/autocomplete-test.js
  web/client/observables/autocomplete.js
  web/client/plugins/FeatureEditor.jsx
Labels: New Feature

#11202 [Backport 2025.01.xx]: #11153: Persist Swipe Layer state after map refresh (#11158)
  web/client/reducers/__tests__/swipe-test.js
  web/client/reducers/swipe.js
  web/client/selectors/__tests__/mapsave-test.js
  web/client/selectors/__tests__/swipe-test.js
  web/client/selectors/swipe.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: bug, Backport

#11008 Remove unused dependency escope from devDependencies
  package.json
Labels: dependencies, External Contribution

#11212 [#11211]: fix incorrect or unintuitive German translations in Geo Processing Tool
  web/client/plugins/GeoProcessing/processes.js
  web/client/translations/data.de-DE.json
Labels: BackportNeeded, External Contribution

#11208 [Backport to 2025.01.xx][#11205] MapStore war stand-alone not starting
  binary/bin-war/pom.xml
  java/printing/pom.xml
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: Backport, ci/cd

#11041 Remove unused devDependency progress-bar-webpack-plugin
  package.json
Labels: dependencies, External Contribution

#11051 Remove unused devDependency react-motion
  package.json
Labels: dependencies, External Contribution

#11052 Remove unused dependency react-input-autosize
  package.json
Labels: dependencies, External Contribution

#11216 Fixing failing tests due to timeout
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
Labels: BackportNeeded

#11219 Remove usage of object-assign
  build/buildConfig.js
  build/testConfig.js
  web/client/components/TOC/fragments/RefreshLayers.jsx
  web/client/components/TOC/fragments/settings/ThematicLayer.jsx
  web/client/components/app/StandardAppComponent.jsx
  web/client/components/app/StandardContainer.jsx
  web/client/components/app/StandardRouter.jsx
  web/client/components/background/BackgroundSelector.jsx
  web/client/components/buttons/InfoButton.jsx
  web/client/components/catalog/Catalog.jsx
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/featuregrid/editors/DropDownEditor.jsx
  web/client/components/data/query/AutocompleteFieldHOC.jsx
  web/client/components/data/query/ComboField.jsx
  web/client/components/data/query/FilterField.jsx
  web/client/components/data/query/GeometryDetails.jsx
  web/client/components/map/leaflet/Feature.jsx
  web/client/components/map/leaflet/Layer.jsx
  web/client/components/map/leaflet/Map.jsx
  web/client/components/map/leaflet/Overview.jsx
  web/client/components/map/openlayers/Layer.jsx
  web/client/components/map/openlayers/snapshot/GrabMap.jsx
  web/client/components/mapcontrols/search/SearchResultList.jsx
  web/client/components/mapcontrols/searchservicesconfig/ResultsProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/WFSOptionalProps.jsx
  web/client/components/mapcontrols/searchservicesconfig/WFSServiceProps.jsx
  web/client/components/misc/Dialog.jsx
  web/client/components/misc/Modal.jsx
  web/client/components/plugins/__tests__/PluginsContainer-test.jsx
  web/client/components/print/MapPreview.jsx
  web/client/components/search/SearchBarToolbar.jsx
  web/client/components/styleeditor/Editor.jsx
Labels: dependencies

#11221 Remove unused devDependency karma-ie-launcher
  package.json
Labels: dependencies

#11199 Update openId.md
  docs/developer-guide/integrations/users/openId.md
Labels: BackportNeeded

#11182 [Backport 2025.01.xx]: Fixes #11139 Search service shows not all options due to amount of search services configured(#11144)
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/themes/default/less/searchbar.less
Labels: enhancement, Backport

#11181 [Backport 2025.01.xx]: Fixes #11154 Max zoom level configuration from localConfig for Coordinate Search(#11159)
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/plugins/Search.jsx
Labels: enhancement, Backport

#11223 [Backport 2025.01.xx] Update openId.md (#11199)
  docs/developer-guide/integrations/users/openId.md
Labels: Documentation, Backport

#11226 [Backport 2025.01.xx]: #11162: Improve MS actions to automatically zoom to filtered features (#11163)
  web/client/actions/__tests__/mapInfo-test.js
  web/client/actions/__tests__/search-test.js
  web/client/actions/mapInfo.js
  web/client/actions/search.js
  web/client/epics/__tests__/identify-test.js
  web/client/epics/__tests__/search-test.js
  web/client/epics/identify.js
  web/client/epics/search.js
  web/client/utils/QueryParamsUtils.js
  web/client/utils/__tests__/QueryParamsUtils-test.js
Labels: enhancement, Backport, New Feature

#11225 [Backport 2025.01.xx] - fix #11071 improve interactions layerdownload plugin and comp DownloadDialog
  pom.xml
  web/client/actions/layerdownload.js
  web/client/components/data/download/DownloadDialog.jsx
  web/client/components/data/download/DownloadOptions.jsx
  web/client/components/data/download/DownloadWPSOptions.jsx
  web/client/components/data/download/ExportDataResultsComponent.jsx
  web/client/components/data/download/__tests__/DownloadDialog-test.jsx
  web/client/components/data/download/__tests__/DownloadOptions-test.jsx
  web/client/components/data/download/__tests__/checkWPSAvailability-test.jsx
  web/client/components/data/download/__tests__/data/download-estimation.xml.js
  web/client/components/misc/infobubble/DefaultInnerComponent.jsx
  web/client/components/misc/infobubble/InfoBubble.jsx
  web/client/components/widgets/enhancers/tools/withMenu.js
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/configs/localConfig.json
  web/client/epics/__tests__/layerdownload-test.js
  web/client/epics/layerdownload.js
  web/client/plugins/Dashboard.jsx
  web/client/plugins/LayerDownload.jsx
  web/client/plugins/widgetbuilder/enhancers/layerSelector.js
  web/client/reducers/__tests__/layerdownload-test.js
  web/client/reducers/layerdownload.js
  web/client/selectors/__tests__/layerdownload-test.js
  web/client/selectors/layerdownload.js
  web/client/themes/default/less/common.less
  web/client/themes/default/less/infobubble.less
  web/client/themes/default/less/layerdownload.less
  web/client/themes/default/less/mapstore.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: Backport

#11229 [Backport 2025.01.xx] fix: incorrect or unintuitive German translations in Geo Processing Tool (#11212)
  web/client/plugins/GeoProcessing/processes.js
  web/client/translations/data.de-DE.json
Labels: Backport, Translations

#11238 gs-stable CORS policy issue on QA #11234
  web/client/configs/localConfig.json
Labels: bug, BackportNeeded, Regression

#11247 [Backport 2025.01.xx]:#10839: Allow printing by freely setting the scale factor (#11130), (#11245)
  web/client/actions/__tests__/print-test.js
  web/client/actions/print.js
  web/client/components/map/openlayers/Map.jsx
  web/client/components/mapcontrols/scale/ScaleBox.jsx
  web/client/components/print/MapPreview.jsx
  web/client/plugins/Print.jsx
  web/client/plugins/__tests__/Print-test.jsx
  web/client/plugins/print/MapPreview.jsx
  web/client/reducers/__tests__/print-test.js
  web/client/reducers/print.js
  web/client/themes/default/less/select.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/MapUtils.js
  web/client/utils/PrintUtils.js
  web/client/utils/__tests__/MapUtils-test.js
  web/client/utils/__tests__/PrintUtils-test.js
Labels: enhancement, Backport

#11255 #10930: fix Annotation circle editing causing MapStore to crash
  web/client/components/I18N/IntlNumberFormControl.jsx
Labels: bug

#11248 Thousands separator is always active while Mapstore is in French #10639
  web/client/components/I18N/IntlNumberFormControl.jsx
  web/client/components/data/query/NumberField.jsx
  web/client/components/data/query/__tests__/NumberField-test.jsx
Labels: bug, BackportNeeded
