Repository geosolutions-it/MapStore2, pull requests merged in 2025-02, with the labels that each got.

#10788 #10787: add missing documentation part related to interactive legend for wfs layer
  docs/developer-guide/LayerFilter.md
  docs/developer-guide/local-config.md
Labels: Documentation

#10795 Fix #10783 Support for favorites
  docs/developer-guide/mapstore-migration-guide.md
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
  web/client/configs/localConfig.json
  web/client/plugins/ResourcesCatalog/Favorites.jsx
  web/client/plugins/ResourcesCatalog/ResourcesFiltersForm.jsx
  web/client/plugins/ResourcesCatalog/api/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/api/resources.js
  web/client/plugins/ResourcesCatalog/components/ResourceCard.jsx
  web/client/plugins/ResourcesCatalog/containers/Favorites.jsx
  web/client/plugins/ResourcesCatalog/containers/__tests__/Favorites-test.jsx
  web/client/plugins/ResourcesCatalog/index.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/heart-o.svg
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: New Feature, Homepage

#10797 #10736: fix issue of not hiding the enabled/disabled filter icon in case there is no filters after reseting the interactive legend
  web/client/epics/__tests__/styleeditor-test.js
  web/client/plugins/TOC/components/FilterNodeTool.jsx
  web/client/plugins/TOC/components/__tests__/DefaultLayer-test.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
Labels: bug

#10796 Fix #10782 Support for Tags
  docs/developer-guide/mapstore-migration-guide.md
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
  web/client/configs/localConfig.json
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/ResourcesFiltersForm.jsx
  web/client/plugins/ResourcesCatalog/ResourcesGrid.jsx
  web/client/plugins/ResourcesCatalog/TagsManager.jsx
  web/client/plugins/ResourcesCatalog/actions/__tests__/tags-test.js
  web/client/plugins/ResourcesCatalog/actions/tags.js
  web/client/plugins/ResourcesCatalog/api/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/api/resources.js
  web/client/plugins/ResourcesCatalog/components/ALink.jsx
  web/client/plugins/ResourcesCatalog/components/DetailsInfo.jsx
  web/client/plugins/ResourcesCatalog/components/FilterItems.jsx
  web/client/plugins/ResourcesCatalog/components/ResourceCard.jsx
  web/client/plugins/ResourcesCatalog/components/TagsManagerEntry.jsx
  web/client/plugins/ResourcesCatalog/components/TagsManagerPanel.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/TagsManagerEntry-test.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/TagsManagerPanel-test.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcesGrid.jsx
  web/client/plugins/ResourcesCatalog/containers/TagsManager.jsx
  web/client/plugins/ResourcesCatalog/hooks/__tests__/useFilterFacets-test.js
  web/client/plugins/ResourcesCatalog/hooks/useFilterFacets.js
  web/client/plugins/ResourcesCatalog/index.js
  web/client/plugins/ResourcesCatalog/reducers/__tests__/tags-test.js
  web/client/plugins/ResourcesCatalog/reducers/tags.js
  web/client/plugins/ResourcesCatalog/selectors/__tests__/tags-test.js
  web/client/plugins/ResourcesCatalog/selectors/tags.js
  web/client/plugins/ResourcesCatalog/utils/ResourcesFiltersUtils.js
  web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js
  web/client/plugins/ResourcesCatalog/utils/__tests__/ResourcesFiltersUtils-test.js
  web/client/plugins/ResourcesCatalog/utils/__tests__/ResourcesUtils-test.js
  web/client/plugins/manager/ManagerMenu.jsx
  web/client/themes/default/less/react-select.less
  web/client/themes/default/less/resources-catalog/_details-panel.less
  web/client/themes/default/less/resources-catalog/_resources-panel-wrapper.less
  web/client/themes/default/less/resources-catalog/_tags-manager.less
  web/client/themes/default/less/resources-catalog/_utility.less
  web/client/themes/default/less/resources-catalog/index.less
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: New Feature, Homepage

#10800 Fix #10781 Review pluginsConfig after introduction of new homepage plugins
  build/docma-config.json
  project/standard/templates/configs/pluginsConfig.json
  web/client/configs/pluginsConfig.json
  web/client/plugins/ResourcesCatalog/BrandNavbar.jsx
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/themes/default/less/resources-catalog/_brand-navbar.less
  web/client/themes/default/less/resources-catalog/index.less
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
Labels: enhancement, Internal, Homepage

#10772 #10770: Vector files import limits
  web/client/components/import/ImportDragZone.jsx
  web/client/components/import/dragZone/enhancers/__tests__/processFiles-test.jsx
  web/client/components/import/dragZone/enhancers/__tests__/useFiles-test.js
  web/client/components/import/dragZone/enhancers/processFiles.jsx
  web/client/components/import/dragZone/enhancers/useFiles.js
  web/client/plugins/MapImport.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/utils/FileUtils.js
  web/client/utils/__tests__/FileUtils-test.js
Labels: enhancement

#10806 #10637: fix Longitudinal profil does not close properly and it leads to conflicts between the longitudinal profil and measure plugin
  web/client/epics/__tests__/longitudinalProfile-test.js
  web/client/epics/longitudinalProfile.js
  web/client/selectors/__tests__/draw-test.js
  web/client/selectors/draw.js
Labels: bug, Internal

#10763 #10758: Support for Cesium Ion Terrain Provider
  docs/developer-guide/maps-configuration.md
  web/client/components/map/cesium/plugins/TerrainLayer.js
Labels: enhancement

#10006 #10005 update babel configuration
  package.json
  utility/eslint/index.js
  utility/eslint/package.json
  web/client/api/WFS.js
  web/client/components/TOC/fragments/settings/FeatureInfo.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/geostory/contents/texteditor/CustomEditorLink.jsx
  web/client/components/import/style/StylePanel.jsx
  web/client/components/map/cesium/Map.jsx
  web/client/components/misc/datetimepicker/DateTimePicker.js
  web/client/components/misc/datetimepicker/Hours.js
  web/client/components/resources/modals/Save.jsx
  web/client/components/share/ShareEmbed.jsx
  web/client/components/styleeditor/WMSJsonLegendIcon.jsx
  web/client/libs/numeric-input/NumericInput.jsx
  web/client/plugins/SidebarMenu.jsx
  web/client/plugins/TOC/components/WMSLegend.jsx
  web/client/utils/ogc/Filter/FilterBuilder.js
  web/client/utils/ogc/Filter/__tests__/FilterBuilder-test.js
  web/client/utils/ogc/WFS/RequestBuilder.js
  web/client/utils/ogc/WFS/__tests__/RequestBuilder-test.js
  web/client/utils/ogc/WFST/RequestBuilder.js
  web/client/utils/ogc/WFST/__tests__/WFST-test.js
  web/client/utils/ogc/WPS/autocomplete.js
Labels: C125-AUSTROCONTROL-2024-MapStore

#10821 #10816: Allow dynamic management of style editing permissions
  web/client/plugins/StyleEditor.jsx
  web/client/plugins/__tests__/StyleEditor-test.jsx
  web/client/selectors/__tests__/styleeditor-test.js
  web/client/selectors/styleeditor.js
Labels: enhancement

#10803 #10799: Cesium map dark when opened in the evening
  web/client/components/map/cesium/Map.jsx
  web/client/components/map/cesium/__tests__/Map-test.jsx
  web/client/plugins/map/mapsettings/MapSettings.jsx
  web/client/themes/default/less/settings.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
Labels: enhancement

#10834 Backport[c105-cgd2.3-2023.02.xx]: Layer download fails when layer attributes are changed in feature grid #10597
  web/client/epics/layerdownload.js
  web/client/observables/wps/download.js
Labels: C105-2024-EMSA-SC3_CGD

#10832 Layer download fails when layer attributes are changed in feature grid #10597
  web/client/epics/layerdownload.js
  web/client/observables/wps/download.js
Labels: C105-2024-EMSA-SC3_CGD

#10833 #10825: Fix - Unnecessary re-rendering of the resource plugin
  web/client/components/app/withExtensions.js
  web/client/plugins/ResourcesCatalog/api/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/api/resources.js
  web/client/plugins/ResourcesCatalog/hooks/useQueryResourcesByLocation.js
Labels: bug

#10798 #10737: Interactive legend for TOC layers [Vector Layer part]
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/components/catalog/editor/AdvancedSettings/CommonAdvancedSettings.jsx
  web/client/components/catalog/editor/AdvancedSettings/__tests__/CommonAdvancedSettings-test.js
  web/client/components/map/BaseMap.jsx
  web/client/components/map/cesium/__tests__/Layer-test.jsx
  web/client/components/map/cesium/plugins/VectorLayer.js
  web/client/components/map/leaflet/__tests__/Layer-test.jsx
  web/client/components/map/leaflet/plugins/VectorLayer.jsx
  web/client/components/map/openlayers/__tests__/Layer-test.jsx
  web/client/plugins/Map.jsx
  web/client/utils/FilterUtils.js
  web/client/utils/__tests__/FilterUtils-test.js
  web/client/utils/cesium/GeoJSONStyledFeatures.js
Labels: New Feature

#10813 Fix #10805 JAXBException while updating an existing dashboard
  web/client/api/GeoStoreDAO.js
  web/client/api/__tests__/GeoStoreDAO-test.jsx
  web/client/api/usersession/__tests__/server-test.js
  web/client/plugins/ResourcesCatalog/api/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/api/resources.js
  web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js
  web/client/plugins/ResourcesCatalog/utils/__tests__/ResourcesUtils-test.js
Labels: bug, Internal, MapStore Homepage

#10841 [Backport c040-2024.02.xx]: backport Update build.yml commit
  .github/workflows/build.yml
Labels: Backport

#10827 Fix #10776 Review the open properties icon and the order of item in the viewer navbar
  web/client/plugins/ResourcesCatalog/BrandNavbar.jsx
  web/client/plugins/ResourcesCatalog/DeleteResource.jsx
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/Save.jsx
  web/client/plugins/ResourcesCatalog/SaveAs.jsx
  web/client/plugins/ResourcesCatalog/components/ResourcesMenu.jsx
  web/client/plugins/tocitemssettings/defaultSettingsTabs.js
  web/client/themes/default/icons.less
  web/client/themes/default/icons/icons.eot
  web/client/themes/default/icons/icons.svg
  web/client/themes/default/icons/icons.ttf
  web/client/themes/default/icons/icons.woff
  web/client/themes/default/icons/icons.woff2
  web/client/themes/default/svg/details.svg
  web/client/themes/default/svg/th-list.svg
Labels: enhancement, MapStore Homepage

#10828 Fix #10824 Adjust placement of Search and TOC button
  web/client/themes/default/less/drawer-menu.less
  web/client/themes/default/less/map-search-bar.less
Labels: enhancement, MapStore Homepage

#10823 Fix #10786 Review of the home description image
  build/prod-webpack.config.js
  docs/developer-guide/mapstore-migration-guide.md
  project/standard/static/assets/img/favicon.png
  project/standard/static/assets/placeholder
  project/standard/templates/api.html
  project/standard/templates/apiTemplate.html
  project/standard/templates/embedded.html
  project/standard/templates/embeddedTemplate.html
  project/standard/templates/geostory-embedded-template.html
  project/standard/templates/geostory-embedded.html
  project/standard/templates/index.html
  project/standard/templates/indexTemplate.html
  project/standard/templates/prod-webpack.config.js
  web/client/api.html
  web/client/apiTemplate.html
  web/client/components/share/api-template.raw
  web/client/configs/localConfig.json
  web/client/embedded.html
  web/client/embeddedTemplate.html
  web/client/geostory-embedded-template.html
  web/client/geostory-embedded.html
  web/client/index.html
  web/client/indexTemplate.html
  web/client/plugins/ResourcesCatalog/BrandNavbar.jsx
  web/client/plugins/ResourcesCatalog/HomeDescription.jsx
  web/client/product/assets/css/maps.css
  web/client/product/assets/img/favicon.ico
  web/client/product/assets/img/favicon.png
  web/client/product/assets/img/hero.jpg
  web/client/product/assets/img/logo.png
  web/client/product/plugins/HomeDescription.jsx
  web/client/themes/default/less/home.less
  web/client/themes/default/less/mapstore.less
  web/client/themes/default/less/resources-catalog/_home-description.less
  web/client/themes/default/less/resources-catalog/index.less
Labels: enhancement, MapStore Homepage

#10822 Fix #10785 Review of footer plugin
  docs/developer-guide/mapstore-migration-guide.md
  web/client/configs/localConfig.json
  web/client/plugins/ResourcesCatalog/Footer.jsx
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/ResourcesFiltersForm.jsx
  web/client/plugins/ResourcesCatalog/components/Menu.jsx
  web/client/plugins/ResourcesCatalog/components/MenuDropdownList.jsx
  web/client/plugins/ResourcesCatalog/components/MenuItem.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/MenuDropdownList-test.jsx
  web/client/plugins/ResourcesCatalog/components/__tests__/MenuItem-test.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcesGrid.jsx
  web/client/plugins/ScrollTop.jsx
  web/client/product/plugins/About.jsx
  web/client/product/plugins/Footer.jsx
  web/client/themes/default/less/resources-catalog/_footer.less
  web/client/themes/default/less/resources-catalog/index.less
  web/client/themes/default/ms-variables.less
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: enhancement, MapStore Homepage

#10861 Fix #10824 Adjust placement of Map Views plugin
  web/client/themes/default/less/map-views.less
Labels: enhancement, MapStore Homepage

#10864 Fix #10853 Context Card buttons issue
  web/client/themes/default/less/resources-catalog/_resource-card.less
Labels: bug, MapStore Homepage

#10873 Fix #10830 eol LF for json files
  .gitattributes
Labels: enhancement, Configuration

#10863 Fix #10852 Edit properties button for Anonymuos user
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
Labels: bug, MapStore Homepage

#10871 Fix #10858 Properties panel from a new GeoStory
  docs/developer-guide/mapstore-migration-guide.md
  web/client/configs/localConfig.json
Labels: bug, MapStore Homepage

#10869 Fix #10854 Homepage - Issues on Tooltips
  web/client/components/map/openlayers/__tests__/BoxSelectionSupport-test.jsx
  web/client/components/map/openlayers/swipe/__tests__/EffectSupport-test.jsx
  web/client/components/mapcontrols/search/__tests__/SearchResultList-test.jsx
  web/client/components/mapviews/__tests__/MapViewsProgressBar-test.jsx
  web/client/components/misc/enhancers/__tests__/buttonTooltip-test.jsx
  web/client/components/misc/enhancers/__tests__/tooltip-test.jsx
  web/client/components/misc/enhancers/tooltip.jsx
  web/client/hooks/__tests__/useIsMounted-test.js
  web/client/hooks/useIsMounted.js
  web/client/plugins/ResourcesCatalog/DeleteResource.jsx
  web/client/plugins/ResourcesCatalog/components/FilterAccordion.jsx
  web/client/plugins/ResourcesCatalog/components/FilterGroup.jsx
  web/client/plugins/ResourcesCatalog/components/Icon.jsx
  web/client/plugins/ResourcesCatalog/containers/Favorites.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcePermissions.jsx
  web/client/plugins/ResourcesCatalog/containers/TagsManager.jsx
  web/client/plugins/ResourcesCatalog/hooks/useFilterFacets.js
  web/client/plugins/ResourcesCatalog/hooks/useQueryResourcesByLocation.js
  web/client/plugins/ResourcesCatalog/hooks/useRequestResource.js
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: bug, MapStore Homepage

#10850 Fix #10804 Prevent creation of duplicate tags
  web/client/plugins/ResourcesCatalog/containers/TagsManager.jsx
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
  web/client/translations/data.zh-ZH.json
Labels: bug, MapStore Homepage

#10843 #10826: Fix - URL aliases ignored on added layers
  web/client/epics/__tests__/catalog-test.js
  web/client/epics/catalog.js
Labels: bug

#10877 Fix #10862 Manage Access Rules issue with new Navigation bar
  build/docma-config.json
  docs/developer-guide/mapstore-migration-guide.md
  web/client/product/pages/RulesManager.jsx
Labels: bug, MapStore Homepage

#10879 Fix #10859 Share button on new dashbaord
  web/client/actions/__tests__/geostory-test.js
  web/client/actions/geostory.js
  web/client/plugins/Share.jsx
  web/client/product/pages/GeoStory.jsx
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/geostory.js
Labels: bug, MapStore Homepage

#10883 Fix #10878 adding mergeableParams params
  web/client/plugins/Print.jsx
  web/client/utils/PrintUtils.js
Labels: New Feature

#10868 #10825: Fix - Skip loading extensions when redirected to homepage
  web/client/epics/__tests__/contextcreator-test.js
  web/client/epics/contextcreator.js
  web/client/plugins/__tests__/ContextCreator-test.jsx
  web/client/reducers/__tests__/contextcreator-test.js
  web/client/reducers/contextcreator.js
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: bug, MapStore Homepage

#10872 #10867: Fix - Saving context loads duplicate extensions as scripts
  web/client/components/app/withExtensions.js
  web/client/utils/PluginsUtils.js
Labels: bug, AppContext

#10885 Fix #10884 Permissions already present on a resource are no longer visible if the properties edit starts from the info tab
  web/client/plugins/ResourcesCatalog/containers/ResourcePermissions.jsx
Labels: bug, MapStore Homepage

#10887 Fix #10857 add tags on new resources
  web/client/observables/__tests__/geostore-test.js
  web/client/observables/geostore.js
Labels: bug, MapStore Homepage

#10888 Fix #10856 GeoStory - The Share button is not present
  docs/developer-guide/mapstore-migration-guide.md
  web/client/configs/localConfig.json
  web/client/plugins/OmniBar.jsx
Labels: bug, MapStore Homepage

#10886 Fix #10855 Show as modal and Show as startup Details issue
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/api/resources.js
  web/client/plugins/ResourcesCatalog/reducers/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/reducers/resources.js
  web/client/plugins/ResourcesCatalog/utils/ResourcesUtils.js
  web/client/plugins/ResourcesCatalog/utils/__tests__/ResourcesUtils-test.js
Labels: bug, MapStore Homepage

#10892 Fix #10778 add db migration scripts
  docs/developer-guide/mapstore-migration-guide.md
Labels: Documentation, MapStore Homepage
