Repository geosolutions-it/MapStore2, pull requests merged in 2025-05, with the labels that each got.

#11068 backport 2025.01.xx - Fix #10958 Clean up old packages and deps (#10959)
  package.json
  utility/generateIcons/README.md
  utility/generateIcons/index.js
  utility/generateIcons/package.json
  web/client/actions/__tests__/widgets-test.js
  web/client/actions/widgets.js
  web/client/components/map/leaflet/SnapshotSupport.jsx
  web/client/components/map/leaflet/snapshot/GrabMap.jsx
  web/client/components/map/leaflet/snapshot/Preview.jsx
  web/client/components/map/leaflet/snapshot/__tests__/GrabMap-test.jsx
  web/client/components/map/leaflet/snapshot/__tests__/Preview-test.jsx
  web/client/components/map/leaflet/snapshot/snapshotMapStyle.css
  web/client/components/widgets/enhancers/tools/__tests__/exportableWidget-test.js
  web/client/components/widgets/enhancers/tools/exportableWidget.js
  web/client/components/widgets/widget/DefaultWidget.jsx
  web/client/epics/widgets.js
  web/client/plugins/Dashboard.jsx
  web/client/plugins/Widgets.jsx
Labels: Backport

#11066 Fix #11064. Restored arguments for login event
  web/client/actions/login.js
  web/client/plugins/__tests__/Login-test.js
  web/client/plugins/login/index.js
Labels: BackportNeeded

#11067 Fix #10966 basic auth for services
  build/docma-config.json
  web/client/actions/__tests__/layers-test.js
  web/client/actions/__tests__/security-test.js
  web/client/actions/security.js
  web/client/components/catalog/Catalog.jsx
  web/client/components/catalog/CatalogServiceEditor.jsx
  web/client/components/catalog/RecordGrid.jsx
  web/client/components/catalog/RecordItem.jsx
  web/client/components/catalog/editor/MainForm.jsx
  web/client/components/map/cesium/plugins/TileProviderLayer.js
  web/client/components/map/cesium/plugins/WFSLayer.js
  web/client/components/map/cesium/plugins/WMSLayer.js
  web/client/components/map/cesium/plugins/WMTSLayer.js
  web/client/components/map/openlayers/plugins/ArcGISLayer.js
  web/client/components/map/openlayers/plugins/COGLayer.js
  web/client/components/map/openlayers/plugins/TMSLayer.js
  web/client/components/map/openlayers/plugins/TileProviderLayer.js
  web/client/components/map/openlayers/plugins/WFSLayer.js
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/components/map/openlayers/plugins/WMTSLayer.js
  web/client/configs/localConfig.json
  web/client/epics/security.js
  web/client/hooks/usePluginItems.js
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/SecurityPopup.jsx
  web/client/product/plugins.js
  web/client/reducers/__tests__/catalog-test.js
  web/client/reducers/__tests__/geostory-test.js
  web/client/reducers/__tests__/layers-test.js
  web/client/reducers/__tests__/mediaEditor-test.js
  web/client/reducers/__tests__/security-test.js
  web/client/reducers/__tests__/widgets-test.js
  web/client/reducers/catalog.js
  web/client/reducers/geostory.js
  web/client/reducers/layers.js
  web/client/reducers/mediaEditor.js
  web/client/reducers/security.js
  web/client/reducers/widgets.js
  web/client/selectors/__tests__/security-test.js
  web/client/selectors/security.js
  web/client/themes/default/less/common.less
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LayersUtils.js
  web/client/utils/SecurityUtils.js
  web/client/utils/__tests__/LayersUtils-test.js
  web/client/utils/__tests__/SecurityUtils-test.js
  web/client/utils/cesium/WMSUtils.js
  web/client/utils/cesium/__tests__/WMSUtils-test.js
Labels: New Feature

#11072 [FIXES #11057] Latest MS binary of 2025.01 series does not start
  pom.xml
Labels: bug, dependencies, BackportNeeded, ci/cd

#11077 Fix #10966 improved basic auth modal and logic
  project/standard/templates/configs/pluginsConfig.json
  web/client/api/ArcGIS.js
  web/client/api/CSW.js
  web/client/api/TMS.js
  web/client/api/ThreeDTiles.js
  web/client/api/WFS.js
  web/client/api/WMS.js
  web/client/api/WMTS.js
  web/client/api/catalog/TMS.js
  web/client/api/catalog/TMS_1_0_0.js
  web/client/api/catalog/ThreeDTiles.js
  web/client/api/catalog/WFS.js
  web/client/components/layout/FlexBox.jsx
  web/client/components/security/SecurityPopupDialog.jsx
  web/client/components/security/__tests__/SecurityPopupDialog-test.jsx
  web/client/configs/pluginsConfig.json
  web/client/epics/security.js
  web/client/plugins/SecurityPopup.jsx
  web/client/reducers/widgets.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/SecurityUtils.js
  web/client/utils/__tests__/SecurityUtils-test.js
Labels: New Feature

#11078 [Backport to 2025.01.xx][FIXES #11057] Latest MS binary of 2025.01 se…
  pom.xml
Labels: Backport

#11055 [Backport 2024.02.xx] #11021: Implement an option to have static WMS legends
  web/client/components/TOC/fragments/settings/Display.jsx
  web/client/components/TOC/fragments/settings/__tests__/Display-test.jsx
  web/client/plugins/TOC/components/StyleBasedWMSJsonLegend.jsx
  web/client/plugins/TOC/components/__tests__/WMSLegend-test.jsx
  web/client/plugins/TOCItemsSettings.jsx
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
  web/client/utils/LegendUtils.js
  web/client/utils/__tests__/LegendUtils-test.js
Labels: enhancement, Backport, Regression

#11079 [Backport 2025.01.xx] Fix #11064. Restored arguments for login event (#11066)
  web/client/actions/login.js
  web/client/plugins/__tests__/Login-test.js
  web/client/plugins/login/index.js
Labels: Backport

#11080 [Backport 2025.01.xx] Fix #11058 .prettierignore improvements (#11059)
  .prettierignore
  tests/plugin.json
  web/client/api/__tests__/classifyRaterResponse.json
  web/client/api/__tests__/classifyVectorResponse.json
  web/client/plugins/StreetView/components/img/marker.gltf.json
  web/client/utils/font-awesome.json
Labels: Backport

#11083 Fix #10966 adding securityPopup in other catalogs
  web/client/components/catalog/Catalog.jsx
  web/client/components/contextcreator/ContextCreator.jsx
  web/client/components/security/SecurityPopupDialog.jsx
  web/client/components/widgets/builder/wizard/MapWizard.jsx
  web/client/epics/security.js
  web/client/plugins/DashboardEditor.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/SecurityPopup.jsx
  web/client/plugins/mapEditor/DefaultConfiguration.js
  web/client/plugins/widgetbuilder/MapBuilder.jsx
  web/client/themes/default/less/common.less
Labels: New Feature

#11035 upgrade spring framework to version 5.3.39
  binary/bin-war/pom.xml
  java/services/pom.xml
  java/services/src/main/java/it/geosolutions/mapstore/controllers/BaseConfigController.java
  java/services/src/main/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsController.java
  java/services/src/test/java/it/geosolutions/mapstore/TestUtils.java
  java/services/src/test/java/it/geosolutions/mapstore/controllers/rest/config/SetParamsControllerTest.java
  java/web/pom.xml
  pom.xml
  product/pom.xml
  project/standard/templates/web/pom.xml
Labels: dependencies

#11084 Fix #10966 updated logic and make security popup static
  web/client/plugins/SecurityPopup.jsx
  web/client/product/plugins.js
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.it-IT.json
Labels: New Feature

#11088 #11085 - Fix: Context maps are no longer opened at the right path
  web/client/api/__tests__/ResourcesCatalog-test.js
  web/client/plugins/ResourcesCatalog/components/ResourceCard.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/utils/GeostoreUtils.js
  web/client/utils/ResourcesUtils.js
  web/client/utils/__tests__/GeostoreUtils-test.js
  web/client/utils/__tests__/ResourcesUtils-test.js
Labels: bug, BackportNeeded, Regression

#11090 IFC position controller no longer working #11086
  web/client/components/map/cesium/plugins/ModelLayer.js
Labels: bug, BackportNeeded, Regression

#11095 Minor home page issues to fix #11081
  web/client/plugins/ResourcesCatalog/Favorites.jsx
  web/client/plugins/ResourcesCatalog/actions/resources.js
  web/client/plugins/ResourcesCatalog/containers/Favorites.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceAbout.jsx
  web/client/plugins/ResourcesCatalog/reducers/resources.js
  web/client/translations/data.ca-ES.json
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
Labels: bug, BackportNeeded

#11100 Refactor: Minor home page issues to fix #11081
  web/client/plugins/ResourcesCatalog/Favorites.jsx
  web/client/plugins/ResourcesCatalog/actions/resources.js
  web/client/plugins/ResourcesCatalog/containers/Favorites.jsx
  web/client/plugins/ResourcesCatalog/reducers/resources.js
Labels: bug

#11101 [Backport 2025.01.xx]: Fix #11086 IFC position controller no longer working (#11090)
  web/client/components/map/cesium/plugins/ModelLayer.js
Labels: bug, Backport, Regression

#11102 [Backport 2025.01.xx]: Fix #11081 Minor home page issues to fix (#11095)
  web/client/plugins/ResourcesCatalog/Favorites.jsx
  web/client/plugins/ResourcesCatalog/containers/Favorites.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceAbout.jsx
  web/client/translations/data.ca-ES.json
  web/client/translations/data.da-DK.json
  web/client/translations/data.de-DE.json
  web/client/translations/data.en-US.json
  web/client/translations/data.es-ES.json
  web/client/translations/data.fi-FI.json
  web/client/translations/data.fr-FR.json
  web/client/translations/data.hr-HR.json
  web/client/translations/data.is-IS.json
  web/client/translations/data.it-IT.json
  web/client/translations/data.nl-NL.json
  web/client/translations/data.pt-PT.json
  web/client/translations/data.sk-SK.json
  web/client/translations/data.sv-SE.json
  web/client/translations/data.vi-VN.json
Labels: bug, Backport

#11106 Adding missing translation property
  web/client/translations/data.en-US.json
Labels: bug

#11108 Fix #11099 Align the behavior of contexts management on the front end to the backend model
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/contextcreator/ConfigurePluginsStep.jsx
  web/client/components/contextcreator/__tests__/ConfigurePluginsStep-test.jsx
  web/client/configs/localConfig.json
  web/client/plugins/ContextCreator.jsx
  web/client/selectors/__tests__/contextcreator-test.js
  web/client/selectors/contextcreator.js
Labels: bug

#10746 Fix #10739 Changing correctly resolutions limits when switching map CRS
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/openlayers/Map.jsx
  web/client/epics/__tests__/map-test.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: bug, BackportNeeded

#11110 c027-2024.01.xx - Fix WMS error and dashboard credentials insertion
  web/client/api/WMS.js
  web/client/components/catalog/CompactCatalog.jsx
  web/client/components/map/openlayers/plugins/WMSLayer.js
  web/client/plugins/widgetbuilder/CatalogServiceEditor.jsx
  web/client/plugins/widgetbuilder/enhancers/catalogEditorEnhancer.js
  web/client/reducers/dashboard.js
  web/client/selectors/security.js
Labels: Backport

#11123 backport 2025.01.xx - Fix #10739 Changing correctly resolutions limits when switching map CRS (#10746)
  web/client/actions/__tests__/map-test.js
  web/client/actions/map.js
  web/client/components/map/openlayers/Map.jsx
  web/client/epics/__tests__/map-test.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: Backport

#11009 #10982 Side panels should be smaller
  docs/developer-guide/mapstore-migration-guide.md
  web/client/components/data/identify/coordinates/Viewer.jsx
  web/client/components/details/DetailsPanel.jsx
  web/client/components/misc/panels/DockPanel.jsx
  web/client/epics/__tests__/maplayout-test.js
  web/client/epics/geoProcessing.js
  web/client/epics/identify.js
  web/client/epics/longitudinalProfile.js
  web/client/epics/maplayout.js
  web/client/plugins/Details.jsx
  web/client/plugins/GeoProcessing/Panel.jsx
  web/client/plugins/Identify.jsx
  web/client/plugins/MapCatalog.jsx
  web/client/plugins/MapTemplates.jsx
  web/client/plugins/MetadataExplorer.jsx
  web/client/plugins/UserExtensions.jsx
  web/client/plugins/longitudinalProfile/Dock.jsx
  web/client/selectors/maplayout.js
  web/client/themes/default/less/get-feature.less
  web/client/utils/LayoutUtils.js
  web/client/utils/MapUtils.js
  web/client/utils/__tests__/LayoutUtils-test.js
  web/client/utils/__tests__/MapUtils-test.js
Labels: enhancement, BackportNeeded

#11134 [Backport 2025.01.xx] Fix #11097 Confirmation modal should not appear if no changes are made (#11125)
  web/client/plugins/ResourcesCatalog/actions/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/actions/resources.js
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourcePermissions.jsx
  web/client/plugins/ResourcesCatalog/reducers/__tests__/resources-test.js
  web/client/plugins/ResourcesCatalog/reducers/resources.js
Labels: bug, Backport

#11149 Fix #11147 Problems with save resource workflow
  web/client/api/ResourcesCatalog.js
  web/client/plugins/ResourcesCatalog/ResourceDetails.jsx
  web/client/plugins/ResourcesCatalog/components/DetailsThumbnail.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceAbout.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceAboutEditor.jsx
  web/client/plugins/ResourcesCatalog/containers/ResourceDetails.jsx
  web/client/utils/GeostoreUtils.js
  web/client/utils/__tests__/GeostoreUtils-test.js
Labels: bug, BackportNeeded

#11144 Search service shows not all options due to amount of search services configured #11139
  web/client/components/mapcontrols/search/SearchBar.jsx
  web/client/components/mapcontrols/search/__tests__/SearchBar-test.jsx
  web/client/themes/default/less/searchbar.less
Labels: enhancement, BackportNeeded

#11151 Fix #10982 Review style of longitudinal profile chart
  web/client/plugins/longitudinalProfile/Dock.jsx
  web/client/themes/default/less/longitudinal-profile.less
Labels: bug, BackportNeeded
